### ISSUE TITLE
Allow object list cache to not be fixed to one language.

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1004]
When using the tools like the Scenario Editor and the Roller Coaster designer, the descriptions show up in Italian. (UK English is set in the options.)

![scr62](https://cloud.githubusercontent.com/assets/1478678/7042053/22238262-dddf-11e4-8cf2-b24f0a0f790d.png)
![scr63](https://cloud.githubusercontent.com/assets/1478678/7042054/22ecab10-dddf-11e4-8345-13e371c82493.png)

**Comment by duncanspumpkin** [comment]
This is because it is read direct from the object list so it will show in whatever language you had set when the object list was last created.. We could modify the object display so that it creates the descriptions dynamically though (See object list for how they are created). Could probably just remove that entry from the object list completely but thats a task for another day.

**Comment by Gymnasiast** [comment]
Perhaps switching a language could force reloading descriptions if reading it dynamically is too slow (which could happen if the user has thousands of custom objects, like me).

**Comment by duncanspumpkin** [comment]
Redoing all the descriptions would be a massive amount of cpu usage when switching language so that's not a good idea. I think dynamic names in the displayed object list shouldn't be too hard to pull off. Plus it means we could possibly start work on removing that part of the object list. (Its one of the fields that makes the list take so long to generate as it has a dynamic size)

**Comment by duncanspumpkin** [comment]
What needs to be changed is object_get_name in object.c.

Change the whole function to use the code snippet from https://github.com/IntelOrca/OpenRCT2/blob/develop/src/object_list.c#L647-L669 
You would need to get the chunk address but that can be found by using the find_object_in_entry_group and using the object_entry_groups with the returned value.

And that should solve the issue. If this causes lots of problems then we can investigate the problem then.

**Comment by IntelOrca** [comment]
Fixed now so that it re-generates the object cache if the language is different.
