### ISSUE TITLE
Request: Add a Competitive Multiplayer Mode

### ISSUE THREAD

**Issue by GeorgeWL** [OpenRCT2/OpenRCT2#10138]
OpenTTD has this and I think it's a really great feature, basically each player shares the map, but have their own individual balance and the balance graph shows the profit/loss of all players.

- [x] Specific to multiplayer?

**Comment by AaronVanGeffen** [comment]
I agree, this would be a really interesting game mode. Once we have added support for maps, it might even be feasible. This is far from a trivial change, however.

Currently, all game data structures assume there is only one company. This would have to become more flexible before such a game mode can even be considered.

**Comment by ocalhoun6** [comment]
If they're all sharing the same map, though, can they delete/edit each other's paths, rides, scenery, etc?
I'm guessing you'd have to have each ride/stall owned by one particular player ... but pathing seems more problematic.

If you can remove your opponents' paths, all the players would constantly be disconnecting paths from their opponent's rides and stalls in order to sabotage them. If you can't remove your opponents' paths, then it will quickly become an area-control game, where the goal is to cover as much territory with non-removable paths/rides/scenery as possible in order to block your opponents from building anything of their own. And in any case, there will be massive competition for building space near high-traffic path areas. Just as you're about to finish building a big, magnificent coaster, someone else will put a hedge maze in your way so you can't finish building it.

Not to mention *staff*. No player will want to spend money on staff members that might spend time cleaning opponents' paths or fixing opponents' rides.

The point I'm trying to get to here is that if there's to be a competitive mode, I think it would be better for each player to have their own specifically designated territory. Basically separate parks on one map. 

Any other way, I can't see it being a 'build a better park than your opponent' type challenge -- it would be more of a 'sabotage your opponent' type challenge, resulting in sprawling, ugly, dysfunctional parks covered in incomplete rides and paths that go nowhere.

**Comment by AaronVanGeffen** [comment]
Thanks, I'd forgotten about that one. Closing this in favour of the other issue, then. Feel free to resume discussion there.
