### ISSUE TITLE
Can't build haunted house in Rainbow Summit

### ISSUE THREAD

**Issue by User126** [OpenRCT2/OpenRCT2#10239]
**OS:** Windows 10
**Version:** 0.24-88
**Commit/Build:** 8eb4286

Haunted house can't be placed in Rainbow Summit

- [NO] Reproducible in RCT2 (vanilla)?
- [NO] Specific to multiplayer?

**Steps to reproduce:**
1. Start Rainbow Summit scenario
2. Build haunted house ride
3. Error: can't contruct this here undefined string

**Screenshots / Video:**
![Untitled](https://user-images.githubusercontent.com/36316526/68900403-ab627000-0798-11ea-8c06-f38c361e6ffa.png)

**Save game:**
[Bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/3848862/Bug.zip)

**Comment by James103** [comment]
The scenario "Rainbow Summit" has a restriction that prevents building above tree height. The most likely reason for the game not allowing construction of the haunted house is because it is apparently too tall by default (but it isn't in RCT2 according to what you gave).

Can you retest building a haunted house in the "Rainbow Summit" scenario in RCT2 vanilla and (if you can) RCT1?

**Comment by Gymnasiast** [comment]
> Can you retest building a haunted house in the "Rainbow Summit" scenario in RCT2 vanilla and (if you can) RCT1?

The OP has already said the issue is not reproducible in vanilla.

**Comment by Gymnasiast** [comment]
Marking this is a bug - the error message itself is one at any rate.

**Comment by User126** [comment]
The ferris wheel is broken too
![Untitled](https://user-images.githubusercontent.com/36316526/68909150-43b91e80-07b2-11ea-89cd-66e6a59db57c.png)

**Comment by ocalhoun6** [comment]
As far as I know, it's normal to not be able to place the taller flat rides _above ground_ when there's a height restriction.

You can still place them entirely underground, which perhaps means that this isn't really a bug. Just that whenever you're in a scenario with these restrictions, you can't place these rides above ground.

While you're at it, I think you'll find that you can place the base of an observation tower, but you can't build it tall enough to actually function.

The (undefined string) part is definitely a bug, though. It should be giving you a message about not being allowed to build things above tree height.

**Comment by tupaschoal** [comment]
I did some investigation and this is what happens on my RCT2 copy on Steam:
![image](https://user-images.githubusercontent.com/6443427/68950909-ddc19c80-079b-11ea-853a-04d574577616.png)

OpenRCT2 does reach the line 1350 below while trying to construct those, which would make the error the same as seen above, but somehow it ain't working.
https://github.com/OpenRCT2/OpenRCT2/blob/93083780df9cad2d2eb1dafcb389a1e112650226/src/openrct2/world/Map.cpp#L1343-L1354

I tried switching the string returned there to another that I know works and it didn't also, so I guess the caller is to blame, which I don't know who because I didn't have time/knowledge to dig more :P

**Comment by duncanspumpkin** [comment]
Yeah it wont be working because its setting gGameCommandErrorText and the calling function has forgotten to copy that value into the game action result.

**Comment by Gymnasiast** [comment]
That's odd, since TrackPlaceAction does this:
```
            if (!map_can_construct_with_clear_at(
                    mapLoc.x, mapLoc.y, baseZ, clearanceZ, &map_place_non_scenery_clear_func, quarterTile, GetFlags(), &cost,
                    crossingMode))
            {
                return std::make_unique<TrackPlaceActionResult>(
                    GA_ERROR::NO_CLEARANCE, gGameCommandErrorText, gCommonFormatArgs);
            }
```

**Comment by duncanspumpkin** [comment]
It could be to do with the repeat attempts I've got some ideas

**Comment by Gymnasiast** [comment]
The error in https://github.com/OpenRCT2/OpenRCT2/issues/10196 appears to have the same origin (game action throwing error, but the wrong message is displayed. Though 10196 additionally returns errors when it shouldn't throw one at all).

**Comment by Gymnasiast** [comment]
I have now tested this.

In vanilla, it doesn't allow building the Haunted House, because it is above tree height. This is correct.

In OpenRCT2 (git version 4c2a0f279b62d374a6aa57fd4fa344d035db0996 ), this behaviour is now the same, with the correct error message.

Because of this, I'm going to consider this fixed.
