### ISSUE TITLE
No ratings generated when a shop and track intersect

### ISSUE THREAD

**Issue by Lamalas** [OpenRCT2/OpenRCT2#10376]
OS: Windows 8.1
Version Open RCT2: e.g. 0.2.4 - 174
**ommit/Build: 18ba9b2 (automatically updateding launcher)

 In the challenge "Extreme Heights" I noticed that manny of my rides did not have a rating (Excitment, Intensity, nausia). They all remain on "Not yet available".

I removed every roller coast with this issue, but I can't make new roller coasters without this problem.

- [x] Reproducible in RCT2 (vanilla)? Yes
- [ ] Specific to multiplayer? no, this is single player

**Dump file**

**Screenshots / Video:**

![Stats not yet available](https://user-images.githubusercontent.com/58884911/70851839-cf4dca00-1e9a-11ea-9f8a-26d4072a1427.jpg)

**Save game:**

[Ratings not generated Extreme Heights - kopie.txt](https://github.com/OpenRCT2/OpenRCT2/files/3964057/Ratings.not.generated.Extreme.Heights.-.kopie.txt)

**Comment by jensj12** [comment]
Double-close coasters until it starts working again (if double-close is not enough, edit a piece of track). I have seen cases where the ride rating calculator would get stuck on Flaming Fury, so try that one first.
This bug is quite normal in parks with hacked rides, but I’m not sure what causes it here.

**Comment by Lamalas** [comment]
Thank you for your reply. I tried editting every coaster I have so far, including the flaming fury but it didn't make a difference. I started over, but I'm eager to find out what caused it, so I don't run into the problem again.

**Comment by duncanspumpkin** [comment]
If a ride can't get its ratings then it will block all other rides getting their ratings. Its usually caused by hacking coasters. Its not possible without hacking (as far as I know)

**Comment by Lamalas** [comment]
I wouldn't even know how to start hacking. I deleted the flaming fury and the problem was solved. :)

**Comment by IntelOrca** [comment]
The issue is caused by Fried Rice Noodles Stall 1. If you inspect the tile that is on, you will see two track elements that have the same base height but belong to different rides. This causes an infinite loop in the track loop.

The problem is that if we limit to just track belonging to the same ride, you would no longer get ratings for coasters which change track type mid-way (using different rides).

![image](https://user-images.githubusercontent.com/1482259/70865891-6e85c680-1f5a-11ea-8ade-b7861a52684e.png)

**Comment by Gymnasiast** [comment]
@IntelOrca I suppose it would be possible to have the algorithm prefer track belonging to the ride itself, or not to take shops into account (either by ride type or by track piece ID), wouldn't it?

**Comment by Lamalas** [comment]
Thanks for the help guys, you are the best!
