### ISSUE TITLE
Tile Inspector's selected tile is no longer highlighted

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#10410]
**Version:** 0.2.4-222
**Commit/Build:** a2b9598

The selected tile used to be highlighted when you weren't hovering over another tile. This no longer happens - no tile gets highlighted at all when hovering over an interface or the black void anymore.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the tile inspector
2. Select a tile
3. Place the mouse over an interface or the black void
4. Observe how the selected tile doesn't get highlighted anymore

**Comment by Gymnasiast** [comment]
Most likely a small error in one of the coordinate refactors.

Tagging @duncanspumpkin and @tupaschoal .

**Comment by tupaschoal** [comment]
Not sure what the bug is. When I hover over a tile with the tile inspector, it highlights its borders in white. If I move the mouse it moves to the next tile.

Is that what you meant by the bug? Or did it use to get highlighted permanently in a different color.

I don't use the inspector too much, so I'm kind of unsure

**Comment by duncanspumpkin** [comment]
Found the source of the bug and I've a fix as well
