### ISSUE TITLE
peeps unable to use uphill paths out of toilets

### ISSUE THREAD

**Issue by DollyMixedUpWoman** [OpenRCT2/OpenRCT2#10634]
**OS:** Windows 10

**Version:** v0.1.2

**Commit/Build:** 6547116

Guests get stuck when exiting toilets onto a sloped path. They walk through the path rather than up the hill. When the path tile is deleted they fall through the base land and out of the game. 

- [unknown ] Reproducible in RCT2 (vanilla)?
- [no ] Specific to multiplayer?

**Steps to reproduce:**
1. build toilets at the bottom of a hill
2. build path tile
3. watch peeps get stuck
4. delete path tile to release them
5. watch them fall to their doom

**Screenshots / Video:**
![2020-01-29](https://user-images.githubusercontent.com/33560724/73380654-583e8a80-42bc-11ea-974e-fa536c5743fa.png)

**Save game:**
[Cracking Glacier Park broken bogs.zip](https://github.com/OpenRCT2/OpenRCT2/files/4129385/Cracking.Glacier.Park.broken.bogs.zip)

edit to add: i had the same issue in a different scenario but can't remember what it was

**Comment by ocalhoun6** [comment]
Don't know if it's really a bug, but it might be related to this:

I've noticed that every time a peep exits a bathroom (and also first aid stalls), they first walk straight out for half a tile, then walk back to the bathroom door, and _then_ walk away from the bathroom normally.

My uneducated guess is that they're doing this here, too, but since the path is sloped upward and they walk straight outward from the bathroom, they walk straight through the path and end up getting stuck underneath it.

I just tried it with an upward-sloping path into the bathroom, and they do act weirdly when exiting, being drawn beneath the path for a while as they do their little in-and-out dance ... but on the upward-sloping paths, they don't get stuck.
