### ISSUE TITLE
Android: minimum version required

### ISSUE THREAD

**Issue by thenamelessone1** [OpenRCT2/OpenRCT2#10736]
Hi

What is the  minimum version of Android required to run without problems?

**Comment by AaronVanGeffen** [comment]
Currently, Android 4.4 is the required minimum.

**Comment by jessicajonesunitedkingdom** [comment]
Will the minimum version go up (a lot?) when openrct2 will have new features in the future?
I hope it won't pass the 7.1 version because my tablet is running that version.

**Comment by AaronVanGeffen** [comment]
Because OpenRCT2 handles most of the user interface using its own widgets and what not, we do not make a lot of use of (recent) Android-specific components. I do not expect it to go up any time soon.

To answer your question, Android 7 is certainly still common enough for us not exceed that yet. (Right now, we target 4.4, which is over 6 years old!)

**Comment by thenamelessone1** [comment]
Updated my journal!
