### ISSUE TITLE
Demolishing mazes does not give a refund

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#10985]
**OS:** Linux
**Version:** 0.2.4+
**Commit/Build:** ab50c888ff32d444e5b353102bf9f61089b3c84e

Normally, when demolishing a ride, part of its value is refunded. When demolishing a maze, however, the refund value is 0.

In my mind, this is a known issue, but I could not actually find it logged in our tracker. However, given how many times we patched a money overflow that would occur when refunding mazes, I would not be surprised if the lack of refund is a more-or-less intended side-effect…?

**Comment by duncanspumpkin** [comment]
Its by design. Mazes in the base game refund 0.

**Comment by AaronVanGeffen** [comment]
Hmm, should it, though? I find it quite counter-intuitive. This wouldn't be the first time we deliberately deviate from vanilla behaviour.

**Comment by duncanspumpkin** [comment]
I think it makes sense. I can understand refunding rollercoasters as the metal is worth something. Bushes on the other hand unless able to be recycled are pretty much worthless.

**Comment by AaronVanGeffen** [comment]
Who knows, they might get recycled for the next maze the player comes up with. :wink:

**Comment by Broxzier** [comment]
Mazes also do not refund anything when removing a single block. It makes sense to not refund anything for removing an entire maze.

**Comment by tupaschoal** [comment]
Funny enough, I found a website that allows you to [rent mazes](https://rentamaze.com/support/rentamaze-faq/), so reuse is definitely possible, though I don't know how widespread or feasible. They also [sell hedges for mazes](https://instahedge.com/). That being said, it seems like it takes [around seven years to grow a maze](https://www.theguardian.com/lifeandstyle/2007/jan/06/gardens1), so when building one, we ought to consider that is being bought semi-ready or ready.

So I guess it isn't far fetched to recover some money from the removal, I'd say it shouldn't be 100% because we might factor in damaging of the hedges, unusual format and etc.
