### ISSUE TITLE
Feature: Colored usernames on servers, depending on assigned role

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11512]
**OS:** [Windows 10]
**Version:** [0.2.6]
**Commit/Build:** [06bbf5d]

Something that would be nice to have is the ability to assign a color to a role on multiplayer servers, and then display usernames from people of that role in the assigned color in the chat.

**Comment by IntelOrca** [comment]
I wonder if we could just hack in a format code before the group name...

**Comment by janisozaur** [comment]
No, that doesn't work.

**Comment by IntelOrca** [comment]
You will need to use the real byte coding for it as we don't run the group names through the format token function.

**Comment by kitsiosvas** [comment]
Hello, I am interested if this issue is still open.

**Comment by tupaschoal** [comment]
Yes, feel free to work on it.

**Comment by mattbilik** [comment]
Looking for a few pointers / a more robust spec for the issue -- thinking of taking it on if no one's on it already.

**Comment by janisozaur** [comment]
This is how colours get specified in translations: https://github.com/OpenRCT2/OpenRCT2/blob/03b0c1e884dec69392062a04cf2f9f226a23ae00/data/language/en-GB.txt#L563

This is how they get used in sources: https://github.com/OpenRCT2/OpenRCT2/blob/03b0c1e884dec69392062a04cf2f9f226a23ae00/src/openrct2/localisation/StringIds.h#L596

https://github.com/OpenRCT2/OpenRCT2/blob/03b0c1e884dec69392062a04cf2f9f226a23ae00/src/openrct2/paint/tile_element/Paint.Entrance.cpp#L61

Usernames are specified somewhere in src/openrct2/network, but it might make sense to use a string like https://github.com/OpenRCT2/OpenRCT2/blob/03b0c1e884dec69392062a04cf2f9f226a23ae00/data/language/en-GB.txt#L2565 to render usernames - so that they are only rendered in colour, but logged without any other suf-/prefixes.

**Comment by janisozaur** [comment]
It is ok to alter [OpenRCT2/data/language/en-GB.txt](https://github.com/OpenRCT2/OpenRCT2/blob/03b0c1e884dec69392062a04cf2f9f226a23ae00/data/language/en-GB.txt), other languages get handled in https://github.com/OpenRCT2/Localisation

**Comment by janisozaur** [comment]
Also consider approach suggested by @IntelOrca earlier. It seems more versatile - you'd have to make sure the group name gets passed in correctly

**Comment by evmarcus** [comment]
With @mattbilik, we're taking this request on!

**Comment by janisozaur** [comment]
Is that for a university course?

**Comment by mattbilik** [comment]
Yes -- hope that's alright!

**Comment by janisozaur** [comment]
Sure, we have student contributors occasionally. They often come in pairs. If you need any other guidance join our discord.

**Comment by mattbilik** [comment]
Hi all -- we've come up with a fairly straightforward fix. Thoughts?
