### ISSUE TITLE
Save file from RCT1 loads differently

### ISSUE THREAD

**Issue by rm5248** [OpenRCT2/OpenRCT2#11604]
**OS:** Debian 10(Buster)
**Version:** 0.2.6
**Commit/Build:** 6c3c857dfa5cd0d267b89a9d70930fbacdfbaea4(+ debian packaging fixes on my side; only updated things in debian/ folder)

The file saved in RCT1 deluxe(Steam version) does not load the scenario the same as vanilla RCT1.  The two obvious differences that I saw right away in the attached scenario:
* The path to "The Wooden Monkey" rollercoaster has a special style applied to it in the RCT2 version, whereas RCT1 loads the file correctly and does not have any style associated with it.  Actually, most of the paths shown in the screenshot seem to have this issue.
* The name of "Slide 1" is now "Spiral Slide 1"

This is a rather minor issue, but I noticed it right away as I was playing the vanilla RCT1 earlier today.  I've attached the original save file as well that was created with RCT1 and not saved with OpenRCT2 at all.

**Steps to reproduce:**
1. Load the file in RCT1, notice how the footpaths are normal and don't have a style/theme associated with them
2.  Load the file in OpenRCT2, notice how the footpaths now have a special style/theme associated with them

**Screenshots / Video:**
![rct1-monkeys](https://user-images.githubusercontent.com/56099/80897181-3a6e3080-8cc4-11ea-8c6b-7428855198ea.png)
![Screenshot from 2020-05-02 22-16-37](https://user-images.githubusercontent.com/56099/80897185-43f79880-8cc4-11ea-9f22-a429f2efb1d6.png)

**Save game:**
[threemonkeys.zip](https://github.com/OpenRCT2/OpenRCT2/files/4569521/threemonkeys.zip)

**Comment by tupaschoal** [comment]
I've bisected it as far as `v0.0.5` and it occurs at least since then.

**Comment by janisozaur** [comment]
@rm5248 I'm curious what kind of packaging updates you have? Something worth contributing?

**Comment by Gymnasiast** [comment]
Neither of these are bugs, really.

1. Occurs because the SV6 does not support separate paths and railings - they are always together. OpenRCT2 tries to find the closest match. Support for separate path and railings types is planned, but can only be introduced when the new save format is there. https://github.com/OpenRCT2/OpenRCT2/issues/2253 tracks this feature request.
2. RCT1 has not given any name to the spiral slide. It therefore shows what is set as default. In RCT1 this default is "Slide 1", in OpenRCT2 it's "Spiral Slide 1". Apart from being a very minor thing, it's very hard to import these names exactly - OpenRCT2 would need to have a separate table of (checked) RCT1 names, including translations for all RCT1 versions, just because it doesn't 100% match.

**Comment by rm5248** [comment]
:+1: 

I figured that they probably weren't bugs, but I figured that I should report just in case.  Thanks for the info!

(I wasn't able to find any list of known differences between the current OpenRCT2 and vanilla)

**Comment by Gymnasiast** [comment]
No problem, I'd rather have one bug report too many than one too few.

The differences have been documented here: https://github.com/OpenRCT2/OpenRCT2/wiki/RCT1-Features-not-in-RCT2 (page is in need of a cleanup, but all the info should be there.)
