### ISSUE TITLE
plugins should have a required license field

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#11614]
Right now the plugins are all wild west with almost none of them specifying the license used. This should be a required field of manifest to clear up any confusion lack of it raises.

**Comment by spacek531** [comment]
Why should OpenRCT2 enforce plugin licenses?

**Comment by janisozaur** [comment]
I'd gladly restrict the list to only allow [limited selection of licenses](https://opensource.org/licenses) but would like to hear from others before that happens.

It's to ensure users know what kind of license the plugin is distributed under and if they can modify it, redistribute it, etc.

**Comment by spacek531** [comment]
That does not answer my question. Why should OpenRCT2 enforce plugin licenses? Minecraft has many plugins, and does not enforce licenses; only minecraft forums enforce licenses.

**Comment by AaronVanGeffen** [comment]
There appears to be a misunderstanding. Enforcing licences is not something the OpenRCT2 team intends to do — frankly, nobody has time for that. However, it would be a waste to see plug-ins disappear just because it is unclear to what extent their code can be reused.

What licence to use will remain up to the plug-in authors themselves. The issue is with plug-in authors not stating _what_ the licence is.
