### ISSUE TITLE
erratic zooming with mouse wheel

### ISSUE THREAD

**Issue by jamesixgun** [OpenRCT2/OpenRCT2#11623]
**OS:** Mac OSX Catalina 10.15.4
**Version:**  Version 0.2.6 (develop)
**Commit/Build:** 174b32c09

Zooming with the scroll wheel is somewhat erratic. It's expected to zoom in on the mouse pointer, and that's how Classic and previous versions of OpenRCT2 worked. Something changed in the develop version a couple of iterations ago and zooming in the current develop version is erratic, sometimes zooming to the opposite side, sometimes zooming to some random point, sometimes zooming as expected.

- [ ] Reproducible in RCT2 (vanilla)? nope
- [ ] Specific to multiplayer? unknown

**Steps to reproduce:**
1. open a map
2. zoom using the mouse wheel

**Screenshots / Video:**
Video of issue...  https://youtu.be/wR1T4N0ASlg

**Comment by AaronVanGeffen** [comment]
Good to hear someone else is experiencing this. I can't consistently reproduce this, myself, but I have also come across this behaviour.

**Comment by oli414** [comment]
Usually happens to me when quickly zooming all the way in and out, might possibly be related to the map edge once again

**Comment by Gymnasiast** [comment]
@oli414 Which platform are you on?

**Comment by oli414** [comment]
@Gymnasiast Windows

**Comment by Ruuttu** [comment]
How to reproduce:
- Use a window scale factor greater than 1.
- Engage edge scrolling by keeping the cursor on the left or right edge of the screen.
- Use the wheel to zoom in and out while edge scrolling.
- Notice in every few zooms the map jumps to a wildly different place.

I don't know if all these conditions are required, but the issue is very easy to reproduce with them (:

**Comment by outerwear** [comment]
Was able to reproduce on Manjaro linux pretty consistently: 
1) start a new game, any map (I chose the first one Castle Lake)
2) place view and cursor to middle of the map
3) zoom out to max
4) repeatedly scroll zoom in 1 step, then back out without moving cursor. It will eventually jump to the void. 

I added some log messages to print out when running from command line and see that occasionally the returned mapcoords would jump to 0. This is because inside get_map_coordinates_from_pos() it would set them to info.Loc but that is sometimes NULL if the conditionals above it do not resolve. I noticed this happened if the window was a null pointer or if the screenCoords (which are just the mouseCoords) end up getting corrupted somehow. 

I haven't spent much time looking at it, but the g_window_list must be returning no window incorrectly for the case of a nullptr. I created an 'else if (window == nullptr && flags == 0) {}' to see if I could end up in that new block of code and it was successful! But determining the correct values to draw was difficult because without the proper window and viewport I was unable to determine things like zoom level. I then attempted to use the viewport up the stack by modifying the call to instead be passed &w->viewport from the window_viewport_get_map_coords_by_cursor() since it is looking for a double pointer. However that doesn't seem to have the correct values either, and if the mouseCoords get corrupted between that function and get_map_coordinates_from_pos() then we are hosed.

Maybe someone with more familiarity around the global window list would understand this faster. But I wanted to share my findings because that zoom issue was one I've noticed as well and happy to see an open issue for it.

**Comment by AaronVanGeffen** [comment]
Thanks for debugging the issue, @outerwear. It sounds like it could be the result of recent refactoring indeed. Thanks to your observations, perhaps someone involved in the process will have an idea what's wrong.

**Comment by frutiemax** [comment]
@AaronVanGeffen I don't think this is recent, I've seen the bug up to the version 0.2.3...

**Comment by ZehMatt** [comment]
Theres also an issue when pionting outside of the map and zooming

![s8LVMGHcB0](https://user-images.githubusercontent.com/5415177/88465816-497d0d00-cec6-11ea-8578-d92131bbad06.gif)

When I point inside the map it goes where the cursor is at, when I point outside of the map it will jump to the opposite of the map.
