### ISSUE TITLE
Instant Crash on Apple Computer

### ISSUE THREAD

**Issue by lucidreality2** [OpenRCT2/OpenRCT2#11693]
Trying to run OpenRCT2-0.2.6-macos-x86_64 and program will instantly crash before any window opens.  Running macOS Sierra Version 10.12.6 with the following specs:

<img width="331" alt="Screen Shot 2020-05-09 at 5 04 51 PM" src="https://user-images.githubusercontent.com/6758280/81484879-39368980-9217-11ea-8a5b-c4e3ee1d1c1c.png">

**Comment by AaronVanGeffen** [comment]
Are you trying the 0.2.6 release, or a development build?

The 0.2.6 release still supports macOS 10.12, but any of the recent development builds require macOS 10.14 or higher. It’s unfortunate, but we had to increase the requirements for the plugin system.

**Comment by avenged110** [comment]
I know I'm a little late to the party, but just discovered today that 0.2.5 and 0.2.6 release builds both crash instantly on OS X 10.9.5 (my version of choice). I know the 0.2.6+ development build apparently doesn't support 10.9.5 anymore, but it's unfortunate because 0.2.4 works and 0.2.6 lists 10.8.0 as the minimum version.

![Screen Shot 2020-05-16 at 2 14 42 PM](https://user-images.githubusercontent.com/19438529/82130370-a4d0a780-977f-11ea-8191-42ecbdca18ca.png)

**Comment by AaronVanGeffen** [comment]
Unfortunately, it looks like some of the libraries we use have dropped support for older versions of macOS without us knowing.

You could try building v0.2.6 and the libraries it uses manually, but I don't see us altering the builds at this point, sorry.

**Comment by avenged110** [comment]
Yeah, I figured as much. Just wanted to let you know. 0.2.4 for life.

**Comment by lucidreality2** [comment]
Hi whoops this ended up in a weird folder on my computer.  So if I update
my OS and try updating it should fix the issue?
-Connor

**Comment by AaronVanGeffen** [comment]
@lucidreality2 Yes. However, please be advised that macOS 10.15 drops support for 32-bits applications. If you are still using any, you may have to update them as well. (Please Google around for a guide on how to check.)

**Comment by Gymnasiast** [comment]
The upcoming 0.3.1 release (and current develop) has lowered the minimum macOS version to 10.13. Unfortunately, that's about as low as we can go without having to sacrifice a lot of nice C++ features.
