### ISSUE TITLE
Floating Shops

### ISSUE THREAD

**Issue by chensam93** [OpenRCT2/OpenRCT2#11930]
Windows 10 Home
Version: 0.2.6
Commit/Build: 1ea1d24

I was fiddling around with making shops and stalls, and placed a Donut Shop in front of a ride entrance line. I'm guessing it's just me simply making a stall with an elevation, but I just wanted to make sure there wasn't anything deeper about this.

**Screenshots / Video:**

![Capture](https://user-images.githubusercontent.com/56238240/84339094-8c6f6500-ab52-11ea-9b0b-a3313cb831a2.PNG)

**Comment by IntelOrca** [comment]
Expected. If you hold shift, it will automatically place the shop at the next possible height. If you move your cursor you can select between all possible altitudes including underground.

**Comment by AaronVanGeffen** [comment]
The issue here is with the chip shop, not the donut shop, right? I agree the lack of supports is expected behaviour, though.

**Comment by Gymnasiast** [comment]
> Expected. If you hold shift, it will automatically place the shop at the next possible height. If you move your cursor you can select between all possible altitudes including underground.

@IntelOrca You don't even need to hold shift - it would autoposition the stall at the first valid height. Agree it's expected behaviour.

@chensam93 This looks like correct behaviour, assuming you're talking about the chip shop. But it's fine you checked anyway - I prefer a false positive to a false negative.
