### ISSUE TITLE
Potentially uninitialized local pointer variable in game.c

### ISSUE THREAD

**Issue by kevinburke** [OpenRCT2/OpenRCT2#121]
When attempting to compile in VS2013, I get the following errors:

```
error C4703: potentially uninitialized pointer variable `widget` used on line 526 of game.c
error C4703: potentially uninitialized pointer variable `widget` used on line 647 of game.c
```

I am confused because the game reported a successful compile on openrct2.com/download. Does everyone else use "Build" with less restrictive settings? I just used whatever the default was for VS2013.

**Comment by Gymnasiast** [comment]
Does this still apply to the current code?

**Comment by janisozaur** [comment]
The code has moved to https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/input.c#L798 and I don't think this warning is valid. I ceratinly haven't seen it with clang/gcc compiles.

in line 798 `widget` is declared without explicit assignment, in line 800 `if (w != NULL)` then in line 803 `widget` has value assigned. In line 808, which was previously 526 mentioned in original report, there is a check `if (w != NULL && widgetIndex != -1 && widget->type == WWT_SCROLL)` which dereferences `widget` if and only if `w != NULL`, which guaranteed value assignment in line 803 above.

An assert could be added just after assignment in line 803 to see if widget is not NULL, but otherwise it looks fine.

**Comment by Gymnasiast** [comment]
Considering the changes since 2014 and janisozaur's comment I'll assume this no longer applies to the current state of the code.
