### ISSUE TITLE
Add OGG support

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12237]
This is needed to load the music and sound effects from RCT Classic.

**Comment by AaronVanGeffen** [comment]
Probably also a requirement for supporting alternative assets from the OpenMusic and OpenSounds projects.

**Comment by Gymnasiast** [comment]
Either that, or FLAC: https://github.com/OpenRCT2/OpenRCT2/issues/393

**Comment by Androgeos** [comment]
Wouldn't FLAC massively increase the size of the game, or is that a non-factor since provision of the files depends on the player?

**Comment by RQWorldblender** [comment]
At least adding OGG and/or MP3 support would allow for adding more custom music easily, without having to do the conversion to WAV first.

> Probably also a requirement for supporting alternative assets from the OpenMusic and OpenSounds projects.

Where can I find the OpenMusic and OpenSounds projects, so I can tell what they sound like?

**Comment by Ruedii** [comment]
If we're going to be adding new music format support, I'd like to see it to support as many formats as possible, as well add support for custom music.

For major open source formats this means Vorbis, FLAC and Opus in Ogg and WebM encoding as well as FLAC in raw encoding.  This should be done natively and should be possible with the built in tools of SDL.  

A wrapper to use additional codecs on the machine (platform specific) should also be possible.   SDL should be configured to use Windows Media on Windows, GStreamer on Linux and Android's standard codecs on Android.  I'm not sure what standard library should be used on Mac.  I'm sure an Apple fan can tell me.

No point in not hitting as many birds with one stone when fixing this.  

I recommend against distributing with MPEG support other than by OS installed codecs due to the ridiculous over-extension of software patents by MPEG group.  The same goes for WMA format and Apple Lossless.  Instead, just saying "also supports what your OS supports" should be a better way to handle these.   Meanwhile I'm going to grumble something about Lucent Technology patenting the standard ISO quality control loop being applied to audio.

**Comment by AaronVanGeffen** [comment]
> Where can I find the OpenMusic and OpenSounds projects, so I can tell what they sound like?

They're part of the OpenRCT2 organisation.

> If we're going to be adding new music format support, I'd like to see it to support as many formats as possible, as well add support for custom music.

I would rather not, as each added format comes with a maintenance burden. Particularly with the plan you lay out, where each platform uses one or more different libraries...

**Comment by Ruedii** [comment]
I've done a little research.

It looks like the Xiph codecs would be the most easy to implement cross platform, as they are available as descrete cross-platform libraries so there is no worrying about differences in platform codec support. 

libfishsound is a good universal decoder for FLAC, Speex and Vorbis and combines with liboggz.   
For opus support, opusfile can be used.

As of Ogg encoded audio, this leaves CELT which is pretty much inferior in every way to Opus for the purpose of OpenRCT2.

**Comment by Gymnasiast** [comment]
Implemented by #17217.
