### ISSUE TITLE
Port RCT1 Ladybug and Log Trains to Classic Mini Roller Coaster

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#12328]
**OS:** GNU/Linux
**Commit/Build:** 33898936b02cab6039013cab78b058b81510fe1e

- [ ] Reproducible in RCT2 (vanilla)? N/A
- [ ] Specific to multiplayer? No

**Problem**
There seems to be some problems with RCT1 scenarios concerning the mini coaster.

**Steps to reproduce:**
1. Play RCT1 scenario Diamond Heights
2. Click build window
3. Notice that "children's coaster” is there (a RCT2 thing), but this is not exactly correct at this track type doesn't support steep drops
4. Use tile inspector to look up the rollercoaster type of the Arachnophobia. It's “classic mini coaster”. This makes sense
5. Click on Arachnophobia and click the vehicle tab. Click on the vehicle dropdown. Notice that the list is empty. Maybe it's because ladybugs are not supported by “classic mini coaster”?

**Context**
RCT1 has a rollercoaster which doesn't seem to have an exact equivalent in RCT2 and OpenRCT2.

* RCT1 mini coaster has steep drops and 3 cars: ladybug, log and rocket.
* RCT2 mini coaster is completely different, has a different track and vehicles and also no steep drops.
* RCT1 mini coaster is more similar to the RCT2 “children's coaster” but this one doesn't support steep drops.
* The closest match to the RCT1 mini coaster is the “classic mini coaster”, but this only supports the rocket vehicle for some reason, not the ladybug or log

**Possible solution**
* Consider all RCT1 mini coasters to be “classic mini coasters” in OpenRCT2 since this seems to be the closest match
* Add support for ladybug and log vehicle to classic mini coaster

**Comment by Wuzzy2** [comment]
Oh, something other I noticed in Diamond Heights:

When I activate "ignore research status" I notice that “mini coaster” (RCT2), “classic mini coaster” and “children's coaster” (RCT2) are all available. But only one of them is actually in the original scenario (classic mini coaster).

**Comment by Gymnasiast** [comment]
The problem here stems from the fact that what RCT1 calls the "Steel Mini Roller Coaster" was essentially an amalgamation of the Zierer junior coaster (track style, ladybird trains, log trains) and Schwarzkopf's compact coasters (height, steep drops, rocket cars). This is why RCT2 split up the two.

Now, we are working on reintroducing the RC variant as "Classic Mini Roller Coaster". Currently, every RCT1 "Steel Mini" roller coaster is already imported as such. 

As for the vehicles: the RCT2 variants of the Ladybird and Log trains lack sprites for steep drops. This is why currently only the Rocket Cars are available on the Classic Mini RC. We need to port the actual Ladybird and Log trains to .parkobj files, but that requires matching hundreds of sprites, which is a lot of work. So, as a hack, we currently use the RCT2 Junior RC variants.

**Comment by X123M3-256** [comment]
@Gymnasiast Don't know if it's useful to you but I ported the RCT1 ladybird and log trains to DAT files a while ago. I might still have the files. The actual sprite matching is honestly not too much of an issue, however, the RCT1 trains only have 16 sprites per rotation. If you simply duplicate sprites, they don't quite animate correctly which is why I haven't used the ported trains since.

**Comment by Gymnasiast** [comment]
Implemented in #17418.
