### ISSUE TITLE
Remove goto from Tick128UpdateGuest

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12338]
https://github.com/OpenRCT2/OpenRCT2/blob/d10b615eb33f6cd597340d83d68eaaa97c1a493e/src/openrct2/peep/Guest.cpp#L820-L823

**Comment by Ron4u** [comment]
hello, i am new to open source projects. But, i have studied quite a lot about c++. i believe there is no requirement of removal of usage of goto in the method Tick128UpdateGuest because essentially what goto loc_68F9F3 is doing is braching downwards and out of the branch it is present in and it is the most powerful and correct usage of goto there is.

i suggest that there no requirement of removal of goto statement.

i would like to quote someone else"s explanation here also:

There seems to be universal agreement that goto should never be used to branch UP to an earlier point in a function. Likewise, branching INTO a deeper level of nesting is a universal no-no.

However, branching DOWN in the function and OUT to an outer level of nesting are often described as powerful uses of the goto keyword. For example, a single goto statement can be used to escape from two or more levels of nesting.

please correct me if i am wrong and if theres is really a requirement i would like to do it.

Thank you

**Comment by duncanspumpkin** [comment]
No in this instance the goto just makes for horrible to read code. In general gotos should not be used except where performance, readability and simplicity is required. This is none of those. The function is not a high performance function, the code is less understandable due to the goto and it does not make the function simpler.
