### ISSUE TITLE
Implement RCT1 interest rate

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#12466]
When I start any RCT1 scenario, the interest rate is always 1%. However, some other player told me that the RCT1 interest rate should be 10%.

I don't know what is correct now. I opened this issue to make sure that RCT1 scenarios use the correct interest rate. Please, can somebody verify the RCT1 interest rate?

**Comment by duncanspumpkin** [comment]
Interest rate in RCT1 was 1.33% which we can't easily have in the game ATM so 1% was chosen as the closest available number.

**Comment by Gymnasiast** [comment]
It is indeed about 1.33%. I actually have a branch that changes the code so that the payments match _exactly_ with RCT1's. It would be possible to add a park flag or a special value to bring this kind of behaviour back.

For those interested (no pun intended), it's a single-line change to emulate RCT1 here:
```diff
diff --git a/src/openrct2/management/Finance.cpp b/src/openrct2/management/Finance.cpp
index 7c6490541..adc124e98 100644
--- a/src/openrct2/management/Finance.cpp
+++ b/src/openrct2/management/Finance.cpp
@@ -140,7 +140,7 @@ void finance_pay_interest()
         return;
     }
 
-    interest_to_pay = (current_loan * 5 * current_interest_rate) >> 14;
+    interest_to_pay = current_loan / 2400;
 
     finance_payment(interest_to_pay, RCT_EXPENDITURE_TYPE_INTEREST);
 }
```

**Comment by Makke94** [comment]
I was thinking of handling this. If I read this correctly I would add a flag to all RCT1 parks and do the other interest payment if that flag is set.

**Comment by ocalhoun6** [comment]
Unless you were to do something crazy like make a list of the RCT1 scenarios -- scenario name + scenario description for each one + maybe some other typically unchanged identifiers from the save files, such as park entrance and guest spawn location(s), if you *really* want to be sure you don't get any false positives.

And then when loading a scenario, you compare the scenario being loaded to this list of RCT1 scenarios. First just by scenario name, for speed, then if you hit a match on that, in more depth to make sure it's not a false positive with the same name. And if you find the scenario being loaded matches one of the ones in the RCT1 list, you apply the RCT1 interest rate.

Same goes for loading a saved game -- which is why it's important to choose identifiers that the player is unlikely to change. (Though if they go into sandbox mode and change things that make it no longer match the list ... well, I doubt anybody using sandbox mode on their RCT1 scenario is really going to care that the interest rate changed when they did so.)

The 'match it to a list' method works because nobody is adding any more RCT1 scenarios. It's possible to build a complete and definitive list of them.

That said, maybe it's not the _best_ solution -- it would involve quite a bit of extra code/complexity, and might decrease the performance of loading a scenario/save slightly -- but it _could_ be done without needing the NSF.

**Comment by Gymnasiast** [comment]
@ocalhoun6 Obviously, we already have a list like that - we use it so that SV6 conversions of RCT1 scenarios are recognised as such. But I would only apply this feature to actual SC4/SV4 files anyway, as some conversions (e.g. the ones from Crappage) have their loans adjusted for RCT2’s interest calculation algorithm.

------------

As for the need for the NSF to implement this: the new save format is not needed for this feature, as we could simply add an additional park flag to SV6 like we did to allow charging for both entry and rides. But with the NSF getting so close, adding more stuff to SV6 is not really worth it, I think.

**Comment by Makke94** [comment]
I've been working on this now with the release of NSF. Should I only do as proposed, when importing SC4/SV4 or should I add a setting for it in the scenario editor? If so, is that a separate issue or should I add it as part of this one?

**Comment by MASHzj** [comment]
Now that NSF is here for a while (as well as the code for the correct interest calculation and a list of RCT1 scenarios), I wonder if there are still plans to fix this issue? It might not be a big deal in most RCT1 scenarios where the loan is $10000, which makes the interest $12 instead of $16 per month. But it does matter a lot in some scenarios, especially in the real parks section. For example, in Alton Towers, with a loan of 4.77m, you lose almost $6000 each month on interest, while it should be almost $8000, thus making this scenario much easier than it originally was.
