### ISSUE TITLE
RCT1 Junior Roller Coaster designs don't show up in the Select Design menu

### ISSUE THREAD

**Issue by Cheter2** [OpenRCT2/OpenRCT2#12529]
**OS:** Windows 10 Pro Version 1909 (OS Build 18363.959)
**Version:** 0.2.6 Develop Branch
**Commit/Build:** cd86d3d (I'm not entirely sure when this bug happened, but it's definitely a few weeks old.)

The RCT1 Junior Roller Coaster designs dont show up in the Select Design menu.

As a bit of a side note, I downgraded my game to the latest stable version of the game, and both of the crazy caterpillar designs show up. This bug doesn't seem to affect the other rides in my testing.

**Steps to reproduce:**
1. Go into any scenario that has the Junior Roller Coaster in it. (I used "Build your own Six Flags Park" from the other parks tab)
2. Open up the Build new ride/attraction tab, and select the Junior Roller Coaster there
3. And pay close attention to the list of rides on the left. There should be two versions of the Crazy Caterpillar ride. One from RCT1 and another from RCT2. But only one version shows up as a result of this bug.

**Screenshots / Video:**
![Annotation 2020-07-30 185702](https://user-images.githubusercontent.com/48459112/88982522-80706b80-d296-11ea-9ac9-554911131cff.png)

**Comment by Fred-1044276** [comment]
This is because the RCT1 junior coaster designs (actually called the Steel Mini Roller Coaster) have now been moved to the Classic Mini Roller Coaster, which currently only has the rocket cars available. The Junior and Classic Mini coasters were previously part of "ride groups", but recently, the ride groups have been removed, with the rides in those groups now being their own ride types.

**Comment by Cheter2** [comment]
Oh ok, I never actually knew that. Thanks for pointing it out. The ride that I was looking for was found there so this is definitely intended behavior.
