### ISSUE TITLE
Disable multiplayer button when the user is running through Wine

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12688]
As one of the reasons we recommend against using OpenRCT2 in Wine is because its bcrypt implementation lacks the appropriate algorithms, it's probably better if we disable the multiplayer button outright to avoid crashes. This should also make it clearer to the user they're doing something wrong (as crashes are more often blamed on the game itself) and thus increase the chance they will ask about it on Google, the forums or Reddit.

**Comment by janisozaur** [comment]
I disagree. We already provide the"unsupported" message, this is enough. When wine is fixed this would cause problems again. Instead I would rather see wine skipping the upload of dumps, as for whatever reason they're not very useful.

**Comment by Gymnasiast** [comment]
Is it possible that we are calling a Windows API method, don’t bother checking the result and just continue with the assumption it did work? (In the same way that not checking for null causes trouble?)

**Comment by janisozaur** [comment]
I think it does report an error. Another thing I noticed with this was a malformed (0 byte) key was produced anyway and we tried and failed to import it next time I launched the client.

**Comment by Ruedii** [comment]
Has someone submitted a wine bug report for this.

They have been wanting dogfood reports like this (reports for applications that do have Linux versions) for years.

There is a clear well documented inconsistency in implementation here that should be resolved.

As of another question, why are we using Windows built in encryption functions instead of shipping a compiled cross-platform Open Source library?

**Comment by IntelOrca** [comment]
@Ruedii to reduce code size and allow it to be updated independently from the game, which is good for security related things. It also will use the OS provided certificate store rather than us providing one. We don't bundle OpenSSL or any other alternative on Linux builds either, we rely on that being provided by the OS.

**Comment by janisozaur** [comment]
Fixed in 7.0 (currently rc1): https://github.com/wine-mirror/wine/commit/2795c7f99509a740dffa88b50acd689592a8da7a

**Comment by Ruedii** [comment]
Since it's fixed, I don't think it is a concern, but instructing the user to hand download the dll would have been my temporary solution if a bad version was detected (just add a sanity check for the missing algorithms).  I would of course link to the OpenSSL website so long as they have a Windows binary available.

**Comment by janisozaur** [comment]
I'm not going to implement such checking and certainly not instructing users to replace parts of their wine. There is still something missing from the implementation, going to file a follow up ticket to previous one.

What I may do is to try limiting crashing in case of errors and mention wine there, but it's low priority.

**Comment by Ruedii** [comment]
How win64 implements dll calling allows you to put substitute dll in the
directory of the program.  Wine honors this behavior.

**Comment by janisozaur** [comment]
After testing this a bit more, there were further issues with wine. I filed a bug upstream: https://bugs.winehq.org/show_bug.cgi?id=52426

**Comment by janisozaur** [comment]
As of https://github.com/wine-mirror/wine/commit/f32a9d1e208930d453304aaf715415542445db1a this is now fixed - wine lets user play online - I did test a client and successfully connected to a server. This missed wine 7.0 release by a bit, but should be available in upcoming 7.1 devel release.
