### ISSUE TITLE
Windows cause issues with snow drawing

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#12940]
**OS:** Windows 10
**Version:** 0.3.0-develop
**Commit/Build:** 564cc7b

Snow above windows behaves differently from snow on other places. The speed might be different and snowflakes (dis)appear.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Force weather to snow with the cheats window open.
2. Move or open more windows if the problem is not visible.

**Screenshots / Video:**
Hard to see, but there is some distortion in the snow pattern above the vertical edges of the windows. Most notable are left sides of options and R&D window. It's easier to spot in-game.
![Micro Sandox 2020-09-16 11-39-22](https://user-images.githubusercontent.com/13868449/93320482-6f14fb80-f811-11ea-8306-da56439a1cba.png)

**Comment by tupaschoal** [comment]
I have to admit I'm having a bit of a hard time spotting the issue

**Comment by frutiemax** [comment]
There is an issue; there are 2 dots drawn next to each others instead of one.

**Comment by tupaschoal** [comment]
True, is that what you were referring to @jensj12 ? From the description I assumed it would be something broader

**Comment by jensj12** [comment]
Yes. Though it’s the entire part above a window where the snow behaves differently, in a screenshot this is only visible along the edges. I’ll try to upload a video soon.

**Comment by raacker** [comment]
@jensj12 Is this what you are referring to?
![bug_weird_snow](https://user-images.githubusercontent.com/12020398/96375823-32019900-1130-11eb-8007-730f02a7b52e.gif)

**Comment by raacker** [comment]
It is basically happening because of cosine function in [Weather.cpp#L135](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/drawing/Weather.cpp#L135). Cos function is very good to have here but putting "left" of window value make the snow movement very weird. But even without the left value, movement looks still fine. We might can just adjust other values to move a bit better.

![with_left_snow](https://user-images.githubusercontent.com/12020398/96376686-48f6ba00-1135-11eb-94dc-fff4e6658b42.gif)

![without_left](https://user-images.githubusercontent.com/12020398/96376696-5ad85d00-1135-11eb-937e-582c05a608a4.gif)

I looked at the PR [Let it snow #10754](https://github.com/OpenRCT2/OpenRCT2/pull/10754) but seems this problem didn't get any attention.
