### ISSUE TITLE
Remove hardcoded {SMALLFONT}{BLACK} from all tooltips

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12993]
In general, presentation should not be the responsibility of the strings. There are far more examples, but this one should be quite easy to do and make a nice difference.

**Comment by duncanspumpkin** [comment]
How would you want to go about changing it?

**Comment by Gymnasiast** [comment]
Not sure. I suppose you could render to a buffer and then to a `{SMALLFONT}{BLACK}{STRING}` string, but I'm sure there are other (and better) ways.

**Comment by AaronVanGeffen** [comment]
Tooltips are all prepared in the same place, right? That means that we can indeed allocate a buffer of the right length when the tooltip is created. Then, add the code points for font and colour, and append the string in question. After that, we can just paint  the buffer.

**Comment by gsckoco** [comment]
Are there any occurrences where tool tips use anything other than `{SMALLFONT}{BLACK}`? If not surely this could just be changed where you render the tooltip?

**Comment by IntelOrca** [comment]
@gsckoco that is what this issue is suggesting.

I think I would do it how @Gymnasiast suggested. Use format string with a generic string ID that chains to the given tooltip string ID. Ideally these format strings would go directly in the code rather than being another resource string but we don't have that setup very easily at the moment.

**Comment by duncanspumpkin** [comment]
String 1812 is small font format black string id  it can be used for this.

**Comment by Lukasz-Pe** [comment]
I did it like @duncanspumpkin suggested.
