### ISSUE TITLE
Add Support for 'Ultimate Marketing' Cheat

### ISSUE THREAD

**Issue by hhcarpenter12** [OpenRCT2/OpenRCT2#13018]
This feature adds support for the 'Ultimate Marketing' cheat. When this cheat is enabled, a large number of guests will come to your park. As seen in the image below, the park population went from 0 to over 800 guests in just one month!

Currently, the game offers the 'Large Tram' cheat to generate numerous guests, but it only generates around 200 guests with one click. The 'Ultimate Marketing' cheat will generate a large number of guests as long as the checkbox is selected.

![2020-09-27 20_12_55-Window](https://user-images.githubusercontent.com/57320198/94381316-92d41d80-00fe-11eb-80ea-b2258d94c8bb.png)
![image](https://user-images.githubusercontent.com/57320198/94381657-bd72a600-00ff-11eb-8aba-96d3871cb4be.png)

**Comment by tupaschoal** [comment]
The large tram button already spawns ~200 guests instantly, does hitting it (a few times) not suffice? 
![image](https://user-images.githubusercontent.com/6443427/94382189-2cf19100-0112-11eb-804b-7c41c6c267d2.png)

**Comment by hhcarpenter12** [comment]
I'm thinking about adding this feature so that players can have more control over the number of guests generated, and to make the large guest generation more automatic instead of pressing a button a few times. It might be cool to enhance it a bit to control how quickly the guests are spawned by using a 'more' or 'less' button, but the coding might take some time to implement.

**Comment by ocalhoun6** [comment]
I think I see where you're going with this. It makes the generation of more guests a bit more natural.

If I might suggest...

To make a more granular (and more useful) version of this, have a little drop-down menu that says:
"Guest generation:"
--> 1%
--> 10%
--> 50%
--> Normal (100%)
--> 2x
--> 5x
--> 10x
--> 100x
And have it just apply the appropriate multiplier within the code that the game uses when it decides whether to generate a new peep during this tick or not.

Then you'd still be able to generate peeps in a natural-ish way (instead of the insane waves from the large tram), and you'd have some fine control over just how much you want to cheat. And (because it would probably be pretty easy to do so at the same time) it also provides the ability to have _less_ peeps generated if your park is overcrowded.

I could see this being useful in scenery showcase type parks where you want an appropriate level of peep crowding depending on the theme/look you're going for. Having too many or too few peeps wandering about could make an otherwise beautiful park look a little weird.

**Comment by hhcarpenter12** [comment]
I appreciate your suggestions with this new cheat. It may take some time to develop since I only have a working knowledge of C++ and new to the code base, but I think this will be a really meaningful side-project for me.

**Comment by duncanspumpkin** [comment]
Develop it as a plug-in. I don't see there being any reason for this to be in the codebase. Plugins can be written in any language that can compile to js.
