### ISSUE TITLE
Vehicle collission causing negative number of passengers

### ISSUE THREAD

**Issue by keithstellyes** [OpenRCT2/OpenRCT2#13222]
**OS:** Linux
**Version:** 0.3.1
**Commit/Build:** 645289f4ec1b1c5ed1475da63190153d99f0b406

After a collision in which everyone died (28), info panel for the ride listed -28 passengers on ride. Save/reload fixed issue.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Have fatal crash of all trains on a ride

**Screenshots / Video:**
![loopy-lenny](https://user-images.githubusercontent.com/13317074/96328960-632d7c80-0ffd-11eb-86be-a06f84371cf6.png)
![negative-customers](https://user-images.githubusercontent.com/13317074/96328961-63c61300-0ffd-11eb-8120-e8ccdca163c9.png)

**Save game:**
[ll.zip](https://github.com/OpenRCT2/OpenRCT2/files/5395024/ll.zip)

**Comment by raacker** [comment]
@duncanspumpkin It seems actually causing the issue if you see the fix. Because when peep_sprite_remove is called, [peep remove from ride itself](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/Peep.cpp#L803). So decreasing num_riders from current ride is double action. 

![kill_passengers_bug](https://user-images.githubusercontent.com/12020398/96404523-fd252e80-118f-11eb-97b1-400dd7cd4ba1.gif)

![kill_passengers_bug_fix](https://user-images.githubusercontent.com/12020398/96404527-fe565b80-118f-11eb-8812-d6c7e01008b9.gif)

**Comment by duncanspumpkin** [comment]
Yeah I'm not sure which one is correct though.

**Comment by raacker** [comment]
@duncanspumpkin Well, for this negative passenger bug, just removing the line will fix it. Though, I was trying to reproduce #13234 but this fix doesn't help and I really couldn't get reproduction case yet.

**Comment by duncanspumpkin** [comment]
So i think this is actually an original bug. Customers on ride was not in the original game we added that field. So I suggest we remove the count decrement from vehicle.cpp
