### ISSUE TITLE
Can no longer place Bumble Bee track design

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#13336]
**OS:** Ubuntu 20.04
**Version:** 0.3.1+
**Commit/Build:** 1f7d73a741110f6608124226647eda2af716d342

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

Bumble Bee is a Looping RC designs which can no longer be placed due to this commit: https://github.com/OpenRCT2/OpenRCT2/pull/12707

**Comment by Jay2645** [comment]
I'm seeing this, too -- a number of my designs can't be placed now because of #12707, including a solid chunk of prebuilt rides. I dislike having to use cheats because of the fix to a visual bug, especially when that fix breaks functionality that we have in vanilla. Can #12707 be reverted or at least make it so the "fix" to interlocking loops doesn't block saved rides from being built?

Not to mention the message it gives as to why you can't place these rides is very unclear -- `"Can't place <track design> - In the way"`. It's because the ghost is colliding with itself, but the message is so vague it's only when @LordMarcel brought up the issue in one of his streams that I figured out why a chunk of my designs suddenly weren't working. I _believe_ it applies to Wooden Coasters as well, since I noticed the same message with a couple of my Wooden Coaster designs.

Notably, it appears that there are no in-game thumbnails for any prebuilt with this issue, which at least makes it a bit more obvious which designs have issues. But it's ridiculous to me that you have to do a workaround of enabling cheat mode (which could possibly cause other issues with clearance, since clearance checks are disabled entirely) just to fix a visual bug.

**Comment by Gymnasiast** [comment]
I would not call it a "visual bug" - RCT2's bounding box was incomplete. Nevertheless, I consider the fact that the fix prevents placing track designs that worked in RCT2, including a few that came with the game a bug, which is why I created the issue in the first place.

Also, the track list previews are created by placing the track design in an area of its own and then taking a screenshot, which is why you don't get a screenshot if the track design has an issue of some kind.

**Comment by X123M3-256** [comment]
@Jay2645 I wouldn't cal this "just a visual bug" - the original RCT2 clearance boxes are incorrect and don't actually allow sufficient clearance. The prebuilts that now fail are those that have track so close to the loop that trains would collide with it, and if you look closely you can see the vehicle sprites clip through the track on the loop.

I do think it's awkward that certain vanilla track designs now can't be placed without ZC. I don't think the original clearance boxes should be restored as they were incorrect, but I think an exception should be added for placing track designs that were buildable in vanilla.

**Comment by Gymnasiast** [comment]
I suppose a fix could be to allow track designs to intersect with themselves, but nothing else.

**Comment by IntelOrca** [comment]
@Gymnasiast If I am right in understanding your suggestion... disable clearance only for scenery and track pieces that are part of the design and not already in the park. I am not sure how difficult that would be to implement.

**Comment by Fred-1044276** [comment]
Apologies for the bump and if I already said this, but here's a zip file with fixed versions of the four vanilla prebuilts that became unbuildable without ZC (Atomizer, Bumble Bee, Deep Freeze, Octivator):
[FixedVanillaTD6s.zip](https://github.com/OpenRCT2/OpenRCT2/files/6159441/FixedVanillaTD6s.zip)

**Comment by jeffinbville** [comment]
> Apologies for the bump and if I already said this, but here's a zip file with fixed versions of the four vanilla prebuilts that became unbuildable without ZC (Atomizer, Bumble Bee, Deep Freeze, Octivator): [FixedVanillaTD6s.zip](https://github.com/OpenRCT2/OpenRCT2/files/6159441/FixedVanillaTD6s.zip)

Thank you. This has been driving me crazy.
