### ISSUE TITLE
Ride simulation causes strange station behaviour and makes the ride unusable in some cases

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#13397]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** a3b7ae7

I was building a reverse-incline coaster and at some point I could no longer use the ride simulation. When the coaster was finished I could not open or test the ride, and the error message was rather strange ("Land not owned by park"). After some trial and error I managed to reproduce the issue in a test park. It seems that when you use ride simulation with an operating mode _other_ than "Continuous circuit", in combination with a certain order of operations, it causes the station to glitch, leading to strange behaviour and strange error messages.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start building a coaster that has reverse-incline, or powered-launch operation modes. In the example here I use the corkscrew coaster.
2. Make a station
3. Make sure there currently a station-ghost-piece in front of the station
4. Set the operating mode to reverse-incline or powered launch.
5. Start the ride simulation. Note in the screenshots below the difference between "continuous circuit" and "reverse incline": In "continuous circuit"-mode the ghost train only occupies the real station, in the other mode the ghost train also occupies the station-ghost-piece:
![b1](https://user-images.githubusercontent.com/5968886/98472649-bbb6fa80-21f4-11eb-97c4-efad094f6984.png)
![b2](https://user-images.githubusercontent.com/5968886/98472651-bce82780-21f4-11eb-8999-970c8f83012c.png)
6. Do _not_ build the extra station piece, and simply complete the track.
7. Now the strange behavoir starts:
    1. The ride simulation can no longer be restarted. It shows the error "Land not owned by park"
![b3](https://user-images.githubusercontent.com/5968886/98473088-3bdd6000-21f5-11eb-8052-3b01ed6fde5d.png)
    2. The entrance/exit of the ride can be placed at a seemingly invalid location
![b4](https://user-images.githubusercontent.com/5968886/98473419-56afd480-21f5-11eb-909b-62b06618ea9b.png)
    3. The ride cannot be opened or tested, also with the error "Land not owned by park". Also notice that the front station piece appears to be missing.
![b5](https://user-images.githubusercontent.com/5968886/98473787-72b37600-21f5-11eb-9d6b-87f0638a8f9d.png)

Additionally, there is also strange behavior when you do extend the station after starting the simulation:
1. The ride simulation can no longer be restarted. It shows the error: "Unable to operate with more than one station platform in this mode", while the ride clearly has one station:
![c1](https://user-images.githubusercontent.com/5968886/98475732-29175b00-21f6-11eb-8294-a3be6750e0b5.png)
2. But the ride window indeed shows two stations:
![c2](https://user-images.githubusercontent.com/5968886/98475867-33395980-21f6-11eb-908a-c9f64a93a57d.png)

The only way to fix it that I could find was demolishing and rebuilding the ride. Rebuilding the station, for example, did not help.

**Save game:**
Save game with the two examples shown above. When trying to open the rides in vanilla the game crashes.
[broken-stations.zip](https://github.com/OpenRCT2/OpenRCT2/files/5506925/broken-stations.zip)

**Comment by duncanspumpkin** [comment]
This will have been caused by the desync fixes. We thought there might be some edge cases...

**Comment by manuelVo** [comment]
It indeed is caused by those fixes. I've bisected 1f7d73a to be the culprit, which is actually the commit that fixes the first regression.

This is probably how the bug is caused: c440dac made it so that ghost station tiles aren't able to affect the station's properties. However pacing prebuilt design requires ghosts to modify the station's properties to be able to show the entrance and exit of the ride. Because of this 1f7d73a changed it so modification of station properties is only prevented during simulation (since placing a prebuilt design and simulating isn't possible at the same time this fixes that bug). However what happens now is: When placing a ghost station tile when not simulating the station properties are modified. Now simulation is being enabled. If the ghost tile is now being removed (for example by placing a non-station ghost instead) it cannot undo the changes it did to the station because simulation being enabled prevents this.

I've two ideas how this could be fixed:
1. Revert 1f7d73a and make it so ghost tiles can modify stations only during placement of designs (and never otherwise)
2. Remove ghost tiles before switching to simulation mode and then rebuild them once simulation is enabled (in a similar fashion as we do before and after updating peep logic).

I personally prefer the first, since I feel like it should be the normal case that ghost tiles don't have an effect on anything in the game and if they need to (for example when placing a ride design) that is an edge case. 1 reflects this logic well, while 2 introduces quirky logic in the code that fixes an edge case that shouldn't be one.

**Comment by Mmlh1** [comment]
A video detailing it.

https://user-images.githubusercontent.com/40719238/177962306-bd593af8-cf2f-4232-a2ca-b00c7def6836.mp4

This occurs for the Reverse Freefall's LIM launched mode, too. As far as I can tell, it truly is broken for any non-continuous circuit mode.
