### ISSUE TITLE
Need new release instructions for Debian Bullseye

### ISSUE THREAD

**Issue by alercah** [OpenRCT2/OpenRCT2#13692]
**OS:** Debian Linux
**Version:** Bullseye
**Commit/Build:** N/A

The provided installation instructions do not work on Debian bullseye. `add-apt-repository` is no longer able to add PPAs, it seems because it relies on `apt-key` which is now deprecated. I spent 15 minutes trying to figure out how to add the PPA repository key to my keyring to no success, and have given up.

Additionally, advising users to install Ubuntu packages on Debian is [bad advice](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian). Please make Debian-specific builds and provide a distribution mechanism that supports Debian properly.

**Comment by alercah** [comment]
I tried downloading the package manually, but it will not install because [`libzip5` is not available in Debian](https://packages.debian.org/search?keywords=libzip).

**Comment by Gymnasiast** [comment]
> Additionally, advising users to install Ubuntu packages on Debian is bad advice. Please make Debian-specific builds and provide a distribution mechanism that supports Debian properly.

Our development resources are already stretched. We have to prioritise what our users need and what we want ourselves (it's a project developed in our spare time, after all). And Debian does not make it very easy either. If this is genuinely bad advice, I can remove any mention of the PPA from the Debian instructions and just tell the users to compile OpenRCT2 themselves.

Seeing as we're open source, the best way to ensure Debian is properly supported is adding support yourself. We would gladly accept the offer.

**Comment by gibmat** [comment]
This is a bit serendipitous.... I've just recently picked up an old Debian bug to properly package openrct2 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808945). Hopefully it won't be too long before it's available via a simple `apt install openrct2`.

**Comment by gibmat** [comment]
An update on my end: I'm waiting for a sponsor to review my package for Debian (since I'm not a DD/DM). Once that happens the package will hit the NEW queue for review by the ftpmaster team, after which it will land in unstable. Following the standard migration schedule, the package will then be promoted to testing after a few days. If it reaches testing by Feb 12, it will officially be a part of the bullseye release, otherwise it will land in bookworm (but could be backported to bullseye).

In the meantime, I have uploaded amd64 packages for both buster and bullseye to my personal apt repository that people are welcome to use: https://apt.calenhad.com/. Just remember that this is an unofficial Debian repo, and while I believe the packages should work properly, there's no warranty that it won't break your computer.

**Comment by janisozaur** [comment]
@gibmat that's great news! Many thanks for that, keep us posted.

**Comment by alercah** [comment]
Awesome, I'll try to give them a trial sometime in the next week or two then!

**Comment by alercah** [comment]
Seems to work for me!

**Comment by janisozaur** [comment]
@gibmat how does a package reach testing? Is there any way to track progress or help with it? What's the policy once it's in Debian, are the packages there ever updated with new releases? We release ~quarterly, much more often than Debian's cadence.

**Comment by gibmat** [comment]
@janisozaur since this will be a new package for Debian, it needs to go through the following steps:

1. A Debian Developer needs to sponsor the package for upload to the Debian "unstable" repository. This progress is tracked through Debian's bug tracker (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979592); this is where the package is currently in its progress to inclusion in Debian. If you know of a DD who would be willing to sponsor, point them to that bug. Otherwise, there's a group of volunteer DDs that work through the sponsorship queue.
2. After a sponsor upload, the package will be placed into the NEW queue for manual review by the ftpmaster team (https://ftp-master.debian.org/new.html). This is required for first-time package uploads (and a few other cases) and serves as a secondary quality check as well as review of the copyright information to ensure packages comply with Debian's Free Software Guidelines (https://www.debian.org/social_contract#guidelines).
3. Once passed through the NEW queue, the package will land in "unstable". Barring any reported release-critical bugs or issues with some automated quality checks, the package is then promoted to "testing" after 2-10 days, depending on the upload priority. (It will be five days for this package.)

Once the package is in testing, a couple things will happen:

1. If it lands before the bullseye soft freeze (https://release.debian.org/bullseye/freeze_policy.html), whatever version is there will become part of the bullseye stable release. If it is not in testing by Feb 12th, it won't be part of the baseline bullseye release.
2. Since Debian prioritizes stability, packages in stable don't get major version bumps or new functionality during that release lifetime (with some notable exceptions like web browsers). But, there are backports (https://backports.debian.org/) to provide updated versions of software to the stable release.
2. Backporting is basically rebuilding a package from testing for the current stable release. For example, say openrct2 doesn't reach testing until March 1 (so too late for bullseye, but would be part of bookworm), immediately following the bullseye release I would prepare a backport for bullseye to make it easily available for all bullseye users.

My personal plan is to keep the package version in testing closely up to date with openrct2 releases, as well as making backports for the current stable release. That should keep the version of openrct2 available in Debian nice and fresh.

**Comment by gibmat** [comment]
As of today, with the bullseye soft-freeze one week out, it’s very unlikely that OpenRCT2 will land in time to make the bullseye release. I will continue to update OpenRCT2 in my personal repository until the package makes it to Debian proper. I’ll build for both buster and bullseye for the duration of their lifetimes.

**Comment by tupaschoal** [comment]
> As of today, with the bullseye soft-freeze one week out, it’s very unlikely that OpenRCT2 will land in time to make the bullseye release. I will continue to update OpenRCT2 in my personal repository until the package makes it to Debian proper. I’ll build for both buster and bullseye for the duration of their lifetimes.

Thanks for doing this effort and keeping us posted, it's great! Let us know if you need help

**Comment by gibmat** [comment]
> Thanks for doing this effort and keeping us posted, it's great! Let us know if you need help

Of course! Now that the initial package is done, there's not much needed to keep it up to date. I'll keep building and publishing my builds until it reaches Debian's repos.

**Comment by gibmat** [comment]
Thanks to DD Andrius Merkys, openrct2 has reached Debian's NEW queue, where it is awaiting review by the ftpmaster team.

Changes to be aware of:
  * In my personal repo, the packages have moved from "main" to "contrib" to accurately reflect what section of the Debian archive they will be in. This is because to be useful, openrct2 still depends on the original game assets which are not free. If you have added my repo to your sources.list, you'll need to make this change, then run an `apt update` to get future updates.
  * In the "objects" that ship with openrct2, I've had to remove the official DLCs (panda, walls, etc) since I cannot find a license from the original authors that allows free modification (in addition to distribution) that satisfy Debian's licensing requirements. However, it's easy enough for a user to fetch and use those DLCs, if they wish.
  * Discord integration is not enabled, since openrct2 depends on a library that is deprecated, and not already packaged in Debian. I don't think it would be accepted to try to introduce a deprecated library into Debian that's only used by one program.

**Comment by IntelOrca** [comment]
> This is because to be useful, openrct2 still depends on the original game assets which are not free.

Note, that to run an OpenRCT2 dedicated server, you do not need any original game assets, and can be regarded as a completely free application.

**Comment by gibmat** [comment]
Correct on both points, although I'd wager a guess that headless server mode is more of an edge case use. I actually mentioned the same thing in a private email while working on packaging with a person on the Debian mailing lists. Until there's something like OpenTTD's free graphics, the contrib part of the archive seems to be the correct location. This won't make any difference to an end user when they install it.

**Comment by Gymnasiast** [comment]
> Correct on both points, although I'd wager a guess that headless server mode is more of an edge case use.

Not really, a lot of servers are run this way.

> In the "objects" that ship with openrct2, I've had to remove the official DLCs (panda, walls, etc) since I cannot find a license from the original authors that allows free modification (in addition to distribution) that satisfy Debian's licensing requirements. However, it's easy enough for a user to fetch and use those DLCs, if they wish.

I'm not sure I'm happy about this. The objects you removed include objects **selected by default** and included in some scenery groups, which will cause error messages to pop when working with them in the Object Selection. I don't know if Debian will accept the objects if they consist of a ZIP with the original unmodified .DAT file along with our metadata, but leaving them out is just providing users with an incomplete product - and _we_ will get the bug reports, even though we are not responsible for the packaging.

**Comment by gibmat** [comment]
Hey, sorry about the delay in responding -- life and my day job demanded most of my time these past couple of weeks.

The core issue with the official DLC items is that, while they are freely available, the closest to a license covering them that I could find is "© 2002 Infogrames Interactive, Inc. All Rights Reserved. © 2002 Chris Sawyer. All Rights Reserved." ([link](https://web.archive.org/web/20021128013303/http://rollercoastertycoon2.com/)) That doesn't allow for modification or further derivations of those DLCs, which then runs afoul of Debian's [Free Software Guidelines](https://www.debian.org/social_contract#guidelines).

The ideal solution would be for Atari to issue a statement somewhere that the DLC content is in the public domain or re-licensed under something like the Creative Commons. As the DLCs are freely available, it's not as if they'll be loosing any money, but who knows what their corporate lawyers would say.

I certainly don't want to cause errors for people using the game if it can't find these additional objects. Grepping through the main code and object repos, it looks like the panda DLC objects are entirely self-contained and there's no reference to them in any external groups. The walls are mentioned in a scenery group, but I could edit that json definition to not list them. That would prevent any errors from occurring, unless a scenario or save game is loaded that contained references to those objects.

In working on packaging, I did stumble across OpenRCT2/src/openrct2-ui/windows/ObjectLoadError.cpp, which looks like a way to allow a user to fetch missing objects via an API. For example, if I delete the Information Kiosk definition (rct2.infok.json) and try to load a scenario that has an Information Kiosk, I'm presented with the following dialog, with an option to download the missing object(s) via a backend API:

![image](https://user-images.githubusercontent.com/6611789/115482113-73891300-a23d-11eb-8709-be74fb4a2dec.png)

Currently the API is returning an error (`INFOK query failed (status 500)`), but would it maybe be possible to put those DLC objects into that remote hosting service, so if a user tries to load a scenario or save same and don't have the DLCs, they would have the option to download them. I could document that in the package's README, and I think that would be pretty close to a solution that would keep everyone happy. What do you think?

**Comment by IntelOrca** [comment]
@gibmat The API currently downloads objects from https://www.nedesigns.com/, so they would need to be uploaded there for it to download them. The information kiosk is a RCT2 object and therefore cannot be downloaded, as they either already come with OpenRCT2 in JSON form, or the base game in DAT form. The API and nedesigns currently does not support JSON objects.

**Comment by gibmat** [comment]
I spent some time looking at the download API code yesterday, as well as looking at what's available at NEDesigns. It appears that all the .DAT files for the different DLCs are already there, but I couldn't download them via the API that OpenRCT2 uses. I would always get a HTTP 500 error, both when trying from the game, as well as manually constructing the URLs by hand. Is that code still running properly?

If the various .json metadata files were changed to reference the .DAT files rather than all the individual images, would downloading via the API work? The Debian packaging still wouldn't be able to directly redistribute the .DAT files, although the metadata is OK. An end-user who then wanted to use one of the DLC objects would be able to automatically download the .DAT files, so there wouldn't be any missing functionality for those who wanted it.

I'd be happy to help out with testing any changes.

**Comment by rmacklin** [comment]
@gibmat Is it no longer available on https://apt.calenhad.com/ ?

I'm seeing https://tracker.debian.org/news/1405508/accepted-openrct2-043ds-1bpo111-source-all-amd64-into-bullseye-backports/ but even after adding `deb https://deb.debian.org/debian bullseye-backports main` to `/etc/apt/sources.list`, I'm getting
```
$ sudo apt install openrct2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package openrct2
```
so I'm not sure where to get openrct2 for bullseye...

**Comment by ocalhoun6** [comment]
Yes, support for this should probably be managed somehow.

In the meantime, you could try installing it via AppImage. 

Go to https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.5 (Or any other release/version.) And download the `OpenRCT2-0.4.5-linux-x86_64.AppImage` file. And you might be able to get OpenRCT2 running that way as a temporary solution, though it's not as ideal as a real installation.

I did that once for Ubuntu, and it worked very painlessly. Though I think you'd have to manually do it over again every time there's an update. Actually installing from a repository would be better because then you do updates far more easily.

**Comment by gibmat** [comment]
> @gibmat Is it no longer available on https://apt.calenhad.com/ ?

That's correct -- openrct2 is available directly from Debian's repos, although it's in the `contrib` section of the archive, so your sources.list will need a line like `deb https://deb.debian.org/debian {bullseye,bookworm}{-backports} main contrib`.

bullseye-backports and bookworm have version 0.4.3; version 0.4.5 is pending in bookworm-backports and available in testing/trixie. The processing of backport packages for bookworm hasn't really started yet, so openrct2 is currently waiting with almost a hundred other packages for that machinery to startup -- no ETA on that.

Also, beginning with Lunar Lobster, Ubuntu has started importing the openrct2 package into its multiverse repository too.

**Comment by rmacklin** [comment]
Ah, thank you! Shortly after posting I ended up going with the flatpak installation and got it running that way, but good to know what I was missing.

**Comment by Gymnasiast** [comment]
Created https://github.com/OpenRCT2/openrct2.github.io/issues/47 to improve the documentation on our own website. Once that is done, one could try updating openrct2.org too, if the owner can be bothered to pull it.
