### ISSUE TITLE
Refactor window to class: EditorObjectSelection

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13770]
See #13737 for more details.

**Comment by owlyoop** [comment]
I want to try to start on this

**Comment by Broxzier** [comment]
Go ahead, @owlyoop. If you have any questions, let us know either here or on Discord.

**Comment by owlyoop** [comment]
I am having trouble understanding what a piece of code in the Open function, and what to do with it.

In this function, called on line 376 in `rct_window* WindowEditorObjectSelectionOpen()`
```
static void WindowEditorObjectSelectionInitWidgets()
{
    auto& widgets = _window_editor_object_selection_widgets;
    if (!_window_editor_object_selection_widgets_initialised)
    {
        _window_editor_object_selection_widgets_initialised = true;
        auto tabWidget = widgets[widgets.size() - 2];
        for (size_t i = 1; i < std::size(ObjectSelectionPages); i++)
        {
            widgets.insert(widgets.end() - 1, tabWidget);
        }
    }
}
```

I am not sure what the insert is doing. Looking at a bunch of other refactored window classes, the widgets change from `static std::vector<rct_widget> _window_editor_object_selection_widgets` to `static rct_widget _window_editor_object_selection_widgets[]` . So I don't really know what to do with the widgets.insert part of the above code, because `widgets` was originally a reference vector and it's now a pointer to rct_widgets (I think?) 

My C++ is very rusty so sorry if I mixed up terminology

**Comment by IntelOrca** [comment]
The editor object selection is a very complicated window. If you aren't very familiar with C++, I recommend choosing a smaller / simpler window to refactor.
