### ISSUE TITLE
Show / hide UI

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1402]
Add a shortcut key to toggle the visibility of the top and bottom toolbar.

**Comment by MaikelS11** [comment]
I've added the shortcut with letter t (toolbar)

**Comment by mzmiric5** [comment]
I think the original description for this issue was limited. When I originally discussed this with @IntelOrca the show/hide ui should really hide any open windows, and prevent the drawing of any new windows being drawn when the user presses the shortcut for that window (but it should still know it should open them, so when the ui is shown again, those windows are there)

**Comment by MaikelS11** [comment]
Oh ok. Well that wasn't the description from IntelOrca. ;)
In the current implementation the user can show/hide the top and bottom toolbar by pressing the T key.

I also don't know if you really want to hide all the (new) windows. If a user clicks on an object (like a ride) or presses a shortcut, when the toggle is activated, he probably do this with purpose. For what reason you would want to avoid this?

**Comment by IntelOrca** [comment]
I think this is fine, if the user doesn't want any windows they can just close them.

**Comment by mzmiric5** [comment]
Hmm, well when I originally proposed this toggle function, it was to enable the "postcard" (as some games call it) view. Basically when you are in this mode, no UI at all is drawn, and it enables the user to position the camera exactly the way they want, allowing for more controlled clean screenshots (or in the case where i was using this with a custom build, video recordings).

I guess what I'm trying to say is that having such a toggle on the whole UI level (rather than just closing the top and bottom toolbar) would be more of a standard behaviour as experienced in other games offering this feature (the latest game I can think of that is doing this is Cities: Skylines, and i know The Sims game offer the same feature).

Regardless, great work @MaikelS11 . I guess it's up to you and @IntelOrca if you decide to just leave it as is now, or if you want to dig into the full UI drawing disable (I was looking into it, but didn't have time to actually write it).

**Comment by IntelOrca** [comment]
@mzmiric5 You can close the windows though if you don't want them to be visible. You weren't able to close the top and bottom toolbar.

**Comment by mzmiric5** [comment]
@IntelOrca I am aware of that, I'm just saying, that Hide UI is deceiving if all it does is hides the toolbars. Just my 2¢

**Comment by duncanspumpkin** [comment]
Implemented in #1490.
