### ISSUE TITLE
Allow saving designs of flat rides.

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1417]
I understand why it's not an original feature, because there's nothing custom about flat rides, but I think people would appreciate the ability to save them with scenery and entrance/exit/path placement.

**Comment by Horsti12** [comment]
that would be cool :D

**Comment by Gymnasiast** [comment]
I have worked on this, but it has turned to be harder than just removing the checks. If I save a flat ride, it is for some reason elevated by 5 or 6 units.

**Comment by KC-7** [comment]
Any updates?

**Comment by Gymnasiast** [comment]
None since 18 May, no. As I said back then, after I removed the checks that prevented flat rides from being saved, it didn't work as expected, as the whole design would be 5-6 blocks too high. I'd have to find the cause, but I have no idea what causes it. And I have been busy with lots of other bugs/features.

**Comment by KC-7** [comment]
Alright. Thank you for your work.

**Comment by flipflop97** [comment]
Sounds as if it might be related to #400.

**Comment by Gymnasiast** [comment]
Has now been implemented.

**Comment by KC-7** [comment]
Cool.
