### ISSUE TITLE
Sorting by date doesn't work

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1439]
![schermafdruk van 2015-06-23 21 31 33](https://cloud.githubusercontent.com/assets/1478678/8315215/483479a6-19ef-11e5-9835-ca82248ddb69.png)

**Comment by rctdude2** [comment]
Works properly on Windows, so it probably only affects Linux (possibly OSX as well).

**Comment by IntelOrca** [comment]
A wine issue maybe?

**Comment by Phasedetect** [comment]
Can confirm that it has never worked on OSX.

**Comment by ThomasdenH** [comment]
It does work on my Windows PC too, I wonder what the cause might be. Windows also has the [GetFileTime](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724320(v=vs.85).aspx) function, but it would be less elegant since the result would have to be converted to time_t. Still, if that for some reason fixes it, why not?
