### ISSUE TITLE
Game doesn't ask for path to RCT2 on first launch

### ISSUE THREAD

**Issue by tsunamistate** [OpenRCT2/OpenRCT2#1445]
Instead upon creation of config file, it writes OpenRCT2 root folder as `game_path`.
Most likely caused by #1352 

Reproduction:
* Move or rename your old `config.ini`
* Launch OpenRCT2 to create a new one
* Unless you have copied necessary files to OpenRCT2 root it will crash with this error
![image](https://cloud.githubusercontent.com/assets/4958520/8329278/c392a30c-1a80-11e5-839e-ac6de5d8bb77.png)

Offtopic enhancment proposition - what if instead of creating a location link to RCT2 files, it would copy necessary files and folders into OpenRCT2 root, which would make `game_path` unnecessary?

**Comment by IntelOrca** [comment]
This is only an issue for people that do not have RCT2 installed in any of the normal locations. It however is an issue - it should check if the directories it checks contain RCT2 files rather than just checking if the directory exists.

When OpenRCT2 no longer requires the original exe, the plan is to copy the data files over so that the RCT2 install directory is no longer needed and can be deleted afterwards.

**Comment by Phyxion** [comment]
Is the original executable still required in the installation folder? I renamed the original executable to rct2.exe.bak and it's working OK here (so far at least). I did this so I can just launch it through Steam.

**Comment by IntelOrca** [comment]
@Phyxion The executable is distributed with OpenRCT2, you do not need the original version that you might have.

**Comment by Phyxion** [comment]
Thanks, I expected as much.
