### ISSUE TITLE
Add returning marketing campaigns 

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1452]
Add the ability to repeat a marketing campaign. Stop the campaigns when the balance becomes negative.

**Comment by Patrik356b** [comment]
I'd like to see this or something similar:
[X] Repeat [Unlimited/1-64] Times

**Comment by IntelOrca** [comment]
@Gymnasiast has increased the maximum number of weeks to 12. I think a limit is intentional to keep the players on the ball, otherwise it would be too easy if the player could just simply forget about the process - making it redundant. A limit also gives players a chance to change what is being advertised for food and drink.
