### ISSUE TITLE
Scenery window cannot display more than 32 tabs.

### ISSUE THREAD

**Issue by DCMeGaMaxX** [OpenRCT2/OpenRCT2#14635]
**OS:** Windows 10
**Version:** v0.3.3
**Commit/Build:** 16c10f6

If there are more than 32 scenery groups selected, The first 31 scenery groups will in their respective tabs, but scenery groups 32 and higher are selected, they appear under "Miscellaneous"

- [No] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Select more than 32 scenery groups in the object selection window
2. The 32nd scenery group and higher now appear in the "Miscellaneous" tab rather than their respective scenery group tab.

**Screenshots / Video:**
31 scenery groups selected.
![Unnamed park 2021-05-12 07-41-04](https://user-images.githubusercontent.com/16751824/117976487-75526d80-b2f5-11eb-9e15-5c22119b2b50.png)
Prehistoric Theming is the 32nd scenery group selected.
![Unnamed park 2021-05-12 07-40-41](https://user-images.githubusercontent.com/16751824/117976548-8602e380-b2f5-11eb-889a-3990adbbc3df.png)
Prehistoric Theming appears in Miscellaneous. Additional scenery groups will be here.
![Unnamed park 2021-05-12 07-21-43](https://user-images.githubusercontent.com/16751824/117976677-a92d9300-b2f5-11eb-833b-396c6852e775.png)

**Comment by duncanspumpkin** [comment]
All issues with the new save format to in the new save format pr

**Comment by James103** [comment]
> All issues with the new save format to in the new save format pr

The exact PR to go to is #10664.

**Comment by fidwell** [comment]
@duncanspumpkin I am looking into the development effort needed for this enhancement. Can we re-open this ticket? or should I make a new one?

**Comment by duncanspumpkin** [comment]
I have tried to implement this a few times but didn't like my solutions. I was thinking of adding a scroll bar to the tabs to allow as many as required. Just a word of warning @trzejos is currently working on this window I suggest speaking to him (crazyduck8 on discord) to make sure the both of you aren't walking over each others work.

**Comment by fidwell** [comment]
Thanks for the heads up; I'll keep an eye on #19341 as it will definitely cause conflicts.

I was experimenting last night and came up with this solution: ![screenshot](https://cdn.discordapp.com/attachments/521878642184159253/1073456948474814555/image.png)

This is not a mockup; this is an in-game screenshot. I think it works pretty well, but it needs some refactoring and testing still. I think rows of tabs would work better than a scroll bar since you could see all tabs at once and it wouldn't take extra clicks to find what you need.

**Comment by ocalhoun6** [comment]
Looks like the best solution so far!
What happens if even more tabs are added? 3+ rows?

It is a little odd that the top row of tabs has the brown color on the sides, while the bottom row of tabs has the green color on the sides, though.

There's also something going on behind the top row of tabs. The ones on the left have brown background (which you can see at the corners), but the ones on the right have a dark green background. The same dark green background is in the first 4 tabs on the bottom row. It's possible that this is a preexisting visual glitch not related to your changes. It seems to only affect the expansion pack scenery groups -- possibly it has something to do with the icons for those groups.

**Comment by trzejos** [comment]
Yeah I expect this will conflict with #19341. I've been experimenting with giving the "all scenery" tab some special widget properties. This might actually work out nicely though if I revert those changes.

**Comment by fidwell** [comment]
@ocalhoun6 ---

The visual effects are because I'm kind of abusing the way the tab widget is "supposed" to work. It does feel a little hacky. There might be a better visual solution but, if there is, I haven't figured it out yet.

My proof-of-concept allows for an arbitrary number of rows. For now, I've capped it at 128 tab groups (4 rows at 32 tabs per row), but it's arbitrary. I can't imagine a lot of people would want more tabs than that, but you never know...

**Comment by spacek531** [comment]
It looks nice Fidwell! Is it easy or possible to offset higher rows? In my opinion having the rows offset like keyboard keys is a bit easier to read.
![image](https://user-images.githubusercontent.com/3454156/218222510-c090e560-a81d-4257-b30f-5822343d2010.png)

**Comment by fidwell** [comment]
@spacek531 That's a cool idea! Shouldn't be too hard to do with my implementation; I can look into it.

**Comment by ZeeMajora** [comment]
It looks really nice! I would say it should go up to 255 tabs as that is the maximum you can enable, it might be a bit uncommon to select over 128 but it still seems like a situation that could still happen if someone just went nuts and enabled everything they have in their objects folder and it might be confusing if half the tabs they enabled were just missing.

Also would it be possible to lower the amount of tabs per row? 32 makes the tabs window really wide to the point where on lower resolutions (and window scales as a result) the scenery window is too big to even fit on the screen
![Windswept Wilds 2023-02-10 18-47-25](https://user-images.githubusercontent.com/42477864/218223063-faa96a2f-223b-449e-9375-c1e4dbcfa070.png)
I think lowering the number of tabs per row to 20 would fix this.

**Comment by fidwell** [comment]
@ZeeMajora No problem. Like I said the numbers are all arbitrary, so switching to 20 tabs per row and up to 255 total tabs (plus misc and search) should work fine. I'll put together some more proof-of-concept screenshots

**Comment by fidwell** [comment]
20 tabs per row:

All non-custom groups:
![image](https://user-images.githubusercontent.com/5436387/218225839-eaf86ed2-9cc7-4400-a120-6b726085aaed.png)

129 groups (I don't have any more custom ones than this):
![image](https://user-images.githubusercontent.com/5436387/218226160-f8a2d385-5ba4-4790-ae5d-1bd46a16a1e0.png)

**Comment by ZeeMajora** [comment]
Looks quite nice! This definitely seems like the way to go.

**Comment by fidwell** [comment]
255 tabs would be like 12 rows, which is absurd and would be basically the height of the original window once over. Hopefully no one actually goes for that

**Comment by ZeeMajora** [comment]
Eh to be fair other windows are pretty equally as absurd if you were to max out their object counts.
In theory you can select a little over 500 footpaths (255 footpath surfaces and 255 legacy footpaths) and they'll all be in your footpath window... i can't even begin to comprehend that.
So i don't think it's worth worrying about too much, as long as it still technically works it should be fine.

**Comment by fidwell** [comment]
@spacek531 Might be more trouble than it's worth, it looks kinda awkward in practice, but I can keep experimenting...

![image](https://user-images.githubusercontent.com/5436387/218230892-3c831f28-9e1b-4f07-b28e-971a65386321.png)

**Comment by 733737** [comment]
couldn't we simply change the default theme so the widow is green instead of light brown?

**Comment by fidwell** [comment]
Better, but I still am not sure if I like it. I'll sleep on it.

![image](https://user-images.githubusercontent.com/5436387/218232207-06e85be8-a633-4939-919d-39d93449a669.png)

**Comment by spacek531** [comment]
![image](https://user-images.githubusercontent.com/3454156/218234392-423d583f-d41a-4a25-887e-0011ce3b15da.png)
![image](https://user-images.githubusercontent.com/3454156/218234507-5b370b1c-c7cb-4ac5-9603-314c37edda26.png)
![image](https://user-images.githubusercontent.com/3454156/218234610-58219992-be6a-49d5-b8c1-4daedae85b24.png)

Here's some concepts.

1st is 8 px horizontal offset each line.
2nd is 4 px horizontal offset each line and offsetting stops at the 5th line
3rd is 4 px horizontal offset and inside a scroll frame. I only showed it exactly 4 rows here but I imagine 4.5 rows would be ideal since it's a passive indicator that there's more below. Also, I imagine the 4 px offset would loop every 4 rows, which would be another passive mnemonic device for builders.

**Comment by fidwell** [comment]
Yeah, good mockups. I like the second one best; it's not too extreme.

Also, I think we would want to only do this kind of offset when there's more than one row. It'd be confusing if, when there's only one row (most of the time on the whole, I'd think), the tabs are shifted over for no apparent reason.

**Comment by spacek531** [comment]
I agree. I think the upper rows' offsets should be determined by how many rows there are.

**Comment by 733737** [comment]
Why do we need offsets in the first place?

**Comment by Legotown55** [comment]
The offsets loocks cool

**Comment by fidwell** [comment]
We don't _need_ them, no. There are a lot of things we don't need but did anyway.

I have to wait on a PR for this regardless while the search stuff goes through, so I  might as well take my time and make it look nice.
