### ISSUE TITLE
Handymen Prioritize Footpaths Over Queue Paths

### ISSUE THREAD

**Issue by ejmiers** [OpenRCT2/OpenRCT2#14697]
One thing that has always bothered me about the handymen in RCT is their affinity to wander into queue paths and neglect the regular footpaths which are far more likely to become dirty with litter/vomit. I think a good QOL improvement would be to have handymen prioritize regular footpaths over queue paths while on patrol.

**Comment by Ryder17z** [comment]
I don't think guests can vomit on queue paths. 
Also i doubt the Queue TV path object can be vandalized (reference: #4613 )

**Comment by keiyakins** [comment]
Guests don't puke or litter while in the queue, but they *can* puke or litter while walking normally on a queue path (because you closed the ride or whatever.) Still, that's uncommon enough that even handymen refusing to go on queue paths unless directly ordered would probably be fine. Something like a 1/10 chance to check the queue would definitely be fine.

**Comment by ocalhoun6** [comment]
If this is going to be done, it would probably be good to also keep mechanics and security guards out of queue lines.

For security guards, since no queue line path items can be vandalized, security guards are useless on queue paths.

For mechanics, wandering around in queue lines generally increases their distance from the next ride breakdown/inspection they're called to. If I remember right, a mechanic might be called to an entrance-only station during certain breakdown modes, *but* that shouldn't be a problem -- a mechanic's active pathfinding is handled with completely different code than their passive random wandering when not on assignment, right?

**Comment by deurklink** [comment]
Guests cannot vomit on queue paths, but there can be flowers next to queue paths that need to be watered, or grass to be mown.

**Comment by ocalhoun6** [comment]
Hm... Maybe handymen avoid queue paths if they have 'water flowers' and 'mow grass' turned off in their settings?
