### ISSUE TITLE
Pressing a options tab in the title screen doesn't produce clicking sound

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1470]
All the other buttons also doesn't make sounds anymore after opening the options window.

**Comment by MaikelS11** [comment]
I did a quick look at this problem.. this is a problem in the whole game.

It seems that the sounds aren't correctly closed/removed. (the sounds are not played anymore because of the 'Too many sounds' check)

**Comment by Gymnasiast** [comment]
Hm, that sounds very plausible. I have had a few occasions where it would stop playing tab sounds after a while. Also, I have had a few occasions where the sound wouldn't work at startup, only to come back again a few sessions later. But since I'm running on Wine with its flaky sound layer, I wasn't sure whether the issue was in OpenRCT2 or not.

**Comment by rctdude2** [comment]
I've had this issue as well on Windows. It only seems to happen on the main menu.
