### ISSUE TITLE
odd teleport effect when banked turns overlap (disable clearence checks) creates an infinite loop

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#14795]
**OS:** Linux x64
**Version:** AppImage from https://github.com/OpenRCT2/OpenRCT2/actions/runs/886297708

![image](https://user-images.githubusercontent.com/2000703/120119164-7b21cd00-c196-11eb-8708-a0a3f68d6d17.png)

**Steps to reproduce:**
1. Build a track where flat, banked turns intersect like this
2. Test it.

I don't think this should happen as it creates an infinite loop.

**Comment by Broxzier** [comment]
This is pretty much how the merging trick works. Because it is used so often in both vanilla RCT2 and OpenRCT2, I'm hesistant to "fixing" this. The way this works is that the _current_ track block's position and banking matches the position and banking of another track piece (only with a different orientation in this case, but that's not always the case for merged tracks). The vehicle then takes the _first_ element on the tile (that is the lowest of the two in the list in the Tile Inspector) as the new _current_ track block.

**Comment by Ryder17z** [comment]
Understandable. Thanks for the detailed explanation.
