### ISSUE TITLE
End cars missing on Corkscrew Roller Coaster trains in RCT1 scenarios

### ISSUE THREAD

**Issue by jmorrph** [OpenRCT2/OpenRCT2#14833]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** c1c9353

When loading an original RCT1 scenario the end cars of corkscrew roller coaster trains are missing.
This affects roller coasters present and operating when the scenario starts.
Resetting the ride and respawning the train(s) fixes this.
My RCT1 and 2 are the GOG versions.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Have RCT1 linked.
2. Load a RCT1 scenario that starts with an operating corkscrew rollercoaster, e. g. Funtopia.
3. Observe the end car missing on 'Defibrillator'.
4. Reset the ride to see a new train with an end car spawning.

**Screenshots / Video:**
When the scenario is loaded the end car is missing:
![no_end_car](https://user-images.githubusercontent.com/33931653/120923150-5add9b00-c6cd-11eb-9915-5cfd53374cf8.JPG)

After resetting the ride the end car appears:
![end_car](https://user-images.githubusercontent.com/33931653/120923183-7ea0e100-c6cd-11eb-904a-65bcc74e97bd.JPG)

**Comment by ZeeMajora** [comment]
This is due to RCT1 having different corkscrew coaster trains that did not have a tail car, As seen in my screenshot.
So OpenRCT2 is correctly importing them, It's just the RCT1 corkscrew train's RCT2 counterpart is a pretty different train.
Whether or not the RCT1 corkscrew trains should be ported to OpenRCT2 is up for discussion.
But that would be a solution to this issue.
![rct1corkscrewcoaster](https://user-images.githubusercontent.com/42477864/120933864-13a1db00-c6ca-11eb-84ea-837f89ffe1aa.png)

**Comment by Gymnasiast** [comment]
Besides what Majora has already mentioned, there is also this: we can’t add that extra car to existing trains - adding cars to vehicles already in use is tricky enough, but it would also affect stuff like mass, which in turn means their behaviour on the track might change. As such, this is the best we can do.

Whether we should port the trains and use those as defaults for RCT1 parks is another thing entirely.

Because of these reasons, I’ll have to close this issue as works-as-intended.
