### ISSUE TITLE
Scrolling on touch device doesn't work like it works on original

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#1496]
Running RCT2 with Windows XP Compatibility on a Microsoft Surface 3 (Atom/128GB/4GB) runs correctly, and scrolls correctly - using the Surface 3 Pen, I can right-click and drag nicely and smoothly.

Running OpenRCT2, no change to any compatibility, just the base install, scrolling is lightning fast and unusable as it so quickly scans to the opposite side of the park and there's no granular control.

Not sure if it's the Pen causing this, or the resolution, or I'm missing something else.

Source: https://openrct2.com/community/topic/7/scrolling-on-microsoft-surface-3

**Comment by martyf** [comment]
I reported this on the Community pages.

If any testing or experiments are needed, I'm happy to help - not a C++ developer, but a web developer, so far from being computer illiterate.

**Comment by mrtnptrs** [comment]
Does this issue still happen? Even after the many updates the Surface 3 got, the update of SDL to 2.0.4 and the many code changes (and engine changes) OpenRCT2 got? Does this also happen when you use the OpenGL renderengine or Software (through hardware)?

**Comment by martyf** [comment]
Just tried again on the Surface 3 (all up to date) and the issue still exists in any of the rendering engine modes.

In original RCT2, the issue is not apparent. This is something only in OpenRCT. I've also tried changing scrolling settings but nothing here adjusts the issue.

**Comment by youngspe** [comment]
While I'm digging up old issues about touch input, I'm experiencing this myself on a Surface Pro 5 and I think I have an idea what the issue is.

It looks like when you're dragging the viewport with the right mouse button, it resets the cursor position each frame to where it was the previous frame (see [`input_viewport_drag_continue()`](https://github.com/OpenRCT2/OpenRCT2/blob/7fd0571b9c72e3a9833ad8bcdfd72733ecdaf0ad/src/openrct2-ui/input/MouseInput.cpp#L533-L586) in MouseInput.cpp), so your mouse ends up in the same place it was before you starting scrolling, which is nice. But naturally you can't programatically change the location of a finger on a touch screen, so if you've moved your finger 100 pixels to the right since you started scrolling, the game thinks you're scrolling 100 pixels every single frame.

I'm not sure what to do about that, but hopefully it's useful to somebody.
