### ISSUE TITLE
Combine both zoom in and out buttons on top UI

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1497]
Like what locomotion does have the one button that shows a drop down to allow you to select either zoom in or out. 
![zoom](https://cloud.githubusercontent.com/assets/1381723/8391746/f928f836-1cc4-11e5-8641-1e4d0a1f0e19.png)

**Comment by Gymnasiast** [comment]
I find that bad UI; makes it harder to use without any real benefit. It made a little bit of sense when Locomotion came out since 800*600 (or worse, 640*480) resolutions were still prevalent at the time. Not so much in 2015.

**Comment by IntelOrca** [comment]
I have played Locomotion a fair amount, and I didn't like this because you often want to press both of them an equal amount. Although I actually never use these myself since you can use the scroll wheel. However if might useful for people on touch screens that don't like the pinch and zoom method. In their case they should want it only if they are low on screen space I think.

**Comment by Phyxion** [comment]
I dislike this idea very much.

**Comment by mrtnptrs** [comment]
@Phyxion Met too, it causes a lot of clicks if you want to zoom far out or in...

**Comment by ThomasdenH** [comment]
You might not want to choose it, but foe small windows it is a great idea.

**Comment by Gymnasiast** [comment]
I beg to differ. RCT2's controls even work for 640x480. And even then, this is a very bad example of sacrificing usability for the sake of saving a few pixels. Locomotion's UI makes hardly any sense at all, any ideas taken from it must be treated with suspicion.

**Comment by IntelOrca** [comment]
In Locomotion, you didn't have to click on the zoom button for the menu to appear, it appears when you hover over it.

**Comment by Phyxion** [comment]
I fully agree with you @Gymnasiast. The UI is small as-is (I can barely read it at my resolution), I'd rather not have even less.

**Comment by ThomasdenH** [comment]
The resolution on small screens might be fine nowadays, but the space could still be lacking once the switch is made to a scalable UI. I do not see how this could be opposed on those screens as there really would be no disadvantage.

**Comment by Phyxion** [comment]
Yes, there is a huge disadvantage, namely another useless menu to save a few pixels. If there is a scalable UI you could easily scale the menu to fit it on large screens, so...

**Comment by ThomasdenH** [comment]
Just to be clear; I am proposing to collapse the buttons into one when they don't physically fit on the screen. While the resolution might be enough, with dense screens the buttons would have to be made larger to be useful and therefore they might not fit. I understand that the current way is better, but surely this method is preferable to having the toolbar cut off because there isn't enough space. Heck, make it optional if you want to keep these two buttons at the expense of others. I just feel that a minimal degree of responsiveness, even if completely optional, can only make the game better.

**Comment by Patrik356b** [comment]
If we change the width of the separators, some space could be saved for
better use

On Tue, Jun 30, 2015 at 9:09 PM, Thomas den Hollander <
notifications@github.com> wrote:

> Just to be clear; I am proposing to collapse the buttons into one when
> they don't physically fit on the screen. While the resolution might be
> enough, with dense screens the buttons would have to be made larger to be
> useful and therefore they might not fit. I understand that the current way
> is better, but surely this method is preferable to having the toolbar cut
> off because there isn't enough space. Heck, make it optional if you want to
> keep these two buttons at the expense of others. I just feel that a minimal
> degree of responsiveness, even if completely optional, can only make the
> game better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/1497#issuecomment-117308510>.
>



-- 
Best regards; Hexile
