### ISSUE TITLE
Object selection window bug

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1500]
Open object selection during a scenario, reorder the ride list and either at the bottom or top of the list there will be a blank space.
![screen shot 06-27-15 at 02 20 pm](https://cloud.githubusercontent.com/assets/1381723/8392153/3705f83a-1cd8-11e5-9317-0b40058b4199.PNG)
![screen shot 06-27-15 at 02 23 pm](https://cloud.githubusercontent.com/assets/1381723/8392154/3a6d1b2a-1cd8-11e5-84c1-b52304b2511c.PNG)

**Comment by IntelOrca** [comment]
I can't reproduce.

**Comment by Gymnasiast** [comment]
I think it might be caused by broken objects. (I have had a few more issues caused by dodgy objects.)

**Comment by Gymnasiast** [comment]
Contrary to what the OP said (but what I think he meant) the issue is reproducible when opening the object selection during normal gameplay. Opening it in Six Flags over Texas even immediately crashes the game, at least for me. Opening it in SF Great Adventure doesn't show empty boxes, but still crashes the game when you close the window.

Also, I noticed that some objects that are definitely used are not checked sometimes.

**Comment by Gymnasiast** [comment]
Solved by #2177! :D

**Comment by KC-7** [comment]
How do you open this while playing? Please help, need ASAP for project

**Comment by IntelOrca** [comment]
You need to enable debug tools from options. It is then available on the golden spade icon.

**Comment by Gymnasiast** [comment]
@IntelOrca No, it isn't. It is then available from the gears icon next to the golden spade.
