### ISSUE TITLE
Buildings placed or displayed incorrectly

### ISSUE THREAD

**Issue by 5655474** [OpenRCT2/OpenRCT2#15011]
<img width="1003" alt="Screenshot at Jul 15 21-08-37" src="https://user-images.githubusercontent.com/76697711/125847641-21d672a4-1656-473c-a064-eefc590a19ee.png">
<img width="924" alt="Screenshot at Jul 15 21-09-10" src="https://user-images.githubusercontent.com/76697711/125847651-774619fc-7066-4703-aed2-21e373f65cf8.png">
<img width="820" alt="Screenshot at Jul 15 21-09-27" src="https://user-images.githubusercontent.com/76697711/125847658-1d0a25f9-ac41-46d2-a822-7d2d123dc27c.png">
<img width="885" alt="Screenshot at Jul 15 21-09-42" src="https://user-images.githubusercontent.com/76697711/125847671-e4946dbf-f667-433b-894e-0fa71baf60ff.png">

**Comment by Broxzier** [comment]
Because there are paths there, the game raises the shops and stalls higher up. They are now actually floating above the paths. The wooden floor beneath them is an indication of this. You're pretty much being fooled by an optical illusion.

Personally, I never liked this behaviour for single-tile objects for exactly this reason.

**Comment by 5655474** [comment]
OS: macOS
Version: 0.3.3
Commit/Build: 3f65f282d on HEAD

Reproducible in RCT2 (vanilla)? unknown
 Specific to multiplayer? no
