### ISSUE TITLE
Refactor Park Set Name

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#15358]
Park set name appears to be capped at 32 characters there doesn't appear to be any reason for that. Remove the limit. (note will be truncated on sv6 export as per all other user strings until nsf)

**Comment by Bepso** [comment]
I've been looking at this issue. I've just changed the "max_length" input on the "window_text_input_raw_open" for renaming of the park to INT_MAX instead of 32. 

While this works and "removes" the issue. There comes the problem of the inputbox not responding well to large amounts of characters.

I've attached three pictures, one from how it looks like originally, one how it looks with two rows and then ultimately when it doesnt work anymore 
![image](https://user-images.githubusercontent.com/84444906/137905930-1bf67cdb-0899-4120-9d92-d9ae962b3638.png)
![image](https://user-images.githubusercontent.com/84444906/137905995-b660670e-368d-4e2f-8d2c-49a671d01fbb.png)
![image](https://user-images.githubusercontent.com/84444906/137906030-f370840a-af05-4ebc-b9a4-a77d94a46bb0.png)


The "OK" and "Cancel" button disappear.

One "solution" I found was in the "Textinput.cpp" file, inside "window_text_input_raw_open" to triple the "height" variable. This way it kinda works. But with that being said I don't think that is a good solution. Is there a better solution anyone is aware of?

**Comment by tupaschoal** [comment]
Since this is an entire different issue, I'd solve what this report is asking for and tackle the problem you found on another issue you file later. The park name can be changed both on the text window, but also via script, so there might be users that won't face what you're seeing to set a big name.

That being said, the way I'd try tackling this issue is to implement something on the `OnPeriodicUpdate` function that calculates whether a new height is required and invalidates the window to be redrawn. Not 100% sure this works, but it seems like a valid way.
