### ISSUE TITLE
When building a ride if you open the path toolbox, it will open for a second and close both windows.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1565]

**Comment by IntelOrca** [comment]
This does not happen when placing an entrance or exit. Only when placing a new stand-alone track piece or part. So very common for flat rides.

It should close the ride window, but when the close event gets triggered on the ride window, it closes the new tool window - it shouldn't because the reason the window is closing is because another tool was selected.
