### ISSUE TITLE
>32 cars on go-carts don't color themselves correctly by default

### ISSUE THREAD

**Issue by josepher44** [OpenRCT2/OpenRCT2#16024]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (28c821f on develop) provided by GitHub

### Describe the issue

When building go-carts with more than 32 vehicles, all additional cars are colored black, instead of the rainbow-coloring they typically default to.

### Steps to reproduce

1. Build go-cart
2.  Go to cheats ride, menu, disable vehicle limits
3.  Increase the vehicle count on the go-carts beyond 32

### Attachments

![image](https://user-images.githubusercontent.com/29904858/143663555-83624fec-de8e-4d83-9a6a-9316477b9fec.png)

**Comment by spacek531** [comment]
This is not a bug. The different colors per vehicle effect is defined as a maximum of 32 values, and is defined in the vehicle object, not in the code. Even if the code were modified to allow more than 32 values, the go-karts object will still have only 32.

**Comment by ZehMatt** [comment]
I wonder if we should maybe just wrap the index for the color when the color table is smaller than the requested amount instead of using the default for when it exceeds.

**Comment by ocalhoun6** [comment]
Wrapping it instead of going to a single default sounds like a really good idea.

Should also be useful for coasters and other rides with more than 32 trains. If, say, you wanted alternating colors, you'd just make the first 32 alternate, and then the remaining trains would automatically get alternating colors to match.

**Comment by GalBr** [comment]
After debugging for a while, I found where the kart colors get assigned for premade kart rides:
https://github.com/OpenRCT2/OpenRCT2/blob/f65e12fc78e65d7f605af94348b623c7fe64b4b4/src/openrct2/actions/TrackDesignAction.cpp#L260-L266
`tdIndex` here remains 31 and that's why all the karts beyond that index get the same color.
I changed `tdIndex` to be:
`auto tdIndex = i % (std::size(_td.vehicle_colours) - 1);`
That change resulted in the wrapping of the colours for premade kart rides:
![image](https://user-images.githubusercontent.com/33638710/147384305-88869d30-e350-4c94-96ac-028577abf9c2.png)
But not for custom ones:
![image](https://user-images.githubusercontent.com/33638710/147384312-b1a79aaa-30b2-49c9-a5d5-5434014b26de.png)
I will keep digging but would love some help with the custom rides, and whether you think this is a good fix / direction.

**Comment by GalBr** [comment]
I found the code for the custom kart rides here:
https://github.com/OpenRCT2/OpenRCT2/blob/f65e12fc78e65d7f605af94348b623c7fe64b4b4/src/openrct2/ride/Ride.cpp#L2165-L2171
Changing `count` to always be `presetList->count` and using the same modulo technique from before:
 `auto index = i % static_cast<uint8_t>(32);`
  `VehicleColour* preset = &presetList->list[index];`
  `ride->vehicle_colours[i] = *preset;`
Fixes this for custom built kart rides.

So, there are two places in the code we need to change. What do you think? Should I open a PR for these changes?

**Comment by duncanspumpkin** [comment]
Yes feel free to pr the changes
