### ISSUE TITLE
Can't test cable lift hill with simulation mode

### ISSUE THREAD

**Issue by Alib234** [OpenRCT2/OpenRCT2#16053]
### Operating System

Arch Linux x86_64

### OpenRCT2 build

OpenRCT2, v0.3.5.1-104 (c7851983e4 on makepkg)

### Describe the issue

As the title states you can't test cable lift hills with the simulation, as the ghost cart doesn't wait for the cable to go down and just goes on itself and fails to go up the hill because it's not on the cable lift

### Steps to reproduce

1. Make giga coaster with a cable lift hill 
2. Put the coaster into the simulation mode
3. Watch as the ghost cart goes up the hill with the power of the station and then goes back down as soon as it's out of the station

**Comment by Fred-1044276** [comment]
My workaround to this is to build the cable lift hill like normal and quickly complete the circuit, which will cause the cable lift to work with the simulation mode. Once I get the cable lift hill to work, I simply remove the rest of the track from the back of the station all the way to the cable lift hill (without actually deleting the cable lift hill because otherwise the game will crash) and then build the rest of the coaster the way I want it.

**Comment by ocalhoun6** [comment]
> without actually deleting the cable lift hill because otherwise the game will crash

That sounds like a bug of its own that should really be reported and looked into. Personally, I'd say that a complete game crash -- however rare -- is a much more important issue than ghost train simulation not working on a particular kind of ride.

**Comment by Alib234** [comment]
> without actually deleting the cable lift hill because otherwise the game will crash
I don't get any crashing if I do all you do and delete the cable lift. Inconsistent bugs are the worst

**Comment by telk5093** [comment]
Sounds like that it is duplicated of #10044
