### ISSUE TITLE
Newly saved track designs show "Space required: 1 x 1 blocks" regardless of their actual size

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#16060]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (7037524 on develop) provided by GitHub

### Describe the issue

Saving a new track design without scenery in the new save format build works fine - however, selecting the newly saved track design in the design select window shows its "Space required" field as 1 × 1 instead of what it should have. The junior coaster design I saved here is supposed to have a footprint of 19 × 6.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Create a new track design and save it
2. Open the "Build new ride/attraction" window
2. Select the ride type you saved your new track design for
3. Select the newly saved track design
4. Now it will say "Space required: 1 x 1 blocks"

### Attachments

![Fred's Workbench 2021 2021-11-28 22-43-16](https://user-images.githubusercontent.com/61885939/143820685-f1cd762a-567a-4319-bb26-56aeaf5ab865.png)
[Junior Mobius 13cars 6trains.zip](https://github.com/OpenRCT2/OpenRCT2/files/7616084/Junior.Mobius.13cars.6trains.zip) - the track design I saved that has the "Space required: 1 × 1 blocks" issue

**Comment by Gymnasiast** [comment]
@ZehMatt Perhaps the result of track design code refactors?

**Comment by GalBr** [comment]
I tried to debug this.
`space_required_x` and `space_required_y` get their values here:
https://github.com/OpenRCT2/OpenRCT2/blob/1d5c0361b51f39c8c09aabeef236c17c831ea893/src/openrct2/ride/TrackDesign.cpp#L316-L327
`TrackDesignPreviewOutlines` is creating a **local** tds object with the correct information:
https://github.com/OpenRCT2/OpenRCT2/blob/1d5c0361b51f39c8c09aabeef236c17c831ea893/src/openrct2/ride/TrackDesign.cpp#L1900-L1904
So `previewMax` and `previewMin` in `tds` in the outer scope both stay 0, resulting in `space_required_x` and `space_required_y` to be equal to 1.

This behavior seems to be the same for at least 3 months, and I don't know when was the last time it worked. I don't know if the local `tds` was intentional or not but it gets repeated in a bunch of functions so it doesn't look like a mistake.
The solution on paper seems to be more or less straightforward, give `TrackDesignPreviewDrawOutlines` a ref to `tds` so it can modify it, but I'm not familiar enough with the code to know if this is the right thing to do and what is the reasoning behind how it works now.

**Comment by Gymnasiast** [comment]
> I don't know if the local tds was intentional or not but it gets repeated in a bunch of functions so it doesn't look like a mistake.

The state previously used a global. This was refactored. This bug is simply the result of a mistake during that refactor.

> The solution on paper seems to be more or less straightforward, give TrackDesignPreviewDrawOutlines a ref to tds so it can modify it, but I'm not familiar enough with the code to know if this is the right thing to do and what is the reasoning behind how it works now.

That sounds like the proper solution. Have you tested this?
