### ISSUE TITLE
Prebuilt tracks not available in some RCT1 scenarios

### ISSUE THREAD

**Issue by DRY411S** [OpenRCT2/OpenRCT2#16066]
### Operating System

Windows 10 64-bit Pro

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

Not sure this is a bug but...

In Forest Frontiers RCT1 I can:

build small monorail, but in OpenRCT2 it's a miniature railroad
build candy floss but in OpenRCT2 it's a ice cream stall
build a steel mini coaster but in OpenRCT2 it's a Junior Rollercoaster.

Was there a steel mini coaster in RCT2? I don't remember. But the loss of the RCT1 pre-built track designs is a bit of a shame.

### Steps to reproduce

1.  Just start Forest Frontiers in OpenRCT2 and compare what's available in RCT1.
2. 
3.

**Comment by Fred-1044276** [comment]
The Steel Mini Roller Coaster from RCT1 is in OpenRCT2 as the Classic Mini Roller Coaster.

**Comment by DRY411S** [comment]
> The Steel Mini Roller Coaster from RCT1 is in OpenRCT2 as the Classic Mini Roller Coaster.

OK, but that doesn't address my observations about the monorail and the stall, and if it's the case, why isn't the Classic Mini Roller Coater being used in the scenario?

Perhaps some kind of 'mapping' between RCT1 and OpenRCT2 objects/entities when allowing us to play these scenarios needs reviewing?

**Comment by DRY411S** [comment]
I installed RCT2 and RCT1 then OpenRCT2. I haven't added anything else, so it's all vanilla as far as I know.

**Comment by DRY411S** [comment]
Perhaps the title of the report is wrong. The issue is that some 'wrong' coaster, ride and stall types are being loaded into the OpenRCT2, when compared with vanilla RCT1.

**Comment by Gymnasiast** [comment]
There are basically two issues here:

1. Some RCT1 scenarios, including Forest Frontiers, use a system where some items in the research list are swapped at random. The Miniature Railway and Monorail are two examples. Try starting the Forest Frontiers scenario several times in RCT1 and you should notice that sometimes the monorail is available, and sometimes the miniature railway is. The same applies to the candyfloss and ice cream stall. Also see here: https://rct.wiki/wiki/Forest_Frontiers#Randomly_selected
2. The RCT1 Steel Mini Roller Coaster is a weird amalgamation of two different coaster types: junior coasters from Zierer, and smaller coasters from Schwarzkopf. Because of this, RCT2 did away with it and instead created the Junior Roller Coaster (same track, no steep slopes, no rocket cars) and the Mini Roller Coaster (steep slopes, rocket cars, but no Ladybird or Log trains). OpenRCT2 is in the process of reintroducing the Steel Mini as the “Classic Mini Roller Coaster”, but since we still lack ports of the Ladybird and Log trains, this doesn’t always translate entirely well in RCT1 scenarios.

**Comment by DRY411S** [comment]
1. When I was better known as rcthelp, I wrote the RCT Station knowledgebase article about RCT1 research trees, and what was available and researchable in every RCT1 + expansions scenario. So this is rather embarrassing, I don't remember the randomisation at the start. Maybe it hadn't been identified as a 'thing' at that time.
2. Understood. You had to make a choice about how to translate the RCT1 ride.

I consider this closed.
