### ISSUE TITLE
Low green bars and high red bars flashing much faster than normal in guest statistics

### ISSUE THREAD

**Issue by Stever1009** [OpenRCT2/OpenRCT2#16324]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (f65e12f on develop) provided by GitHub

### Describe the issue

When viewing a guest's statistics and they have a high red bar or low green bar, it will flash much faster than normal.

### Steps to reproduce

1. Click on a guest.
2. Click the statistics tab (the face icon) to see if they have a high red bar or low green bar. And if they do, it will flash much faster than normal.

**Comment by GalBr** [comment]
I bisected the commits and found that the problem started here (faster but not as fast as now): 20ef6837446d58da9406e10bc6536fb7b48e89a9 and reached the current state here: 531aace06080bd43dc15df483c9ed7d37ba2f27c
@ZehMatt Might be able to find out why quickly, because they worked on that branch, but I'll try to dig deeper when I have time in case we still don't know what caused this.
