### ISSUE TITLE
Changelog window is empty if OpenRCT2 is installed in a non-standard location

### ISSUE THREAD

**Issue by erikjanp** [OpenRCT2/OpenRCT2#16426]
### Operating System

Linux

### OpenRCT2 build

v0.3.5.1

### Describe the issue

If you install OpenRCT2 in a non-standard location, the changelog window is empty because it can't find changelog.txt: it only searches in ./doc and /usr/share/doc/openrct2.
Fix the issue by adding ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DOCDIR} to the searchdir.
Patch can be found here (github doesn't allow patches as attachments???)
https://forums.openrct2.org/applications/core/interface/file/attachment.php?id=8956&key=a1f62c2b975d722f2d08c8089600b2ad

### Steps to reproduce

1. Install OpenRCT2 with -DCMAKE_INSTALL_PREFIX=/opt/OpenRCT2
2. Open the changelog window
3. Look at the empty screen

**Comment by Gymnasiast** [comment]
Creating issues and enclosing patches is very 2000s. Could you make a proper pull request for them (like I asked you on the forums)? There are several reasons why pull requests are better:

- They allow for far easier review
- They save you and us a lot of work, you can just commit on your own system, push it and create a pull request, no manual integration required
- Our CI will test the patches and provide immediate feedback, rather than us having to go back and forth
- You can easily push any fixes that are needed for it to get merged

I know that some projects (overwhelmingly cathedral projects though, not bazaars) still use this old workflow of creating issues with patches attached, but we do not - pull requests save a lot of efforts and time, and also make the threshold for contribution a lot smaller, which is what we want.

If you’re not overly familiar with how pull requests work, we will happily guide you through the process. I can do so via DMs on the forums or on Discord, and I speak Dutch.

**Comment by ocalhoun6** [comment]
Is it also not reporting the version information for you?

If so, it's the same as here: https://github.com/OpenRCT2/OpenRCT2/issues/12909#issuecomment-884470124
