### ISSUE TITLE
Curved wall pieces can be placed intersecting each other

### ISSUE THREAD

**Issue by duckytopia** [OpenRCT2/OpenRCT2#16435]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (7fff8fa on develop) provided by GitHub

### Describe the issue

You can place a curved wall piece inside of another curved wall piece at a different rotation. This affects both of the generic curved wall pieces (tan and colorable). Interestingly, this happens even when the curved wall piece is rotated 180 degrees from the other (and the collision flags should match). In this case, the new curved wall still gets placed but at the wrong orientation.

### Steps to reproduce

1. Select either of the generic curved wall pieces.
2. Place a curved wall piece anywhere.
3. Place another curved wall piece at a different rotation in the same location. The wall is placed when it should instead fail its collision check and display "Can't position this here."

### Attachments

![image](https://user-images.githubusercontent.com/6344725/149311565-f173dfad-cc7d-40de-86d6-49399b9027f1.png)

**Comment by duncanspumpkin** [comment]
Does it work like this in vanilla

**Comment by TheClaudeQC** [comment]
> Does it work like this in vanilla

yes, i did it in rct2 vanilla

**Comment by Gymnasiast** [comment]
As strange as it may sounds, this is correct behaviour. It only uses opposing quadrants, so you can place other stuff in the other two. See this example:

![afbeelding](https://user-images.githubusercontent.com/1478678/150679426-60f69dee-f068-4662-8cf4-315646b13ead.png)

Since the two quadrants left are also opposing, you can place another of these diagonal objects there:

![afbeelding](https://user-images.githubusercontent.com/1478678/150679501-2829c129-d5fd-445c-a3f0-a26572c9c509.png)

Removing this capability would only piss off users and not fix anything.
