### ISSUE TITLE
Tile inspector visibility hotkey does not use a game action

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#16453]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (730364d on develop) provided by GitHub

Still occurring in 0.4.4.

### Describe the issue

When using a hotkey to make an object visible or invisible in the tile inspector, it does not use a game action. This means that in multiplayer, when connected as a client, the host and other players will not see the invisibility toggled. It also will not persist in replays.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Set a hotkey for "Tile inspector: Toggle invisibility".
2. Connect to a multiplayer server as a client.
3. Make any object invisible using the hotkey.
4. Other players still see the object.

#### Persistence: Server-side
1. Restart the server using a local autosave.
2. Reconnect as the client.
3. The object is visible again.

#### Persistence: Client-side
1. Save the map as the client.
2. Load the map in single-player mode.
3. The object is invisible as expected.

**Comment by Broxzier** [comment]
@fidwell I am unable to reproduce this issue using the steps you provided. Do you still experience this issue, and if so, can you please provide additional information?

**Comment by fidwell** [comment]
I've noticed this is still happening, but have learned that it is **only when you use a hotkey** to make things invisible. Clicking the eye icon works as intended.

**Comment by ZehMatt** [comment]
I briefly looked into it, I think its bypassing game actions to do this which means you are doing this only locally and not on the server which also will result in a desync.

**Comment by deurklink** [comment]
I noticed replays also don't pick up on tile inspector action to make things invisible when done through hotkeys - which makes sense since the replays read game actions.

**Comment by ZehMatt** [comment]
The current way the hot key works for this is a bit hacky and has to be refactored, the hotkey should be directly tied to the tile inspector window as it also requires the selected index in order to work, its probably best done by using the window intent system which also needs some overhaul. The best case is that a window simply subscribes to an specific event and when the intent is send to the UI system it will invoke all subscribed functions, there is a big switch that manually deals with this per window basis.
