### ISSUE TITLE
Game not simulating after pausing

### ISSUE THREAD

**Issue by ciscodisco1** [OpenRCT2/OpenRCT2#16617]
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (9466e27 on develop) provided by GitHub

### Describe the issue

Im having a strange issue, when I pause the game it just doesn't resume the simulation anymore after pausing. If I restart the game or reboot my computer it still doesn't resume. I can build and do everything but the simulation just don't run. If I load the same park from an earlier time it still loads. It Might be related to the savegame, so I will attaching the same park from 2 different times and latest updates I played. The file Coaster dreams Entrance works fine, while I cant get Coaster Dreams Pause to resume. 

I would attatch a savefile of the park but Github doesn't seem to support any zip file, but I shared them on this dropbox link: https://www.dropbox.com/sh/c69tjzkvqf3ubxy/AAAyNqH2QmbCOOiWpsthXsIza?dl=0

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Load the park named Coaster Dreams Not running and you will see its not simulating

**Comment by equinoxmatt** [comment]
Not sure if this is helpful, but recently started playing the game and was curious about the code. Anyway, I spent a few minutes working out what was happening here, and all I have so far is that the pause toggle is using values 2 <> 3 rather than 0 <> 1.

How it got in that state - I am not sure. I assume the save state is in the park file.
