### ISSUE TITLE
Auto-Rotate shop to face path, unless manually turned

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#1675]
Basically when you place a shop, orient the shop to face the path, unless the person has hit the rotate button.

**Comment by vzybilly** [comment]
This would be amazing to have, I do allot of poorly designed shopping centers and I waste so much time there placing shops, a good 20 seconds per shop, 2 of each shop, and around 20 different shops, that's a good 800 seconds of time (something over 10 minutes) used with mostly just rotating. granted in the 5+ hours of game, not much time but still allot to go through at once...

**Comment by Patrik356b** [comment]
I'd like to see a button to toggle this feature on/off in the build window

On Sat, Jul 25, 2015 at 4:30 PM, vzybilly <notifications@github.com> wrote:

> This would be amazing to have, I do allot of poorly designed shopping
> centers and I waste so much time there placing shops, a good 20 seconds per
> shop, 2 of each shop, and around 20 different shops, that's a good 800
> seconds of time (something over 10 minutes) used with mostly just rotating.
> granted in the 5+ hours of game, not much time but still allot to go
> through at once...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/1675#issuecomment-124851134>.
>



-- 
Best regards; Hexile

**Comment by vzybilly** [comment]
I think a toggle would be more clear as to "why is it rotating?!" kinda thoughts for people that don't know of the feature... and trying to build the shops before the paths... one thought would be a key mod to turn this feature on with the toggle button, like Ctrl+mouse to have it face a path... another way would be to break each tile into 9 (5?) and have the edge pieces of the tile make the ship turn to face that way... possibly with the toggle functionality as well

**Comment by chrismilne300** [comment]
Why not make the new shop window like the scenery window, where it shows the sprites and have a rotation button that rotates all the sprites to face a certain direction.

It would remove the need for this window to pop up every time you select a shop 

![screen shot 05-14-16 at 09 59 am](https://cloud.githubusercontent.com/assets/1381723/15267457/b154cf1e-19ba-11e6-9697-47b590433c49.PNG)

And would mean that you wouldn't have to keep opening the new shop window every time you wanted to build lots of shops in one go.

![456](https://cloud.githubusercontent.com/assets/1381723/15267462/dd1e8036-19ba-11e6-8b4c-68b02047ef4f.jpg)

This way you could also add a snap to path button directly onto the shop window, which the user could toggle as they needed instead of hiding it away in options.

My only issue with this would be we loose the nice little pictures of the shops like these

![screen shot 05-14-16 at 10 03 am](https://cloud.githubusercontent.com/assets/1381723/15267475/3c6bc77e-19bb-11e6-83cb-d8d53b0f0214.PNG)

**Comment by Patrik356b** [comment]
I prefer the old previews

**Comment by YufeiG** [comment]
I think tapping CTRL should make it snap to the road. And pressing it again would snap to another road if there is another one (thus if there's roads all around you can make it spin around by repeatedly tapping CTRL).

By the way what is the rotate button? I tried R and T but it didn't rotate the shop.

**Comment by janisozaur** [comment]
Implemented in #7411
