### ISSUE TITLE
Focusing OpenRCT2 window after it has lost focus makes it do maximized animation

### ISSUE THREAD

**Issue by Shadowblitz16** [OpenRCT2/OpenRCT2#16989]
### Operating System

KDE Neon 20.04

### OpenRCT2 build

OpenRCT2 v0.3.5.1 (, Debug) (ppa) and OpenRCT2 v0.3.5.1 (appimage)

### Describe the issue

It seems if you have the window maximized (not full screen) and you click on it when it doesn't have focus the window animates like it's expanding the window even if it's not minimized.

I do have compositing enabled when I play.

### Steps to reproduce

1. Open OpenRCT2
2. Expand the window to take up the whole monitor
3. Click out
4. Click back in.
5. See the annoying animation.

**Comment by janisozaur** [comment]
I don't fully understand this issue, could you provide a video of the issue? Also that sounds might like SDL2 issue maybe, not OpenRCT2 specific

**Comment by Shadowblitz16** [comment]
I don't have a video recorder.
But you know how the window expands from a size of current window to the size of the monitor when you maximize it?
It does that, but even if the window size or state hasn't changed when I focus the window.

This only happens in when the window is maximized

**Comment by mrpenguinb** [comment]
I can't reproduce the issue, I sometimes get a visible white flash but that's it.

**Comment by CorySanin** [comment]
[UiContext.cpp:346](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/UiContext.cpp#L346) has got to be the culprit. This little hack is irritating me as well.

I have multiple monitors on my Manjaro XFCE desktop. Let's say default_display is 0 in my config. When I open the game, it opens on display 0. If I move the window to display 1, lose focus, then re-focus the window, the restore and maximize calls will move the window back to display 0.

This block is intended to fix an issue with SDL 2.0.3. Can we just remove it? I'm going to open a pull request to remove it since I can't reproduce #2158 with the hack removed.
