### ISSUE TITLE
See-through guests makes them invisible instead of see-through

### ISSUE THREAD

**Issue by marcinkunert** [OpenRCT2/OpenRCT2#17052]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1-906-gdaeaa98 (daeaa98 on develop) provided by GitHub

### Describe the issue

See-through button makes guests invisible instead of see-through (as for example vegetation)

https://user-images.githubusercontent.com/2963232/165076240-ec716424-2a3b-434c-9217-6cda527233cd.mp4

If there are no plans for making guests see-through, then IMO the button should be replaced with a non-clickable image and an eye-button should be added below for making them invisible.

The same applies for staff.

Related to #16797

### Steps to reproduce

1. Start game
2. Go to transparency options
3. Press invisible button for guests

**Comment by oli414** [comment]
This is intentional, the buttons below (eyes) allow you to toggle between see-through and fully invisible. The button above is to turn the selected mode on or off.

Since the peeps do not support see-through at this time they do not have the eye button to toggle between these different modes.

It does look like the tooltip may need updating to reflect this better.
