### ISSUE TITLE
Path from roller coaster's exit is unable to connect to existing path despite being at the same height

### ISSUE THREAD

**Issue by RuslanTL** [OpenRCT2/OpenRCT2#17179]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

I built a twister roller coaster on the top of a mountain, and then when i tried to connect the exit to the existing path, the path coming from the exist looked slightly raised. It says that they are on the same height, but i'm unable to connect them. I've never encountered this before.

### Steps to reproduce

1. Build twister roller coaster with track raised above ground
2. Try to connect exit to existing path 

### Attachments

![image](https://user-images.githubusercontent.com/53999108/167291442-982957eb-f175-47f9-b6ff-731f92a15719.png)
![image](https://user-images.githubusercontent.com/53999108/167291595-529a4382-1ece-4118-9df4-ddc067914d8d.png)

**Comment by Gymnasiast** [comment]
You enabled the cheat that allows you to build at invalid heights. This is the sort of thing that will happen if you do.

The only solution is to turn off that cheat, delete the roller coaster and the invalid path and rebuild it.

**Comment by ocalhoun6** [comment]
For the benefit of @RuslanTL -- there actually _is_ another solution. Kind of a hack, but it actually works.

1: Disable clearance checks.

2: Build another path underneath the raised path you're trying to connect to.

3: Leave both paths in place, so that they overlap.

4: With the tile inspector, make sure that the ends of both paths have the connection flag turned on.

Peeps will then be able to walk from one path to the other -- when going down, they'll just fall a short distance onto the lower path. When going up, they'll magically teleport slightly upward where the path overlaps. Even staff will be able to use it. Not sure if the peep pathfinding works correctly over such a connection, though, so you might want to have a mechanic with a dedicated patrol zone that keeps him on the odd-height path.

The connection between the two paths will look ugly and glitched, but you can hide it behind some scenery if you want.
