### ISSUE TITLE
Object Selection ride tab animations glitch when holding mouse button down on an inactive ride tab

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17390]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0-240-g9a244b1 (9a244b1 on develop) provided by GitHub

### Describe the issue

This was reported by Jettomukade on Discord.

In the object selection, when holding down the mouse button on an active tab, two ride tabs will play their animations, twice as fast and with possible out-of-bounds sprites.

Some refactoring is required to have support for more than 1 animated tab. Alternatively, fix this by _not_ playing the animation for the tab that is pressed but not active (other windows with animated tabs do this)

### Steps to reproduce

1. Open the object selection
2. Click and hold down the mouse button on any of the other ride tabs
3. The tab animation now plays twice as fast, and may include random sprites

### Attachments

https://user-images.githubusercontent.com/9705046/173927771-279e7e53-46d7-4240-ae0b-db79e8c494e7.mov

**Comment by Derpercoaster** [comment]
I cannot fix the issue myself, since code scares me, but I think I know exactly why this issue occurs. Someone tell me if I am wrong please.

Each tab icon animation is actually a collection of still images, cycling really fast to create a smooth animation.
To show the correct images, the game relies on a timer (running on ticks) to prevent more than the requires images from being cycled through. This "timer" starts with the first desired image, and changes to the next image every tick, until reaching the last assigned image. Each animation has it's own timer.

When you click-hold on another tab, the game prioritizes the animation for the left-most selected tab. However, it does not stop the animation for the currently active tab (something it does in the vanilla game, which means this bug is not present in the vanilla game) when you select a new one.

The problem arises here: The game prioritizes the left-most animation, and thus its corresponding timer, but since the other tab's animation is not deactivated, the timer applies to that other tab too.

Since the timers for each tab are different, one of two things will occur:

1. The left-most animation is shorter than the right-most animation, causing the right one to end sooner than it should, or...
2. The left-most animation is longer than the right-most animation. In this case, the right animation will use up its own images, and will pull from the next image in the image cache, which causes seemingly random images to appear.

My best idea of how to fix this is simple: Force a tab's animation to deactivate if you click on another tab that uses animations (or just another tab in general).

**Comment by AaronVanGeffen** [comment]
This happens because it's using the wrong animation length. The sequence is off by one due to the 'all' tab being present. The code is compensating for it, but incorrectly.
