### ISSUE TITLE
Scenario Editor Terrain Generation & Park Entrances

### ISSUE THREAD

**Issue by xperia64** [OpenRCT2/OpenRCT2#1762]
If I place one or more park entrances, and generate some terrain, terrain generation removes all of the park entrances as expected, but the editor thinks the entrances are still there and won't let you finish because it's impossible to place a path to them. If you place all four entrances, it's impossible to place any entrance after terrain generation.

**Comment by MrManiak** [comment]
I posted this issue before realizing it was already here. Here's my post:

Hey, I was editing a scenario when I noticed a bug. If you generate a terrain using the Simplex Algorythm tool with a park entrance already in place, it will glitch the scenario into thinking that there's an unlinked entrance on the map, thus preventing you from going further in the scenario creation process. It says "Can't advance to next editor stage... Park entrance is wrong way round or has no path leading to map edge"

Plus, I can only place 2 entrances meaning that the 2 first entrances that I placed before map generation are still technically somewhere in the scenario since the entrance limit is 4.

Here's the glitched scenario.
https://dl.dropboxusercontent.com/u/94196634/Chuck%20Woods.sc6

EDIT: I can confirm that every generation tool can cause the bug.
