### ISSUE TITLE
Can't save parks/tracks or write anything to disk

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#17664]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

889293f

### Describe the issue

At some point after playing for a few hours, a certain bug occured that prevented all writing to disk. I discovered that the bug had happened when trying to save the park and it said "save game failed".

The last autosave was made at 22:42:59, so the bug happened between that point and 5 minutes after it. This time period starts at roughly 2 hours and 46 minutes into the stream: https://www.twitch.tv/videos/1548387157

### Steps to reproduce

I have no idea how to reproduce it or what triggered it.

### Attachments

The last autosave:
[autosave_2022-07-31_22-42-59.zip](https://github.com/OpenRCT2/OpenRCT2/files/9229764/autosave_2022-07-31_22-42-59.zip)

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/17665 to get some more info

**Comment by lalip** [comment]
I tried reproducing this bug:

I made a fresh install of windows 10 on an old laptop (2007 core 2 duo) and left Marcel's park running on build `4fcdafc` (which was the latest at the time) at "turbo" speed, and with autosave set to 1 minute intervals. At first, I figured it'd be better if I didn't ask it to render much, so I pointed the viewport outside the park where the only motion would come from balloons and rain. Several rides crashed in the meantime, and I closed the windows whenever I saw them.

Turns out some of this might play a part, because the game ran for almost 22 hours straight; at this point I moved the viewport closer to the middle of the park, and the bug showed up within an hour. I started the test over (although I forgot to reboot the computer for good measure) without moving the viewport away, and this time it happened in just under 2 hours.

Hope this helps in some way
[17664-attempt-1.zip](https://github.com/OpenRCT2/OpenRCT2/files/9380014/17664-attempt-1.zip)
[17664-attempt-2.zip](https://github.com/OpenRCT2/OpenRCT2/files/9380016/17664-attempt-2.zip)

**Comment by janisozaur** [comment]
Thanks, we will take a look at those dumps. Can you also provide the park where it happened? In your second attempt did you perform any actions or just moved viewport around? Together with the dump there should be a replay file, is it available (I think we use .parkrep extension)? Can you upload it as well?

**Comment by lalip** [comment]
The park is the one attached to the OP. I'll upload my last autosave just in case, though I guess it won't say much. The one from my first attempt is surely gone by now though.

In the second attempt I might have closed a ride window out of habit, but other than that, yes, I only moved the viewport a little to keep it near where it failed the last time. It wasn't very scientific to be honest 😅

> there should be a replay file

Ohh, yeah sorry about that, I made a mental note of it when I saw it in the console window but then forgot.
I'm attaching the config file too just in case.
[more files.zip](https://github.com/OpenRCT2/OpenRCT2/files/9385362/more.files.zip)

**Comment by Cowscrazy** [comment]
I'm getting the same glitch.  I seem to be fine and then I can't save after about 5-10mins of game play after restarting.  The game is totally unplayable now.  I thought it might have to do with OneDrive since thats what it was saying it couldn't save to but that wasn't the issue.  

I will point out that when it fails to autosave there are times I am able to pause the game and do a manually save.   Then reboot the game and play for another 5-10mins.       But most times it will not allow this.

**Comment by CookiePLMonster** [comment]
#18178 should fix this.
