### ISSUE TITLE
Undefined string when building on height inbetween

### ISSUE THREAD

**Issue by autosysops** [OpenRCT2/OpenRCT2#17703]
### Operating System

Windows 11 Build 22000

### OpenRCT2 build

Version: 0.4.1 (be518f4)

### Describe the issue

![image](https://user-images.githubusercontent.com/96066335/182720301-c281c266-b00f-4395-86ac-fe7beee3239b.png)
When building a piece of track which is in between two heights (so on a odd number) I get this error (as shown in the screens)

### Steps to reproduce

Build a piece of track
use the object tile inspector to lower it 1
open the ride and construct it again and try to add a piece.

**Comment by ocalhoun6** [comment]
There's a cheat in the cheat menu for "enable building at invalid heights". Do you have that cheat enabled?

**Comment by autosysops** [comment]
> There's a cheat in the cheat menu for "enable building at invalid heights". Do you have that cheat enabled?

I was sure I selected it but I just checked and it was unselected. might still be a bug because of the undefined string :), but the functionality works.

**Comment by Gymnasiast** [comment]
Yes, the undefined string is definitely a bug. It _should_ tell you the height is invalid.

**Comment by Kuhnovic** [comment]
The string is present in the language file (stringid 954, STR_CONSTRUCTION_ERR_UNKNOWN), but it's empty. And then there's this code in the GetString function (LanguagePack.cpp):
![image](https://user-images.githubusercontent.com/68320206/182920761-fd2a214a-1fbf-47fd-b395-b27ded28d9be.png)

Seems a bit odd to me to return a nullptr if the string is actually found but empty. It might be empty by design.
