### ISSUE TITLE
Custom music objects

### ISSUE THREAD

**Issue by ZeroDiamond** [OpenRCT2/OpenRCT2#1783]
I know that the game already allows for two custom tracks if converted to 16-bit stereo 22050hz WAV and named CUSTOM1.WAV and CUSTOM2.WAV respectively, but it would be a nice enhancement to allow for full customization of music from within the game.  The idea is that the music dropdown would have a "Custom music..." option at the bottom that, when clicked on, would open a browser window and allow you to choose any song on your hard drive.  Ideally this feature would allow for MP3/OGG music to be used, but even if it still required the specific WAV type the engine currently allows, it would still be useful just for the sake of having more than two custom tracks.

**Comment by Gymnasiast** [comment]
It's in the plans, @LRFLEW is even tinkering with this kind of feature.
However, since it wouldn't be compatible with SV6, don't expect it too soon.

The plans are to turn the ride music into (a kind of) .DAT files, after we switch to our own save format (SV6/SC6). This will require full implementation first.

**Comment by LRFLEW** [comment]
Since I started some basic development on this feature before I was told about the .DAT solution proposed, I started designing my own system. With the creation of this issue, now seems like as good of a time as any to outline what I plan on doing.

So the game has two concepts for music: tracks and styles. Tracks are individual songs, (currently stored in WAV format in the base game's install directory). Styles, however, are a set of one or more tracks that will play a random track when selected (The base game has only one style with more than one track, which is the Merry-Go-Round's style). I plan on creating a system where you can add custom tracks, and setup custom styles. The game supports 255 tracks and styles, but only uses 46 tracks and 33 styles. This leaves a lot of room for custom music.

For sources, I'm currently working on just WAV files for now (It doesn't need to be 22.05kHz anymore). After I get it working with WAV, I will be focusing on getting codecs to work (FLAC first, then OPUS, Vorbis, MP3, AAC, then whatever else I have time for). I have 4 ideas for playing audio right now. They are: playing a local audio file, streaming an audio file via HTTP, and two "helper" streaming types (YouTube and Twitch). Once the codecs are working, the other 3 types of audio sources will be feasible.

This feature setup is complex, but doesn't need to wait for full-decompile to begin. I'm going to work on this issue as much as I can. Once the time comes, a .DAT solution can be easily made to work with the system I've outlined here.

**Comment by Patrik356b** [comment]
I could contribute with a scifi / horror track if interested.

**Comment by PFCKrutonium** [comment]
LRFLEW, you mentioned Twitch - I would love to have a Windows that isn't auto closed that plays a twitch stream ;)

**Comment by Gymnasiast** [comment]
You should use the actual names of the tracks, that would make it a lot easier to distinguish between styles and tracks. For example: 'Techno style' and 'Brimble's beat'. :)

**Comment by devnoname120** [comment]
Should this work with multiplayer too, knowing that music files might be big, and thus long to transfer? Maybe we could use deferred music loading, so that music continues to load in the background while the player is playing on the server. Also some caching, so as to avoid loading them each time the user joins a server.

**Comment by ddugovic** [comment]
@devnoname120 Traditionally that would be called a music streaming service, no?  I like the idea of custom music playlists, although trying to keep all players' music queues in sync (with delayed playback) sounds challenging.

**Comment by devnoname120** [comment]
@ddugovic I thought about downloading the whole prior to playing it, while streaming usually means buffering a little ahead while playing the song. I thought short tunes for rides or something like this, I don't think that it would be a good idea for whole songs, it would be too heavy.

**Comment by IntelOrca** [comment]
The plan is for music to be like objects, but not bound to a saved game or scenario. This means you can play a game without owning the music object (a substitute will be used).

For all objects... rather than sending them from server to clients, they can instead just send only the object IDs that are required. The client can then automatically fetch and download them from a content distribution server if they do not have them before joining the game. This is how OpenGRFs work in OpenTTD.

**Comment by PFCKrutonium** [comment]
So we need a CDN.

**Comment by Patrik356b** [comment]
It would be nice to incorporate something like ccmixter.org for music cdn if possible.

**Comment by IntelOrca** [comment]
This is essentially complete now. It will automatically be enabled when we move to our new save format.
