### ISSUE TITLE
handyman stuck on few tiles of clear path

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18023]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

b161a46 develop, AppImage

### Describe the issue

Got a handyman that will never leave the same 2-3 tiles. Turning back will _not_ always happen at the same place, sometimes he walks one tile more (happens after a couple of seconds in in the savegame, and at ~12 seconds in the video)

Observations:
- The patrol area is larger.
- _Removing_ the patrol area liberates him.
- There's trash on the path in/under the Haunted House "No entrance"-styled exit. He never removes it.

I have not managed to recreate the issue "from scratch".

### Steps to reproduce

- run attached park (it's actually zipped this time)
- see handyman never leave the same 2-3 tiles

### Attachments

[stuck_handyman.zip](https://github.com/OpenRCT2/OpenRCT2/files/9561465/stuck_handyman.zip)

**Comment by cheweytoo** [comment]
Video:

https://user-images.githubusercontent.com/29800630/190028779-32af8eef-1f2b-4eb1-a369-f948354a0312.mp4

**Comment by cheweytoo** [comment]
Sort of related question that came up when I tried to replicate the issue: Is there a way to manually place/remove trash? I haven't found anything relating to that in the tile inspector.

**Comment by ocalhoun6** [comment]
There's (somehow) trash on the tile of path underneath the invisible exit of this haunted house. The handyman is trying to get to it, but he can't because a ride exit is in the way.

And because handymen are kind of stupid about pathfinding, he just keeps trying to get to that one piece of trash forever.

For the handymen's stupid pathfinding, we have issue #3205

This particular instance of it is caused by using the zero clearance cheat to have a path and a ride exit on the same tile. I assume the path was built first, and then some peep dropped trash on it before the ride exit was placed? This is probably a very rare occurrence, but to avoid it in the future, you could build the ride exit first and then the path underneath it second.

**Comment by cheweytoo** [comment]
I'm honestly not completely certain, but I _think_ I remember building the exit first, and only adding the path via cheat because the ground looked empty then.

**Comment by ocalhoun6** [comment]
Is it possible that peeps exiting a ride could drop trash on the ride exit's tile _if_ that tile also has a path on it?

If so, that might be the bug behind the bug.

To test that, I'd recommend building a large test park with _lots_ of rides situated like this -- invisible entrances/exits, with path tiles place underneath with zero clearance ... plus plenty of shops and stalls that sell trash-producing items ... and no handymen to clean it up. Just to be sure, build all of that before opening the park, so you can be sure that no litter was dropped before the ride exits were placed.
Let that run in hyper speed for a few hundred in-game years, then:
1- Close the park
2- Use the 'remove all guests' cheat
3- Delete all the path tiles _except_ the ones underneath ride exits
4- Delete all the rides
5- Observe and see if you can find any trash on the remaining path tiles that were underneath ride exits.

**Comment by Broxzier** [comment]
> There's trash on the path in/under the Haunted House "No entrance"-styled exit. He never removes it.

There's the problem. The handyman tries to get to the trash, but bumps into the invisible exit.

**Comment by cheweytoo** [comment]
Closing this since it's "wontfix" and the root cause is #18090.
