### ISSUE TITLE
Bumbly Beach Big Dipper Construction Issue

### ISSUE THREAD

**Issue by whj9014** [OpenRCT2/OpenRCT2#18053]
### Operating System

Win 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.4.1-312-gd263464 (d263464 on develop) provided by GitHub

### Describe the issue

Trying to edit Big Dipper at Bumbly Beach, but the coaster building options are severely limited. Cannot add special tiles (brakes) and only curves available are slight bend.

No cheats enabled, no changes made. This is the first action after loading the scenario.

### Steps to reproduce

Launch the game.
Start Bumbly Beach.
Close the Big Dipper and try to modify the track.

### Attachments

![image](https://user-images.githubusercontent.com/28377783/190929397-16f8cdff-56ab-4727-9a08-967dfa5d9161.png)

**Comment by James103** [comment]
Does this happen when trying to build or edit any other wooden coaster in any other scenario?

**Comment by whj9014** [comment]
> Does this happen when trying to build or edit any other wooden coaster in any other scenario?

Nope!  Just this specific coaster.  I can build other woodies no problem

**Comment by ZeeMajora** [comment]
I suspect this might be due to the trains for the classic wooden roller coaster (the ride type of this pre-built scenario coaster now) not being in the currently used objects release for develop builds.
I'm not sure how it's exactly handled but a recently implemented change makes it so that rides will only show track pieces if any of their currently available trains have sprites for traversing that track piece. And seeing as the classic wooden roller coaster's trains are not in that could potentially explain why this is happening, as the classic wooden coaster technically does not have _any_ trains available for it to determine what elements should be available.
Does this occur with any other wooden coasters from rct1 scenarios that use the 4 seater cars? (eg: double trouble in crumbly woods, the classic wooden coasters in karts & coasters)
And does it _not_ occur with any wooden coasters from rct1 scenarios that use the articulated cars? (eg: woodpecker in haunted harbor)
If both of those are positive then what i said is probably the case, but luckily this should be fixed as soon as a new objects release comes to develop as the classic wooden roller coaster trains have been added to the objects repo.
In the meantime you should be able to use the arbitrary ride type changes cheat as a workaround to change big dipper's ride type from the classic wooden roller coaster to the wooden roller coaster which should work as expected.
