### ISSUE TITLE
Underground shops & facilities don't show when adjacent to non-underground path.

### ISSUE THREAD

**Issue by PeytonHanel** [OpenRCT2/OpenRCT2#18094]
![Dynamite Dunes 2022-09-24 19-43-58](https://user-images.githubusercontent.com/26446761/192125977-1e670d29-0738-4a68-b1e3-7bddbccecc32.png)

**Comment by Gymnasiast** [comment]
Please use the bug report form next time, it’s there for a good reason.

**Comment by rik-smeets** [comment]
The issue here is that an underground stall right next to a non-underground footpath is basically completely invisible, even though it _is_ actually connected to the path. This can be seen on OP's screenshot - there's a path connection straight into the wall, because there's a shop there. 

I'll try to fix this one.
