### ISSUE TITLE
Longterm Goal: Extra Game Sprites

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1829]
So I was recently talking about classic Rollercoaster Trains. But I just had another thought. Some day, I predict it will be possible to hack track designs themselves, by swapping trains. Example: A Monorail train on a Wooden track. However, as easy as that will be to accomplish, the takeoff would be; glitchy sprites. Somewhere out there, someone may be good with spritework and could edit existing sprites for angles such as upside down or vertical. A better example of my point would be the OpenRCT2 title screen. There is a log flume that goes over a steep drop, but only tilts gently.
I dont expect this to be done immediately, heck, Ill be lucky to see this in Version 1.

Lemme know what you think about this idea, I think it will really help. Thanks!

**Comment by PFCKrutonium** [comment]
If you can get in touch with Simon Foster, if I am not mistaken he still has the original models for the coasters/everything else, and I am also fairly sure that they are under a license to him that would allow us to use them (and by extension, distribute them, making OpenGFX not needed). If you got in  touch with him and convinced him to help us out, we could do it in a fairly short amount of time.

**Comment by AaronVanGeffen** [comment]
Simon is [on YouTube](https://www.youtube.com/user/simonAtDrippycat) and has done several videos on how the models were exported to sprites, but I'd be very surprised if he *could* licence them out to this project. Even if he wanted to, there's probably an exclusivity clause in his agreement with Chris Sawyer.

**Comment by Gymnasiast** [comment]
Some years before, a user from OpenTTD asked him a similar question about Transport Tycoon's model. Simon answered that Atari (through the acquisition of Hasbro Interactive, which had acquired Microprose) had most of the rights, but that he retained the rights to license them under a non-commercial licence.

Now, the same _might_ apply to RCT's sprites as well. I'd say it's worth a shot, at least we'll know. I think I'll do it, since I think it would be very handy if we could legally distribute the sprites.

**Comment by IntelOrca** [comment]
If would depend if the actual 3D models were considered licensed. If you could re-render them as new 32-bit sprites.

**Comment by PFCKrutonium** [comment]
Which would allow us to upgrade our graphics much sooner :D

**Comment by IntelOrca** [comment]
Alternatively someone attempted a kickstarter to reproduce all OpenTTD graphics in 32-bit, although unsuccessful - its a way of having an artist work full time through crowd funding.
https://www.kickstarter.com/projects/1512547915/pineapple-graphics-for-openttd

**Comment by devnoname120** [comment]
@Gymnasiast Were you able to contact him? The idea of better-quality sprites generated from the original 3D models thrills me.

**Comment by Gymnasiast** [comment]
@devnoname120 : I haven't yet contacted him, because I have been busy and I want to do it properly, as well as well as discussing it with IntelOrca first. It is on my list, though, but for the middle or long term, since we're still far from the point where this would be handy. I understand your excitement though. :-)

**Comment by IntelOrca** [comment]
This has been resolved for vehicles that were compatible with steep slopes in RCT1.
As for others, there is a graphics replacement project: https://github.com/zrowny/OpenRCT2-OpenGraphics
