### ISSUE TITLE
Top toolbar doesn't refresh after network desync.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1849]
The top toolbar does not refresh when the game disconnects due to de-synchronisation on a client. This should be as simple as calling gfx_invalidate_screen after the network close function has been run so the toolbar redraws.

**Comment by pizza2004** [comment]
I'm confused as to why it kicks the other player when there's a network de-synchronisation.  I tried playing the latest version with my friend and it was completely unplayable because of this change, since trying to build a roller coaster would cause a de-sync, and so would half of the other actions he took apparently.  We had to downgrade to OpenRCT2.com build 1155 because of these issues.

**Comment by Quantum64** [comment]
Should https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/network/network.cpp#L470 attempt a reconnect?

/cc @zsilencer


/cc @zsilencer

**Comment by IntelOrca** [comment]
@Quantum64 It would be nice if it showed a window with a reconnect button.
