### ISSUE TITLE
Litter bins fill up too fast

### ISSUE THREAD

**Issue by joflashstudios** [OpenRCT2/OpenRCT2#1860]
I need to do some more research on this, but I'm pretty sure the litter bins in my park are filling up way too fast - i.e., after a single guest puts trash into them or something. How much trash are they supposed to take before filling?

**Comment by Gymnasiast** [comment]
2 pieces.

**Comment by PFCKrutonium** [comment]
I would vote to make it maybe 5-10?

**Comment by IntelOrca** [comment]
The amount of storage space there is for how much they are filled is quite limited.

**Comment by IntelOrca** [comment]
Maybe the feature was removed for this reason?

**Comment by Gymnasiast** [comment]
Hm, I'm not sure.
Does anybody know how many pieces of litter a litter bin could take in RCT1?

Anyway, I think it's a limit that we should raise _when_ we have the possibility to do so.

**Comment by joflashstudios** [comment]
Is it two bits? In that case it seems to me (though, obviously you know better than I do) that they should be able to hold at least 3:
00 - empty
01 - one item
10 - two items
11 - three items (full)

Or perhaps that's what you meant and I'm misinterpreting you, @Gymnasiast.

In any event, I still haven't done any further study on this, but I've been playing a lot of RCT1, and I would swear they don't fill as fast as RCT2 bins.

**Comment by IntelOrca** [comment]
@duncanspumpkin implemented the bin logic, so he might be able to shed some light on this when he's back from holiday.

**Comment by Gymnasiast** [comment]
@joflashstudios : I have taken a closer look earlier today and it's a bit murky: it says 2 in one place and 4 in another. The fact that the feature was broken in vanilla RCT2 doesn't make things easier.

**Comment by duncanspumpkin** [comment]
Its actually the other way round 00 - full (3 items), 11 (empty). I've checked the logic for this and it all looks correct. When a peep goes to use a bin it doesn't always count as a bin use there is a scenario_rand() which has to be satisfied as well. This allows bins to actually take much more rubbish than 3. I did test this quite a bit when I wrote it so I think it is working correctly but if someone else could take a look that would be great. Its possible that its actually a graphical mistake and the bins are operating correctly its just that 1 item looks the same as 3 items.

**Comment by IntelOrca** [comment]
Given this feature never worked originally, if the bins are indeed filling up too fast then we can just lower the chances that it will actually increment the bin item count so that its satisfactory.

**Comment by Gymnasiast** [comment]
That sounds like a good solution to me.

**Comment by IntelOrca** [comment]
I'll leave that down to a community poll or something.

**Comment by remcooo96** [comment]
Still no solution? I am playing vanilla again because of this reason.

**Comment by Gymnasiast** [comment]
I didn't have problems with it, to be honest, after the earlier changes. It's also a sign your handymen aren't organised very well. The fact that it doesn't happen in vanilla is just because vanilla litter bug never get full due to a bug.

**Comment by HaasJona** [comment]
In the parks I played with so far (just normal scenarios, nothing too huge) I never noticed any problem with them getting full too fast. I also never really played RCT2 only RCT1 and I don't notice any problem or difference.

You obviously need to hire a few extra cleaning staff for larger food areas, but that's realistic and to be expected.

I wouldn't mind slightly lowered chances, though, if the majority wants that. But I also like the game to be realistic and somewhat difficult.

**Comment by Gymnasiast** [comment]
Well, indeed, I had to hire some extra handyman and put a fixed area on some of them. But for the size of my park, that was well within reason.

**Comment by remcooo96** [comment]
Just one thing I dont understand: In vanilla rct2 my garbage cans  do actually get full now and then. So So that means in vanilla there is a limited capacity, but much higher than in openrct?

With a park with around 6,000 guests it is hard to make profit if you have to hire around 15 extra handymen just to empty your trashcans.

**Comment by HaasJona** [comment]
> With a park with around 6,000 guests it is hard to make profit if you have to hire around 15 extra handymen just to empty your trashcans. 

That sounds reasonable to me. In a more normal size park with 600 guests you probably need about 1-2 extra handymen for garbage in my experience.

**Comment by IntelOrca** [comment]
Obviously its hard to compare with RCT2, so we would need to ask people if they ever noticed a problem with this in RCT1.

**Comment by remcooo96** [comment]
Why do the garbagecans in original RCT2 sometimes get full if it is mentioned earlier that this feature is removed?
Personally, I never had the problem of full garbage cans in RCT1.

**Comment by Gymnasiast** [comment]
You're the first person to claim they actually fill up in vanilla. Not one of the devs has ever experienced this, and I have played the game (disk version) for 12 years.

By the way, I only needed a few extra handymen to empty the bins in my 6000 guest park, so it looks like you have a problem organising them.

**Comment by remcooo96** [comment]
I can show you full garbage cans in an old savegame I have. In that savegame I never ever used openrct, so that couldnt be the reason they got full. Maybe it has something to do with the 2 expansion packs?

**Comment by IntelOrca** [comment]
@remcooo96 I am not sure what the details of the bug was, but it could be that they got filled but never emptied and it never checked if it was full when a peep used one. @duncanspumpkin might have a better idea as he fixed the bug.

**Comment by duncanspumpkin** [comment]
When I said it didn't work in vanilla  rct2 it wasn't quite true. Bins can never fill if you have certain types of rubbish (standard flags rubbish). But if you have only the other type of rubbish (extra flags rubbish) you can fill the bins. At least that's what I remember. We could change the random chance to make it rarer that rubbish fills a bin though

**Comment by remcooo96** [comment]
I think that would be a good idea. In my opinion that would make the game much more realistic, and also more in line with RCT1.

**Comment by IntelOrca** [comment]
@remcooo96 There is no proof that it RCT1 has a lower chance of filling up. And we don't want to really make game mechanic changes unless there is a community push for it.

**Comment by remcooo96** [comment]
Normally there is one thing I hate in games and that are cheats. But in this case maybe a function in the cheats to empty trashcans could help?

**Comment by Gymnasiast** [comment]
There is one: "Remove litter". Gets rid of litter on the paths and in the bins.

**Comment by vzybilly** [comment]
how hard would it be to have the chance be a setting in the cheats menu?
allowing for all types of people... hardcore ones that set it to 100% for a
challenge to get the cleanest park award. also allowing people who don't
want to deal with trash, they can set it to 0%

I think this could actually be a nice thing to have... it would be easy for
people to tweak to their own play styles.

**Comment by Gymnasiast** [comment]
We have a cheat to empty the bins already, that's sufficient. Either the bins currently fill up too fast or they don't. If it's really the first, then we should lower the chances of filling, if it's the latter, we shouldn't.

**Comment by HaasJona** [comment]
Can someone check what the percentage in RCT1 is? If we match the RCT1 behaviour, I'm inclined against a change.

**Comment by remcooo96** [comment]
maybe split the remove litter cheat in clean paths and empty trashcans?

**Comment by duncanspumpkin** [comment]
@HaasJona checking rct1 would be impossibly hard. @remcooo96 I really doubt there is enough demand for anything like that.

**Comment by joflashstudios** [comment]
@HaasJona @remcooo96, there is really no point in adding more cheats or tweaks of any sort for this issue. If you want to cheat to resolve your litter woes use the existing cheats.

The issue is about the appropriate speed/chance of filling litter bins.

**Comment by rvgr** [comment]
Bumping this issue, since I just discovered OpenRCT2 and the filling speed of litter bins is really striking compared to RCT1 (which I still play a lot).

For comparison, here's some handymen stats from RCT1:
![capture d ecran 2016-03-25 a 11 35 47](https://cloud.githubusercontent.com/assets/18069013/14042932/e0289a22-f27e-11e5-8626-825c7d5059b4.png)
(Number 7 is patrolling near food stalls)

And from OpenRCT2:
![capture d ecran 2016-03-25 a 11 36 42](https://cloud.githubusercontent.com/assets/18069013/14042942/f8e8c0f0-f27e-11e5-8b59-ecfb41f4fe8c.png)
(Number 3 is patrolling near food stalls)

In both games they have been hired for around a year, and we can see that in OpenRCT2 the number of bins emptied is enormous (and this park only have 400 guests). At this point bins are filled in a few seconds all over the park, not only near food stalls, and I must assign to each bins a handymen so that it doesn't get out of control.

I don't remember having this problem in vanilla RCT2 and definitely don't have it in RCT1, perhaps is it better to stick with vanilla RCT2 bug of non-filling bins, or highly decrease chance of filling bins?

**Comment by Broxzier** [comment]
Since there are only two bits available, and 4 stages is not enough at all, what about just making the chance a piece of garbage fills the bin lower? When a guests throws something in it, make it a 15% chance it fills the bin by one, this way, then it will take almost 7 times as many items on average, with still only two bits in use to store its current state.

**Comment by Broxzier** [comment]
After having looked at the code, and some talk in the Gitter chat, it looks like that the chance of litter filling up the bin already has been reduced, but it's still 85% (7/8).

By changing `scenario_rand() & 7` to `scenario_rand() & 7 == 0` it should be only 15%. This might be a result left from an error made while decompiling the original code, since the x86 instructions check for zero instead of > 0.

**Comment by HaasJona** [comment]
That actually sounds very likely. I think I read somewhere earlier that the chance is supposed to be around 15%. If the code is really missing the ==0 then that should be fixed.

**Comment by Broxzier** [comment]
That might have been my earlier comment, but there my 15% was just an estimation, it's really a coincidence that it's actually 15%.
