### ISSUE TITLE
Allow languages to fall back to more than just en-GB

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#18945]
In order to more easily allow different variants of languages to be supported we should allow them to fall back to more than just en-GB. For example, if we were to add Canadian French, it should first fall back to European French and only then to UK English.

**Comment by TheClaudeQC** [comment]
Subscribed to this issue to get read up to work out in fr-CA

**Comment by AaronVanGeffen** [comment]
An approach for this could be to have an extra field specifying the fallback language in the language definitions, which could then bubble back. For example, `fr-CA` could fall back to `fr-FR`, which in turn falls back to `en-GB`. You could chain this, e.g. hypothetically `nl-NL` -> `en-US` -> `en-GB`.

I would suggest leaving `en-GB` as the implicit default and last-resort, rather than specifying `en-GB` in pretty much all other places.

**Comment by karst** [comment]
I think it'd be nice on the top of language would read out what language it'd default to in the language files themselves. `STR_FALLBACK   : en-GB`

**Comment by AaronVanGeffen** [comment]
> I think it'd be nice on the top of language would read out what language it'd default to in the language files themselves. `STR_FALLBACK : en-GB`

In OpenLoco, language files have a header for this kind of metadata, removing the need for hardcoded definitions in C++ entirely:
https://github.com/OpenLoco/OpenLoco/blob/0bd7055b548b77a93b3a8f8e5c2dcd182199595c/data/language/en-GB.yml#L1-L5

Perhaps something similar can be implemented in OpenRCT2, but that might be a bit out of scope for this issue. :-)

**Comment by TheClaudeQC** [comment]
Can I have a ping when the product will be ready?

**Comment by tupaschoal** [comment]
@TheClaudeQC I suggest you just subscribe to this issue, cause when the feature is implemented, the issue will likely be closed and then you'll hear about it
