### ISSUE TITLE
Change _currentTrackCurve to a struct

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#19003]
Currently, bit 16 is set when a special track piece is selected, which complicates checks. Rather, it should be a struct with a track piece (16-bit unsigned int) and a bool. This struct may also be needed for some other variables, this needs to be checked.

**Comment by spacek531** [comment]
I believe `_currentTrackCurve` is *three* properties:
- SpecialTrackPieceSelected flag
- TrackElemType uint16
- a value from this enum: https://github.com/OpenRCT2/OpenRCT2/blob/0674d9527c8a5872c62607dccbac91d104d40fb4/src/openrct2/ride/Track.h#L203-L214

These properties are taken from the TED when that piece is built, it will choose the next piece to build from the CurveChain property.

My understanding of the value is:
- track elements that have a specific track piece that follows/precedes has that TrackElemType defined and the SpecialTrackPieceSelected flag set (e.g. corkscrew -> next corkscrew piece)
- track elements with only a direction set will use the selected turn radius with the appropriate slope and bank values

I have a feeling this could be refactored heavily. For example:
- _currentTrackCurve only stores the radius and direction state of the window. An enumvalue of 255 is added to indicate "use special track element"
- TrackCurve values are refactored to be *only* TrackElemType values
- another property is added to TED to store the radius and direction value of the track element, since they're the same for backward and forward building

Example of what TED values would look like:

TrackElemType::LeftCorkscrewUp
CurveChain = { TrackElemType::RightLargeCorkscrewDown, TrackElemType::Flat}
CurrentPieceCurvature = TRACK_CURVE_NULL

TrackElemType::LeftQuarterTurn3TilesUp25
CurveChain = {TrackElemType::LeftQuarterTurn3TilesUp25, TrackElemType::LeftQuarterTurn3TilesUp25}
CurrentPieceCurvature = TRACK_CURVE_LEFT_SMALL

**Comment by Gymnasiast** [comment]
I misidentified the flag - it’s not set when a special track piece is selected. Rather, when it is set the value contains a track piece ID, and if it is not set, the value contains a curve. So it’s only two after all.
