### ISSUE TITLE
Ride rating calculation very slow on large parks

### ISSUE THREAD

**Issue by formlesstree4** [OpenRCT2/OpenRCT2#1912]
This is not game breaking. It's more of an annoyance.

I have a rather large park (the same park in #1911 ) that, upon constructing a new ride and testing it, the test results take a very long time versus a park that has much fewer rides. I assume that's because the game engine is doing a lot of work while performing the calculations, but I felt it should be brought to light.

Save file:
https://www.dropbox.com/s/vgm5liku4senrsa/The%20Flatlands%202.SV6?dl=0

EDIT: v0.0.3 Build 1215

**Comment by IntelOrca** [comment]
This is present in vanilla RCT2. It is because the game is always checking every single ride in turn and updating its ratings (as new scenery and environmental changes can affect the ratings). Thus the more rides, and the longer they are (tracks), the longer it will take to calculate each ride rating until it gets to the ride which you are waiting to be calculated.

Whilst it is quite easy to increase the amount of computation that is done per game tick, I don't want to interfere with it until I have a greater understanding of the performance implications. So I could only suggest that its modified to prioritise rides that do not have a rating first in the ride calculation loop.
