### ISSUE TITLE
Rename `Id` to `ID`

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#19261]
This is a common misspelling in our codebase, induced by TitleCase renaming.

**Comment by Broxzier** [comment]
I'm not sure if this is actually the best approach of going about abbreviations. This way you can have abbreviations directly followed by another word, and it's not immediately clear where a word ends and begins. Of course, `ID` is small, but it would be ideal if things are consistent. `RC` vs Rc` for example.

The [Google C++ naming rules](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules) even mentions this explicitly, and shows an example:

> a "word" is anything that you would write in English without internal spaces. This includes abbreviations, such as acronyms and initialisms. For names written in mixed case (also sometimes referred to as "[camel case](https://en.wikipedia.org/wiki/Camel_case)" or "[Pascal case](https://en.wiktionary.org/wiki/Pascal_case)"), in which the first letter of each word is capitalized, prefer to capitalize abbreviations as single words, e.g., `StartRpc()` rather than `StartRPC()`.

We already have a function that's all-caps now because of the recent refactors: `CPUID`, which should be named `CpuId()`. The former makes it look like a macro.

**Comment by Gymnasiast** [comment]
I have already corrected Rct and Rc and some others, renaming Id to ID **makes** it consistent. And I'm sure as hell not going deliberately induce spelling mistakes just because the function looks like a macro. Then you should just come up with an alternative.

**Comment by Broxzier** [comment]
That some work has been put into it doesn't mean that it's right or can't be improved. The reason I put that information here is that the current style has downsides. Considering this is mentioned in a global coding style used by many, makes it a largely tested approach. I am all for consistency, but clear naming and avoiding collisions are important considerations too.

> I'm sure as hell not going deliberately induce spelling mistakes.

-1 because of this. I don't get why you often feel the need to use this kind of language while discussing the simplest things. I'm merely putting my doubts about this approach here.

**Comment by Gymnasiast** [comment]
I'm just stating that I'm not going to introduce spelling mistakes, and that's unacceptable now?

**Comment by Broxzier** [comment]
Yes, because that doesn't mean anything. We're not writing books, but code. Like the quote from my first comment says, "prefer to capitalize abbreviations as single words", following these style guidelines doesn't make it a spelling mistake.

**Comment by Gymnasiast** [comment]
Fine. Do whatever the hell you want then.

**Comment by ZehMatt** [comment]
Considering Id comes from "Identifier" I would argue that the short version should be "Id", going to close this.
