### ISSUE TITLE
Request: Clone Tool

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#1926]
The idea being I could build a section of part, like say a food court, or a custom building made from scenery, and then use the clone tool to quickly copy and paste it. It should copy shops/stalls/flat rides, but not Roller Coasters, as well as copying Paths/Items on paths (Benches, Garbage Cans, Lamps). It should of course cost the total value of all the items, as new items. 

Edit: Not a cheat.

**Comment by IntelOrca** [comment]
It should definitely not be classified as a cheat. I have ideas for a system where you can copy and paste path & scenery and even save it as a scenery design just like you can save tracks.

**Comment by Patrik356b** [comment]
In RCT3 there is a blueprint tool to do such things so i wouldn't call it a cheat

**Comment by Nubbie** [comment]
#4737

**Comment by Broxzier** [comment]
@Nubbie: The tile inspector barely implements this tool, it only copies _one_ map element, while this new tool should be able to copy multiple elements, and have a preview and a ghost show up.

**Comment by fromthere** [comment]
We should implement
- drag to draw area for copying since selecting all object by hand will be annoying
- object selection code of track design save could be re-used but we should modify "select all nearby object"
- file format for saving(if we add new file format, maybe we can change other file format too)
- if used object not found, player should warned about missing object
 - maybe bundling object in saved objects file?

**Comment by AaronVanGeffen** [comment]
Has since been implemented in the tile inspector, I believe?

**Comment by jensj12** [comment]
This suggestion is about copying large areas at once. The tile inspector can only copy one item at a time.

**Comment by IntelOrca** [comment]
This is basically track designs with scenery and without tracks.

**Comment by IntelOrca** [comment]
Implemented by plugin: https://github.com/Sadret/openrct2-scenery-manager
