### ISSUE TITLE
Save game dropdown doesn't prompt for overwriting if there is a save with the scenario name

### ISSUE THREAD

**Issue by Enzemo** [OpenRCT2/OpenRCT2#1942]
If you start a game on Forest Frontiers for example, play a little and save it as Forest Frontiers, and then start a new game on Forest Frontiers and click the "Save game" option on the drop down, it will immediately overwrite your other save file. This works on any scenario and seems to be 100% reproduceable. It's led to me losing a couple of parks by accident, but that's my own fault really

**Comment by IntelOrca** [comment]
I think the fix for this should be for "Save" to only save if the park was previous saved using Save As or loaded from an existing file - otherwise it should do the same action as Save As. Save should not default to anything if you start a new scenario and perform a Save As until there is a user specified file.

**Comment by Enzemo** [comment]
That sounds like the most logical solution, and would stay in line with traditional behaviors of most popular programs; Word for example

**Comment by runelaenen** [comment]
#2004 should fix this problem.
