### ISSUE TITLE
Big positive vertical G Force no longer red?

### ISSUE THREAD

**Issue by giraty** [OpenRCT2/OpenRCT2#19566]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-344-ga018cb1 (a018cb1 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Looks like there's a bug now when big positive vertical G Force above 5 no longer marked red

### Steps to reproduce

1. Build a ride.
2. Go wild with the speed and curves that result in big G Forces.
3. Positive G's are not red above 5.

### Attachments

![image](https://user-images.githubusercontent.com/8456673/222940808-6d5df39c-3b57-4b95-a99f-9a59f51a7ff1.png)

![image](https://user-images.githubusercontent.com/8456673/222940822-cc3ff4bd-e09d-4ee3-97d4-e4cc38d0f565.png)

**Comment by ocalhoun6** [comment]
This was an intentional change -- because no coaster or other ride has a stat penalty for excessive positive G-forces.

(High positive vertical Gs still contribute to the intensity rating, but there's no single threshold number where it's suddenly *too* high. Compare that to lateral Gs or negative vertical Gs, where there is a specific stat penalty for going over a specific number. And those numbers will turn red when they hit the penalty zone.)

**Comment by giraty** [comment]
Makes sense, sorry I missed that as I haven't play in some months
