### ISSUE TITLE
Cross-platform multiplayer

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#1965]
As we have a working Linux build now and aim in general direction of cross-platformness, multiplayer should not depend on winsocks, as it does now, but rather on some other portable library that would allow connecting regardless of the machine and system the user is using.

We should also try to keep maintaining a "no network" (like we do now) build for easier porting to systems that might not support networking.

**Comment by JarnoVgr** [comment]
Maybe ENet can be useful? http://enet.bespin.org/

Also, is there a reason to favor TCP over UDP?

**Comment by janisozaur** [comment]
TCP seems to be discouraged for multiplayer (http://gafferongames.com/networking-for-game-programmers/).

Perhaps there might be something interesting in OpenTTD's code, I think they've done it nicely.

**Comment by IntelOrca** [comment]
TCP is the right protocol to use for this game, I would never consider UDP because the order of packets matters and most would always get re-sent if they never reached the other size. TCP implements this on a network level, if we use UDP this would be done at application level and therefore be less efficient.

**Comment by zsilencer** [comment]
Winsock is 99% the same as normal sockets and is simple to convert.  Intelorca is right and openttd uses TCP also.

**Comment by janisozaur** [comment]
I think it can be closed now, as multiplayer generally works with @zsilencer's #1970
