### ISSUE TITLE
Unable to edit a pre-existing rollercoaster

### ISSUE THREAD

**Issue by Hypo74** [OpenRCT2/OpenRCT2#19906]
### Operating System

Windows 10 64 bits

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

In scenarios with pre-existing rollercoasters that you cannot remove, the ride cheat "All destructible" allows me you delete the ride, but I cannot edit it, for instance removing a piece track.
It happens in every scenario with pre-built rides like Dragon's Cove, Dusty Desert, etc.

### Steps to reproduce

1. Open a scenario such as Dragon's Cove.
2. Enable "All destructible" ride cheat.
3. Try to remove a piece of track of any coaster.

### Attachments

![rct2-bug](https://user-images.githubusercontent.com/122159876/231285166-de82f28d-bb58-4828-8c9c-2c8eb5b2d89a.png)

**Comment by ZehMatt** [comment]
The issue is that it only clears the indestructible flag on the rides but the track elements used store another flag `TRACK_ELEMENT_FLAGS2_INDESTRUCTIBLE_TRACK_PIECE` which is not removed from the track elements when the cheat is used. The way the cheat currently works is by iterating over all rides and removing the indestructible flag but it would be better if the cheat toggled an boolean to signal that the action should ignore that flag instead of removing it, there is the problem that this cheat can not be reverted while the other option preserves the original state. TLDR: To tackle this issue we should introduce a new cheat variable that is either on or off and make the game actions ignore the flag when the cheat is currently enabled.

**Comment by Chase-Percy** [comment]
Hi, I had an attempt at fixing it as you mentioned @ZehMatt. It seems to have fixed it but I am not familiar with the engine and may have missed something.
