### ISSUE TITLE
Classic wooden coaster should be 34.5 meters, not 60 meters

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#20094]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.4-209-gd464e71 (d464e71 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

so, in rct1, you can build the wooden coaster (classic wooden coaster) at a maximum of 34,5 meters high [115 feet] (23 units) above the ground, but in OpenRCT2, the classic wooden coaster have the same height as the rct2 wooden coaster, which is 60 meters [200 feets] (34 units) above the ground, which dosen't make sense, especially if the chainlift is only between 4 to 8 kmph (3 to 5mph)

### Steps to reproduce

1. open a park whit the classic wooden coaster
2. build yourself a classic wooden coaster
3. try to build it as high as you can
4. you get stopped by "supports too high" at around 60 meters, which is the bug (rct1 only have a maximum of 34,5 meters (traducted in rct 2 metric)), why should I get to build them higher than I could do it in rct1?

### Attachments

what it is like right now (notice that the hybrid is also here but it shouldn't be too much borthered):
![Parc sans nom 2023-04-29 19-03-24](https://user-images.githubusercontent.com/83843734/235327911-06dd7513-9015-4621-8ed2-3f4f6856caea.png)

how it should be :
![Parc sans nom 2023-04-29 19-03-42](https://user-images.githubusercontent.com/83843734/235327932-69b1bef7-1d31-499a-b693-647747e73afe.png)

**Comment by ZeeMaji** [comment]
Can this be assigned to me? I want to fix this along with checking for any differences between the max build heights of other ride types to see if any more ride types need to be changed for rct1 parity.

**Comment by TheClaudeQC** [comment]
I could check out on the go if I saw other rides whit also this issue

**Comment by TheClaudeQC** [comment]
oh, and I have a question.

Why the hypercoaster was raized from 66 meters to 81 meters?

**Comment by TheClaudeQC** [comment]
and we should consider the rct1 corkscrew train seperate of the rct2 one, as rct1 allow a massive 54 units versus 27 units for the rct2 counterpart, which the rct2 hypercoaster seem to have gotten since OpenRCT2

**Comment by TheClaudeQC** [comment]
and it seem that we should be allowed the number of cars to a minimum of 3 in the articulated trains from the rct2 wooden coaster, as rct1 allow between 3 to 12 car per train

**Comment by ZeeMaji** [comment]
> I could check out on the go if I saw other rides whit also this issue

I would rather check it myself as i would like to check and compare every ride type between the two games, i'll look into it tomorrow. I appreciate the offer though.



> oh, and I have a question.
> 
> Why the hypercoaster was raized from 66 meters to 81 meters?


> and we should consider the rct1 corkscrew train seperate of the rct2 one, as rct1 allow a massive 54 units versus 27 units for the rct2 counterpart, which the rct2 hypercoaster seem to have gotten since OpenRCT2

I believe that's because that was the height of the corkscrew coaster in RCT1, which in turn meant it was also the height of the hypercoaster in RCT1 due to them sharing the same ride type. 
As for the corkscrew coaster's height i believe the devs have mentioned in the past that they do not want RCT1 parity for it or the twister coaster (as it and the hyper-twister also shared the same ride type and thus build heights in RCT1) due to the RCT1 heights being absurdly unrealistic when used on the now separate corkscrew/twister coasters.

I could be wrong or they could have since changed their minds, if so then i could also change those in my upcoming PR.

**Comment by ZeeMaji** [comment]
> and it seem that we should be allowed the number of cars to a minimum of 3 in the articulated trains from the rct2 wooden coaster, as rct1 allow between 3 to 12 car per train

I wouldn't say this is super on topic for this issue but i have looked into this before, there's quite a few trains with different min cars per train between the two games but i'm a bit more wary about changing those as it could break specific track designs with short stations due to this being a minimum, so i would prefer to avoid changing these at this current time.
