### ISSUE TITLE
Refactor ride type flags for RIDE_TYPE_FLAG_HAS_NO_TRACK, RIDE_TYPE_FLAG_HAS_TRACK

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#20239]
That seems quite odd to have two flags
```cpp
RIDE_TYPE_FLAG_HAS_NO_TRACK = (1uLL << 15),
RIDE_TYPE_FLAG_HAS_TRACK = (1uLL << 28),
```
We can ditch RIDE_TYPE_FLAG_HAS_NO_TRACK  and assume its trackless for when RIDE_TYPE_FLAG_HAS_TRACK is not present, having both states makes no sense.

**Comment by reul** [comment]
I'm looking into that issue and trying to understand if there would be any unexpected side effects to that. 

Does that mean that, eg in `src/openrct2/ride/gentle/meta/FlyingSaucers.h`:                    

`RIDE_TYPE_FLAG_CANNOT_HAVE_GAPS | RIDE_TYPE_FLAG_NO_TEST_MODE | RIDE_TYPE_FLAG_HAS_NO_TRACK |`

we'd ditch `RIDE_TYPE_FLAG_HAS_NO_TRACK` 

and then in `./src/openrct2/ride/RideConstruction.cpp`, instead of 
`(ride->GetRideTypeDescriptor().HasFlag(RIDE_TYPE_FLAG_HAS_NO_TRACK))`

we would check:
`(ride->GetRideTypeDescriptor().HasFlag(RIDE_TYPE_FLAG_HAS_NO_TRACK))`

My concern is if there's any ride types that don't have either of the flags set. I'm going to check each of them.

**Comment by reul** [comment]
I'm looking into that issue and trying to understand if there would be any unexpected side effects to that.

Does that mean that, eg in src/openrct2/ride/gentle/meta/FlyingSaucers.h:

`RIDE_TYPE_FLAG_CANNOT_HAVE_GAPS | RIDE_TYPE_FLAG_NO_TEST_MODE | RIDE_TYPE_FLAG_HAS_NO_TRACK |`

we'd ditch `RIDE_TYPE_FLAG_HAS_NO_TRACK`

and then in ./src/openrct2/ride/RideConstruction.cpp, instead of
`(ride->GetRideTypeDescriptor().HasFlag(RIDE_TYPE_FLAG_HAS_NO_TRACK))`

we would check:
`(!ride->GetRideTypeDescriptor().HasFlag(RIDE_TYPE_FLAG_HAS_TRACK))` .

My concern is if there's any ride types that don't have either of the flags set. I'm going to check each of them.

**Comment by Gymnasiast** [comment]
Yes, that would be very prudent. We named those flags based on what the code did, but there is no guarantee they are truly each other’s opposite. I do not know if @ZehMatt checked this before opening the issue, but if he has, he didn’t mention it.

**Comment by Gymnasiast** [comment]
Coasters use the _COMMON_COASTER define, which is several flags grouped together, including HAS_TRACK.
