### ISSUE TITLE
park or the game

### ISSUE THREAD

**Issue by Tramcoaster** [OpenRCT2/OpenRCT2#20284]
![Schermopname (1)](https://github.com/OpenRCT2/OpenRCT2/assets/108947550/a7103514-f21b-4b95-aaf1-8d1ab41f5df6)
### Operating System

Wndows 10 

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub
### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

the game crashes every time i change map or scenario too many times. and when you close the game

### Steps to reproduce

if you go to a different park every time the game will crash I don't know what the problem could be

### Attachments

ignore the other screen. 
this happens every time when opening another park too many times

**Comment by Gymnasiast** [comment]
Did you click 'Yes' when asked to upload the dump?

**Comment by Tramcoaster** [comment]
no i didn't do anything. i click no. what should i click yes?

**Comment by ZehMatt** [comment]
Yes

**Comment by Lastorder-DC** [comment]
1. Upload dump by clicking "Yes"(If your issue is reported before, no new issue will be created)
2. Manually find dump file from your OpenRCT2 user folder(usually located at `%USERPROFILE%\OpenRCT2\crash` or `%USERPROFILE%\OneDrive\Documents\OpenRCT2`

If you don't do neither above no one can check your issue. first is usually most easy way.
