### ISSUE TITLE
shop_item_is_food_or_drink() returns true for sunglasses

### ISSUE THREAD

**Issue by ccfreak2k** [OpenRCT2/OpenRCT2#2056]
I'm not sure if it's an original bug, but I'm not sure that sunglasses are classed as a food item since the caller in marketing.c uses this call to determine whether to make the free food/drink voucher available.

**Comment by RollingStar** [comment]
![image](https://cloud.githubusercontent.com/assets/4810902/10498399/1773a55a-7299-11e5-9883-383c684b6a13.png)

This is from normal RCT2. It looks like ORCT2 does extra testing to determine which advertising campaigns to make available. Normal RCT2 behavior is to list all campaigns and show an empty dropdown menu if there are no applicable attractions in the current park.

The bug is that ORCT2 shows the "voucher for free food or drink" campaign even with just a sunglasses stall enabled in the park. It's a one-line change, but I'm going to test it before submitting a PR.

Here are two scenarios for testing. They are in "Other Parks".

http://www.mediafire.com/download/sab479bf43c4b8i/Sunglass_Test.SC6

http://www.mediafire.com/download/r8xnkwyxyw6rfy1/No_Food_No_Drinks_No_Glasses.SC6

**Comment by duncanspumpkin** [comment]
Fixed in #2055
