### ISSUE TITLE
Generate terrain from heightmap image (e.g. png)

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2060]
Self-explanatory idea, but i dunno how this would be implemented...

**Comment by vzybilly** [comment]
This is my thought of how to achieve this.

each tile would be 2x2 points (pixels for grey-scale), rct2 map size is heightmap.width/2, heightmap.height/2

Step 0, smooth lightly, since I don't think a tile can be more than 2, maybe 1 height difference between corners.
Step 1 would just have to set the heights for all the tile corners... the tile center, if needed, would be the average of the 4, rounded.



Another way would just be to set the tile height, leaving rough edges to be smoothed, either by the user or by a smoothing algo

**Comment by IntelOrca** [comment]
The random map generator already has code to convert a 2D height map array into RCT2 map element form with appropriate smoothing and terrain applying. So that can be used initially for a basic implementation of this feature. The water level would work in the same way.

However this won't allow you to set cliffs or lakes above the water level which you could add into a height map. If you use greyscale, you only have a precision of 8 bits for height... if you want to more accurately specify cliffs and smooth ground in the height map and water, you will want to make use of all three RGB components using a scale of e.g Blue to Brown to Green to White.

**Comment by Patrik356b** [comment]
@IntelOrca  Another way to set water level could be by using a different/mask file

**Comment by Aroidzap** [comment]
I would like to do that and also improve whole map generator, but it will take me some time (few months I think), becouse I want it to be perfect and I am new to this project. Could you associate it to me @IntelOrca? Thx in advance :)

**Comment by Gymnasiast** [comment]
@Aroidzap : We can only assign ourselves unfortunately.

**Comment by Aroidzap** [comment]
ok, so should i work on it? or leave it to someone else?

**Comment by AaronVanGeffen** [comment]
You can make a PR for your ongoing work, I guess. Just indicate that it shouldn't be merged yet and it'll be tagged "work in progress".

Mind you, if you think it might take you "a few months" it might be better to split your goal into different subtasks and make PRs for them separately.

**Comment by IntelOrca** [comment]
I wouldn't have thought something like this would take more than a few hours of actual time working on it. We can't assign issues to any user, only those that have write access to the repository. So your own assignment message should be enough.

**Comment by Aroidzap** [comment]
For experienced programmer it will take few hours... but not for me... I'm just offering my little help. If you don't want it, it's ok and assing it to someone else. I just tought this feature is not so important to be done early.

**Comment by Gymnasiast** [comment]
If you want to do it, please do it. I just meant that I can't use Github's assignment feature on other people. Consider this your assignment. :)

**Comment by Aroidzap** [comment]
ok ;)

**Comment by Patrik356b** [comment]
Any progress on this?
The current map generator i feel should have 2 sliders on the first two tabs to make it more useful :
Terrain style: Flat - Mountain slider
Land/Water slider

**Comment by Aroidzap** [comment]
Sorry, not actually

**Comment by IntelOrca** [comment]
@Patrik356b I think @X123M3-256 has been doing some things with map generation.

**Comment by X123M3-256** [comment]
@IntelOrca Yes, I have code for translating a heightmap into tile positions, but I do not have a way to load the heightmap from disk. Does OpenRCT2 already link SDL_Image or another image loading library? I'd rather not introduce a new dependency for this so if there's already a library I could use that would be ideal. What is used for saving screenshots?

Also, my code is not ideal. When fed nice smooth functions it gives good results, but when given noisy functions more typical of terrain, there's a lot of tiles that could be placed better.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/image_io.h

**Comment by X123M3-256** [comment]
OK, I'll use that to load the heightmap.

**Comment by janisozaur** [comment]
#5282
