### ISSUE TITLE
Remove VScode settings from the repository 

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20618]
I'd like to remove `.vscode/launch.json` and the gitignore rule for `.vscode/tasks.json`  from the repository.

It's not usual to include IDE settings like this in a repository since they can vary by developer. In my case, I use VSCodium which doesn't even support most of what's in `launch.json`. For people still using VSCode, if they ever try and set up a pre launch task they'll always have spurious changes in their repository that they'll have to be aware of when committing or rebasing or whatever.

**Comment by IntelOrca** [comment]
I think you can prevent this by doing `git update-index --assume-unchanged .vscode/*`.
The .vscode files currently checked in are agnostic and should work for everyone by default since they use default or relative paths. These are very useful for developers checking out fresh as they can debug straight away in vscode.

In particular, the cpp properties file has the right information for background parsing the OpenRCT2 code base for each platform.

**Comment by mrmbernardi** [comment]
I never had a problem with the `c_cpp_properties.json` file and I can use your `assume-unchanged` workaround to deal with the `launch.json` file.

However, I still maintain that `tasks.json` should be removed from the `.gitigore`. It's currently set to never ignore this file, which means that as soon as you create it you will forever have an untracked file listed.  Most people working on the project with .vscode for more than a couple hours would create this file so I'm probably not the only one with this issue.

`assume-unchanged` doesn't work on this file since it's not actually in the repository. Nor does adding it to `.git/info/exclude`.
