### ISSUE TITLE
0.00 Excitement rating

### ISSUE THREAD

**Issue by TreyJ84** [OpenRCT2/OpenRCT2#2064]
I downloaded the 0.0.3 Build 1313 a few days ago. Played for a little bit & everything seemed to be working OK.
Today I was playing in the Beach Barbecue Blast/Australia - Fun at the Beach scenario.
I built a Splash Boats ride and tested it. I got 0.00 excitement rating. I edited it, made the ride a bit longer, but when I tested it again, 0.00 excitement. I deleted the ride and built a new one. This time I got a normal rating.
So I then build a Flying Roller Coaster... Spent several game months saving the money (don't wanna cheat) and when I finished, tested it... 0.00 excitement rating. I saved the design and deleted the ride. I built it again, tested it, but same thing, 0.00 excitement rating. So I close out the program and try again. I use the saved track design in a different saved game. After testing, I got a good excitement rating, but noticed the Intensity rating was about 1.00 difference. So I open the Beach Barbecue saved game and rebuild my coaster. Tested, 0.00 excitement. Not sure what the problem is; anyone else having this issue?

**Comment by rctdude2** [comment]
I noticed this as well, however after a few seconds it updates properly.

**Comment by TreyJ84** [comment]
It's quite odd. I just tried building the saved design and it worked this time, but the Intensity ratings are still very different. When showing 0.00 excitement, the intensity was about 9.75. Now that it's showing excitement (8.35), intensity is 8.52. Also, just wanted to say THANK YOU for this project. My RCT2 wouldn't work before! Now I'm in heaven.

**Comment by TreyJ84** [comment]
So I've been playing fairly often in this same Beach Barbecue Blast scenario and noticing it's not just the excitement rating that's affected. Like rctdude2 says, it will eventually fix itself, but several times I've had all ratings at 0.00 or just really low.
I built a large woody with a loop that gave me something like 0.00 excitement, 2.42 intensity & 1.25 nausea. It updated of course, but still weird. I haven't tested in any other scenarios or saved games yet.

**Comment by e-foley** [comment]
I've encountered this myself on build 1327. I built a wooden roller coaster and saw that the excitement rating was 0.00 and the intensity rating was way off.  Both fixed themselves after about 30 seconds or so.

**Comment by Dragondraikk** [comment]
Encountered this myself. It looks like ride ratings are automatically set to 0.00 instead of saying that it's still calculating them, as it used to be. This does not have an impact on guest behavior though, so it seems to be a UI only bug.

**Comment by IntelOrca** [comment]
I think I know the problem now, will fix later.

**Comment by e-foley** [comment]
I'm not thrilled with this solution since any ride that has an excitement rating of exactly -0.1 will mess up the check.  I'd rather address the only place in code that allows an excitement rating to be negative in the first place, which is that condition involving RIDE_TYPE_FLAG4_HAS_AIR_TIME [here](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/ride_ratings.c#L801).  Limiting the airtime penalty would help the problem and save us from worrying about the "-1" corner case.

**Comment by IntelOrca** [comment]
@e-foley -1 or 0xFFFF is used all around the codebase as it did in RCT2 to mean undefined. Perhaps this might change in the future but right now that's how it works and I have to be consistent.

**Comment by e-foley** [comment]
You're not wrong.  What I'm saying is that we haven't really fixed the negative-excitement bug until we've addressed the source of the negative ratings.  There's a difference between addressing a problem at its source and passively adjusting for it downstream.  We're doing the latter right now and that approach tends to mask the core issue.

**Comment by IntelOrca** [comment]
Well its because the penalties outweigh the ratings. See #2031.

**Comment by HaasJona** [comment]
Yeah. The better fix would probably be to limit the penalty to be at max as large as the current excitement rating so it doesn't go below zero.

Or just apply the suggested changes from the other bug because heartline coasters are horribly useless.

**Comment by IntelOrca** [comment]
The penalties aren't necessarily applied last though.

**Comment by HaasJona** [comment]
I don't think that matters. If we add some bonus after resetting it to 0.0 then it will maybe become 1.2 or something like that. Which still is very bad and probably makes even more sense than 0.0. But I also support the proposed fix of just capping the airtime bonus instead of applying the penalty.

**Comment by IntelOrca** [comment]
@HaasJona It does matter, you would get higher ratings if penalties were done before other additions but were capped due to going negative. Most of the time they will go positive by the end of all the calculations. Its only the odd scenario where it doesn't and needs to be capped to 0.

**Comment by e-foley** [comment]
With only *one* exception, ride ratings are calculated by doing all the additive operations first, then doing multiplicative operations on the resulting ratings based on the various "penalties" the game imposes.

The reason the airtime reward/penalty is so weird is because it is an additive/subtractive tweak that happens after every single other ride rating adjustment.  As I discuss in #2031, it's also the only adjustment that allows the result to go negative.

@IntelOrca says that penalties aren't necessarily applied last.  This in itself is true, but it implies that the airtime penalty acts the same as the other penalties, which is not the case.  We should be looking at the additive or multiplicative nature of the adjustments, not the "bonus" or "penalty" nature of them.

If I can get Visual Studio working, I'll test the change I would make and submit a PR for it.

**Comment by pizza2004** [comment]
I have to agree really.  This seems like an oversight by Chris Sawyer, and honestly it seems to make the roller coaster useless from what everyone says.  Why not try to make it more like what it seems intended to be like?

**Comment by pizza2004** [comment]
I mean, unless when he programmed it his intent was that you'd get no bonus for that kind of ride, but if airtime lasted more than 96 you'd get a penalty for doing that.  I don't know what exactly that accomplishes, unless maybe he just wanted it to drag the score down.  I'd have to look at what ride this even is.

**Comment by pizza2004** [comment]
Has anyone considered that maybe it was supposed to add instead of subtract in the first place, just that it was meant to only start applying the bonus after 96 airtime instead of for the entire airtime?

**Comment by HaasJona** [comment]
> Has anyone considered that maybe it was supposed to add instead of subtract in the first place, just that it was meant to only start applying the bonus after 96 airtime instead of for the entire airtime?

I think looking at the ride and the decompiled code it's pretty clear that the intent was to cap the air time to 96, not subtract 96 from the air time.

The problem with Heartline coasters is, that it's very easy to get a lot of air time, so just subtracting 96 from the bonus is not enough of a nerf there. Capping makes more sense, I think, and would be closer to the original game.
