### ISSUE TITLE
"Parts Not Supported"

### ISSUE THREAD

**Issue by JohannDerJaeger** [OpenRCT2/OpenRCT2#20671]
### Operating System

Windows 11 64-Bit

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

It won't let me save rides in the track designer and a popup tells me "Parts not supported by track design format". Why there's any parts that aren't allowed in the track designer doesn't make sense. If this isn't a bug, I would recommend adding whatever unsupported track pieces to whatever determines what parts are and aren't allowed. This issue is primarily on ride types added in OpenRCT2 like the single rail rollercoaster.

### Steps to reproduce

1. build single rail rollercoaster using the quarter-loop, left and/or right zero-g turn, and downward left and/or right twist on a 90-degree drop.
2. Try to save the track design.
3. Get frustrated that you can't save a design for an arbitrary reason.

### Attachments

![Screenshot 2023-08-01 071331](https://github.com/OpenRCT2/OpenRCT2/assets/141138495/4e72bb5d-1541-428d-ab70-7dd241fbdf4f)
![Screenshot 2023-08-01 071428](https://github.com/OpenRCT2/OpenRCT2/assets/141138495/4442605d-d562-4805-aea6-27f6563490cf)
![Screenshot 2023-08-01 071506](https://github.com/OpenRCT2/OpenRCT2/assets/141138495/5e9925ec-9a92-496e-bf07-91337a282b2c)
![Screenshot 2023-08-01 071537](https://github.com/OpenRCT2/OpenRCT2/assets/141138495/a2cf8b5a-fbaa-4dce-ba40-08f2faaf4900)

**Comment by X123M3-256** [comment]
This isn't a bug. This happens if you use track pieces that were not in the original game. This currently means zero G rolls, medium half loops, large corkscrews, and diagonal sloped turns. These elements cannot be saved in a TD6 file and so it is not possible to save track designs using these pieces until OpenRCT2 moves to a new track design format.

You can save the new ride types as long as the design doesn't use the new elements aren't used.
