### ISSUE TITLE
Add authors, tracks and image field to ride music window.

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#20832]
A good first issue feature request that people have been asking for.  Thisone is from #17385.

With the addition of ride music objects, custom music can be added. To give proper credit to these people the tracks field and authors field of the object should be displayed on the ride music window of rides.

These fields are currently already displayed on the object selector.

With a ride music object you can include an image, this should be displayed when it's been included with the object.

The track field can become quite long if someone adds a big playlist. See Fairground organ style 2. Make sure there's enough space to add have this, or make the window expand with a certain amount of given tracks.

**Comment by karst** [comment]
That's starting to look wonderful.
I am curious what it'd look like if the current slider on the side would be aligned with the arrow of the drop down, and then have a slider on the bottom for text that's longer than that. To better fit in the window, as it might be odd for it to expand horizontally.

**Comment by johnwdolph** [comment]
Here's a few screenshots of the progress with this feature:

1. This is what the windows look like when an image preview is available (the preview is always centered with the left text box)
![music_previews](https://github.com/OpenRCT2/OpenRCT2/assets/29528014/8d5c6ab5-cf2c-487f-afe9-b8188d9b2060)
3. This is what the windows will look like when no preview is available (the windows can be resized alternatively to using the scroll bars)
![music_no_previews](https://github.com/OpenRCT2/OpenRCT2/assets/29528014/0555d10b-a2e6-4921-bc23-df5993feba02)
4. I might need some help figuring out a bug. Whenever the music toggle is disabled when opening the ride window, the scroll bars are not visible. They reappear when I click on the music page tab. When the toggle is enabled upon opening the ride window, the scroll bars display as expected.
![bug](https://github.com/OpenRCT2/OpenRCT2/assets/29528014/767a4707-daab-4992-bbff-cd59420c0010)

My most recent code is in the ui branch of my fork (https://github.com/johnwdolph/OpenRCT2/tree/ui).
The bug is the last thing that needs work unless there are new suggestions for the layout.

Thanks
