### ISSUE TITLE
Trying to save under a folder with no write permissions causes a crash.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#20845]
It seems that attempting to do so will just lead to a crash instead of proper error handling and informing the user that saving the file failed.

To reproduce such a crash try to save a park file under `C:\Program Files` or any other folder in where the write permissions are restricted, this requires UAC on Windows to be enabled. The same will most likely happen on Linux too when trying to save it under `/root` when the user is not root or has no permissions granted to write anything there.

**Comment by ocalhoun6** [comment]
Just tested this in linux:
![Screenshot_20231003_154132](https://github.com/OpenRCT2/OpenRCT2/assets/26573303/ea076a63-10d9-4f5d-8475-468b8c310de9)
It gives a very sensible error message, but the error message is presented in a new out-of-game window. The game appears to freeze at that point, and appears to crash when you close the error message, *but* it actually doesn't. The game only gets minimized and runs in the background. If you switch back to it with Alt+Tab, you can resume play without losing anything.

----

I kind of suspect that it might be the attempt to display this error message that's actually crashing windows, not the save attempt itself.

**Comment by ZehMatt** [comment]
I just tested this, it definitely asks if the user wants to report a bug but when the user doesn't have permissions to write in a certain directory, its not really a bug and should rather tell the user to choose a different path instead of giving the possibility of sending a useless report.

**Comment by zzril** [comment]
This error message was added to [src/openrct2/park/ParkFile.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/0e8d46ea7cfdb2118435d1735967a359f936dbea/src/openrct2/park/ParkFile.cpp#L2576-L2604) in #17665 as a means to collect memory dumps in order to help with investigating the - at that time unfixed - #17664. (See [this](https://github.com/OpenRCT2/OpenRCT2/pull/17665/files#r935443662) resolved discussion in the PR that introduced the error message.)

That issue has been identified as a memory / resource leak and fixed with the merge of #18178 in October 2022, so there's no need for the error message anymore.
