### ISSUE TITLE
info kiosk moves

### ISSUE THREAD

**Issue by MichaelJmad** [OpenRCT2/OpenRCT2#20974]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) 

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Noticed the game saying people could not reach the kiosk, looked and it was not where I placed it
if you rotate the game it moves and when you rotate back to the angle it was placed its back where it should be

### Steps to reproduce

Place the info kiosk then rotate the game

**Comment by ocalhoun6** [comment]
Likely what happened is that you placed the kiosk on top of the path instead of next to it, the game automatically raised it high enough to be placed above the path, and due to the 2.5D perspective, it looks like it's in the proper place from some angles, but other angles show where it really is.

Can you post a screenshot or saved game to confirm?

**Comment by Gymnasiast** [comment]
The explanation of @ocalhoun6 seems the most likely to me - the isometric perspective often confuses new players. Since OP did not reply, I’m closing this.

**Comment by MichaelJmad** [comment]
Thanks for the reply, I was never notified that anyone had posted.
Thanks @ocalhoun6 I opened the save and did some testing and you appear to be correct, I grew up on these games and had at least to my memory never had that happen, and to be fair, I did not even know it was possible.
