### ISSUE TITLE
Split-sec glitch when opening a ride with uncapped FPS

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2104]
When you open a ride like a log flume with uncapped FPS on, there is a frame or two where you can see all the vehicles in their uninitialised / partially uninitialised positions.

![image](https://cloud.githubusercontent.com/assets/1482259/10674453/cd54f1b2-78f2-11e5-94ab-5e811dcadba3.png)

**Comment by Nubbie** [comment]
Couldn't reproduce this in the latest build 4e53fc4
Is it fixed?

**Comment by IntelOrca** [comment]
No, it still happens.

**Comment by mrtnptrs** [comment]
Does this only happens when you build the log flume in water?

**Comment by IntelOrca** [comment]
@mrtnptrs I noticed it

**Comment by ZehMatt** [comment]
Appears this bug is because of the tween code capturing the initial position and then its moved far away next frame.

**Comment by tupaschoal** [comment]
This still happens on v0.3.1.
It only happens when opening, not testing. I could capture one buggy frame in the gif

![JDGUBMJ](https://user-images.githubusercontent.com/6443427/94998841-4586fe80-058b-11eb-835f-a08414b29828.gif)

I used this park
[FlumeFlicker.zip](https://github.com/OpenRCT2/OpenRCT2/files/5322110/FlumeFlicker.zip)

**Comment by ZehMatt** [comment]
Can't reproduce this, this is probably fixed, even using host_timescale 0.1 I can't see the anything happening.
