### ISSUE TITLE
Guests have rendering issues in queue lines

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#21042]
### Operating System

Windows 11, 64-bits

### OpenRCT2 build

OpenRCT2, v0.4.6-174-g004592b (004592b on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

It will show any queue lines whit guests glitching

### Steps to reproduce

1. Open any scenario (my example is in Diamond heights whit the Snake River Falls Log Flume's queue line)
2. Check any non-covered queue line
3. Guests will partially dissapear

### Attachments

https://github.com/OpenRCT2/OpenRCT2/assets/83843734/d7e4d69d-038d-41fa-a27f-8cc5ded50fcb

**Comment by TheClaudeQC** [comment]
it's actually worst. Any non-OpenGL settings will make the issue

**Comment by mrmbernardi** [comment]
I originally though this might be issues with sprite sorting or maybe copying the wrong pixels around, but after turning all the other sprites off it seems the guests are being clipped somehow. It gets worse or better depending on framerate. I had a situation where it chopped almost all the guests in half but I couldn't reproduce it while recording (I'm guessing since it alters the framerate).

[vid.webm](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/ec03d333-bb4e-4dfc-9b5c-b24d4254d1b3)

**Comment by ZehMatt** [comment]
How did you disable the sprites? This might be still a sorting bug, keep in mind that the void is also in the graph so it might be fighting with that.

**Comment by mrmbernardi** [comment]
Yeah I just used the transparency options. If it was sorting, wouldn't it occur with OpenGL too? And wouldn't it be the entire sprite not just the upper section?The dirty region debug setting is currently broken but it appears to be caused when the peeps are split across two regions. Invalidating the entire screen doesn't fix it, but when I do that they only seem to be broken for one frame. 

I think it might be in the paint quadrant handling

**Comment by ZehMatt** [comment]
> Yeah I just used the transparency options. If it was sorting, wouldn't it occur with OpenGL too? And wouldn't it be the entire sprite not just the upper section?The dirty region debug setting is currently broken but it appears to be caused when the peeps are split across two regions. Invalidating the entire screen doesn't fix it, but when I do that they only seem to be broken for one frame.
> 
> I think it might be in the paint quadrant handling

The thing with OpenGL is that it draws everything every frame so its not a reliable testbed for this kind of stuff. Did you use the Software (Hardware) renderer for the dirty region option? I think its the only renderer that implements this. Quite the curious bug, my best guess is that the drawing order is wrong which can be caused by a bunch of things such as their bounding boxes being wrong, keep in mind that the void also uses blank sprites and also has its own bounding box so that could overdraw over some peeps at least that is one of the possible causes.

**Comment by mrmbernardi** [comment]
The guests appear to be being redrawn without being in an invalidated block. 

https://github.com/OpenRCT2/OpenRCT2/assets/7877312/f95855a8-a795-45f9-91e1-6693191c5d07

**Comment by mrmbernardi** [comment]
The cause appears to be that Peeps have incorrectly positioned rectangles in SpriteData.SpriteRect. Oddly, it is correct for some peeps and incorrect for others as seen in the screenshot.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/e92d72f9-c3dd-4d38-9bac-479928372c01)

**Comment by janisozaur** [comment]
How come the fix only touched s4importer, is it limited to rct1 parks only?

**Comment by mrmbernardi** [comment]
> How come the fix only touched s4importer, is it limited to rct1 parks only?

I checked all the other places that had this code too. This was the only one with the error
