### ISSUE TITLE
Ride entrances and exits are not visible in Track Designer

### ISSUE THREAD

**Issue by NinjaCowboy** [OpenRCT2/OpenRCT2#21054]
### Operating System

Void Linux x86-64, kernel 6.5.12_1

### OpenRCT2 build

OpenRCT2, v0.4.6-186 (004592b58 on develop, DEBUG)

### Base game

RollerCoaster Tycoon Classic

### Describe the issue

When placing ride entrances and exits in Track Designer, they don't show up initially. You can see where the entrance and exit should be due to a small break in the station fence, but the actual buildings are completely invisible. In the colour scheme options tab of the ride window, the station style is also blank. Only after selecting one of the options in that dropdown do the entrance and exits actually become visible.

### Steps to reproduce

1. Launch OpenRCT2
2. Go into Track Designer
3. Select some ride(s)
4. Build a ride and place the entrance and exit.
5. Entrance and exit will not be visible.

### Attachments

![Unnamed park 2023-12-04 12-48-54](https://github.com/OpenRCT2/OpenRCT2/assets/137745099/05f80c73-a82f-44fe-be68-452462cba8da)

**Comment by karst** [comment]
I can reproduce this on Windows too.
It has to do with the entrance not being available after having it selected in a different scenario. It's not a big deal as you can select a new entrance style from the drop down menu.

It's still a bug, because if that entrance isn't available it should default to the top of the list.

**Comment by zzril** [comment]
There seem to be more differences in the entrance selection between scenario play and track designer:
* "No entrance" is missing in the dropdown in track designer
* entries are sorted in track designer, but are not in scenario play
* default is "Plain" in scenario play, but "No entrance" in track designer (despite not being available in the dropdown there)

Not sure how the solution should look like w.r.t. sorting. Having "Plain" and "No entrance" somewhere in the middle seems suboptimal to me. So, better exclude them from an otherwise alphabetic sorting and put them on top?

**Comment by zzril** [comment]
> It's still a bug, because if that entrance isn't available it should default to the top of the list.

Is there even a good reason to not have it available in the track designer?

---

Checking this a bit more, there seem to be more differences in the entrance selection between scenario play and track designer:
* "No entrance" is missing in the dropdown in track designer
* entries are sorted in track designer, but are not in scenario play
* default (for the first ride after opening park / track designer) is "Plain" in scenario play, but "No entrance" in track designer (despite not being available in the dropdown there)

Not sure how the solution should look like w.r.t. sorting. Having "Plain" and "No entrance" somewhere in the middle seems suboptimal to me.  
So, better exclude them from an otherwise alphabetic sorting and put them on top?
