### ISSUE TITLE
Entrance style dropdown not sorted in a consistent way

### ISSUE THREAD

**Issue by zzril** [OpenRCT2/OpenRCT2#21227]
### Operating System

Linux

### OpenRCT2 build

33523c98c24d17d2df0f2e47e8a1db51496271d4

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

(Came across this when investigating #21054 .)

The sorting of entrance styles in the corresponding dropdown in the ride / paint window is not always the same.

In parks originating from old `*.SC6` scenarios, the sorting is as in vanilla RCT2, with the "plain" entrance style on top, then "wooden", "canvas tent", ... and finally "space" on the bottom:  
(And the new "no entrance" style added below that.)

![from-sc6-scenario](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/936b9acd-9375-4828-b5be-e4cfd842918b)

In parks originating from new, `*.park` scenarios, the sorting is purely alphabetic:  
(No "no entrance" in the example picture as I had not selected that when creating the scenario.)

![from-new-scenario](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/0628acc0-c178-47a5-9d8c-c1ad8388730c)

In the track designer, we also get the alphabetic sorting:

![from-track-designer](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/d7702279-30ee-418e-9956-f8e6b7fbdf16)

---

I am not a 100% sure what the preferred order would be. Alphabetic sorting makes some sense, but the original ordering from vanilla RCT2 seems deliberate as well, with the "plain" one on top, followed by the ones from RCT1 (iirc), then the newer ones.  
Surely, it should be uniform across all parks, though.

---

From what I can tell so far, this is not a UI issue, but stems from the fact that park objects are loaded in a different order in the old parks compared to new parks or the track designer.

### Steps to reproduce

1. Start any scenario from RCT2 base game that has at least one ride that's not a stall (e. g. Electric Fields).
2. Click on any ride, open paint tab, click on the entrance style dropdown.
3. Repeat steps 1 and 2 this in track designer.
4. Create a new scenario and repeat steps 1 and 2 there.

Observe that the sorting is different in the RCT2 base game scenario.

**Comment by ZeeMaji** [comment]
This is because in old s4/s6 saves/scenarios, the entrance styles are imported and thus, ordered by their internal values.

While in new parks they are objects, so they are added to the save alphabetically which will order them as such.

It would probably be nice if we could get a "priority" flag in entrance/station style objects similar to what exists for scenery groups, which would take precedent over the alphabetical ordering.

**Comment by MASHzj** [comment]
I think alphabetical is not a good order because that is different in other languages.
The best in my opinion is ordering on when they were added, or when their corresponding theme was added (in RCT1 you can only use the style of the themes that are available + 3 not bound to a theme):
Plain (default)
Canvas Tent (not bound to a theme)
Wooden (not bound to a theme)
Classical / Roman (Roman theme since RCT1)
Log Cabin (mine theme since RCT1)
Jungle (theme since CF/AA)
Abstract (theme since CF/AA)
Snow/Ice (LL)
Castle (Brown) (LL)
Castle (Grey) (LL)
Space (LL)
Pagoda (LL)
No entrance (added in OpenRCT2)
No entrance, no platform (added in OpenRCT2)

**Comment by zzril** [comment]
I'm for now using the old ordering from RCT 2 in my PR, to make as little change as possible.  
Can change it if others agree with @MASHzj's suggestion.

Changing the sorting function later should also not be much of a problem anyway; most of the work is refactoring the code to use a sorting function at all.

**Comment by Gymnasiast** [comment]
> I think alphabetical is not a good order because that is different in other languages. The best in my opinion is ordering on when they were added, or when their corresponding theme was added (in RCT1 you can only use the style of the themes that are available + 3 not bound to a theme)

for 99% of users, it is completely irrelevant when an entrance type was added. The other 1% knows it by heart.

Also, I don’t understand your argument about alphabetical order. If you’re looking for a style, it is MUCH easier to parse an alphabetical list than it is to find it in a list with an arbitrary order.

We sort many other, very similar lists too, like the list of available vehicles for a ride, or the ride type selector (the one tied to the cheat). The latter only attracted positive feedback when it was changed.

**Comment by MASHzj** [comment]
> > I think alphabetical is not a good order because that is different in other languages. The best in my opinion is ordering on when they were added, or when their corresponding theme was added (in RCT1 you can only use the style of the themes that are available + 3 not bound to a theme)
> 
> for 99% of users, it is completely irrelevant when an entrance type was added. The other 1% knows it by heart.
> 
> Also, I don’t understand your argument about alphabetical order. If you’re looking for a style, it is MUCH easier to parse an alphabetical list than it is to find it in a list with an arbitrary order.
> 
> We sort many other, very similar lists too, like the list of available vehicles for a ride, or the ride type selector (the one tied to the cheat). The latter only attracted positive feedback when it was changed.

I had to think a bit why I exactly did that proposal. I can explain it as follows: it's not that I know when everything was added by heart, but in short lists, I rather expect the entries in the list in a fixed spot regardless of language. I play both in English as Dutch. For short, unscrollable lists, there is little need to really "search" between the entries when I see them all at once. It's a different thing for long lists, for example the object selection, there I totally expect the list to change order when switching language.
Specific for the entrance styles I'm also still used to RCT1 that I played a lot when I was young. There  you only get 3 default styles: plain, canvas tent, wooden. The others are only unlocked with their corresponding theme. That's why keeping them at the top doesn't feel arbitrary to me. I checked for entertainers, where this mechanism is still in RCT2 and OpenRCT2, and there the default ones (panda, tiger, elephant) are indeed always on top. I would find it more logical for selecting vehicle types too, as those are usually the 2 to 3 options.
If I happen to be the only one with this vision, that's fine. It's not _that_ important.
