### ISSUE TITLE
Formatter seems overwritten before being used

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#21837]
https://github.com/OpenRCT2/OpenRCT2/blob/9b7face116a7d8b83f5c092511be74092af3b95c/src/openrct2-ui/windows/RideConstruction.cpp#L1505-L1541

In the code above in line 1505 formatter `ft` is created and then values are added to it in 1506, 1516, but then in 1539 `ft` is assigned to again and its values consumed in 1541.

It seems the code in 1505, 1506 and 1516 is unnecessary.

**Comment by Gymnasiast** [comment]
It uses the common formatting buffer, so what the code here essentially does is ensure the internal pointer is set to offset 4. Probably because offsets 2 and 3 are occupied by the brake speed, which is not always set.

The real solution then is to either:
- Replace the overwriting assignment with a Rewind() call.
- Increment the pointer if there is no brake/booster speed.
