### ISSUE TITLE
Bad path placement under bridges.

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#2186]
Perhaps pictures can explain this bug better than words.

In this picture, I am trying to build a queue line that passes under a bridge. My cursor is currently where that black dot is in the image. Screenshots hide the mouse pointer, so I had to put a dot.
![bad_path_placement_1](https://cloud.githubusercontent.com/assets/15527244/10900321/e3c7b060-81a3-11e5-8cc0-62d6f5a0b418.png)

I'd expect the new path segment to be placed where the ghost is shown, but what actually happens is that it gets placed here:
![bad_path_placement_2](https://cloud.githubusercontent.com/assets/15527244/10900419/3704e1d4-81a5-11e5-91dc-733f286eaca1.png)
This only happens if the cursor is towards one edge of the tile like shown in the screenshot. If it's in the center, the path segment will be placed as expected.

Another interesting thing is that if I do the same as above with the bridge only one level above ground (in other words, there's no room for a path to pass under the bridge), I get the expected red error message about a footpath being in the way, yet it still places the path segment on the bridge as above.

**Comment by osconnoisseur** [comment]
I did a bit more investigation on this, and it seems to be an issue with path ghosts. The standard behavior is to change a path style if the cursor is positioned over it. Because supports are considered part of a path segment, you can change the style of a bridge path segment by just clicking its supports. What happened above was that I placed my mouse cursor on the middle of that square where a path can be placed, so a ghost was generated. I moved my mouse slightly so that it is over one of the (now invisible) support posts of the bridge. Since my cursor is positioned over the support post, clicking will apply the path style to the segment on the bridge, even though the ghost below is still visible.

This is a very minor issue and also occurs in the original vanilla RCT2, so it probably shouldn't be bothered with any time soon.

Perhaps I'm being a bit too pedantic. :)

**Comment by spacek531** [comment]
I cannot recreate this bug, it appears to be fixed.

**Comment by ZehMatt** [comment]
If this is still happened please let us know.
