### ISSUE TITLE
No reason specified when attempting to place benches, lamps, or bins on path with all four sides occupied

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#21974]
### Operating System

Windows 11 Home

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

![Fred's Workbench 2024-05-05 23-39-19](https://github.com/OpenRCT2/OpenRCT2/assets/61885939/0f7fd049-9448-48d9-b026-3d87df82da6d)
![Fred's Workbench 2024-05-05 23-39-21](https://github.com/OpenRCT2/OpenRCT2/assets/61885939/88aa4ca3-ac22-4ae4-a435-f033cbdd4d2c)
When attempting to place down new benches, lamps, or bins on footpath tiles which have all four sides connecting to other path (e.g. a path crossing or a tile in the middle of a 3x3 path grid), a "Can't position this here..." error message appears, but it does not provide a specific reason. A possible new error message reason in this case could be something like "No available sides for path additions on this footpath tile".
A similar issue existed with door wall scenery objects not providing a reason for being unable to be built over unsuitable track, but that was recently fixed in v0.4.11.

### Steps to reproduce

1. Build a path network including either at least a 3x3 path grid (in screenshot 1, shown using red tiled path) or a path crossing (in screenshot 2, shown using green tiled path)
2. Try to place down any benches, bins, or lamps on path tiles that have all four sides connected to other path tiles
3. No specific reason for the "Can't position this here..." message appears

**Comment by harvito** [comment]
![Diamond Heights 2024-05-06 18-16-24](https://github.com/OpenRCT2/OpenRCT2/assets/14914822/cd258e48-ec68-49be-9a7d-af8da1fa0edf)
Since there's a reason in the case of a level crossing, probably a reason in case of no available unconnected edges is a good idea. Note that exact same reason appears in case of corner path additions (snowballs, jumping fountains) on a level crossing, but corner additions are allowed on all footpath, regardless of connected edges and corners:
![Diamond Heights 2024-05-06 18-29-30](https://github.com/OpenRCT2/OpenRCT2/assets/14914822/7439c5ae-b8b1-44af-92a6-dd9b85211e58)
I like SpartanFrederic104's suggestion "No available sides for path additions on this footpath tile," but could also go for a more succinct "No edges available" or "No unconnected edges" or "No unconnected edges available."
Some related testing notes:
- Connecting the last edge of a path tile with addition (eg bench) makes the bench disappear, but the path is still shown in tile inspector to have the addition. Deleting a connected path piece makes the bench appear again.
- Building a railroad track through a path with addition removes the addition entirely
- You're allowed to build signs accross level crossings (bug?)
- The game only allows you to build signs accross paths but doesn't prevent you from placing path all around an existing sign

**Comment by harvito** [comment]
![Forest Frontiers 2024-05-06 23-06-15](https://github.com/OpenRCT2/OpenRCT2/assets/14914822/ce9ff478-9172-4261-9cb5-b9c97d564a66)
looking into making PR

**Comment by harvito** [comment]
#21980 please review

**Comment by harvito** [comment]
#21980
