### ISSUE TITLE
Possible to build OpenRCT2 with MinGW on Windows?

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#2205]
So far, I have been using Linux to cross-build OpenRCT2 for Windows as described in the wiki. I normally like to use Windows and MSYS2/MinGW for my programming projects, especially on my laptop which runs Windows XP, and therefore can't run the most bloated IDE on the planet nor any binaries produced by it.

Since it's already possible to build with MinGW on Linux, would it be a lot of work to make build.sh and install.sh run properly on MSYS2? I just don't know anything about CMake or this project's build process to modify the script for my needs.

**Comment by janisozaur** [comment]
To be honest I only maintain `build.sh` and `install.sh` for them to be able to build on travis. I don't consider them a to be valid build system for anything else and they may even be dangerous if you blindly run them (well, you shouldn't random run scripts from the internet that use sudo anyway…).

Personally I have no interest in adding windows to them, but that should be fairly trivial, just like building with mingw on windows. I'm quite confident it won't be hard, so feel free to take a stab at it.

I can provide you with some support here if you have any specific questions, but it's been a long time since I last used cygwin, so my knowledge may be a bit rusty by now.

**Comment by IntelOrca** [comment]
You can build natively for linux using just make and GCC now.

**Comment by Gymnasiast** [comment]
Closing as AP has closed his/her account.
