### ISSUE TITLE
MacOS "Universal" builds do not support macOS versions before 10.14

### ISSUE THREAD

**Issue by AnnaSaysHi** [OpenRCT2/OpenRCT2#22094]
### Operating System

MacOS 10.13.6

### OpenRCT2 build

OpenRCT2 v0.3.5

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

As in title. I'm currently running 0.2.4 and my Mac simply will refuse to run recent versions (I only checked versions newer than 0.3.5).

I'm not sure what category to consider this as.

### Steps to reproduce

1. Be running MacOS 10.13.x or older.
2. Download any recent release of OpenRCT2.

**Comment by Gymnasiast** [comment]
macOS 10.13 has been out of support for 3.5 years. And Apple is extremely slow in implementing new C++ compiler features, so we cannot support anything older. In fact, even 10.14 is only possible due to a polyfill. (Essentially, it is easier for us to support Windows XP or even 98 than macOS versions from the 2010s. Make of that what you will.)

Your best bet is upgrading your macOS version. If that isn’t possible, you can try installing Wine and running the Windows version of OpenRCT2. Or install Linux on your Mac if you’re feeling especially adventurous.
