### ISSUE TITLE
Cannot open park by double clicking save file

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#22107]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 0.4.11-170-ce626b6

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

I have set .park files to be opened by OpenRCT2 when I double click them in Windows. This used to work fine, but since recently (probably since the loading sequence) the parks fail to load when I double click them. It does work properly when I load a save from within the game.
![image](https://github.com/OpenRCT2/OpenRCT2/assets/6469413/aba441e4-370a-4b7c-bb6d-0c4feec42f42)

### Steps to reproduce

- Set .park files to open using OpenRCT2.exe
- Double click a .park file in windows
- OpenRCT2 starts up, then fails to load the game

**Comment by AaronVanGeffen** [comment]
Odd, it shouldn't be trying to load before the (object) repository initialisation has completed. I likely made a mistake in the introduction of the loading scene, indeed. Will investigate.

**Comment by AaronVanGeffen** [comment]
This is due to how the `DetermineStartUpScene` function was spun off the `Launch` function. Both reside in `Context.cpp`.

`DetermineStartUpScene` determines what scene to transition to after the preloader scene is done. However, in the case of `StartupAction::Open`, it also immediately tries to load (or download) the park provided in the startup argument (e.g. by file association or CLI). This loading process will most likely fail at this point, as the object repository hasn't been initialised yet.

I'll need to think about how best to resolve this. Ideally, we'd defer the loading until just before the scene transition takes place, I think.
