### ISSUE TITLE
Unwanted "platform" appears underneath some shops

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22286]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.12 provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When building shops/stalls sometimes a "platform" appears under the shop.   This occurs even if the land and adjacent path are at the same height.  Sometimes I can bypass the problem by demolishing the shop, lowering then raising the land, and rebuilding the shop.  But this does not always work.  

When this happens the guests cannot access the shop and I get warning messages.  

 I have attached a screenshot of a fried chicken shop circled in red with this problem.
![Platform](https://github.com/user-attachments/assets/478f7a1b-0843-4a1c-8dc4-5a14290e5d48)

### Steps to reproduce

Try to build a shop.   Problem trigger conditions are not known to me.

### Attachments

![Platform](https://github.com/user-attachments/assets/b5e015bd-c92e-431e-b449-fbbedda851b7)

**Comment by beesman93** [comment]
Can you provide the save with the floating shop / upload a screenshot when you rotate the screen.
I think you are just placing the shop above the MarryGo entrance or it's queue maybe?

**Comment by ZehMatt** [comment]
The shop is actually floating above the path, its one of those isometric view gotchas. So not a bug.

**Comment by jcurbaniak** [comment]
OK.  I am attaching a save with the area now zoomed in.   I do not see any conflict with the Merry Go Round.

[Three Monkeys Park.zip](https://github.com/user-attachments/files/16202969/Three.Monkeys.Park.zip)

**Comment by ZehMatt** [comment]
![image](https://github.com/user-attachments/assets/c3ef77b1-c1bb-4b82-8a74-6352fa14153b)
You can see it better from this rotation.

**Comment by beesman93** [comment]
> OK. I am attaching a save with the area now zoomed in. I do not see any conflict with the Merry Go Round.
> 
> [Three Monkeys Park.zip](https://github.com/user-attachments/files/16202969/Three.Monkeys.Park.zip)

Yep as suspected, it's just build above a path (the one in middle of the xroad) as Zeh pointed out:
you can see it's 1.5m above see level, whereas the toilet on the ground is 1.5m below see level:

![image](https://github.com/user-attachments/assets/8bc3c217-ba0b-4a99-902c-d607a42fcc12)
![image](https://github.com/user-attachments/assets/0c480179-3b52-47e4-afed-833ebb566247)

Deleting the path below it reveals the isometric trickery the best
![image](https://github.com/user-attachments/assets/800856c3-e942-402c-8df3-acb8537f7d64)

**Comment by jcurbaniak** [comment]
I do not see where I did something incorrectly.

**Comment by beesman93** [comment]
https://github.com/user-attachments/assets/18b07483-1ec3-4765-84eb-185313700814

**Comment by jcurbaniak** [comment]
So in my humble view, there IS a glitch here.   Based on what kind people have shown me.

 

If I remove the footpath from the tile diagonal from the fried chicken build site, then the shop builds correctly and the guests have access.

 

Then the footpath can be replaced where it was and everything is fine.

 

I do not think I should have to do that.  

 

It seems that for some reason if the footpath is there the build wants to incorporate that with the shop.

 

But I do want to say this is a marvelous intriguing game and that I am not complaining.

 

Jerry U.

**Comment by beesman93** [comment]
In the video at 0:22 you can see I built the shop on the correct position without removing the path - so it's just "aiming" correctly.
Sadly I don't think there is any fix possible - since building something above path is a valid counter request.
It can get very finicky in small parks, with lots of rides and supprts on all sides etc - as I said we all suffer from these missclicks for 20 years now :D But there are lots of options to hide certain things when the view gets confusing - and the OpenRCT has even more options to do so, so yeah it's just being careful when placing the stall/ride/object but not a bug/glitch.

The game will tell you pretty quick that guests are trying to reach stall XY and cannot when it happens on accident, so it's usually not a big deal :)

Hope you enjoy the game further, when isometric gets to your nerves, try rotating around it really puts things into perspective (pun fully intended) :D
