### ISSUE TITLE
Port #19740 surface element fixes to .parkpatch files

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#22655]
#19740 had several fixes for surface elements to be patched on scenarios that were held off until #21189 was merged. These can now be applied via the .parkpatch files.

**Comment by HtotheTML** [comment]
Aside from Botany Breakers, I can think of another map that has surface element errors.
I could take time at some point to comb through for them, but the one I recall off the top of my head is:

- A number of underwater tiles in Alcatraz are grass rather than rock.
![image](https://github.com/user-attachments/assets/48440908-b21f-46c0-bc8a-9d58b7996039)
There's more than just these two, but I'll look for them later when I have time.
