### ISSUE TITLE
Object Selection causes MP crashes

### ISSUE THREAD

**Issue by zsilencer** [OpenRCT2/OpenRCT2#2294]
When someone changes the available objects in the cheats menu and tries to use them, it will cause crash.

**Comment by duncanspumpkin** [comment]
We should disable it in multiplayer cause that will open a whole can of worms.

**Comment by zsilencer** [comment]
Yes and maybe create checks on game commands if invalid object entries are trying to be used.

**Comment by IntelOrca** [comment]
Validating game commands is a whole different story.
Essentially anything that we have added that doesn't use game commands would need to be disabled for muliplayer, e.g. cheats, scenario options, changing map size.

**Comment by Nubbie** [comment]
Just like Duncanspumpkin said, isn't it disabled right now in MP?

**Comment by Margen67** [comment]
@Nubbie The debug icon is disabled in MP, but Object Selection can be opened with the console command open object_selection

**Comment by mrtnptrs** [comment]
Can't we let the game check for the multiplayer flag when you press the hotkey to open the console. So, that it checks if you are using multiplayer and if so, don't open the console. That would simply fix this issue.

**Comment by Margen67** [comment]
That wouldn't fix the issue. That would just work around it.

**Comment by mrtnptrs** [comment]
That's true, what do the developers think?

**Comment by Margen67** [comment]
I think a better workaround would be to automatically close the Object Selection window only if you're a client because hosts can use it to update the object list, and all it does for clients is cause a desync and/or crash.

Hosts can use Object Selection to update the object list etc, but for clients it only lets them cause crashes and desyncs. Same with Tile Inspector, but that's a different issue. #3245

I think the game crashes because it tries to find the path, then fails because it doesn't have the file, or tries to load from a slot which doesn't have a path.
If a path slot is already taken up it just uses the path already in that slot instead.
