### ISSUE TITLE
Please use consistent naming conventions for release asset file names

### ISSUE THREAD

**Issue by Greelan** [OpenRCT2/OpenRCT2#23410]
Versions up to 0.4.15 just use the version number in the download file names.

But 0.4.17 and 0.4.16 now include `v`, ie `v0.4.17` and `v0.4.16`.

This is a pain for automation. Please keep consistent naming.

**Comment by ZehMatt** [comment]
What kind of automation doesn't take this into account?

**Comment by Greelan** [comment]
A panel that runs the server. The user is prompted to enter the version number that they want to download. It's confusing to have to tell them different formats depending on the particular version number involved

**Comment by janisozaur** [comment]
I understand your pain and considered it when changing the scheme, but it makes more sense for us to use the actual tag name, rather than strip it. This is a consequence of us finally automating the release process over the last few versions, in particular https://github.com/OpenRCT2/OpenRCT2/pull/23236 and preparation for it. With this now merged, the naming should not change.
