### ISSUE TITLE
Placing banners not possible while paused

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2342]
Tested with the "Enable building in pause mode" ticked.

I was using build 1016 from the Launcher when I found out.

**Comment by duncanspumpkin** [comment]
By banner I assume you mean Large Scenery Signs. I accidentally broke it when I refactored it the other week. Fixed in the pre-release.

**Comment by hytacker** [comment]
I've encounterd this problem with other objectes as well. A couple infact. I could make a list of the objects with this problem if you want @duncanspumpkin But I thought maybe there is a better way of looking at this problem from a "programing'' view. That enables you to find all of the other objects with the same problem as well. If not the I will post every object that I encounter while playing. I pretty much build the entire time in pause mode. Because this save file crashes every time when I unpause the game. (btw is this fixable? or is the game lost?)

**Comment by Broxzier** [comment]
@hytacker The fix is not in the launcher builds yet, but it fixed all big scenery (some 1x1 tile scenery is also 'big', which prevent you from building fences right next to it). As for your problem, do you get the ``map animations`` assertion failure?

**Comment by hytacker** [comment]
Ohw I see. And yes I think I have the map animation failure
![naamloos](https://cloud.githubusercontent.com/assets/15657920/11325711/ccf2d372-9154-11e5-8b06-22497872e8f1.jpg)
