### ISSUE TITLE
Complete Vehicle Update

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#2400]
Goal for 0.0.4 is to complete the vehicle update code.

**Comment by Christipher** [comment]
These old bug reports deal with this section of the code (if there is a question mark, I'm not exactly sure if it is in that part of the code, though it could be valid check as well):
#2216 (chairlift restricted to only one car in station to station mode)
#2153 (River Rapids issues)
#2131 (Multi - tracked separate coasters)
#2126 (Ferris Wheel problem)
#2081 (Infinite Loop Crash)
#2031 ? (Low excitement ratings for Heartline Twister coaster)
#1972 ? (Schoolbus ride causes glitch with toilet sprite)
#2373 , #1923 , #1868 (All relate to arrive at station glitches, one of the three are closed due to duplicate)
#1411 & #1122 (this bug report got duplicated) (Giga Coaster cable lift hill)
#1322 & #1178 (referencing older closed report as well as they are the same thing) (synchronize coasters for racing/dueling coasters crashes game)
#1303 ? (Vertical tracked rides with only station act strange)
#866 (boat hire path-finding)
#717 ? (Jet skis can't cross broken down sub ride)

There may be a few issues missing from this list as well if someone wants to double check that.
Hopefully that helps.

**Comment by duncanspumpkin** [comment]
#2153 wouldn't be part of vehicle-update, #2031 is fixed afaik, #1303 would be, #717 is a won't fix.

**Comment by duncanspumpkin** [comment]
This has now been completed

**Comment by duncanspumpkin** [comment]
Reopening to remind me to check the old original bugs to see if they can be fixed

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/2694

**Comment by duncanspumpkin** [comment]
Listed are the current list of original vehicle bugs:

#2216 (chairlift restricted to only one car in station to station mode) Issue caused by station direction special case for chairlifts. Could be fixed
#2131 (Multi-tracked separate coasters) Issue caused by the logic not checking for unconnected track loops. Likely impossible to fix without messing with existing track exploits.
#2081 (Infinite Loop Crash) Issue caused by the logic which advances to the next track piece. Possibly introduce a count to prevent the stack overflow.
#1923 , #1868 (Arrive at station glitches) 
#1411 & #1122 (Giga Coaster cable lift hill with block stations) Issue caused by logic not understanding correct layout for block stations and lift hills in certain configurations. Could be fixed
#1303 (Vertical tracked rides with only station act strange) 
#866 (Improve Boat pathfinding) Could cause issues with backwards compatibility.

**Comment by duncanspumpkin** [comment]
This is being closed and reopened as #3078
