### ISSUE TITLE
Adding Chinese Currenies (CNY/NTD/HKD/MOP)

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#2403]
I just realised that no Chinese currencies are currently in game right now, I think it is suitable to add some.

**Comment by Gymnasiast** [comment]
I think it might be a better idea for the next stable to add an option that allows one to define his/her own currency.

**Comment by gdabi** [comment]
I've recently made a patch that adds bitcoin cryptocurrency to OpenTTD, which has a very similar currency implementation.

https://bugs.openttd.org/task/6409

May I help with that, but I need to do some investigation, because I'm a newbie contributing to open source, and I don't want to break anything :)

**Comment by janisozaur** [comment]
Does any font provide that?

**Comment by gdabi** [comment]
I was able to display the ฿ symbol by setting the suffix to " \340\270\277", which is the octal values of the UTF-8 code, but the bitcoin symbol has two vertical lines, instead of that symbol, so I decided finally to set the suffix to "mBTC"

**Comment by Gymnasiast** [comment]
I don't really want to more built-in currencies really... having an option to define one's own currency should cover it IMO. Especially in the case of bitcoin, which would always require the user to set it, considering it isn't an official country currency.

**Comment by gdabi** [comment]
The custom currency is certainly necessary. It'll be a little more difficult than adding built-in currencies, because it's needed to create a new window to let the user set up the custom currency.

Anyway, even if this issue is closed after the implementation of the custom currency, I think everybody will want to see its local currency in the game. It'll be a good idea, when the whole game is decompiled and refactorized, to keep the currency system decoupled and easy to maintain, to let almost everyone add its local currency.

**Comment by PFCKrutonium** [comment]
>.> GitHub looks a lot better than FlySpray imo.
