### ISSUE TITLE
Cheats Options : Peep Needs Freeze

### ISSUE THREAD

**Issue by romantyke** [OpenRCT2/OpenRCT2#2501]
Good day!
I am a usual user of rct2 and open rct2. I have realized that by using the regular rct2 and a trainer, I can make peeps never to get lost by freezing their needs like happiness, hunger, etc... it makes them far more better at pathfinding and it never changed for a good many years now. To me, at least.

Do you think you may be able to implement this option for OpenRCT2 as well? Please?

Thank you all in advance. You work is amazing!

**Comment by Patrik356b** [comment]
why not keep hitting the various cheat buttons?. And i don't see how this would improve pathfinding

**Comment by romantyke** [comment]
Hello.

Well, I can assure you that pathfinding is optimized to perfection when I freeze the happiness, the energy, the patience and the machoness of the guests by using Son of Beast Trainer.

In any case, I do not think most players would like to keep mashing buttons.

I tried it that way several times already, and the effects are not helping matters any in pathfinding.

**Comment by pizza2004** [comment]
It sounds like (and I don't know the code, so this is just a guess) you're basically removing most of the factors that would change how the AI handles deciding where to go, so the guests just pick a place and head there, or something.

**Comment by romantyke** [comment]
Hello!

It definitely does so, I think. Freezing these settings actually does improve their AI like I never saw before.
I am playing a custom park called Insular Insomnia. A winning vacation park from Todd Lee and Mama Bear.
In the past, I could not play the game at all because it was simply not peep friendly. OoenRCT2 came out with better results at first but lately the AI pathfinding is horrible no matter what i use with the ingame Cheats, no offence...
I had to reverse to the real CT2. Son of Beast Trainer is good at freezing guests needs. It includestheir money, their patience in the queue lines, their nausea and their machoness, which gives them the will to go to any ride they stumble upon. Since I found out this function two years ago, the park is fully playable like I never thought it would have ever before. It includes all other parks with double paths.
I am only asking to at least try to implement these functions to openRCT2 cheats. I am just asking. I do not mean to force anyone. It might help with it.
By the way, I don't freeze their hunger, their thrist or their bathroom needs. I want them to use stalls, and they do so amazingly well.
I have 8248 guests in this park. Thanks to cleaning paths, it allows for more sprites in it.

Thanks for listening. I love this game. I am glad to find others like you. It's nice of you to help people out. Open RCT2 is amazing,

**Comment by vzybilly** [comment]
I think we might want to take a peek at the trainer and see what all it
does... from the sounds of it, it seems to actually change the AI... might
be useful for our AI update...

**Comment by romantyke** [comment]
Hello!

Sure, why not? Might be great to check it out.

It is the Son of Beast Trainer.

You know... using this, I found out through the months that guests don't even think I'm lost. They do say I can't find this or that, but that Trainer makes it so that even when looking for a particular ride or stall, if they stumble on a ride queue line, they will go on it without question. I checked out even further, and I was surprised that some of them may have been on that ride earlier, but will still not complain and ride it without question.
Another thing. They never say been queuing for ages at all, they will wait forever until the ride starts without complain or getting angry.
This trainer has a very good and one of a kind coding that I find to be very useful.
You may try to see what coding it does and benefit from this research.

**Comment by Gymnasiast** [comment]
@vzybilly : No, I think @pizza2004 is right on this one. What trainers do is alter values in memory. When a trainer is set to freeze values, it will reset the value every time it gets changed. Problem is: there are quite a lot of places where one the values gets changed.

To me, it sounds like your map being peep awkward is really the problem here. Apparently they can't find food stalls, drink stalls, toilets etc. and the queues are apparently too long.

About the AI: there are some issues in the AI, yes. We prefer solving those above hiding them.

If this does get implemented: the cleanest implementation would probably be one that executes food min, drink min, etc. (the guests functions in the cheat window) every X ticks or seconds.

**Comment by Broxzier** [comment]
I agree with @Gymnasiast.

![](http://i.imgur.com/xjgoAfK.png)

There are two ways I can think of implementing this. Either at every place where these parameters are being changed (probably lots of work, and some might still be changed in the rct2 procs), or the way Gymnasist described, and setting the values over and over every so often. Perhaps keep track of what the peep's stats were, or making the min/max button a toggle (keeping it pressed) to make it 'freeze'.

**Comment by romantyke** [comment]
Good morning!

This is very interesting! I actually happen to know quite a bit about hexadecimal coding. However, not with PC games, but with Nintendo Gameshark codes. I created my own codes using hexadecimal and decimal modifiying. I don't think I van be of any use here.

Perhaps just trying to implement a stats freeze may be worth a try. If it doesn't changes how the AI works, I can assure you I won't blame you. After all, you are all doing your best to make this game a better one, and it takes a lot of work, and you don't even charge for it.

Thank you all, buddies! You are very nice.

I'll be continuing to follow the discussion. Totally open to that.

Cheers!

**Comment by vzybilly** [comment]
maybe every X seconds going through all the peeps... seconds * tps = the
amount of ticks to work, peeps / that number = amount of peeps to update
every tick, then just keep a location counter that moves and wraps
around... that or some where in the AI code where it finds a value to
small, it just set the value and continue like it didn't find the value...

**Comment by Gymnasiast** [comment]
@romantyke : Hexadecimal has nothing to do with any of this.

Anyway, since Son of Beast (or 8 cars for that matter) couldn't change AI, replicating its effects will not require editing AI. Improving AI _is_ on our list however, because it is also bad in better formed parks.

**Comment by romantyke** [comment]
Well, sorry to have upset you.

**Comment by romantyke** [comment]
I do apologise.

**Comment by Gymnasiast** [comment]
I am not upset. Don't worry.

**Comment by romantyke** [comment]
I see...

I am autistic, so I have this social issue concerning the decoding of second degree meanings. Even though I got my diagnosis at the age of nine and now Iam twenty five. Got better with time but I still have loads to learn.

I hope this doesn't creep anyone away. I just needed to explain why I wrote this earlier.

**Comment by kkirby** [comment]
@romantyke, me too! Well, Aspergers, or high functioning autism, anyways. So no worries!

**Comment by romantyke** [comment]
I'm Asperger.

**Comment by romantyke** [comment]
My medium is litterature and linguistics. I can fluently speak, write and read several languages.
I'm also married (I' m gay) and write for my locak newspaper.

**Comment by pizza2004** [comment]
I'm also autistic.  PDD-NOS, because I never suffered from the social problems enough to be considered Aspergers, and at 22 I doubt anyone could tell if I didn't tell every person I meet, but when I was a kid it was much more obvious.

**Comment by kkirby** [comment]
Hey guys, lets leave this discussion to the issue itself. If you want to continue the conversation, there is a non-dev room on gitter.

**Comment by romantyke** [comment]
Oh, right! Sorry!

Well, has any decision been made about the way this may be implemented? I know I am really poor at helping for this... but...

**Comment by ptkato** [comment]
Wouldn't be easier just implement the 8Cars or Son of the Beast themselves inside the game? I mean, transform all their functions as native.

**Comment by vzybilly** [comment]
that's kinda what I was thinking but I believe they've already lifted most
of 8 cars... at least I think I remember someone saying that afew months
back... I'm just interested in how the other trainer got the peeps
better... I think with some tricks they could change AI but I'm just going
to stay out of this now... atleast for the most part

**Comment by Gymnasiast** [comment]
@ptkato : Every useful function in 8 cars or Son of Beast will probably be implemented, though not always in the same way to keep the code clean, and also because we have fewer limitations than the programmers of 8 cars and SoB had.

@romantyke : If I'm upset, I will just tell you. I always try to be as clear as possible in what I say. Another thing: I rarely get really angry; that requires people actively and intentionally being obnoxious.

As for this particular feature request: I have no real objections, so it will probably be implemented at some point, although fixing bugs and many other features will go first.

**Comment by romantyke** [comment]
Hello!
That is excellent!
 I am most gracious for your help!
vzybilly, about the pathfinding AI.. I don't really know to say this but... sigh... what would I gain by lying? I am being quite serious. I may be thinking wrong but I am quite perplexed...
Dear oh dear... it makes my head hurt with questioning...
As for the autism thing, those who wanted to continue the conversation about it can send me a PM. It'd be nice to chat a bit. Tee hee.

**Comment by ptkato** [comment]
A button to disable collisions would be awesome! Sometimes I want to overlap structures and need to alt-tab to the trainer.

**Comment by Gymnasiast** [comment]
@romantyke : vzybilly has not accused you of lying. He only suggested your idea that SoB changed pathfinding was incorrect.

@ptkato : That has been in the game for many months now. Make sure the cheats menu is visible and put a check in front of "Disable height checks". (Almost every feature people frequently use has been implemented, except for many map object manipulation functions.) Please take a good look through OpenRCT2's possibilities first before you ask on Github; if you have questions about gameplay, please ask them on the forums. Also, this issue is not about zero clearance.

To everyone: please stay on-topic now. Other things can be discussed in the non-dev channel on Gitter or on the forums, which are also a good place to ask questions about OpenRCT2. Github is meant to track bugs and other technical things, and because of this more knowledge of the game is required to take part on the discussions.
