### ISSUE TITLE
Localisation not work on *nix system

### ISSUE THREAD

**Issue by zzoru** [OpenRCT2/OpenRCT2#2537]
Localisation is not work on *nix system
Because, string.c:891 fontPath is fixed on Windows system. 
I already fix it on my system(mac). but, we should make options that user can choose a font directory & font files.

**Comment by janisozaur** [comment]
It works, but you have to provide a font in a font named `C:\Windows\Fonts\arial.ttf`.

**Comment by zzoru** [comment]
@janisozaur yeah, i already wrote that it works on Windows, but not on *nix system
because, *nix system have differennt font directory (like /System/Library/Fonts)
so, we need to add some options that user can choose a font directory & font files.

**Comment by janisozaur** [comment]
@zzoru please read my comment again. I assure you it works.

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/drawing/string.c#L891

Need to change this to default system font path.

**Comment by zzoru** [comment]
@janisozaur oh, i see you mean that just make a file named like "C:\Windows\Fonts\arial.ttf".
but, it is a ridiculous measure, and we should make some cmdline options or add some code to string.c

**Comment by janisozaur** [comment]
@IntelOrca yeah, i've been eyeing Fontconfig for a while, but never got around to implementing it, as the current solution is "good enough" and works. I may do this over current break.

**Comment by AaronVanGeffen** [comment]
Weighing in with some thoughts I had on this in chat earlier.

I don't think OS X uses fontconfig. The lot just resides in either the user's or the system's Library folder, e.g. `/Library/Fonts` or `~/Library/Fonts`. Incidentally, it looks like fonts always have their full name as file name -- e.g. "Arial Black.ttf" and "Times New Roman.ttf"

To get the lot cross-platform, we should probably either:
* Get a font's path by *name* through APIs, instead of hardcoding both path and file name, or
* Hardcode the TTF filenames in the *platform* files instead of `language.cpp`, along with the system font path. (Currently hardcoded in `string.c`)

I'm not sure about the state of this on Windows and Linux, but OS X installs fonts to the user's font folder by default. So, while the second option is likely easy to implement for system-only fonts, it may not be ideal. (It'd probably suffice, though.)

**Comment by IntelOrca** [comment]
We need to make the fonts customisable by the user anyway. At least by specifying in the config.ini.
