### ISSUE TITLE
Readme.md file is incorrect about Mac OS X build

### ISSUE THREAD

**Issue by valyron** [OpenRCT2/OpenRCT2#2585]
`readme.md` states that I can build with `./build.sh` on Mac which worked in early December. Now the scripts have been moved to `scripts/linux/` in #2544. Readme should be updated and `scripts/linux/` is in my opinion not the right naming since these files work on Mac as well.

**Comment by AaronVanGeffen** [comment]
The rationale behind the change was the introduction of an Xcode project for us OS X users. Personally, I don't use Xcode either -- if you install the dependencies through Homebrew you should be able to use `cmake` as described on the Wiki.

I agree the documentation needs improvement, though. Bear in mind OS X compatibility is fairly recent -- we'll sort it out given time.

**Comment by AaronVanGeffen** [comment]
This is still not updated. I guess it's best to refer macOS users to Xcode in the readme, rather than given them instructions that no longer work, though. Perhaps we could make note that cmake works, too, in a similar capacity to Linux? A wiki page on this already [exists](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-OSX).

**Comment by PFCKrutonium** [comment]
@IntelOrca Should this be closed because of the changes that @LRFLEW Made in #4645 ?
