### ISSUE TITLE
'json_boolean_value' was not declared in this scope

### ISSUE THREAD

**Issue by Mailaender** [OpenRCT2/OpenRCT2#2595]
I tried packaging version 0.0.3.1 for @openSUSE games, but compilation failed:

```
[   60s] [ 96%] Building CXX object CMakeFiles/openrct2.dir/src/network/http.cpp.o
[   60s] /usr/bin/c++  -DCURL_STATICLIB -DHAVE_CONFIG_H -DORCT2_RESOURCE_DIR=\"/usr/share/openrct2/\" -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -DDEBUG=0 -m32 -std=gnu++11 -fno-omit-frame-pointer -I/home/abuild/rpmbuild/BUILD/OpenRCT2-0.0.3.1/lib -I/usr/include/SDL2    -o CMakeFiles/openrct2.dir/src/network/http.cpp.o -c /home/abuild/rpmbuild/BUILD/OpenRCT2-0.0.3.1/src/network/http.cpp
[   60s] /home/abuild/rpmbuild/BUILD/OpenRCT2-0.0.3.1/src/network/twitch.cpp: In function 'void twitch_parse_followers()':
[   60s] /home/abuild/rpmbuild/BUILD/OpenRCT2-0.0.3.1/src/network/twitch.cpp:269:53: error: 'json_boolean_value' was not declared in this scope
[   60s]     member.isFollower = json_boolean_value(isFollower);
[   60s]                                                      ^
```

**Comment by janisozaur** [comment]
`jansson>=2.7` is required.

**Comment by janisozaur** [comment]
I wonder how you managed to get this error, as we explicitly require `jansson>=2.7` in `CMakeLists.txt`: https://github.com/OpenRCT2/OpenRCT2/blob/develop/CMakeLists.txt#L140

Can you show us what does the cmake configuration step log for you?

**Comment by Mailaender** [comment]
I think it is falling back to the one you put into `orctlibs.zip` now.

**Comment by Mailaender** [comment]
Ah forget it, I went with `-DDISABLE_HTTP_TWITCH=ON` for now.

**Comment by janisozaur** [comment]
No, `orctlibs.zip` is for mingw builds, you're creating a native build.

Anyway, I missed that you mentioned you're compiling 0.0.3.1, which did not have this check: https://github.com/OpenRCT2/OpenRCT2/blob/master/CMakeLists.txt#L37

**Comment by janisozaur** [comment]
`-fomit-frame-pointer` will likely break the game

**Comment by Mailaender** [comment]
Probably comes from the `%cmake` macro. Will avoid that.

**Comment by janisozaur** [comment]
we specify `-fno-omit-frame-pointer` ourselves (it's seen further to the right), but I'm not sure which one takes precedence.

**Comment by janisozaur** [comment]
I have absolutely no idea about OBS (even though I am aware of its existence), but I managed to create a package there… I think. Keep in mind that there were many changes/improvements to the build system since 0.0.3.1.

This is as far as I can get you, please feel free to take it further.
v0.0.3.1: https://build.opensuse.org/package/show/home:janisozaur:branches:home:Mailaender:branches:games/openrct2
develop: https://build.opensuse.org/package/show/home:janisozaur:branches:home:janisozaur:branches:home:Mailaender:branches:games/openrct2

The latter does not link properly, from the looks of it there is something wrong with the way `curl` is wired up in pkgconfig, perhaps missing `-lz -lssl`.

If you find this a bug on our side, please let me know. This is something I would start investigations with: https://github.com/OpenRCT2/OpenRCT2/blob/develop/CMakeLists.txt#L174

Feel free to join us on gitter.

One final note: please note the project name is `OpenRCT2`, not `OpenRTC2`

**Comment by Mailaender** [comment]
I thought the `orctlibs.zip` was only required for cross-compiling from Linux for Windows.

**Comment by janisozaur** [comment]
it carries 3rd party libs too
