### ISSUE TITLE
Crash when zooming out

### ISSUE THREAD

**Issue by atmaxinger** [OpenRCT2/OpenRCT2#2610]
OpenRCT2 crashes when I want to zoom out in the following park. No custom objects used. The park was built in a multiplayer game lasting several hours today, but it suddenly started crashing when zooming (both in single player and multiplayer).

[Crazy Castle.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/75644/Crazy.Castle.sv6.zip)

![bildschirmfoto 2015-12-31 um 18 00 16](https://cloud.githubusercontent.com/assets/5960633/12066451/5c1f8a5c-afe8-11e5-890d-1516bcdb4095.png)

**Comment by IntelOrca** [comment]
This happens because a ride has become corrupted, one of the ride / track tiles. It is common for rides to get corrupted in multiplayer. We don't know why yet and for some reason we don't have an issue for this bug which has been reported dozens of times.

**Comment by telk5093** [comment]
I think this issue must be solved as earyly as possible. I cannot run a stable dedicated server since this issue occurs too often.
Will You be helped to investigate if we attached broken save game files whenever it occurs?

**Comment by IntelOrca** [comment]
@telk5093 I would love to fix this, but I don't know why its happening. Attaching a save that is broken is not helpful because the damage has already been done. We need reliable steps to reproduce.

I have a feeling it might be related to ghosts:
* #2140
* https://www.reddit.com/r/openrct2/comments/3ypkwq/certain_things_and_actions_cause_parts_of_a/

So if you can help make a video of reproduce this - that would help solve it much quicker.

**Comment by IntelOrca** [comment]
Caused by corrupt rides / track elements.
