### ISSUE TITLE
Disable cheats and hacks on multiplayer

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2652]
Right now... none of them will work properly and just cause problems. So just disable them.

**Comment by duncanspumpkin** [comment]
Disable clearance is used a lot on collaborative servers we should make sure this one always has a way to be enabled

**Comment by IntelOrca** [comment]
Since when is a server not collaborative?

**Comment by devnoname120** [comment]
Fast staff is also often used on sandbox-mode servers.
I think that it would be better to display a warning, rather than preventing the user from using cheats, as some work.

**Comment by janisozaur** [comment]
Cheats are now disabled in multiplayer by means of #2812

**Comment by devnoname120** [comment]
Yes, and since this update, a lot of server owners actively ask users to use an older version so that cheats work (especially chain lift speed, and sandbox mode). I don't think that using an older version is a good idea, yet removing cheats in multiplayer caused it.

Is it really not possible to add a group permission for the cheat window? It seems easy to implement and it looks like the best makeshift solution to me.

**Comment by PFCKrutonium** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/2862

Looks like the cheats are being made Multiplayer Safe

**Comment by devnoname120** [comment]
The cheats are now supported in multiplayer, I think that this issue should be closed.
