### ISSUE TITLE
Opening And Closing Park

### ISSUE THREAD

**Issue by dowlingl01** [OpenRCT2/OpenRCT2#2664]
I guess this is not really a issue but something which could be annoying to someone who has a big park with a lot of rides.

When you close the park it closes all your rides,
When you open, They are all still closed.

Just wondering if maybe anyone could add something which opens all rides when you open the park.

Thank you :)

**Comment by pizza2004** [comment]
Not exactly what you want, but if you open the rides window there's a button to open or close all of the rides at once, which is helpful.

My bigger question is, why does closing the park force all the rides to close?  Did that happen in RCT1?  I don't really remember, I just know I've played 1 more than two in the recent past (before OpenRCT2, but since I was a kid) and I just don't remember that being a thing that would happen.

**Comment by Gymnasiast** [comment]
OpenRCT2, like RCT2 and RCT1, does not close the rides when you close the park. I even tested it to be certain. It could be that you used the cheat Remove all guests, which indeed closes all rides for technical reasons. As @pizza2004 points out, opening all rides is easy to do with the Ride list window.

**Comment by IntelOrca** [comment]
I am sure the remove all guests cheat could be improved now so that it didn't close the ride... or revert the state of each ride if it was closed.

**Comment by Gymnasiast** [comment]
Indeed, 8 cars was capable of doing that, but I couldn't get it to work (people would still be in the rides even though they were supposed to be gone), hence why I opted for closing and clearing instead. It would be nice if we could match 8 cars in this respect.

**Comment by IntelOrca** [comment]
I am 8 cars did not do anything clever, it could only modify memory after all. When you tried to do it, did you modify any of the vehicles? There are lots of ride variables to change - that is why I think its better to close the ride (twice) as that deals with everything then set status back to what it was.

**Comment by dowlingl01** [comment]
Ah thank you all :D
