### ISSUE TITLE
Register an OpenRCT2 URI scheme

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2691]
**Source:** https://msdn.microsoft.com/en-us/library/aa767914%28v=vs.85%29.aspx

By adding a registry on Windows, the URI `openrct2://` can be defined which opens the application passing in the text after it.

**For example:**

``` text
openrct2://open/https://somewebsite.org/parks/SnowyPark.sv6
```

which will launch OpenRCT2, which then downloads the park and opens it. Websites can then interoperate the URI for downloadable parks and users can simply click a button to open it up in the game without downloading it via the browser. Just like how you can clone a GitHub repo in the desktop app by clicking the clone button in the browser.

Not sure how to do this with OSX or Linux.

Other things that could be done as pointed out by @ajvpot :

``` text
openrct2://join/somewebsite.org/11753
```

**Comment by LRFLEW** [comment]
I'm not sure how useful this is. I know it's possible on OS X because Steam does it, but wouldn't just using filetype association do the same thing?

**Comment by pizza2004** [comment]
https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102207

Doesn't look too difficult.  In fact, I'm not even sure it requires any sort of recompile of the code to do.

**Comment by ajvpot** [comment]
It would probably also be good to allow a "connect to server" path in the URI. Example: 
    openrct2://map/http://map.website/map
    openrct2://server/server.domain/port

**Comment by marijnvdwerf** [comment]
What should happen when the app is already running and you click a link?

**Comment by IntelOrca** [comment]
Well it should probably focus your already running game and prompt you with the save park before quitting dialog.

**Comment by RollingStar** [comment]
"openrct2://" is cumbersome to type and read. Does any existing program use "rct2://"?

**Comment by IntelOrca** [comment]
@RollingStar Why would you be typing it?

**Comment by RollingStar** [comment]
@IntelOrca Even though you're the head of the project, you can't know exactly what OpenRCT2 is going to be in 1, 5, 10 years. Can you really say there's no potential case where someone might type an Open RCT2 URL?

"Hey, check out my server at rct2://RollingStar !"

**Comment by IntelOrca** [comment]
@RollingStar The project is called OpenRCT2 though and users are more likely going to assume the protocol is ```openrct2``` rather than ```rct2```. Just like you have to type ```openrct2``` into the terminal to run the game (if in your PATH).

And if you were to shorten it to rct2, why not go further and just have ```rct://```

**Comment by PFCKrutonium** [comment]
![whynotboth](https://cloud.githubusercontent.com/assets/3945538/12371155/eb079384-bbf7-11e5-9143-612769504c84.jpg)

**Comment by AxxiD** [comment]
First: I really like this idea. I really come in handy when using some sort of server list. This list can be on a website or even in an app. For that it's extremly great to have a URI that is opened in and handled with in OpenRCT2.

Personally I find it more intuitive to write `openrct2` rather than just `rct` since this is not the original but an reimplementation.
In addition to that one could also use `orct2` as a short version of `openrct2`. (which has 5 chars like https)

Something I also want to mention here is Teamspeak 3 since their URI for connecting to a server via a link on a website is `ts3server://` which isn't particularly short at all. But it does its job to tell its purpose. And that is what I have in my mind here. The URI should tell the user exactly what it is for which is OpenRCT2 and not RCT or something alike.

**Comment by Mailaender** [comment]
I can help setup the MIME data for Linux. It is as simple as extending the .desktop file https://github.com/OpenRCT2/OpenRCT2/pull/3507.
