### ISSUE TITLE
OSX Command Key not read for keyboard shortcuts

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2704]
Currently it's set to CTRL, and the command key is ignored (e.g. cmd+s shows the staff screen). Should be the other way around.

**Comment by IntelOrca** [comment]
You mean change the default keyboard shortcuts for OSX?
Are you also suggesting that copying object Z should be CMD as well?

**Comment by marijnvdwerf** [comment]
Yeah, I was talking about the keyboard shortcuts. Even when attempting to change the default, the state of the Command key is ignored.

I don't understand what you mean with your second sentence

**Comment by IntelOrca** [comment]
OK if the command key is ignored when changing the keyboard shortcut then that is a bug that needs to be fixed.

When you are placing scenery, you can hold down CTRL while your mouse is hovering over another piece of scenery that already exists. This will set the Z position of the scenery your placing to the same Z position as the piece your hovering over so that you can more easily place a set of things at the same altitude.

**Comment by marijnvdwerf** [comment]
Hmmm, I'm unsure. On OS X, CTRL is like the least-used modifier, coming after CMD, SHIFT and ALT. I think the easiest solution would be to just say 'CMD is CTRL on OS X'

**Comment by pizza2004** [comment]
Technically speaking, holding down control and clicking counts as a right click on OS X.  It isn't even used as a modifier by the OS from what I can remember.

CMD is literally the CTRL of OS X.

**Comment by marijnvdwerf** [comment]
Forgot that about Option. My Dutch Apple keyboard has Alt printed on it though, which is fairly odd.

**Comment by AaronVanGeffen** [comment]
It says both "Alt" and "Option" on the US keyboard in front of me, too.

Nonetheless, Ctrl very much functions as Ctrl in certain applications. Of course, this is most notable in terminal-based apps (and includes sending signals like with ^C), but even the Adobe suite still uses Ctrl-based shortcuts.

Personally, I don't think we should just treat Cmd as Ctrl on OS X — they should just both work.

**Comment by marijnvdwerf** [comment]
International keyboards actually don't even say 'Option' at all:
![](http://i.imgur.com/FPFNU26.png)

Adobe shouldn't be seen as an example to follow. They're not exactly acting a proper citizens on either platform. Nevertheless, I agree that both keys should be configurable. Though I'd prefer CMD to be the default option.

**Comment by pizza2004** [comment]
Some people might want to hold down CTRL to use right click is the thing.

Yeah, that weird little symbol below alt means Option.  Just like the weird squiggly means Command.  It says Alt also because that's the alt key if you're using it with Windows, in OS X it's never referred to as alt.

I agree that just because Adobe does it doesn't mean it's proper.  I'd much rather have CTRL allow for right clicking like it would in the regular OS and use Command and Option when Ctrl and Alt would be used.  That's the standard behavior in OS X generally speaking.

**Comment by IntelOrca** [comment]
You can't just map CTRL to CMD because then you prevent users from having CTRL as an available shortcut modifier.

**Comment by jensj12** [comment]
@marijnvdwerf Looking at your left shift key, you clearly have a dutch keyboard there (the button with ` and ~ next to the left shift isn't there on international keyboards).
Changing the default keymapping for OSX to use CMD instead of CTRL seems the best solution to me, as it still allows the use of CTRL as extra modifier.

**Comment by IntelOrca** [comment]
This issue needs an OSX developer to add the necessary code to allow CMD to be used for shortcuts. Any volunteers?

**Comment by marijnvdwerf** [comment]
See #2711.
