### ISSUE TITLE
Using git submodule instead of manually merging translations

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/OpenRCT2#2733]
Currently, the translations are regularly merged from the other repository. This is a suboptimal solution as it pollutes the history of the main repository, and translations are outdated until someone merges them again.
http://www.git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by IntelOrca** [comment]
I have had my fair share of experience with git submodules and they cause way more problems than they resolve. This is why we do the merging instead.

**Comment by janisozaur** [comment]
Agree with @IntelOrca

**Comment by devnoname120** [comment]
What kind of issues did you encounter? I myself have not used them yet, so I am interested in your feedback.

**Comment by IntelOrca** [comment]
http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/

Also a submodule points to a specific commit. Thus using it for language would still require frequent commits to the main repository in order to update the submodule commit reference for the localisation repository.

There is lack of support from GUI clients which many users will use and we already have to help people with git problems as it is, that would be truly magnified if we used submodules.
