### ISSUE TITLE
Saving track design causes window to lose focus

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2757]
When saving a track design, a popup window appears:
![schermafbeelding 2016-01-17 om 22 48 55](https://cloud.githubusercontent.com/assets/737603/12380183/c4d266f0-bd6c-11e5-8c0e-8ee8f1ca7f3a.png)

When closing this window, the game window doesn't automatically focus again.

Expected behavior would be to use a sheet instead of a file dialog. This way, the game window will probably also keep focused

![schermafbeelding 2016-01-17 om 22 49 45](https://cloud.githubusercontent.com/assets/737603/12380185/cd49da3e-bd6c-11e5-99c7-cdfc4bcfe7ee.png)

**Comment by LRFLEW** [comment]
I've noticed this issue when loading saves. It shouldn't be too difficult to use SDL to regain focus once the window is closed. Also:

> Expected behavior would be to use a sheet instead of a file dialog. This way, the game window will probably also keep focused

Not really. That style is only relevant for document-based applications. Since we're using a graphics canvas (which is always an OpenGL window), the sheet doesn't really make sense. The [OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowDialogs.html) talks about the difference between the two in fairly significant detail.
