### ISSUE TITLE
Changing color of Fruity Ices stall

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2766]
The original RCT let you change the color of the stripes on the Ice Cream stall.  The Ice Cream stall's graphic was reused as the Fruity Ices stall in RCT2, but the option to recolor the stall was removed.  Would it be possible to re-add this feature down the road?  (I understand this would be low priority.)

This was first brought up in #468, but the issue was closed without discussion.

**Comment by Gymnasiast** [comment]
The reason that was closed is because the goal has always been reintroducing RCT1 features. As it is listed on the Wiki, there was no need for an issue. This was mentioned by Duncan in the issue you mentioned, but perhaps not clear enough.

Also, it's not that difficult to create a colourable version, as it's an official object, which doesn't get overwritten by saved games when the checksum differs (which certainly will be the case when it's more colourable). The only difficulty is that the user-provided ObjData still contains the unmodified version.

**Comment by IntelOrca** [comment]
Its not related to the code base either, its just a limitation of the object file. You can create your own object file to resolve this.

**Comment by e-foley** [comment]
Gymnasiast, the link in that issue is broken.  Either way, why wouldn't we have precise issues for each of the RCT1 features to reintroduce? Sounds like a good opportunity for a new tag.

**Comment by IntelOrca** [comment]
Take the tiled pathing... it was in RCT1 - that doesn't mean that we can just code back in. You instead download a custom object for that path. Thus you need to make or find someone who has made a custom object for a colour-able ice cream stall.

**Comment by Gymnasiast** [comment]
@e-foley : I fixed the link.
@IntelOrca : It would be nice if the _default_ ice cream stall had the ability to change colour. I'm sure it's possible, but it would probably be easier when we use our own DAT format anyway (reintroducing the ability when importing from RCT2).

**Comment by IntelOrca** [comment]
But I don't think the graphics for the object is using the remap colour.

**Comment by Gymnasiast** [comment]
No, but we could possibly key out the blue and replae it with the remap colour when importing. (Or even ask the user to supply a RCT1 disk, or grab it from the demo version of RCT1.)

**Comment by Horsti12** [comment]
We would need a new label for RCT1 kind of stuff like this. (rct1 import is just for importing scenarios from rct1)

**Comment by Gymnasiast** [comment]
This has now been implemented 99%. It is still hidden behind a flag because all previously placed Fruity Ices Stalls have their colour set to red, even though they are blue. This is fixed upon SV6 import.

When we switch to our own save format, we can remove the flag and recolouring stalls will be possible.
