### ISSUE TITLE
Expose Player IP's to Server Owner and allow IP bans

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2870]
And also, we need IP Bans.

**Comment by janisozaur** [comment]
what for?

**Comment by haloflooder** [comment]
To IP ban players who destroys the park.

**Comment by harrysbird** [comment]
Agree, Add reason for the ip ban

**Comment by IntelOrca** [comment]
Closing as #3155 will resolve this, or otherwise moves the problem to users needing to create new accounts with unique e-mail accounts and what not.

**Comment by wolfreak99** [comment]
Could I ask what the problem is with allowing straight ip bans? I understand that theres UUIDs and other alternative things that can be used, but you say "moves the problem to users needing to create new accounts with unique emails", which is pointing out it's still expoitable, we have the code that allows retrieving servers IP addresses, is it just hard to get IP addresses for players through c?  The average 14 year old script kiddie could easily create a new email and come back into servers every 15 minutes if he's getting a worthy reaction (I did it myself back when i was 14). It's a bit more complex to switch ip addresses, without trying to just an online proxy which would slow down the game and make it unenjoyable. Is there like a security issue with allowing server games to have access to player ip addresses?

**Comment by IntelOrca** [comment]
@wolfreak99 Any user with a dynamic IP address probably only has to reboot their router to get a new IP address. Create a new OpenRCT2 account is much more effort and requires a new e-mail account, activation. Plus we can always block IP addresses on repeated account creations.
