### ISSUE TITLE
Permanent permissions

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/OpenRCT2#2873]
Currently, the server admin needs to reassign players to their respective groups whenever they reconnect, which is not practical. The privileges should be permanent.

For this, I think that there should be a control on a connection token (randomly generated at the first join on the server, stored on both the client and the server), and the IP. This should be enough to avoid spoofing.

**Comment by LinusU** [comment]
I don't think there is a need to involve the IP, that seems bad since IPs change.

How about letting the server generate a UUID when it start, this id will be broadcasted to the clients. Whenever the client connect to a new UUID, it will in turn generate a UUID for use on that server. This id is only sent from that specific client to the server, and can thus be considered secret. The server will store permissions tied to that id, and when the client connects the next time it will authenticate with that id.

Please don't tie it to the IP address...

**Comment by Patrik356b** [comment]
Considering some people might want to play on public WiFi spots, 3g/4g connection, etc, tieing permissions to the IP is kinda pointless. 

Not to mention that nearly all ISPs will generate a new ip upon reconnect. (some might offer static ip but most likely not)

**Comment by wolfreak99** [comment]
In my honest opinion, i think IP Address should be the first step to implementing better control.
Sure, some will be able to bypass the features, but a UUID would likely be more complex to implement than detecting an ip address. Baby steps first... Just because there are some disadvantages to IP banning, does not mean it's completely pointless. We gotta start somewhere. I have a system setup right now that allows for reassigning people groups as they join in (as long as the server stays connected, working to get it to save to a cfg or something), but without even knowing how to get an IP Address of a client, i'mcurrently stuck assigning them to a players name, which could be much more easily changed than an IP change. I'm still sticking with player name linking because i know how to access it, and it's better something than nothing.

**Comment by PFCKrutonium** [comment]
A UUID System would be just as difficult/east to implement as an IP system, with the advantage of the UUID not changing. You could literally just generate 20 numbers using the systems random number generator and call it a UUID.

**Comment by wolfreak99** [comment]
It might be because idon't know c very well and i'm having trouble dissecting the code for the networkpackets and how the networking even works. if someone could build a function that could give the ip address or uuid or whatnot, i'd be easily able to port my system into it and add it. otherwise, i'll have to spend some time looking into how the networkaddress/networkconnection/networkplayer work, and figure out myself which will take longer and likely use ip address tagging until someone else could work onto my work or work up their own method.

**Comment by IntelOrca** [comment]
Closing now as #3155 will resolve this with permanent user IDs where permissions can be saved against for a server.
