### ISSUE TITLE
Dedicated Server Questions

### ISSUE THREAD

**Issue by mike-koch** [OpenRCT2/OpenRCT2#2930]
I am able to setup a dedicated server via the instructions on the wiki; however I have a couple questions that don't seem to be included in the wiki:

1. Is there a list of additional parameters available when starting the server (such as setting a password, whether to advertise the server on the master server list, etc)?
2. When I join the server as a client, I am added to the "Spectator" group.  Is there a way through the dedicated server (or through the client itself, such as a remote console) to change my group? I did not see anything documented.

**Comment by pizza2004** [comment]
I've been following the project for a while, and while I think the ability to set a password on a dedicated server is in the code it was only added recently, which would be why it's not well documented, and in general the features for dedicated servers are lacking.  There's no way to set up groups or assign yourself to one that I know of, but I didn't pay super close attention to the permissions code when it went through, so it /might/ be possible to change the groups with some file configuration, but I don't think we have any way of tracking who is who when connecting to a server yet, so there wouldn't be any way to assign yourself to a group.  I also don't remember whether or not anyone implemented a parameter for advertising on a dedicated server since the last time it was suggested, but there's a good chance it isn't in the code.

I'll go check some of these things and come back and edit this comment.

**Comment by IntelOrca** [comment]
1. ```openrct2 -h``` will list command help.
2. Not yet, this is a known issue: #2873
