### ISSUE TITLE
Add option to create custom currency

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2991]
As I mentioned a few times before, I don't want to add many extra currencies to the game. To cater for an audience that wants to use OpenRCT2 in an unincluded, virtual or even fantasy currency, an option should be added to define your own.

If anyone else wants to pick it up, please say so.

**Comment by telk5093** [comment]
I think we should discuss that this currency's name would be, if OpenRCT2's own currency comes up.

**Comment by PFCKrutonium** [comment]
RSGP Here I come.

**Comment by cmg5461** [comment]
Bitcoins!

**Comment by Nubbiy** [comment]
Would rather want a multiplication system for the currencies to make them more realistic.

For example: 1 $ = 7 kr       **NOT** like it is right now       1 $ ≠ 1 kr
1 kr is just 0,12 $

That is what makes it unrealistic (for that currency and others) when you have a item for 5 kr (0,60$) and they complain for the high price just because it replaces the **$** sign with **KR**. So instead of just replacing the $ 'letter', multiplying it to the correct value, in this case 1 $ x 7 kr = 7 kr would be appreciated<3 ,
And if 'bitcoins' are added.. which is "1 BTC = 415 $" .. oh boy

**Comment by IntelOrca** [comment]
@Nubbiy this is deliberate otherwise things to do get incremented in round numbers such as admission price.

**Comment by Nubbiy** [comment]
@IntelOrca Isnt it just possible to add a multiplying number and then round it to no decimals?

**Comment by Patrik356b** [comment]
@Nubbiy Kr is different for different countries by the way.

**Comment by Gymnasiast** [comment]
Exactly. And I'm not going to add virtual currencies like bitcoin, the whole point of this feature is to allow people to use anything (Bitcoin, litecoin, GymnasiastIsAMasturbatingMonkeyCoin) as their currency, with any exchange rate to the pound they want (including insane ones).

**Comment by Nubbiy** [comment]
@Patrik356b I know, but then it can be called SEK etc

**Comment by gDanix** [comment]
I'm inspecting the code and this doesn't seems difficult to implement, I think I can do it

**Comment by gDanix** [comment]
Ok, I think I can show you the progress made with this issue.

Here you can see a new entry for the custom currency, clearly separated from the rest of the "ordinary" currencies:
![captura de pantalla de 2016-06-23 23-54-21](https://cloud.githubusercontent.com/assets/1117657/16321655/6a7a9232-399e-11e6-8d56-d05a6a72c379.png)

Whenever you select that dropdown entry, the custom currency configuration window will appear:
![captura de pantalla de 2016-06-23 23-52-46](https://cloud.githubusercontent.com/assets/1117657/16321677/8e33f588-399e-11e6-9e16-b61301053367.png)

Here you'll can configure most relevant aspects of the new defined currency:
![captura de pantalla de 2016-06-23 23-55-51](https://cloud.githubusercontent.com/assets/1117657/16321693/a7d39e58-399e-11e6-8c15-b29191688ba4.png)

Here, the rate is relative to 0.1 GBP. Why?. Because we consider GBP as the reference currency, and it's defined with `rate = 10`. The text shows 0.1 because a monetary unit is divided by the GBP rate. What you're really doing in this window is setting the `rate` value and the symbol affix of the custom currency (and in the near future, the symbol too)
