### ISSUE TITLE
Voice chatting in-game

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3066]
There should a feature where people can voice chat in-game. There should be also be a feature where you can mute someone's voice if the person is like screaming into mics, disturbing, or if someone is playing an inappropriate song. The control for voice chatting should be CTRL + C. Should this be a great idea if we had voice chatting to go along with muting in case someone is screaming and cussing?

**Comment by Gymnasiast** [comment]
There are plenty of services for that, like Skype or Teamspeak, which do their job fine. No need for additional development burden for no or little benefit.

**Comment by PFCKrutonium** [comment]
@birthdaybrian I would suggest using Discord for that imo. It has an ingame overlay and everything to give you full control. (Will require Hardware Display to be on though.)

**Comment by IntelOrca** [comment]
This is wishful thinking right now. Its better to just use 3rd party services who specialise in this.

**Comment by JarnoVgr** [comment]
Sure I can understand that this is very low priority. But many major games have support for this. If you play on a public server you can't expect everyone to be on a separate TS server or being in a Skype call.

**Comment by devnoname120** [comment]
I agree with @JarnoVgr. Or alternatively, you could integrate a service such as Discord in OpenRCT2.

**Comment by Gymnasiast** [comment]
That's easy to request if you're not the one who has to maintain the code. Every added feature means more maintenance.

**Comment by JarnoVgr** [comment]
@Gymnasiast Shall we just stop requesting any new features because we're not the ones maintaining the code?

The thing is, I don't think anyone expects this to be implemented right away. But when multiplayer gets more popular, stable and mature then it should definitely be considered **at some point**. Proper voice communication is vital for multiplayer games, even for OpenRCT2. I personally see this as a **long-term** and **low priority** feature request.

Now I do agree that using third party software is better and such. But that's not the perfect solution for public servers.

**Comment by IntelOrca** [comment]
Whiskey station is such example that offers a discord voice chat for a public server.
