### ISSUE TITLE
Plugins Support For Server

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#3166]
Would great ideas to add Plugins support for server everyone want this feature this mean: add-on commands, plugin loader and more.

**Comment by IntelOrca** [comment]
In what way? Its open source so anyone can maintain their own fork with extra features on the server side. Obviously we will try to make the code more... hook / DI friendly to make it easier over time.

**Comment by harrysbird** [comment]
yes, so people can code to make commands and api for multiplayer server

**Comment by zsilencer** [comment]
what would be an example of a plugin that you are wanting

**Comment by harrysbird** [comment]
yes

**Comment by JarnoVgr** [comment]
Support for plug 'n play plugins/scripts is welcome. Not everyone has C/C++ knowledge, and scripts are an useful alternative. Now I can't think of any plugin-ideas at this moment. But I'm sure others can, and will.

**Comment by Gymnasiast** [comment]
RCT2 already had a plug-in system, I think we should extend that support*. I like being able to unload them, and I also think a proper plug-in system increases the chances they work well with each other.

OpenTTD's NewGRF system is more of a mod system, and because of that doesn't allow unloading. We could even allow both, as mods usually allow modifying more aspects of the game.

* Things that could be converted to plug-ins (after full implementation):
- Land types (surface and edge)
- Music tracks (possibly allowing them to tie to a style, or creating a new one)
- Ride entrance styles
- Entertainer styles

And going further, possibly even
- Ride modes
- Track types

**Comment by Juli199696** [comment]
Just an idea, maybe add a predefined script like " if (!command)
                                                                               {
ingame text message to player
}
Command example  "!help or /help or /admin 
As you can define the command yourself you can use it for ideas like "!goal, !stats, !maps, ..." and as there is an web api you can easy add scores to a webpage and link to it with a ingame command.
Example !help shoes commands on this server (!help,!web,!maps)
If you type !web it will show the website link of this server ingame for more information. You can do many more stuff. Just take a look on the OpenTTD servers. There are commands normal on every good server.

**Comment by harrysbird** [comment]
You can learn C++ or C# in http://www.programmr.com/practice/
