### ISSUE TITLE
No sound in the game

### ISSUE THREAD

**Issue by ptkato** [OpenRCT2/OpenRCT2#3305]
**OS:** 
Arch Linux
**Version:** 
0.0.5-develop
**Commit:**
e5666f2

No sounds at all, simply doesn't work.
I've installed it via AUR.

- [ ] Reproducible in RCT2 (vanilla)?  
Can't run it in Linux.
- [ ] Multiplayer?  
No. But the sound doesn't work there either.

**Steps to reproduce:**
1. Open the game;
2. Just silence.

**Comment by Gymnasiast** [comment]
Possibly one for @janisozaur to look into.

**Comment by AaronVanGeffen** [comment]
What sound system are you using on Arch? ALSA directly, or do you use PulseAudio or another mixer?

**Comment by ptkato** [comment]
I'm using PulseAudio.

**Comment by zsilencer** [comment]
have you tried changing the device in the options

**Comment by ptkato** [comment]
There's only the default.

**Comment by ptkato** [comment]
I still am without sounds. I've updated to the latest commit available in AUR (cd7482b).

Can anyone point me to a troubleshooting?

**Comment by janisozaur** [comment]
Hey, can you join us on gitter?

**Comment by mmarquezs** [comment]
I had the same issue here with Arch it might not be related specifically to OpenRCT2, because I had the issue on stellaris too which uses SDL too.  For now i have changed SDL audio driver to Alsa setting SDL_AUDIODRIVER=alsa on /etc/environment. Stellaris  worked immediately after this (well after a reboot) and OpenRCT2 after the change it seemed like it didn't work yet but after resetting the configs in ~/.config/openrct2 the sound came back. 

I also have a laptop which works fine with pulseaudio and sdl and openrct2 and Arch but that might be because i haven't update it for a while.

**Comment by Goddesen** [comment]
I'm haivng no trouble with ArchLinux and Pulseaudio, though I didn't get the code from AUR. No warnings about potentially missing libraries?

**Comment by ptkato** [comment]
I've reinstalled Arch and now it works fine.

**Comment by Lucki** [comment]
There's a `master_volume` key in `[sound]` from `~/.config/OpenRCT2/config.ini` which has no corresponding slider ingame.
After setting the value from `0` to `100` the audio went back.
