### ISSUE TITLE
Opening tile inspector then footpath closes both windows.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3324]
**OS:** Windows
**Version:** 0.0.5
**Commit:** e5666f214bcaf882bbf7922849656037cebed9b8

Opening the tile inspector and then opening the footpath construction window will close both windows and have the footpath tool selected but unusable.

**Comment by gDanix** [comment]
This can be caused because both windows are requiring the cursor to "do special things". Opening the footpath window having the Clear Scenery Tool already opened causes this one to disappear, and footpath the only one visible.

I can confirm this happens in Linux, and not only with footpath window, but for Clear Scenenery and Land windows too.

I'm working on this.
