### ISSUE TITLE
Rides don't report rider numbers over 250

### ISSUE THREAD

**Issue by bbc100** [OpenRCT2/OpenRCT2#3330]
Windows 10
v0.0.5 e5666f2
**Commit:** ???

My Monorail ride is how I found this out
- [?] Reproducible in RCT2 (vanilla)?
- [?] Multiplayer?

**Steps to reproduce:**
1. Build a big Monorail ride or similar near the entrance to the part
2. Spawn heaps of people and see how many go on the ride to test

**Save game:**
I can post one if you want me to

**Comment by PeteyPii** [comment]
What I'm seeing on 3405fd5bad1d3cc74c7db9b9a057f7725e32c050 is that rider count (displayed in the main window of the ride) wraps from 255 down to zero. Otherwise put: I believe what @bbc100 is seeing is some unsigned 8-bit integer overflow.

![image](https://cloud.githubusercontent.com/assets/626369/14660297/2d6a53e6-0672-11e6-9555-f67f541605dd.png)

I'm totally new but from what I can tell, the number displayed comes from the `rct_ride` struct member variable `num_riders` which is indeed a `uint8`. I'm not sure what is required to fix this (or if it is even possible) in addition to changing the member to be of type `uint16`. The memory layout seems to be significant for this struct.

**Comment by bbc100** [comment]
Ah, ok, I wondered if it could be fixed

**Comment by IntelOrca** [comment]
RCT2 only allowed 1 byte for storing the number of riders for a ride. We won't be able to change this until we move away from RCT2 and SV6 format. As long as it doesn't overflow then this is a technical restriction, not a bug.

**Comment by e-foley** [comment]
...But it DOES overflow, as @PeteyPii said.  Why was this issue closed?

**Comment by bbc100** [comment]
"As long as it doesn't overflow then this is a technical restriction, not a
bug."

**Comment by e-foley** [comment]
Again, the counter *does* overflow from 255 back down to 0, then continues 1, 2, etc., so the statement @IntelOrca made is moot and this issue should not be closed.

**Comment by bbc100** [comment]
Okay...

**Comment by PFCKrutonium** [comment]
I think what he meant was that as long as it isn't an overflow that actually breaks anything aside from the obvious.

**Comment by Gymnasiast** [comment]
Thing is, this limitation is imposed by SV6. In order to fix it properly, we have to move from SV6 to our own format. For now, we can't really do much.

**Comment by bbc100** [comment]
Ah, ok

On Sun, Apr 24, 2016 at 8:29 PM, Michael Steenbeek <notifications@github.com
