### ISSUE TITLE
Info Kiosk Glitch when importing RCT1 saves

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3414]
OS: Windows 10
Version:0.0.5

When I import some of my RCT1 saves into OpenRCT the Info kiosks will display as a coaster train rather than an info kiosk.

I've included zip files of all the save files that display the kiosks correctly and another one which displays the coaster train

Screenshot:
![untitled](https://cloud.githubusercontent.com/assets/1381723/14769079/8c492fd4-0a48-11e6-865c-4215ed8cbb78.jpg)

[With Info Kiosk Glitch.zip](https://github.com/OpenRCT2/OpenRCT2/files/233555/With.Info.Kiosk.Glitch.zip)
[Works.zip](https://github.com/OpenRCT2/OpenRCT2/files/233557/Works.zip)

**Comment by Gymnasiast** [comment]
The problem seems to be in research - the non-working parks don't have the information kiosk - it's not selected in object selection.

**Comment by IntelOrca** [comment]
Its not strange that they are in the object selection, I do a map tile loop for scenery and track etc. and a ride list loop to ensure it adds the required objects.

I think extra code is needed to scan ```rct1_s4::available_rides``` and ```rct1_s4::available_vehicles``` which are bit maps representing what it currently researched or not.

**Comment by Gymnasiast** [comment]
Yes, but they don't appear in the research list at all.
By the way, when you import an SV4 (any SV4), nothing is available until you open and close either the inventions window or the object selection window. (This did work before your refactor, as my code simply made everything invented and ignored research.)

**Comment by Gymnasiast** [comment]
Some more information:
- No rides being available in the New Ride window can be solved by called `sub_684AC3()` at the end of `S4Importer::ImportResearch()`.
- When opened in vanilla RCT1, the Looping roller coaster is not available and the info kiosk is. When opened in OpenRCT2, it is the other way round.

**Comment by Gymnasiast** [comment]
Spotted another thread: all five affected parks have one thing in common: none of them has the Steel Roller Coaster / Looping Roller Coaster in it (i.e. not available and not researchable). Also, the Steel Roller Coaster train has vehicle index 0.

**Comment by Gymnasiast** [comment]
Found a fix! PR incoming in a few minutes.

**Comment by IntelOrca** [comment]
> Yes, but they don't appear in the research list at all.

Right... which is why I said the bit map has to be used. Presumably RCT1 just removed items from the research list when they got researched or something.

> By the way, when you import an SV4 (any SV4), nothing is available until you open and close either the inventions window or the object selection window. (This did work before your refactor, as my code simply made everything invented and ignored research.)

Well we certainly don't want everything to be researched, we want it to convert the research state. I mainly concentrated on SC4s not SV4s, so extra work like the above might be necessary.

> Spotted another thread: all five affected parks have one thing in common: none of them has the Steel Roller Coaster / Looping Roller Coaster in it (i.e. not available and not researchable), if the RCT Wikia is to be believed.

I'll check with the RCT1 saved game modifier.

> And another thing: the Steel Roller Coaster train has vehicle index 0 in RCT1.

I know, that is why ```RCT1_VEHICLE_TYPE_STEEL_ROLLER_COASTER_TRAIN``` is defined as 0. Not sure otherwise what you are trying to say.

**Comment by Gymnasiast** [comment]
What I meant was that when you import a ride from RCT1 that does not use vehicles, like the information kiosk, the (unused) `vehicle_type` field is likely to be 0. That vehicle index happens to belong to the Steel Roller Coaster Train, which is why it was glitched like this.

The problem turned out to be that the code that determined which .DAT files to load did not check whether the ride had vehicles and thus loaded the Steel Roller Coaster train for rides that didn't use vehicles. Since most parks have the Steel Roller Coaster available, this only caused problems in parks that didn't have it available, like the five the OP attached.

**Comment by IntelOrca** [comment]
@Gymnasiast yes you're right, I even had a TODO there to remind me but you have now done the fix: #3437
