### ISSUE TITLE
Append default extension when none is entered in save dialog

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3510]
**OS:** Linux (OS X?)

As exposed by https://github.com/OpenRCT2/OpenRCT2/pull/3477, the Linux version of `platform_open_common_file_dialog` does not append default extension when none is given.

Windows version does that, not sure about OS X.

**Comment by gDanix** [comment]
This only happens when using Zenity dialog style.
KDialog does append the extension when the appropiate option is set (it is by default) (I'm assuming this behviour is expected, si there's nothing wrong with KDialog)

I'm working on this.

**Comment by gDanix** [comment]
Apparently, there is no way we can obtain the filter selected by the user inside the Zenity dialog. This means that we must rely on the fact that the only present filters in the dialogs we are creating are:
1. The relevant filter: *.sv6, *.td6 (as an example)
2. The "all files" files: *.*

Because of this, the only thing I can do is to extract the extension from the **first** filter, don't know if it's possible to do a more intelligent thing.
