### ISSUE TITLE
Save cheats 

### ISSUE THREAD

**Issue by kevdog3700** [OpenRCT2/OpenRCT2#3517]
Something I hate is that whenever I load up my park all of my cheats are turned off if you could add a option to save the cheats i turned on/off when saving the game that would be awesome.

**Comment by jensj12** [comment]
This has been discussed in the chat a few days ago. Once we are on our own savegame format, cheats will most likely be saved in the save. Until then, just re-enable them every time.

**Comment by Gymnasiast** [comment]
@jensj12 I don't remember this being discussed in the chat. There was a conversation on Reddit though.

Anyway, until a few months ago, cheats you could turn on and off _were_ persistent. They were taken out at @IntelOrca 's request, although I was against it. I still am, I find it as irritating as you.

**Comment by Patrik356b** [comment]
It should be saved with the same game in my opinion

**Comment by TeamSpen210** [comment]
Could this extra data be stored in special `rct_map_element` items? An element could be added to the map at 0,0 (or another special location) using a type in the unused 8-15 range, and use the 4 bytes to store cheat settings and other OpenRCT2 values. It would depend on whether vanilla RCT ignores the invalid type. Alternatively it could use something like the maximum value for a scenery ID, or a large scenery combination known to be invalid in a vanilla RCT2 object. 

(I don't know much about the code, I'm not sure if this is feasable to implement.)

**Comment by Nubebuster** [comment]
So, will this be added or not?

**Comment by AaronVanGeffen** [comment]
Not until a new save format has been implemented. The issue has been tagged as such as well.

**Comment by l0lzelig** [comment]
And why exactly do you not simply store these settings in a seperate .ini file or something similar that OpenRCT itself reads from?  This is such an annoying thing to do every time I want to play.

**Comment by Broxzier** [comment]
Because then we need to add backwards compatibility for that config file later. These kinds of things only slow down development.

**Comment by Richard-L** [comment]
fwiw I'd be glad if I can plea for cheat settings to be remembered, too. I just googled up this issue. Since the game is played in so many different ways, I can understand how it might help to reset cheats on every boot and not remember them, so that people don't accidentally keep them on. But in my case it's a little cumbersome to keep having to re-enable the "Allow building in pause mode" each and every time. This option is especially handy to keep the game frozen at a given frame, whilst allowing minor editions to the park.

I remember when cheats were remembered. Surprised to see the dates on the above messages that this was apparently taken out so long ago. Feels much more recent to me somehow.

**Comment by AaronVanGeffen** [comment]
This has already been implemented in the new save format.
