### ISSUE TITLE
add maximum window number config

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#3523]
**OS: OS X** 
**Version: 0.0.5** 
**Commit: fc74e50** 

after #3303, maximun count of window increased. but since it's high than vanilla limits, openrct slows down when hiring staffs a lot, even freezes when window is too many. I think there should be user adjustable limit in window system.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by Wirlie** [comment]
I have the same problem... (My FPS slows to 1-2 FPS if I have a lot of windows)

**Comment by Mijago** [comment]
Why don't you just use Shift + Backspace to close all open windows?

**Comment by IntelOrca** [comment]
@Mijago and when we implement pinned windows you can pin the staff window to stop that from closing when pressing Shift+Backspace.

**Comment by Wirlie** [comment]
@Mijago I know, but I do not use Shift + Backspace because this closes all windows (included the staff window, etc), @IntelOrca has said a possible solution for this.

**Comment by IntelOrca** [comment]
I just wanted to point out that the issue happens when all the windows at in the same area on the screen. When you open up a bunch of guest windows or staff windows, after the 4th one, each one after that gets placed under the 4th one (bottom right corner of the screen) and the FPS drops. If you then move all those windows from the bottom right corner of the screen and spread them out over the entire screen, the FPS goes back up.

So it looks like we can improve the performance in other ways, and in particular it should not draw a viewport if its completely obscured by another window.

In my OpenGL branch, the drawing is fast enough for this to not be an issue anyway.

**Comment by Nubbie** [comment]
#3805 has been merged so this can be closed, especially when #3993 backs it up
