### ISSUE TITLE
Wild idea: new types of staff

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3546]
I have no idea if this could be done, but it would be amazing: adding new types of staff in addition to handymen, mechanics, security and handymen. I got the idea from an old post somewhere here, it suggested that mechanics could fix vandalised stuff.

I guess fixing that stuff seems like a job a handymen would do, but a repairing sprite already exists for the mechanic, making him the best candidate to take on this role. Not really a good idea to make a new staff type for that then.

What would be cool new staff types?
- Photographers: staff members taking pictures of people and selling them as well as raising happiness. A sprite for a photographic peep already exists, so the sprite could just be that peep with a uniform colour
- Similarly: a charicature painter. Sprites are again already in the game
- Promotor: a peep sprite (maybe with a hat, sunglasses, whatever, to make it stand out) assigned to direct peeps to a ride of your choice. Could be great to promote not-too-popular rides.
- Ballon guy: giving peeps free balloons
- Medic: healing nausea
- Psychologist: making peeps stop complaining and destroying stuff. Okay this one is silly

I'd love, LOVE the painters and the promotors.

**Comment by Ziscor** [comment]
This might be the perfect time to leave this here:

https://openrct2.org/forums/topic/1086-staff-upgrades-maintenance-carts/

**Comment by Gymnasiast** [comment]
Obviously, many people would disagree about adding new staff types, as they change how the game works fundamentally. Of course, that doesn't just apply to staff, but to many other possible changes as well. There is also the increased maintenance burden for us.

We have plans for a plug-in system. It will have to be flexible enough to add extra staff types, at which point anyone who wants extra types of staff can add them to the game, people who don't won't have them, and it also decreases our own maintenance burden.

Because of those reasons, this won't get implemented in the base game. I will therefore close the issue.
