### ISSUE TITLE
Suspended Swinging Coaster crashes on selecting rolling/banking track

### ISSUE THREAD

**Issue by DagonX** [OpenRCT2/OpenRCT2#3564]
**OS:** Windows 7
**Version:** 0.0.5 Develop
**Commit:** 4298f41

Explanation of the issue:
When you try to switch the rolling/banking while building a custom Suspended Swinging Coaster, the game crashes. Upon further inspection, this is not reproducible in RCT2 Vanilla...because Suspended Swinging Coasters cannot be rolled/banked.
**The option to do so should not be there in the first place.**

Reproducible in RCT2 (vanilla)? No.

**Steps to reproduce:**
1. Start building a custom Suspended Swinging Coaster
2. Try rolling/banking the track

**Dump/Save file**

[OpenRCT2Crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/258277/OpenRCT2Crash.zip)

**Comment by Broxzier** [comment]
This does apply to many more coasters. https://github.com/OpenRCT2/OpenRCT2/commit/aa929e1593e7a2adcc0c5886c2693c3e2ec407fa seems to have caused it. In b5c0913b76facd25f8db03c4f6f7bbd615eb6e76 (parent) the banked button is not displayed for rides that don't have them.

**Comment by Wirlie** [comment]
Vertical Loop track have the same problem on many rides, for example Giga Coaster have this track but on the vanilla game Giga Coaster does not have this track.

OpenRCT2:
![scr18](https://cloud.githubusercontent.com/assets/7508197/15370350/3adcdf44-1cfc-11e6-85ad-223fe16dc8c9.png)

RCT2:
![scr2](https://cloud.githubusercontent.com/assets/7508197/15370565/2ae8b684-1cfd-11e6-8c05-456acd27fa4e.png)

But, I have noticed that if you try to open a game previously saved in OpenRCT2 the bug is reproducible in RCT2.

RCT2:
![scr5](https://cloud.githubusercontent.com/assets/7508197/15370652/8394748a-1cfd-11e6-884f-6fa696a25d4a.png)

**Comment by Christipher** [comment]
I have also seen this in the original game (though I think later versions fixed this, though I have seen this bug before) where in some circumstances taking the car into a bank at some random point will cause it to crash (this is also caused by the same thing if I'm not mistaken... I've only had this type of rolling/banking crash on the LIM Launched Coaster (especially taken at high speeds) and the Spiral Roller Coaster (which both have that option in the original game)).  I suspect this is an original bug that's been aggravated and is caused by an original bug.

**Comment by Patrik356b** [comment]
There is a sloped banking curve you can try building in the original game but the build button refuses to accept this. I don't remember exactly how to reproduce this

**Comment by Broxzier** [comment]
@Patrik356b: I believe that's for diagonal pieces going up or down. In OpenRCT2 it does respond, but shows you an empty build button that cannot be pressed.

**Comment by PureTryOut** [comment]
Reproducable on Ubuntu and Arch Linux, both on newest development version as of this moment (3914e92117debc1709b18a2655ae7d44b94a9dcf). At the exact moment you select the banked turn it crashes.
