### ISSUE TITLE
Map generator can leave terrain uneditable

### ISSUE THREAD

**Issue by X123M3-256** [OpenRCT2/OpenRCT2#3568]
**OS: Windows** 
**Version: 0.0.5-develop** 
**Commit: 30a044a** 

The map generator can generate terrain that exceeds the 120ft height limit imposed by the game. This terrain then cannot be edited (raised or lowered), because it exceeds the height limit.

**Steps to reproduce:**
1. Open map generator
2. Set "Low" and "High" to 24 and 36 respectively
3. Look for some terrain that's above 120ft, and try to edit it.

**Comment by Gymnasiast** [comment]
Best solved by raising that (seemingly arbitrary) limit then, I'd say.

**Comment by X123M3-256** [comment]
Yep, I agree. The actual limit is much higher than the one imposed by the game.

**Comment by PFCKrutonium** [comment]
It should probably be an Option, marked with "Could make your save incomparable with the original game."

**Comment by X123M3-256** [comment]
As far as I'm aware it doesn't make your save incompatible with the default game. There are certainly examples of parks made in vanilla that exceed this limit.

**Comment by spacek531** [comment]
Except that the original game can handle higher terrain. The random terrain generator is only capable of generating terrain as high as 225 feet, there is a park that works just fine in the original game that has terrain as high as 310 feet, which I linked to in the issue I opened.

The only problem with taller terrain is that the camera boundaries are are based on map size XY and no taking into account for Z, so it can be impossible to see what is at the edges when the terrain is tall. Different camera behavior will need to be implemented for maps with tall terrain near the edges so that the entire park can be seen.

**Comment by Gymnasiast** [comment]
I will cap the terrain at 64 units (96 metres, 320 ft), for both the land generator and the land tool. To me that seems like a sensible limit.

**Comment by Patrik356b** [comment]
Sounds good

**Comment by Christipher** [comment]
yeah - I believe the final height limit is somewhere between 600ft. and 650ft.

**Comment by spacek531** [comment]
Any news on this? It would be great to be able to have higher terrain (and especially water) for the current NE Designs competition.
