### ISSUE TITLE
Steel twister rollercoaster always shows all track designs

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3681]
**OS:** win10
**Version:** 0.0.5
**Commit:** 4944fe1, 349684b

The Steel Twister Roller Coaster always shows ride designs from other rides with the same track type, even when 'Select rides by track type (RCT1 style)' is turned off.

~~On the forum another issue with the steel twister was reported in the same topic, the ride selection window now shows the long trains instead of the wide ones when both are selected. Couldn't reproduce that one yet. https://openrct2.org/forums/topic/1301-steel-twister-roller-coaster-have-some-problems/~~ _(Moved to other issue, fixed now)_

**Steps to reproduce:**
1. Open any park with the steel twister coaster type available
2. Make sure 'Select rides by track type (RCT1 style)' is turned OFF
3. Go to the prebuild ride selection screen of the steel twister roller coaster

**Screenshots / Video:**
![scr108](https://cloud.githubusercontent.com/assets/13868449/15422816/94375658-1e7a-11e6-8853-bc2f8ba88dfb.png)

**Comment by coltongit** [comment]
I wonder who would wanna build that mess of a coaster... Probably someone tired of all the other designs...

**Comment by jensj12** [comment]
It doesn't just happen to the Steel Twister Roller Coaster. Looping Roller Coaster and Water Coaster also show the designs from their WW/TT clones and the Wild Mouse also shows the Spinning Wild Mouse designs (the spinning wild mouse doesn't show wild mouse track designs).

**Comment by coltongit** [comment]
With my testing on Windows 8.1 x64, this doesn't happen.

**Comment by Gymnasiast** [comment]
Vehicles in RCT2/OpenRCT2 can set a flag. If it is set, the vehicle will be listed separately. If it isn't set, the vehicle will be listed under the generic name of the track type and be switchable. Floorless RC has set that flag, while the two hyper-twister trains (wide cars and 6-seater cars) haven't.

The problem seems to be that the track list seems to ignore the separate flag when listing the designs for vehicles that haven't said the flag. This is why only pops up with certain vehicle types.

**Comment by Gymnasiast** [comment]
This has now been fixed, but you'll need to delete your objects.idx file in order for it work.
