### ISSUE TITLE
reporting dump files

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#3896]
**OS:** [win vista 32-bit sp2]
**Version:** [e.g. 0.0.5]
**Commit/Build:** v0.0.5-develop build 0ec2b00

[Explanation of the issue...]

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multipl
[7dc6cb77-a4ae-4d83-b67d-211782e3d492(0ec2b00).zip](https://github.com/OpenRCT2/OpenRCT2/files/321199/7dc6cb77-a4ae-4d83-b67d-211782e3d492.0ec2b00.zip)

r?

app. crash, dump file created
1. [step 1]
2. [step 2]

**Dump file**
[If you have a dump file: zip it before you drag & drop it here.]

**Screenshots / Video:**
[Drag & drop screenshots here. Use https://vid.me to upload video.]

**Save game:**
[Change the file extension to .txt or package to a .zip so that it can be drag & dropped here...]

**Comment by Nubbie** [comment]
Please, try to fill in the headers correctly ;o

The bold letters are titles, e.g., move down the dump file under 'Dump File'

**Comment by mrtnptrs** [comment]
@Gymnasiast See, it can even be done worse :P

**Comment by Gymnasiast** [comment]
Please provide more information. We cannot solve bugs if you don't describe what you were doing, whether it was in multiplayer, single player, scenario editor, etc.

**Comment by Gymnasiast** [comment]
You don't need the expansion packs, unless you want to join a multiplayer server that uses them on their map, or want to load a game that contains them.
'Latest build' is a bit vague, we need build numbers like 2e3500e.
Does the game crash on startup, or later on?

Also, recently some object loading code was put into the game which turned out to cause problems. We reverted that, so please try using the newest version (which is numbered 2e3500e) and see if that helps. If it doesn't work, please try running the game from the command prompt.

**Comment by Nubbie** [comment]
```
>	00100000()	Unknown
 	[Frames below may be incorrect and/or missing]	
 	openrct2.dll!TcpSocket::ConnectAsync::__l8::<lambda>(void * pointer=0x08102430) Line 315	C++
 	openrct2.dll!int <lambda>(void *)::<lambda_invoker_cdecl>(void * pointer=0x08102430) Line 315	C++
 	[External Code]	
 	openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const parameter=0x08102430) Line 115	C++
 	[External Code]	

```

Have some problems tho to open the dump file it seems

**Comment by Invictaz** [comment]
![opengl-hd3000](https://cloud.githubusercontent.com/assets/20338545/16731899/cb934020-477a-11e6-8fd1-29eaf46dd4a0.png)

**Comment by Nubbie** [comment]
Expired?
