### ISSUE TITLE
Idea: tracked ride converter 

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#3935]
While we do have the opportunity to put a corkscrew roller coaster train on the looping coaster track by cheating, it's not optimal and neither is rebuilding the coaster.
Also I don't think that works in vanilla, but I haven't tested this. 

I suggest looking into creating a tool for the roller coaster designer which can do a step-by-step conversion from let's say junior coaster to wooden roller coaster. 

It should ask what to do if there any missing track parts like: abort, skip, use standard piece if available 

This is to handle things like the curved slope with lift chain on the junior coaster.

**Comment by Patrik356b** [comment]
I forgot to add that it would also need something for conflicting operating modes, i.e. Shuttle mode doesn't exist on roller coasters

**Comment by X123M3-256** [comment]
We have a cheat to change train types, a cheat to change track types, and a cheat to change operating modes. Is there anything this feature would do that that doesn't cover?

**Comment by Patrik356b** [comment]
Unlike the cheat, this would be a safe option. And much quicker than rebuilding any tracked rides you would like to change

**Comment by X123M3-256** [comment]
Changing track types is what can cause crashes, and this happens when the track type you choose doesn't have all the required pieces. Obviously, the desired conversion can't be performed in that case. I think it would be better to rectify this issue so that it shows an error instead of just crashing, rather implementing an entirely new feature that does more or less the same thing.

**Comment by Patrik356b** [comment]
But what about vanilla compatibility? 

Let's say I want to convert a corkscrew coaster with a duplicate looping coaster and the track has a left corkscrew piece attached to a right corkscrew piece. 
The "skip piece" option would make the ride complete in this case and you would just have to tie together the loose ends yourself. 

Let's also look at rides with chain lifts at uncommon places, i.e. Junior coaster with sloped curve chain lift. 
This isn't valid for other coasters afaik and I'm not sure how it works with vanilla. 

This piece could be replaced by the standard piece which lacks chain lift if the target type doesn't have this piece

**Comment by X123M3-256** [comment]
> Let's also look at rides with chain lifts at uncommon places

Not a problem. Chain lift can be set on any track piece on any ride and this is 100% compatible with vanilla. Chain lifts are not a seperate track piece, they're a flag that can be set on any other piece. If no sprite is available the default is used, it's not a problem. The problem arises with things like loops and corkscrews - these are actual seperate track pieces and if the track style doesn't have the right sprites it will crash, so you would not be able to convert rides that have these pieces. While you could simply skip them, you'd then be left to fill the gaps manually.

**Comment by Patrik356b** [comment]
Yeah, but it would do most of the process for you when it comes to rebuilding the ride. Shipping unsupported pieces is more useful in most cases.

**Comment by Christipher** [comment]
yeah, Patrik356b is right on this one, though we can probably keep a database as to what is available with each ride type and what is not (there should be a few rides where this is not possible, such as the water coaster (where you would have water sections) and dighny slide (if I spelt that correctly, though it's issue would be the tunnels).  I was thinking that a series of two data bases should be kept and the tool work only if these rides appear in the database (the operating mode issue is getting fixed at the moment) - The first will be the Roller Coasters with only a few exceptions.  If not on this list (all these types of coasters on this list are not convertable for a real reason) - then it should be included in the database.  Read the notes to see if a secondary database for each roller coaster gets created in the process.

- Reverse Freefall roller coaster (can be converted into a Jet Pack booster coaster and vice versa)
- Reverser Roller Coaster
- Side Frction Roller Coaster (can be converted into any other type of coaster, but it cannot be converted back into a Side Friction due to the risk of the cars jumping the track)
- Steeple Chase (this however can be converted into a Soap Box derby Racers and Motocycle Chasers, and any other rides using the same track)
- Suspended Swinging Roller Coaster (also includes few other ride types that can be converted to back and forth and vice versa)
- Mini Suspended Roller Coaster (can be converted into a hoverboard coaster and a Mini Suspended Flying Coaster and vice versa)
- Air Powered Coaster (can be converted into a Boomerang Coaster and a Hod Rod roller coaster and vice versa)
- Multi-Dimension Roller Coaster
- Any Water roller coaster type (i.e. Water Coaster (the water coaster can be converted to a Trilobite ride) and Dinghy Slides)
- Any Inverted Coaster not otherwise mentioned on this list (The Inverted shuttle coaster can be converted into a Inverted Vertical Shuttle and the compact Inverted Coaster into an inverted roller coaster)
- Wild Mouse coasters (the Wooden Wild mouse types can convert between one and the other)
- Heartline Twister Coaster

There may be some I'm missing notes for (i.e. they are the same type of ride and create their own sub database)

Now with that, the remaining lists will deal with compatable sets of conversions of non-roller coaster rides.

- Rafts to Splash boats
- Log Flume or Crocodile Ride to Splash Boats
- Go Karts, Caveman Cars, and the 1920's Racers (all can convert within this bullet point)
- Log Flume to Crocodile Ride and vice versa
- Haunted Mansion Ride, Hovercars, Car ride, Vintage Cars, and Ghost Train all can be converted from one to another
- Elevator, Mineshaft, and Teleporter rides can be interchanged as well.

With that said, hopefully this helps give an idea on how to solve this issue.  If the track piece does not exist for a particular type, it will simply skip that track piece and move on to the next track piece and check again (obviously at the new location).

**Comment by jensj12** [comment]
You can change ride vehicles already to any other. The ones @Christipher mentioned are all just vehicle changes which are already available with the RCT1 ride selection option turned on. There is already a database with all available track pieces for each coaster.
The suggestion here is to change a virgina reel to go karts for example, or soap box derby racers to a wooden coaster (which would work perfectly fine in both cases).

A full corkscrew can be replaced with two sharp turns, though the clearances would change possibly causing normally invalid track. Just skipping non-available track pieces creating an unfinished coaster would be a safe option in any case.

**Comment by Patrik356b** [comment]
Most of the tracks i would like to convert is from a simple to a more complex variant, in most cases it´s from the Steel roller coaster to the corkscrew coaster. as far as i know the latter has all th track pieces of the former plus a few more.

**Comment by Christipher** [comment]
@TheExileFox The corkscrew coaster does not have any banked sloped curves.

**Comment by Patrik356b** [comment]
Ah, I see what you mean. I'm not using those.
