### ISSUE TITLE
Peep AI

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3943]
I think it's pretty much considered to be the biggest drawback to OpenRCT: the awful peep AI. Wouldn't it be a good idea to just go back to the superior original peep AI until all the issues with your AI are fixed? Especially since there doesn't seem to be any progress in this field.

**Comment by IntelOrca** [comment]
This isn't possible, there is nothing to back to other than the original vanilla code - and that won't work in the current state anymore as we have removed all hooks and integrated many variables.

**Comment by Liampie** [comment]
Well, shit! I don't really understand why you can't go back. I thought openRCT simply added things to the game rather than take things away... Do you know if anyone is working on fixing the peep AI? In my personal opinion it should be the #1 priority.

**Comment by Gymnasiast** [comment]
It doesn't have anything to do with taking away. It has actually more to do with adding things, and making sure the code stays readable and extendable. Apparently something broke in the refactoring of the peep AI.
We're far better off improving the AI anyway, since the original wasn't that stellar to begin with - a whole lot better than RCT1, but not exactly 'superior'. But at this point we're mostly concentrating on finishing the implementation. After that, we can concentrate on the bugs, including the peep AI.

**Comment by senner007** [comment]
So when will you get to the AI? In one year, two years?

**Comment by rkkoszewski** [comment]
Any chance to get some info about the difference between the vanilla AI and OpenRCT AI? What are the differences? Is it just related to path finding issues or general behaviour differences between both? Thanks.

**Comment by duncanspumpkin** [comment]
The only difference that should occur between the two is OpenRCT2 uses the map rather than the souvenir to look for further away rides. There should be no other differences. (Except there is possibly a bug that is causing the peeps to be slightly less efficient but I've never been able to find out if that is really true or not)

**Comment by Gymnasiast** [comment]
There are though. It's why I opened #2499.

**Comment by wolfreak99** [comment]
In all honesty, aside from a few staff members acting wonky (taking note that i spend more time in multiplayer mode than i do solo, and i haven't played played in a while, lately it's just been to test code) such as entertainers walking lost or backtracking alot on, say, wide paths (although this would be semi-intentional because they're mostly in an idle state and have no direct motive), the guest ai isn't **that** bad.. sure, they get lost a little more easily and complain about being lost, but alot of the time it can be fixed with just improving your path layouts. one solution i tend to use: go to the guest window and summarize them by thoughts, find the "I'm lost!" thought group and see the actions of them, if there is alot going to a particular ride, they might be stuck, randomly click through the people that are thinking "I'm lost!" and see if you can locate if any are in particularly crowded areas of people walking back and forth. That is the most common problem i notice. 

as far as bugs that were introduced by openrct2 (such as guets not acknowledging a line being full, or staff acting a little ditzy)., you will have to just be patient with the devs. Yes, the problems with the current ai state can be frustrating, and in times of frustration it's not hard to think it could be just thrown back from the default code, i have thought this myself before when dealing with guests not acknowledging full lines, so you're not the only one, but you just have to be patient and remember that in time, the code **will** get better. the main goal right now for the core dev team is to decompile the rest of the code (which considering they are now on rollercoaster tracks / painting tracks (from what i believe), etc, may be a bit of a process considering the amount of track rides), and then refactoring the code (refactoring meaning clean up the code and move it from a "giant functions wrote down following the process from the original assembly code"  state to a "code that is organized into more smaller dedicated methods that can be easily interpreted and modified more easily" state). Once everything is decompiled and cleaned up, it will be very easy to fix the guests ai, as well as improvement to it.

if you believe that the ai renders the game unplayable, you can always play default RCT2 instead, or go back in time a few months and find a version that doesn't have improved/extracted peep ai.  asking if it's going to be within a year or two is showing impatience, and saying that it should be number one priority is showing a self entitled mindset. to give you a clear idea, the core dev team consists of 4, maybe 5, people. for that small of a team, they have alot of stuff on their hands, but they have continued to show that they are determined on this project. this project has been in the works for a couple of years now, and are still the only ones to actgively work on the game where as many other attempts have failed or have not made that much success. you gotta show respect and patience. in the meantime, like i said, you can modify paths, or play vanilla rct2, go back to an older openrct2, or hell, even check out some of the other newer games coming out such as Parkitect or Planet Coaster.

**Comment by IntelOrca** [comment]
AI was improved recently.
