### ISSUE TITLE
Game frame drops to 7 when opening Music acknowledgements window

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3945]
**OS:** OS X
**Version:** 0.0.5
**Commit/Build:** d892f6b

Game frame drops to 7 when opening Music acknowledgements window. it happens only ttf language like Korean,Japanease.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. select korean
2. open Music acknowledgements window
3. game's frame drop to 7 with no reason

**Comment by Goddesen** [comment]
This is (probably) a result of every glyph being redrawn in [this function](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/music_credits.c#L139) several times per frame as the window is invalidated. I don't have the necessary insight to fix this quickly.

Maybe generate a texture or something and scroll the texture instead of redrawing? Or something?

**Comment by Nubbie** [comment]
#6647 related?

**Comment by AaronVanGeffen** [comment]
I can no longer reproduce a frame drop when the Music acknowledgements window is open.
