### ISSUE TITLE
Remove test mode from untestable rides

### ISSUE THREAD

**Issue by Niels-NTG** [OpenRCT2/OpenRCT2#4149]
This has been bothering me ever since RCT1. There are plenty of rides that have a test mode when it doesn't make sense they have one. It seems that currently all rides that require the input of peeps (any type of stall, Go-Karts, Spiral Slide, etc.) don't have a test mode. Rides that can operate autonomously, but can't be customised in any way that affects the _Measurements and test data_ (Haunted House, Pirate Ship, Twist, Merry-Go-Round, etc.) do have a test mode, but could do without.

I get that this seems like a very minor point, but implementing this could help improve the player experience just that little bit more.

**Comment by AaronVanGeffen** [comment]
While it doesn't affect gameplay in any real way, I don't see why you shouldn't be able to test the rides you mentioned. In a real park, such rides would be tested on occasion too, surely?

**Comment by Patrik356b** [comment]
Yes they would, but that is very different. Peeps are required to ride some rides for testing because they can not be tested otherwise. How would you test a gocart without anyone riding it?

**Comment by e-foley** [comment]
The only ride that has a test mode that shouldn't, in my opinion, is the Crooked House.  What is there to test?

I believe the other rides you mentioned should retain their test modes so that you can see the ratings impacts of the different settings (number of rotations, swings, etc.) without requiring riders to be subjected to them.  This is particularly useful for rides like the Top Spin where the nausea ratings are affected by ride settings.

I'd rather just keep the testing options the same as they are now, except maybe the Crooked House.

**Comment by Niels-NTG** [comment]
I suppose that makes sense @e-foley. The fact that I personally never change the settings on those rides doesn't mean they shouldn't have a test mode. Except Crooked House, Haunted House and Circus.

**Comment by janisozaur** [comment]
Before doing anything like that, such change should be consulted with NEDesigns guys.

@Liampie @GForceNE can we have your input?

**Comment by IntelOrca** [comment]
I don't personally see why we would want to change this or how it can be of any harm to anyone.

**Comment by Niels-NTG** [comment]
Yeah… Discussing it made me realise that this is just a non issue really.
