### ISSUE TITLE
Feature: Logging User Actions 

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#4160]
Last night on the Man of Teal server, I saw someone deleting rides, and immediately building scenery afterwards to avoid people detecting him.  Although I pointed it out and drove him off, it would be nice for server hosts and mods to have access to a log of user actions, to monitor users when they're away.

**Comment by joshbgosh10592** [comment]
This would be an awesome feature. It would be extremely helpful for mods, like you said.

**Comment by newton27** [comment]
This is the most needed feature for me as a game host of three servers.

**Comment by delebota** [comment]
Based this off the chat log code for the most part. It saves to /serverlogs instead of /chatlogs and the file has the server name prefixed. Only the host can enable and use server logging, it is hidden for clients like the known hosts option is.

Currently logging:
- [ ] Server Start
- [ ] Server Shutdown
- [ ] Player Join
- [ ] Player Leave
- [ ] Player kicked and by who
- [ ] Delete Ride
- [ ] Edit park properties
- [ ] Cheats and who used it
- [ ] Add Player group and by who
- [ ] Edit Player group permissions and by who
- [ ] Edit Player group name and by who
- [ ] Delete Player group and by who
- [ ] Set a player's group and by who
- [ ] Set default Player group and by who

Let me know what else we want to add. I was thinking pause, but I guess that is limited to the host so no point logging that.

**Comment by joshbgosh10592** [comment]
I'd also say Edit ride properties, and which ride.

**Comment by delebota** [comment]
I just added the code to log demolishing rides, but I didn't tag it correctly. You can see it here: https://github.com/delebota/OpenRCT2/commit/4285bc1c375ad2da61e19ae48da750392f000b24

Also I noticed if you start building a ride and cancel before you build anything it will send the demolish command, is there anyway to distinguish between construction and using the demolish button on a ride?
