### ISSUE TITLE
leading / trailing whitespace in player name should removed

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#4301]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** ae05e0f

Player name can't be duplicated in normal ways if player is registed to server(it will became `Player #2`) but this can be bypassed by adding space to end of player's name. this can be confusing since there's no way to distinguish `"Player"` and `"Player "`.

trailing whitespace should removed by client and server so there won't be any confusion.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Comment by marijnvdwerf** [comment]
What about leading whitespace? Or the different variants of spaces?

**Comment by Patrik356b** [comment]
Only visible characters should be allowed.

**Comment by Christipher** [comment]
Honestly, this could be fixed by adding character codes so that there can be no confusion in the future to a player's username

**Comment by marijnvdwerf** [comment]
And then there's `Ĳ (&#306;)` vs`IJ (&#073;&#074;)` (though cases like these are less of an issue when the sprite font is used)

**Comment by janisozaur** [comment]
Let's say we trim the whitespace. Where do we that? In client username selection? What if the key user has registered with his server of choice was that of a username with space? Should servers validate and enforce this? Since we expect clients to trim usernames, a hacked client allowing untrimmed usernames would be a dead giveaway of it being up to no good. Or should we just rename the user to a one with trimmed whitespace?

**Comment by IntelOrca** [comment]
I think servers use what ever user name is in the users.json, so you should be able to just trim it on the server on first adding a new user.

**Comment by Chaosmeister** [comment]
How should usernames that consist only of whitespaces be handled?

**Comment by Dracheron** [comment]
simple, if it's all whitespaces, it's invalid... (imagine trying to click
on to copy and paste or guess the length of the name should it be all
whitespaces)
