### ISSUE TITLE
Free exitement rating bonus

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#4313]
**OS:** Windows 10
**Version:** 0.0.5-develop
**Commit/Build:** d0399dd

Since #4291, the game allows having 'synchronise with adjacent station' turned on without having any other stations to sync with. This option however gives a free bonus to the exitement and intensity ratings (around .4 and .05 as far as I've tested).

Before #4291 the game simply didn't allow trains to depart when that option was turned on but there was nothing to sync with. IMO it just shouldn't give the rating bonus in that case, but still allow the train to depart.

**Steps to reproduce:**
1. Build a single rollercoaster
2. Switch 'synchronise with adjacent stations'
3. Watch the ratings change

**Comment by Christipher** [comment]
This does occur in the original game as well...

**Comment by IntelOrca** [comment]
@Christipher no

**Comment by YJSoft** [comment]
@Christipher Yes, they do. but ride will never depart because there's no ride to sync. That will make ride useless.

**Comment by Christipher** [comment]
In the original game the pre-done track "Raven Racer" can be used to prove this.

Since I can't have photo evidence, this can be done in the roller coaster editor, and you can do this yourself quite easily.  For both portions use the "Raven Racer" track to do this experiment.

See what it does unsynchronized.  You should have an excitement rating of around 6.85

then see what is does synchronized.  The excitement rating should become close to 7.40 (allowing room for error).

**Comment by jensj12** [comment]
That's normal and expected behaviour. The coaster is more exiting if the trains are forced to leave simultanously (if they do without that option, it's just a coincidence).

**Comment by zaxcav** [comment]
I did the coaster sync fixes in #4291, so this is my fault.
My apologies that it's taken so long to make an appearance here. I was on holiday for a couple weeks :-D
I'll admit, I did not realise there was a slight excitement rating bonus for sync-ed coasters.  I'm not familiar with the rating code, so two obvious options come to mind that I could do to fix this:
1. Where the rating bonus is added, check whether the ride has any adjacent stations.
2. Revert the change that permits a coaster without adjacent stations to depart when sync is checked, forcing the player to uncheck the sync option if they want the coaster to run.

Option 1 would be my preferred solution, since this adds lots of flexibility for syncing multi-station coasters (whether that be coasters with separate entry and exit stations or multi-station coasters syncing with other different coasters at different locations) without the need to use dummy stations where adjacent stations are otherwise missing.

This is a fairly minor issue (IMO), so I'll finish off what I'm working on at the moment and then take a look at this.
