### ISSUE TITLE
PLEASE integrate anti-trolling measures!

### ISSUE THREAD

**Issue by CoasterSparta** [OpenRCT2/OpenRCT2#4452]
Trolling has been going on for quite awhile across certain servers (Avilance, Mozar Community, WhiskeyStation, rct2online.net, etc.) and something needs to be done as soon as you guys can. We are sick of this.

**Here's a list of the thing's I've seen:**

Spamming in the chat

Logging in and out of the server in a repetitive fashion (thus crashing it)

Impersonation of player names

Bypassing permissions they don't have by using ones they own to their advantage (i.e. deleting coasters by omitting tracks using the "Build Ride" permission, spamming if they only have the "Chat Only" permission, etc.)

Circumventing bans by adding spaces to their name (thus clearing out the group category that was given to them)

**How to fix this:**

Spamming in the chat: Have an option where you can configure how many times a person can reply in a matter of time before they are either banned or a timer is placed on said user.

Logging in and out of servers: Remove the "X" at the right hand corner when you are at the "Authenticating..." window. -OR- Placing a restriction on how many times a person can log in before they have to try again in X amount of time (**May not be a recommended fix due to people having disconnection issues of their own**).

Impersonation of player names: Placing a custom tag next to the player's name that has a number and letter combination that is assigned by their IP address.

For example:

Player (4h6g)

Bypassing permissions: Adding a threshold to how many times a person can do certain actions (Build ride, pavement, chat, etc.) before they are kicked/prevented from doing that action for X amount of time. Making "Omit Tracks" a permission that exists (if possible).

Circumventing bans: Making IPs bannable and fixing the naming system so that trolls cannot bypass bans easily.

**AND one more thing:** Make an option to turn off chat reply/user login sounds. Gets annoying after a while.

P.S. Anyone (admins, moderators, players) can chip in on this commit and add ideas of their own. Feel free to add anything that is not here. You are more than welcome to do so. :)

**Comment by Christipher** [comment]
Better idea: for those known trolls, they should be given a red flag to the admin/moderators should they come on so that they get removed quicker.  Also, possibly during the implementation of the standalone build have it so that bans by ip address, name, and character code and place all of that information in a central database type of thing (repeat offenders can be dealt with permanently should that come, though the computer address should be used as the ban item over the ip address (since this is causing issues if ip address locations change), maybe even a ban by the email address as well (though as soon as duplicate accounts are discovered should be deleted as well).

**Comment by Margen67** [comment]
Fixing issue 2294 would help prevent trolls from crashing servers.


IP banning isn't reliable. The griefer could just reset their router and get a new IP to circumvent it.
PR 3155 is a better solution imo.

Also it's hard to moderate since you can only see a user's most recent action.
What would be better is a history tab where you can see all their actions.
PR 4273 should help with that.

**Comment by janisozaur** [comment]
@Margen67 please fix your comment so it is properly clickable.

**Comment by IntelOrca** [comment]
Could you upload the crash dumps?

**Comment by Nubbie** [comment]
It's really hard to stop trolling as there isn't that much you could do without altering big chunks and changing the core of the game- e.g. authentication system
