### ISSUE TITLE
Mechanics can't fix underground attractions.

### ISSUE THREAD

**Issue by kaitek666** [OpenRCT2/OpenRCT2#4630]
**OS:** Windows 10 Pro 64bit
**Version:** 0.0.5
**Commit/Build:** 89d672b

Mechanics have trouble accessing underground attractions. They just walk in circles above the exit and never go underground. In case I put a mechanic underground to solve the problem, he turns around, exits it and still goes in circles on surface.

Not Reproducible in RCT2 (vanilla)
Probably happens in multiplayer too

**Steps to reproduce:**
1. Build an attraction beneath the ground
2. Wait for it to break
3. Watch the mechanic (giving task to somebody else returns in same result)

**Save game:**
In this save file it happens to Launched Freefall 1.
http://www55.zippyshare.com/v/lDmktWNC/file.html

**Comment by janisozaur** [comment]
Please post your file here, not on external service.

**Comment by zaxcav** [comment]
In the savegame, the path leading underground is missing a piece (the last sloped piece), consequently Launched Free Fall 1 cannot be reached from above ground. In this case, the path above the ride is the closest they can get, so this is the expected behaviour.

Once the path is reconnected the mechanics have no trouble reaching Launched Free Fall 1.
Note that I tested with a build that includes the latest pathfinding fixes that are waiting to be merged -  it could be that the downloadable builds don't work quite as well.

**Comment by kaitek666** [comment]
@zaxcav Oh God, I'm such a mess, sorry for trouble - you are right. That's my fault, not a game bug.
I'm sorry, **I'm closing the issue**. Thanks!

**Comment by zaxcav** [comment]
@kaitek666 It's not always easy to see stuff underneath lots of other things, even with rotating the view and with the options for "See through" this and "Invisible" that (especially when that would also hide what you are trying to see).
I bulldozed quite a a few rides and paths just so I could get a clear look at the underground pathing.
Anyway, glad I could help.
