### ISSUE TITLE
"object file" warning/error at particular park load

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#4703]
**vista 32-bit**
**0.0.5 1eb91cb** 

When opening a particular park of mine in orct2 i notice the message: "WARNING[src\object.c:284 <object_load_packed>]: Checksum mismatch from packed object: RIDE9MKY".  This message is in the black, square, ("dos" window") when starting game. Also when I attempt to open this same park in vanilla i get the message "unable to open file... missing object data id: "ride9mky / 0055f509f5122d9a". I have tried copying my object files from orct2 object folder to vanilla rct2 object folder, but the park still does not open in vanilla.

- [ n/a]
- [n/a ] Multiplayer?

**Steps to reproduce:**
1. shown above
2. 

i do not have zipping software

**Comment by Charlieep** [comment]
Broxzier explained it to me this way. It means that there is an object with an incorrect checksum. This means that the file you have, "RIDE9MKY", in your RCT ObjData folder, is invalid, but since you have the option to allow loading objects with an incorrect checksum enabled you can load them anyway.
 
This error message means the save file contains a packed object whose checksum does not match the contents of the file. In theory, this indicates that the object has been corrupted, and the game stops loading of that object.

In practice, there is usually nothing wrong with the object, it just has the wrong checksum. This is because some custom objects include nonzero bytes in locations that are zeroed by the loader - these bytes are zeroed when the object is loaded, but the checksum is not updated. When the object is packed into the save file, it has the wrong checksum. When you reopen the park, you see this message. 
The object and park will run just fine.

**Comment by jamtraks** [comment]
alright, i don't completely understand but i'll try that. I was not having this issue for a week until today. I hope i can find the object and i hope this works. thanks

**Comment by jamtraks** [comment]
sometimes i notice i have certain problems that go away after a new version of orct2 dowmloads but i'll see what happens.

**Comment by mrtnptrs** [comment]
Please stop with posting multiple messages in a row, just edit your old one.... my mail gets spammed now by your messages.
