### ISSUE TITLE
Can't hire staffs bug

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#4745]
**OS: Windows 7**
**Version: 0.0.5-14** [e.g. 0.0.5]
**Commit/Build: a7cd10a** [e.g. 426e106]

Hey. When I hired new staffs, the message pop-ups saying "Can't hire new staffs". This is random after I hired some staffs. Can anyone please fix this bug?

- [ ] Reproducible in RCT2 (vanilla)?
- [ x] Multiplayer?

**Steps to reproduce:**
1. Hire some staffs
2.  Wait until you get the message saying that you can't hire the staff

**Comment by zsilencer** [comment]
For me it just pops up that message but still hires the staff.  Message only appears if you didn't place the staff you just hired.  It is because the new game command to place the staff doesn't allow you to pick up another one if you are already placing one, but it doesn't set the error string so you see the last error caption set.

**Comment by janisozaur** [comment]
Hiring staff has been supported in multiplayer for a quite a while now
