### ISSUE TITLE
There's no way to see owned build rights after #4701

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenRCT2#4748]
After #4701, if there's no build rights to buy, button just disabled. which makes harder to see where i own build rights.

add option see owned build rights(like see path height) would solve this problem easily, but i want to hear opinions.

**Comment by Gymnasiast** [comment]
A possible solution:
Always enable the button in the park window, and show all bought land rights when the Land Rights window is open.

**Comment by RollingStar** [comment]
The reason I made #4559 was to have a way for the user to know that there was no more land for sale. I forgot that construction rights aren't normally shown outside of that buy window. Enabling the window always is probably a good idea, but ideally, there's still a visual and tooltip indicator that there's nothing left to buy.

A "show land rights" option like @fromthere says would also work.

**Comment by Gymnasiast** [comment]
Sure, but you can still keep both buttons _in_ the Land Rights window disabled. I'm just talking about the button in the Park window.

**Comment by RollingStar** [comment]
That's fine. I would prefer if there is still some visual indicator that there's no more land rights to buy in that window. (It can still be clickable.)

**Comment by Androgeos** [comment]
This might either need a better look at or a complete reversion to default RCT1/RCT2 behaviour because, with the land purchase rights button currently disabled on the Purchase land tool, you can't see what land rights you have, leading to apparent oddities such as this:

![katie s dreamland 2017-01-30 16-26-33](https://cloud.githubusercontent.com/assets/18898491/22416425/7c17260e-e709-11e6-8a50-45d18435965a.png)

To add on to Gymnasiast's first reply, if the Purchase land tool is to be made available at all times, it should at least show **both** purchased land **and** land with purchased construction rights.

**Comment by Gymnasiast** [comment]
I plan the following changes:
- The button in the park window will always be enabled
- Opening the Land Rights window will immediately show land rights
