### ISSUE TITLE
Placing large scenery objects can crash the game if the object limit is too close to the max

### ISSUE THREAD

**Issue by YoloSweggLord** [OpenRCT2/OpenRCT2#4777]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** a934590

**Steps to reproduce:**
1. Load the BakerLake.sv6 file (I did not make this park, all credit goes to Coupon) 
2. Attempt to place the RamSam12 - 3 Flatride Arms - MT large scenery object (in the Miscellaneous Objects tab)
3. As soon as the game tries to render the ghost object, the game gives an assertion failed message.
**To my best guess,** this is because the game is too close to the object limit (this can be discovered by placing several small scenery obejcts in the map. In my experience it takes about 13 quarter tile scenery objects to fill up the remaining landscape data area). The game isn't yet at the object limit, so the game attempts to render the object, but it doesn't check of the amount of space left against the amount of space that object takes up.

**Save game:**
[BakerLake.zip](https://github.com/OpenRCT2/OpenRCT2/files/579537/BakerLake.zip)

**Comment by duncanspumpkin** [comment]
Crash is caused by too many elements being allocated.

**Comment by duncanspumpkin** [comment]
This is going to be annoying to fix. When a new multi tile element is being placed it checks it has enough spare tiles for at least 1 new tile element. If it has no spare it errors out. 

In this map though there is 1 free map element but not enough map elements for the full multi tile element. Due to the way map elements are allocated there is no count we can just check to make sure there is more than 1 free. We could make it error out of the game command when it runs out of tiles but then we are left with a corrupted multi tile element that cannot be removed. There are two solutions to fix this. Reverse the allocations when we run out of tiles or keep a list of all of the allocations in the current game command and undo them when it errors. As stated there is no easy way to check that there is enough space before hand see `sub_68B044()` as this function is the pre check function.

**Comment by IntelOrca** [comment]
I think there is a count somewhere for the number of free elements.

**Comment by duncanspumpkin** [comment]
I'm going to modify `sub_68B044` to take a num_elements argument so that you can check for enough free elements.
