### ISSUE TITLE
Can't run the game on mac!

### ISSUE THREAD

**Issue by Juloow** [OpenRCT2/OpenRCT2#4844]
Hello,

I can't run the game on my Mac Snow Leopard 10.6.8 because the application that I downloaded on OpenRCT2 needs Lion 10.7. 

My question is simple, is there a way to still to open it anyway? I tried to play OpenRCT2 with Wine but I can only play on the stable version, but not in multiplayer. 

I broke my PC and now I'm on mac but if I can't play OpenRCT2 I will die. Help me, thanks.

**Comment by LRFLEW** [comment]
Is there a reason you can't update to 10.7 or newer?

The project doesn't support anything less than 10.7 for some technical reasons (a number of language-level features were added in 10.7, including C++11 runtime support and some updated Objective-C paradigms that we use), so it would not be simple to get it to work on 10.6.8. Wine hasn't been officially supported with the project since the native mac builds have been supported, so we can't guarantee you can get that working either (though it should be possible).

**Comment by Juloow** [comment]
I think I can uptade to 10.7.5 (Lion) but I have to buy it 20€ on apple website. It's a rip-off! :(

**Comment by janisozaur** [comment]
@Juloow you're welcome to backport OpenRCT2 to your system.

**Comment by Juloow** [comment]
How can I do that? Sorry, I'm noob.

**Comment by janisozaur** [comment]
You can either start by

a) compiling a recent `libc++`/`libstdc++`/some other C++11 library, then compiling OpenRCT2 against that,
b) porting all C++11 code back to C++03 and compiling against your system's C++ library.

**Comment by Juloow** [comment]
:' )

**Comment by LRFLEW** [comment]
What model of mac are you using? All version of Mac OS 10.9 and higher are all free, so if your system supports that, it should be a free upgrade.

**Comment by Gymnasiast** [comment]
Closing this as OP has refused to answer our questions and has opened another issue.
