### ISSUE TITLE
Prevent saving/usage of "modded" track designs

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#488]
In many .SV6 files you can find online, they contain rides that are considered "Modded"; Either they use an otherwise invalid vehicle type, or they have invisible tracks or combine two different track styles (like a Looping Roller Coaster with Wooden Roller Coaster tracks). Attempting to save or use these kind of rides as a track design should display a "Cannot save/use this track design... this design appears to be abnormal!"

**Comment by Patrik356b** [comment]
This is not an issue, it's a feature.

**Comment by Gymnasiast** [comment]
This will not be implemented. Reasons for this (some already mentioned by others):
- Preventing saving of design with non-standard trains and things like that goes straight against the goal of OpenRCT2 of allowing a bit more freedom and introducing more sandbox-like features.
- The incomplete circuit that merged rides have is nearly impossible to tell apart from the incomplete circuit that launched rides have, other than by actually running a train over it. (It is this property that makes merging possible in the first place.)
- In preventing saving unusable designs it would, because of the above reason, be either too restrictive (preventing saving of Shuttle Loop-like design) or barely effective.
All in all, it would introduce unnecessary complexity for something that is too restrictive and not useful. Because of that, this issue will be closed.
