### ISSUE TITLE
Combine Junior Roller Coaster and Mini Roller Coaster together.

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#4915]
I would like to see a option in the options menu to combine the Junior Coaster and the Mini Roller Coaster together. So that it will be like in RCT1.

**Comment by PFCKrutonium** [comment]
iirc, this is already a thing via the option to switch back to RCT1 style track/car sorting

**Comment by Horsti12** [comment]
![](http://image.prntscr.com/image/bddfadd8189e4ea38588db166703a83d.jpeg)
Not this isn't possible yet, because the mini roller coaster have a little bit different track design. And earlier the junior roller coaster haven't steep slopes. But since the Junior Roller Coaster have steep slopes it would be great to finally combine both roller coasters together. As I said only as a option because some people maybe liked the mini roller coaster as a ride itself.

**Comment by marijnvdwerf** [comment]
The Junior RC and Mini RC use a different track design. How would you even expect this to work?

**Comment by AaronVanGeffen** [comment]
What would this achieve? If you don't want to have Mini RCs in your park, for old time's sake: you can remove them through the object selection screen, if you must.

**Comment by X123M3-256** [comment]
> Not this isn't possible yet, because the mini roller coaster have a little bit different track design

Which is why they shouldn't be combined. If you're going to combine these two you might as well combine everything into one "Roller Coaster" icon. These rides have little in common besides being non-inverting steel coasters. The Junior coaster is a Zierer. The Mini coaster is a Schwarzkopf. The track types look similar but they're not interchangeable, nor do they have the same track pieces (banked, curved drops are not permitted on the Junior, but they are on the mini coaster). 

How would you propose this function? When you click on the combined junior/mini coaster icon, which track type would you get? Should it change when you change the train type? If you want this so you can have the junior coaster trains on mini coaster track, or vice-versa, could you not use the "show all vehicle types" cheat instead?

**Comment by Horsti12** [comment]
I have to say that I changed my opinion a little bit, because that both rides aren't so similar as I thought. So I will close this for now.
