### ISSUE TITLE
Giant screenshot cut off at bottom and top

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#4927]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** c3035b7

When taking a giant screenshot, the top and bottom are cut off. 

**Steps to reproduce:**
1. Open any park and take a giant screenshot from the option under the save menu
2. Observe how the top and bottom are missing

**Screenshots / Video:**
![ccc2 2016-12-26 23-28-44](https://cloud.githubusercontent.com/assets/9705046/21499857/ce9a1d2c-cc39-11e6-96f0-2c381a22fb7b.png)

**Comment by funzinnu** [comment]
It happens especially on small maps.

**Comment by Liampie** [comment]
In my experience, it happens just as often on big maps. It seems OpenRCT2 is ignoring the height of the land and scenery in the top corner, for starters. It's cutting off the screenshot at a certain height, maybe the default land level? Instead of taking into account what has been built in that corner. Doesn't explain missing stuff at the bottom though.

If there's no precise fix, I would really appreciate it if the giant screenshot function would add some margins at the top and bottom. Especially at the top, like at least 500 pixels to be save. It would be a big time saver for me. :)

**Comment by janisozaur** [comment]
You can pass image size manually to the screenshot command.

**Comment by Liampie** [comment]
Where and how can I do that?

![menu](https://user-images.githubusercontent.com/19242088/41527953-fa697a36-72e8-11e8-8b2c-96b8cf0ac677.png)

**Comment by janisozaur** [comment]
[`openrct2 screenshot <file> <output_image> <width> <height> [<x> <y> <zoom> <rotation>]`](https://github.com/OpenRCT2/OpenRCT2/blob/0cf256ac9e31292e76bf35fbd0c1455d90d21680/src/openrct2/cmdline/ScreenshotCommands.cpp#L35)

**Comment by Broxzier** [comment]
You have to run that command from command prompt or powershell, not in-game. For the x and y coordinates you can use 'c' to center it, otherwise it uses the saved game's camera location.

**Comment by Liampie** [comment]
I'd have to guess what to enter for each of those things, including the size of the final image in pixels. That is not going to save time nor is it a fix

**Comment by Broxzier** [comment]
You can just enter very large numbers and then cut out the part you need with an image editor.

**Comment by saxman1089** [comment]
Requiring users (the majority of which have no coding experience) to open the game through a command prompt just to take a correct screenshot is crazy.

If this is a workaround and someone will be able to fix this at some point, state that. Right now it seems like you're saying "Oh, there's a way to do this already, just do it that way," instead of "We're gonna fix this and it should be fixed, but here's a way you can do it in the meantime."

**Comment by Broxzier** [comment]
@saxman1089 We're not saying that using the command is a fix. To help Liampie save some time, we're just suggesting another way of taking screenshots in the meantime. This will be fixed at some point. If it were impossible the issue should have been closed.

**Comment by saxman1089** [comment]
Thanks for clarifying!

**Comment by Patrik356b** [comment]
does the command work in the ingame console though?

**Comment by AaronVanGeffen** [comment]
> does the command work in the ingame console though?

No, it's a shell command.

**Comment by Richard-L** [comment]
With the time that passed since this bug was reported, do we now understand what causes it?

**Comment by Broxzier** [comment]
It's probably the calculations for the viewport dimensions. For the bottom it should be simple, but for the top figuring out the exact height needed to get everything in will be tricky.

**Comment by Patrik356b** [comment]
> 
> 
> > does the command work in the ingame console though?
> 
> No, it's a shell command.

Would be nice to have it working in the console as well. but that's just my thought

**Comment by janisozaur** [comment]
As long as it causes the path to sv6 to be provided at the expected position.
