### ISSUE TITLE
Mechanics don't repair rides even if they are near the entrance

### ISSUE THREAD

**Issue by pawelkondraciuk** [OpenRCT2/OpenRCT2#4994]
**OS:** OSX 10.11.6
**Version:** 0.0.6
**Commit/Build:** f201a8b

Mechanics are called to the broken ride and they are going there but they just loop near the exit. It happened several times on different maps.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load save
2. Click on Magic Carpet 1
3. Go to Maintenance Options
4. Locate Mechanic 5 - he is near entrance and just don't get in.

**Save game:**
[Mechanic_issue.zip](https://github.com/OpenRCT2/OpenRCT2/files/687669/Mechanic_issue.zip)

**Comment by zaxcav** [comment]
This is not a bug.
Mechanic 5 **is not** responding to that breakdown.  He just happens to be walking up and down in those path tiles outside the ride exit (he's trapped in this corner of his patrol area and cannot get out).
Mechanic 4 **is** responding to the breakdown. He's a naughty mechanic that has escaped his patrol zone and gotten pretty far away, but he's on the way.

Mechanics used to be free to wander out of their patrol zone when heading to a ride (this is how vanilla RCT2 works).
In combination with pathfinding bugs, mechanics could wander far away their patrol zones.
This was corrected recently, so Mechanics will not wander out of their patrol areas anymore when heading to a ride.

I **am** observing some bizarre behaviour from Mechanic 4 as he approaches the last corner though - he leaves the path and walks through the fence into the queue line (where he then gets trapped in his patrol area until you let him out).
A mechanic should never leave the path, so I'll have to see what's causing this. Interestingly on one reload he did not do this... which makes me suspect that this tile (or the next) has an invalid wide flag (i.e. the incremental wide flag updates paused at this part of the map) exactly when the mechanic arrives there.

**Comment by zaxcav** [comment]
I've done an initial investigation into what is going on with the behaviour of Mechanic 4.
It is NOT the heuristic search that is directing him to leave the path.
In this case the problem is because the mechanic is outside but directly next to his patrol area but without a connecting path edge into the patrol area for that tile. Under these conditions mechanic_path_finding falls back to mechanic_surface_finding and the heuristic search is not called. I think this needs a broader discussion on how it should be resolved so I'll create a specific issue for this.

This problem described in this issue is not a bug, as explained above, so this issue should be closed.
