### ISSUE TITLE
Ability to remove or make default flat ride bases invisible

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#5146]
This is a fairly common practice in higher level realism parks, and the tile inspector isn't quite able to pull it off. It was possible with 8cars' map object manipulation.

When using the tile inspector technique, large chunks of the ride model also disappear at certain angles.

Example: Top spin in Lenox Mall
http://www.nedesigns.com/park/580/map/37/lenox-mall/

**Comment by Nubbie** [comment]
It's a large screenshot, here is a cropped out version off it
The top-spin in question have a cheekerboard pattern with the base removed in "8cars"
![screenshot](https://cloud.githubusercontent.com/assets/17282384/22459148/be7b950c-e79f-11e6-9933-b447b9d4fac8.png)

**Comment by IntelOrca** [comment]
> It was possible with 8cars' map object manipulation.

How? Was the ride lowered below the ground?

This can't be done by making the track elements invisible because the base, fence and structure is all drawn together. To do this properly we would need to allow more style customisations on the ride and that would require a new save format to store those extra customisations.

**Comment by janisozaur** [comment]
![lenox mall 2017-01-31 11-28-51](https://cloud.githubusercontent.com/assets/550290/22461444/98e482fe-e7a9-11e6-9c86-a81548d7580e.png)

**Comment by IntelOrca** [comment]
@ArcticX9 you need to change the base height for each track element one unit lower than the base height of the surface element.
