### ISSUE TITLE
Cannot build Wild Mouse - Flying Dutchman Gold Mine

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5190]
**OS:** Arch Linux
**Version:** 0.0.7
**Commit/Build:** b21378b7f53e5ab0f5a21d9e82c3d52d1b1b147c

I cannot build the Wild Mouse design "Flying Dutchman Gold Mine". It has no preview and when I try to place it somewhere, it says "Too steep for lift hill".

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![flyingdutchmangoldmine1](https://cloud.githubusercontent.com/assets/8963459/22711352/28b8ead2-ed81-11e6-8824-b544fb2eaf1a.png)
![flyingdutchmangoldmine2](https://cloud.githubusercontent.com/assets/8963459/22711351/28b878c2-ed81-11e6-8b9b-5a01a0c62865.png)

**Comment by IntelOrca** [comment]
Does it work if you disable support limits?

**Comment by ccoors** [comment]
No.

Regarding the error message - the Wild Mouse does have the steep lift hills and on other designs it works just fine.

**Comment by IntelOrca** [comment]
Do you have `Select rides by track type (like in RCT1)` enabled?

**Comment by ccoors** [comment]
No. But if I enable it, it works.

**Comment by rwjuk** [comment]
I am able to build that track (both in the designer and in a park - I tried SF Great Adventure) using the latest build (ccce7b0). Can you update and try to replicate the bug again?

**Comment by ccoors** [comment]
No, still not working.

**Comment by ccoors** [comment]
Oh. It just doesn't work in that scenario? Here it is.

[Simple Sandbox.zip](https://github.com/OpenRCT2/OpenRCT2/files/1042824/Simple.Sandbox.zip)

**Comment by LightningDragon10065** [comment]
I realize this is a few months old, but I too am having this issue; it occurs with any of the saved designs I have, and the only way to circumvent it is to turn on the cheat to enable lift hills on any track piece.

Just loaded up and tested the Fungicide design; it will not build in my Forest Frontiers save, but it will build in the track designer.
For whatever reason, the steep lift hill is available in the track designer, but not in my FF save.
If it makes any difference, the Forest Frontiers was loaded from the original RCT1 scenario file.
Possibly affects other scenarios, as well, but this was the only one I tested.

**Comment by Keatzee** [comment]
After a bit of investigating, I believe some of the vehicle types for Wild Mouse are broken somehow. I'm not sure how the game selects what vehicle types to use by default, but the scenarios that use the Spinning Wild Mouse won't let you build them. Some examples are Forest Frontiers (RCT1) and Crazy Castle (RCT2). But the scenarios that use the regular Mouse Cars or Mine Cars let you build them just fine.

Here's how you can tell from a glance at the preview:

![forest frontiers 2017-08-20 12-33-54](https://user-images.githubusercontent.com/18078273/29496669-8f0dc016-85a5-11e7-963d-4a4c508a6c85.png)

It gets a little weirder. I built Flying Dutchman Gold Mine on a scenario that would let me, but when I switch vehicle types, Mine and Mouse Cars stop working entirely:

![alpine adventures 2017-08-20 12-49-17](https://user-images.githubusercontent.com/18078273/29496750-fd29c738-85a6-11e7-9e91-f694a48e2444.png)

And suddenly, Spinning Mouse Cars work fine:

![alpine adventures 2017-08-20 12-54-20](https://user-images.githubusercontent.com/18078273/29496738-e1beb38c-85a6-11e7-9195-099e82b87a5c.png)

I'm not entirely familiar with the mechanics behind switching track types and that sort of thing, but I hope this helps fix the problem regardless.

**Comment by Gymnasiast** [comment]
When in 'select by track type' mode, the game will use a preferential order of vehicles. The Mine cars take precedence over the Spinning cars, so if the preview shows Spinning cars, it means that Mine cars and Mouse cars are not available.

If they're not, the Spinning cars are selected, but since they are in the same ride group (we're still talking about 'select by track type' mode) it will still show all track designs. Spinning Cars cannot handle steep inclines, which is where the error message comes from.

There are already two bugs here. One of them is that the Spinning cars should not be in the same ride group as the Mouse and Mine cars, as the former cannot handle steep inclines (ride groups are group of vehicles using the same type of track and capable of the same track elements), which the latter two can.

The other bug is that, in 'select by track type' mode, the game should not check the vehicle itself, but the ride group.

There also seems to be a third one, judging from @Keatzee 's screenshot. Keatzee, could you provide detailed steps to reproduce the empty window?

**Comment by Keatzee** [comment]
Here's what I did:
1. Open Alpine Adventures
2. Set ignore research status
3. Build a Flying Dutchman Gold Mine
4. Click on it and go into the Vehicle Details tab
5. Switch from Mine Cars to Spinning Wild Mouse, then switch back to Mine Cars

**Comment by Gymnasiast** [comment]
Both the problem @ccoors had and the problem @Keatzee described have now been solved.
