### ISSUE TITLE
Cheat: Manually Change Ride Stats

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5191]
A useful cheat, would be a way to manually change ride stats like you can in son of beast.

**Comment by IntelOrca** [comment]
There is already a cheat to have guests ignore intensity. I don't see why else you would want to change ratings.

**Comment by xp4xbox** [comment]
This was a quote from NE:

"I need to change stats for my Mario Kart park. When I make the Kart track invisible with Crooked House it drastically drops the stats to the Crooked House numbers. It's drops from an 8+ excitement rating to only 2. So I'll need to change the stats for at least 16 different rides to get peeps to ride them. "

**Comment by Lastorder-DC** [comment]
![image](https://cloud.githubusercontent.com/assets/18280396/22722199/bead94d0-edf8-11e6-9f93-07e1b140ac2e.png)
Inserting corrupt map element with tile inspector also hides track.

**Comment by duncanspumpkin** [comment]
Either way it's annoying to change because stats are constantly recalculated. You would need to add an extra flag to rides to prevent recalculating rides and that would mean changing the save format. It would be incompatible with vanilla and should probably be left for after new save format.

**Comment by IntelOrca** [comment]
@xp4xbox Then don't make it a crooked house. Track can be made invisible like how @Lastorder-DC described.

**Comment by WhenPenguinsAttack** [comment]
@IntelOrca  Is it possible to add one-click invisibility cheats without a new file format (perhaps by exploiting the crooked house process)?

**Comment by WhenPenguinsAttack** [comment]
@janisozaur  IntelOrca was talking about making the process for invisible rides easier, and I had a question related to that.

**Comment by IntelOrca** [comment]
@WhenPenguinsAttack anything is possible, someone might be able to add multi-tile editing support to the tile inspector.

**Comment by WhenPenguinsAttack** [comment]
@IntelOrca  Thanks!  :)

**Comment by tcek** [comment]
I feel this would come in handy to change the excitement level stats, I make great rides but even with guests ignore intensity on, the excitement level is always so low just because the ride is extreme. Freezing the stats you put in manually would be great.

**Comment by Liampie** [comment]
@IntelOrca I don't want to come off as a dick, but it's kinda annoying that the OpenRCT developers team is constantly asking us to contribute problems, ideas and other suggestions (which I regularly do, gladly) only to have you respond with "why would you want to do that" on multiple occasions. I've been playing the game for almost two decades, I've been at NE for half that time. You know coding, and I know the way people play RCT. This function would be really really useful for many many purposes, trust me on that.

By the way, the corrept tile trick is not useful at all in this instance. Good luck with seperately inserting a thousand corrupt tiles instead of changing a ride's track type with just one or two clicks. To each his own.

**Comment by Nubbie** [comment]
@Liampie 
The thing is, it's a suggestion for the game, a reason to the suggestion would be good.
If all suggestions would be implemented - the game would look extremely messy and confusing

**Comment by ArcticX9** [comment]
I think this suggestion would be useful.

**Comment by Liampie** [comment]
Being able to manipulate ratings is good for plenty of reasons and probably more reasons than I could ever list since the game's possibilities (should) exceed any individual's creativity. Especially the creativity of those who have never actually played the game, no offense. Here are a couple:
- Generating ratings for rides that otherwise don't get them
- Making otherwise well functioning rides less nauseating
- Making rides with low excitement ratings more exciting and thus more popular
- Making rides that are disproportionally popular, thereby completely disrupting the peep distribution throughout the whole map, less exciting/popular
- Making otherwise well functioning rides less intense, permanently, without the current cheat which is only a cheap bandaid you have to re-apply every time you open the game
- Making rides super intense if you don't want peeps to ride them

This all sounds pretty specific and oriented at the NE-crowd, but I guarantee you that even the larger group of casual players will have fun with and will find uses for manipulatable ratings. In my eyes it's the most obvious function to add that is not already in OpenRCT.

**Comment by duncanspumpkin** [comment]
@Liampie either way its not going to be done until we move to a new save format.

**Comment by Liampie** [comment]
Out of curiousity, how come it was possible to manipulate ratings with trainers but OpenRCT can't do it?

**Comment by duncanspumpkin** [comment]
You can manipulate the ratings but they wont save. It doesnt stop the ride from recalculating them later on. If you just wanted to manipulate the ratings for first load of a park then yeah that could be done but its also not very useful.

**Comment by IntelOrca** [comment]
@Liampie I would put it under the same category as displaying 1000 guests in the park when you only have 10. Pretending that a roller coaster has a high excitement and low nausea when in fact it does not - it would discourage the challenge of building good roller coasters.

If you think the ratings are not well calculated for a particular ride then the calculation algorithm can be tweaked instead.

If you want want guests to not take ratings into consideration then we have a cheat for that. Its an example where you don't actually want to modify the ratings but achieve something else in which case there should be a tool for that specific purpose.

> By the way, the corrept tile trick is not useful at all in this instance. Good luck with seperately inserting a thousand corrupt tiles instead of changing a ride's track type with just one or two clicks. To each his own.

My plan is to add a new attribute to the track element where the track type is specified - similar to colour schemes to avoid creating extra rides to achieve so. And the corrupt tile is only a hack until we can had a new visibility attribute to the tile. Like @duncanspumpkin said - we are still constrained by the file format.

**Comment by Gammadivided** [comment]
I'm sorry, but that logic really doesn't apply. Not everyone plays for "the challenge of building good coasters", especially when the ratings system is so flawed. Modifying ride ratings isn't useful for bragging rights, it's useful for making peeps ride rides with low excitement, for which the "guests ignore intensities" cheat doesn't work. I really appreciate what you guys are doing with OpenRCT2, but going only by scenario players' logic limits what you can do with the game.

**Comment by Liampie** [comment]
@duncanspumpkin You can make manipulated ratings permanent through exploiting the 'ratings queue': https://github.com/OpenRCT2/OpenRCT2/issues/5257 (read my post there)

@IntelOrca "it would discourage the challenge of building good roller coasters." --> that's a very silly thing to say, if that were true you might as well remove the whole cheats menu in OpenRCT. Peep trams, sunny weather, mowed grass, adding money, all of it takes away the challenge of building functional parks. >if you choose to enable these functions<. Why is tweaking the game's algorithms to suit an individual ride (another ride may need a different algorhitm) better than allowing the user the flexibility to do whatever he wants? I would not know where to begin changing the calculation algorithm. I'd have to read books, study coding, and study OpenRCT's code before I'd be able to modify my ride to whatever I want it to be. And in the same amount of time my hair will be grey and I could've rebuilt the entire park in ClosedRCT with my preferred ratings a hundred times. OpenRCT is lagging behind in this regard.

"My plan is to add a new attribute to the track element where the track type is specified - similar to colour schemes to avoid creating extra rides to achieve multi-track type rides. The corrupt tile is only a hack until we can had a new visibility attribute to the tile. Like @duncanspumpkin said - we are still constrained by the file format.'"

"That sounds nice, but wouldn't that also mean that we wouldn't be able to change an entire ride's track type anymore? That would be a major handicap in my opinion. Say I want to build a ride with invisible track... I wouldn't even be able to see what I'm doing.

**Comment by duncanspumpkin** [comment]
@Liampie I'm sure when the time comes to make invisible track it will be more like colouring the track.

**Comment by IntelOrca** [comment]
> that's a very silly thing to say, if that were true you might as well remove the whole cheats menu in OpenRCT

I think cheats should only be available in sandbox mode. I think cheats are abused too much and make the game look like a joke, particularly when you see YouTube videos where players are just setting all their coasters to extreme ridiculous speeds.

> but wouldn't that also mean that we wouldn't be able to change an entire ride's track type anymore?

No you would still be able to do that.

**Comment by Liampie** [comment]
@IntelOrca "We want to avoid using exploits and instead add proper functionality to achieve such things. The more exploits that get used, the harder it is to add compatibility for old parks when we change the format."

If you're disablig exploits that old parks use, how are old parks benifiting from that? It doesn't sound like you want proper functionality, it sounds like you want to take away a lot of flexibilit because in your opinion there is only one way the game should be played. As is evidenced by the following quote:

"I think cheats should only be available in sandbox mode. I think cheats are abused too much and make the game look like a joke, particularly when you see YouTube videos where players are just setting all their coasters to extreme ridiculous speeds."

So you're a developer with a personal agenda 😀 I'm not sure what you want here. If it's just a matter of turning sandbox mode on or of off, do you really think it will change the way people play the game? 

You're talking in circles now, anyway. First you said you think manually changing ride stats shouldn't be in OpenRCT. Then I compared it to existing implemented cheats, and now it appears you are okay with that if it's something you can seperately enable or disable. But this ratings thing was literally proposed as a cheat, so why the distinction? And the cheats window is already disabled by default, so whay difference would the sandbox mode make in this case?

**Comment by IntelOrca** [comment]
@Liampie I want things to be done properly, in a non-hacky way. Corrupt elements is a hacky way of making things invisible. Adding a flag to the map element structure for visibility is reliable and maintainable.

> If it's just a matter of turning sandbox mode on or of off, do you really think it will change the way people play the game?

Yes. It distinguishes playing the game properly without temptation of using cheats and playing the game as a sandbox.

> Then I compared it to existing implemented cheats, and now it appears you are okay with that if it's something you can seperately enable or disable.

My argument is probably that most of the cheats can be done legitimately. For example repairing vandalism can be done by replacing all the benches etc. Changing ratings can't without editing the layout or surroundings.

**Comment by Gammadivided** [comment]
>My argument is probably that most of the cheats can be done legitimately. For example repairing vandalism can be done by replacing all the benches etc. Changing ratings can't without editing the layout or surroundings of said ride.

Why are cheats so taboo anyway? For me, they represent a way of pushing the game to the max to create stuff you wouldn't be able to without them.

**Comment by IntelOrca** [comment]
@Gammadivided I think they are too often abused. They make the game look silly.

**Comment by Gammadivided** [comment]
@IntelOrca While on the one hand, it can look silly (500mph coasters and stuff), on the other hand, they can look amazing (http://www.nedesigns.com/park/3737/nes-mirage-islands/). And even if they can be silly on scenario play, I'd just let people have fun.

**Comment by Liampie** [comment]
People will find ways to make any game look silly. Especially in games like this, where messing around is at least half of the appeal. Would you rather have a more serious game that is less appealing and popular? Embrace the way the game is played, don't try to surpress some aspects in favour of others purely because of a personal preference...

**Comment by Nubbie** [comment]
We already have many silly cheats in-game
Don't understand the appeal of having something temporary that won't save the score in the long run (as I understand it)
Anyways, check out #5259 which should close this issue

**Comment by wolfreak99** [comment]
As far as invisible tracks go, i have a proposal..

What if, under the ride theming tab, there were two buttons.
"Hide all track pieces" and "Show all track pieces", that allowed a user to automatically insert a corrupt element below each track element piece. it could use the tile inspectors game commands that way it could be multiplayer compatible. This would in essense, allow a user to paint the entire track visible/invisible at once, while still being able to go through the tile inspector to make specific portions visible/invisible.

The reason I suggest this over being able to paint a track invisible, is (at least right now) it may be a bit difficult to make the game paint an invisible piece a different color. Currently, if you place an invisible scenery piece, there is no way to manually right click to remove it as the game looks for the graphic you're clicking on, rather than the bounding boxes. if there's no graphic, you can't click it. I fear it may be the same issue with painting an invisible track different.

**Comment by xp4xbox** [comment]
Good idea.

**Comment by xp4xbox** [comment]
Here is the GUI from son of beast:

![capture](https://cloud.githubusercontent.com/assets/24964930/23973021/98a616fe-09aa-11e7-8857-dae4081793b7.PNG)

**Comment by xp4xbox** [comment]
I figured out a way to get good stats on custom rides that use crooked house to make them invisible. Just switch the track type to "Enterprise" instead and you will get good ratings with the track invisible.

**Comment by Gymnasiast** [comment]
For the record: we will introduce a way to make a ride completely invisible/visible with one click, without the need for hacking the ride type.
