### ISSUE TITLE
No test results or excitement/intensity/nausea ratings

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#5257]
OS: Windows 10

Can't seem to get test results on anything I build since this morning on the latest version (7005d5d).

Some rides that have been testing in this save have test results, and others refuse to show results. In the cast of coasters, the excitement/intensity/nausea doesn't appear.

Only noticed in single player so far.

**Comment by IntelOrca** [comment]
Related: #4695]

This is usually caused by one particular ride getting stuck in an infinite loop while calculating results. Can happen with hacked rides.

**Comment by Nubbie** [comment]
^
Happens both in multiplayer/singleplayer
Remove rides one by one to see which one it is, but like IntelOrca said, it's often by hacked rides

**Comment by ArcticX9** [comment]
All non-hacked rides and includes flat rides. Appears to only be happening in this save file at this time.

**Comment by duncanspumpkin** [comment]
Provide the save file then.

**Comment by ArcticX9** [comment]
I think I misunderstood what could have caused this, and now realize there are several rides that could block the testing results. I would still like to know how to tell or which ride is causing this and if it is possible to fix without removing or redoing several rides.
[Essex.zip](https://github.com/OpenRCT2/OpenRCT2/files/799795/Essex.zip)

**Comment by IntelOrca** [comment]
I do want to make it skip rides that take too long to calculate, but that would involve a new save format so that it can save the number of iterations it has done so far.

**Comment by ArcticX9** [comment]
That would be nice. I'd like to know which one it is. The park isn't a scenario or anything so the ratings aren't necessarily crucial, but it would be nice to know what the problem is.

**Comment by Nubbie** [comment]
Just load the save, run it in a faster speed and delete them one by one as a small coaster runs in the background testing to see if it appar
Poor man versions fix

**Comment by ArcticX9** [comment]
Thanks Nubbie, I found the one and thankfully it's an easy fix!

**Comment by Liampie** [comment]
Once you know what you're looking for, these rides are easy to spot: they're rides where the train does not return to the original station of departure. Double close those rides to generate test results for all other rides. In 'ClosedRCT', an alternative way of dealing with this problem was to give the hacked ride ratings using the Son of Beast trainer. This was exploitable in a nice way because having such a ride operating would ensure that other rides' ratings would not be updated anymore. If you manually gave a merry go round a 15.00 excitement rating with the trainer, it would stay that way because ratings wouldn't be updated. Otherwise, ratings would go back to normal farly quickly.

I'd rather see OpenRCT implement the possibility to manually adjust ratings than have them fix this 'ratings queue', as it would be a fantastic feature anyway and it would not harm the functionality of the parks that exploited the hack I described above.

**Comment by ArcticX9** [comment]
Yeah, double closing the stuff will work fine, I just have to do a bunch to fix stuff up beyond that.

**Comment by 733737** [comment]
These rides calculate ratings perfectly fine in the latest build

**Comment by ZehMatt** [comment]
Probably solved with #19683
