### ISSUE TITLE
OpenRCT stores exported .DAT files in own folder, not default RCT2 folder

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5260]
This is not a bug, but it's something inconventient that may not be necessary. First of all, it takes up more space on my hard drive than necessary because it results in duplicate files. In this case scenery files. Second, if I cannot open a park now due to missing scenery, I can't actually use Parkdat to check which files I'm missing. If you can't open a savegame, you're pretty much fucked currently if you rely on just OpenRCT.

edit: Same with savegames. Why did OpenRCT copy all my savegames without asking? That's several gigabytes.

**Comment by duncanspumpkin** [comment]
Your not meant to write to the Program Files directory. This has now been fixed by writing to the OpenRCT2 folder.

**Comment by PFCKrutonium** [comment]
(For Reference, this has been the case forever, but Microsoft started enforcing it with Vista.)

**Comment by IntelOrca** [comment]
@Liampie This might be more bothersome for you if you still like to play RCT2. The idea in the future is that RCT2 will only be the vanilla files and all custom content will be stored in your documents under OpenRCT2. OpenRCT2 does this because applications can not write to program files nor should (unless they are ran as administrator).

You can however pass a command line argument to OpenRCT2 so that OpenRCT2 uses your RCT2 directory instead for content - this however will require running OpenRCT2 as administrator. Also note that RCT2 will not actually write to program files as Windows will re-route it to ProgramData for compatibility purposes.
