### ISSUE TITLE
Mechanic is called to fix a ride that's outside his patrol area

### ISSUE THREAD

**Issue by andoruB** [OpenRCT2/OpenRCT2#5284]
**OS:** Debian Sid
**Version:** 0.0.7
**Commit/Build:** 8bd10df85 / 6d2776d (Git)

I've recently encountered this behaviour, and I'm not sure if this happens in vanilla (if by that you mean the original RCT games), as I never had this problem before, so I'll assume that it doesn't.
I've had a mechanic get a radio call to go fix a ride that was outside his patrol area, even though there was another mechanic that had that ride in his patrol area. He did not leave the patrol area (so it's not the same as #4842), and he was just walking around in his patrol area, while other rides that had broken down weren't fixed. After moving the mechanic to a different area (still in his patrol path), he took on the broken rides that he could access.
EDIT: Forgot to mention that sometimes when I place the first mechanic in another spot, the other mechanic is assigned the task to fix the ride, but it doesn't happen every time. Sometimes I have to insist, or place the mechanic nearer to the ride's exit.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Set patrol areas for two mechanics
2. A ride breaks down that's not in the first mechanic's patrol area 
3. The mechanic is ordered to repair the ride that he cannot reach

**Save game:**
[savegame.zip](https://github.com/OpenRCT2/OpenRCT2/files/826069/savegame.zip)

Unfortunately I didn't think I should save before this happened, but I'll attach another savegame next time I encounter this issue.

**Comment by PFCKrutonium** [comment]
(Vanilla does mean the original games, Specifically RCT2.)

**Comment by andoruB** [comment]
@PFCKrutonium Thanks!
Okay, I encountered this again, and took another savegame:
[savegame-broken-ride.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/827185/savegame-broken-ride.sv6.zip)

Mechanic 1 attempts to go fix Firetrap, while the ride is in Mechanic 2's patrol area.

**Comment by zaxcav** [comment]
@andoruB Double check your Mechanic 1 patrol zone. I looked at the second savegame you provided. In that, Mechanic 1 has the areas under the main lift hill of Firetrap included in his patrol zone, and this covers the ride exit.

**Comment by andoruB** [comment]
*facepalm* D'oh! Sorry about that...
Removed those patrol areas. I'll see if this still happens.

**Comment by ensiform** [comment]
Without having looked at the save, do you have enough mechanics per ride that have at a patrol for each ride or no zones at all?

**Comment by andoruB** [comment]
I currently have 4 mechanics for 15 rides. What constitutes "enough" mechanics?

**Comment by ensiform** [comment]
Well 1 per ride. (or per station for like transport rides). Since you only have 4 mechanics, for example, it will still pick one I assume (even in error) which cannot leave its zone to complete the task.

**Comment by andoruB** [comment]
Okay, will use that setup once I'm absolutely sure this was my error (which it probably was... ugh), and not a bug.

**Comment by ensiform** [comment]
Just my thought. It might still be issue. I don't think game factors the patrol areas into account per-se for who gets called.

**Comment by andoruB** [comment]
Did you notice that behaviour in vanilla?

**Comment by zaxcav** [comment]
The game definitely does consider the patrol areas when calling a mechanic to inspect/fix a ride.

Back to this issue. I see there **is** a minor bug in the code, that I introduced with PR #4576 - specifically when the game calls a mechanic it uses the path tile connected to the ride exit for checking the patrol zone.  With PR #4576 mechanics are sent to the exit itself rather than the path tile connected to the ride exit.  This means it is possible for the game to call a mechanic that cannot reach the exit.
It's a trivial fix. I should have time to submit a PR for it over the weekend.

**Comment by andoruB** [comment]
Seems I'm too late, but I'll attach the savegame nonetheless.
Indeed, Mechanic 1 still goes to fix the ride (FireTrap 1) that's outside his patrol area, even after having fixed the wrongly placed patrol areas for that mecanic (as pointed earlier by @zaxcav )

[savegame-broken-ride.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/837104/savegame-broken-ride.sv6.zip)

**Comment by zaxcav** [comment]
@andoruB The fix I made (PR #5296) isn't in the public builds yet.
It takes time for submitted fixes to get reviewed and accepted into the project.
In the meantime, set your patrol zones to work around the bug. i.e. if you've set a patrol zone with the ride exit bordering on it, expand it one zone more to cover the ride exit too.

In any case, I checked your latest savegame - here Mechanic 1 is being incorrectly called to Top Spin 1 because the ride exit is bordering on his patrol zone, as per the identified bug.
I disabled the other mechanics and Mechanic 1 is not called to FireTrap 1, so that looks fine.
With the patch, Mechanic 1 is not called to Top Spin 1 either, so that will be fine too once the patch is merged.
