### ISSUE TITLE
Mechanic cannot reach Fabergé-twist 1

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5414]
**OS:** Ubuntu 17.04
**Version:** 0.0.7
**Commit/Build:** bf11fdeb21145805e89f21c1568791c1c41b7148

Mechanic cannot reach the broken Fabergé-twist 1, even though it's very close and the assigned area is correct. This is a clear regression from RCT2, that had no problem with this.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**

![from the ashes 2017-04-30 13-20-39](https://cloud.githubusercontent.com/assets/1478678/25563959/5fb32e8c-2da8-11e7-8c18-7b42bf31699a.png)
![from the ashes 2017-04-30 13-20-42](https://cloud.githubusercontent.com/assets/1478678/25563960/60d0644c-2da8-11e7-8f75-83a843cd0037.png)

**Save game:**

[From The Ashes zc.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/966702/From.The.Ashes.zc.sv6.zip)

**Comment by Gymnasiast** [comment]
Tagging @zaxcav .

**Comment by zaxcav** [comment]
I hate wide paths!
The issue here is that the wide path flags are acting like a wall through the patrol zone.
This is something that I had not thought of until now, but it jumped out at me as soon as I read the error report and saw the screenshot, even before I checked where the wide paths are flagged.

The path finding heuristic currently only allows peeps to continue searching through a wide path tile if the peep is currently on a wide tile. This helps avoid peeps getting stuck in the classic scenario where the pathing requires the peep to first walk away from destination in order to get there.

It is trivial to relax this restriction, fixing this case, but the cost will be significantly worse path finding.

I need to think this over for a bit to see if I can come up with some logic that fixes this issue related to patrol areas but does not negatively impact the path finding heuristic in general... maybe ignore the wide path flag if the path tile is on the edge of the patrol zone.
