### ISSUE TITLE
Feature Discussion: Cost Multiplier/Inflation Setting

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#5420]
Just some shower-thought after seeing the monthly cost of hiring staff of just $80 a month. The feature I though of is to give players an option to adjust the cost of hiring staff, building tracks etc. (e.g. 2x/0.5x to the original cost) to make the game become difficult/easy as the players want. Not sure whether it is a good idea though, therefore I decided to leave it open for discussion. And an inflation setting imo is an epic feature which may be considered later.

**Comment by Christipher** [comment]
I don't see how this is too hard to do though - since everything would be up (except prices, sadly those don't inflate at the same rate), and since inflation would make it easier for people to walk into the park, I would say that the dynamics become interesting in higher - number years as guests would walk in with more money in their pocket than you would think and loads of guests would also walk into your park.  Inflation might make it easier for the park entrance entry fee only parks a little easier while making the ride entry fee parks slightly harder (since the rides only have so much they can take in at a time).  This could balance the game just a little bit.

**Comment by Gymnasiast** [comment]
> I don't see how this is too hard to do though

You have never contributed any code, how can you know?


In any case, I think it makes it unnecessarily complicated for the player, since you can no longer remember prices as they all keep changing. It also adds another load of bloat to the codebase for something the majority of users most likely does not want.

**Comment by Nubbie** [comment]
Not too many games have inflation built in - mostly as it does create a bit off a hurdle for new and experienced people to know pricing etc
If the games had for example stocks and other investment opportunities, I think it would workout better.
But one main-point I agree with Gymnasiast, "no price in RCT is realistic"

**Comment by IntelOrca** [comment]
It makes more sense in Transport Tycoon and Locomotion as it had actual years, e.g. 1950 to 2050. But RCT is very agnostic to time other than age of rides, time in park, duration of ride etc.

**Comment by daihakken** [comment]
The reason I gave up on RCT2 (put it back for 1-2 years before playing it again) every time is that the money earning mechanism is way too easy. Plop a launched looping roller coaster and it will cover 90% (bit exaggerating, but still) cost in that scenario. This makes the game very boring after 5-10 years in game time.

Yes, I also I agree that no price/cost in RCT is realistic, but putting an *opt-in* option to make the cost/cash pumping up a bit may be a good idea to balance the game, that's why I raised my opinion here at the start. Anyway, thank you for discussing on this idea guys.
