### ISSUE TITLE
Feature: Add Booster Option To Mini Coaster

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5464]
This would be useful as the only way to have flat booster track, is by changing the track type from giga coaster. And even then, the boosters do not work.

**Comment by Gymnasiast** [comment]
The boosters not working on the Mini Coaster is a bug, which I'll solve. I'm not sure about adding a direct way to build them, for reasons of realism.

**Comment by rwjuk** [comment]
There's an argument to be made that as the Junior Coaster and Mini Coaster are so similar, given their shared RCT1 heritage, it's not unreasonable for the Mini to have boosters as well.

**Comment by Gymnasiast** [comment]
The problem here is that the Junior RC has wheeled boosters that aren't particularly powerful, just as you'd expect. The sprites for the Mini RC are a different case: they're really Giga Coaster LIM sprites. By that I mean there are Giga Coasters with 3 rails (like in RCT2) and with two (with a track that looks exactly like the mini coaster). So the Mini RC boosters aren't really Mini RC boosters, but Giga Coaster boosters.

I do see a way to better support both types, but I would need to know the following first:
Do Giga Coasters use either 3 or 2-railed track for the entire roller coaster, or it is common to use both types in one roller coaster?

**Comment by xp4xbox** [comment]
IRL, giga coaster tracks, use the flat track for launch for pretty much all manufactures. I made them as the triple track for the launch because I thought for general players, they would prefer just to use regular triple rail track. As seen here used flat launch track for cheetah hunts launch:

https://www.coasterfriends.de/forum/attachments/europa-news/138324-2013-neuheit-juvelen-multi-launch-coaster-intamin-djurs-sommerland-daenemark-cheetah-hunt.jpeg

**Comment by Gymnasiast** [comment]
Are there also cases where the two-railed track is used for other parts on something that otherwise acts like a regular (non-Mini) coaster?

**Comment by xp4xbox** [comment]
Also for breaks, and some hills on coasters, etc.

![image](https://cloud.githubusercontent.com/assets/24964930/26002949/442615a2-36ff-11e7-8925-1c0d1481669a.png)

**Comment by Gymnasiast** [comment]
Hm, the above coaster is basically a Mini RC track, Giga C supports and a Giga C train.

What I want to do is use the mechanism currently used by the Dingly slide and Water coaster to allow the two varieties.

**Comment by YoloSweggLord** [comment]
Here's my understanding of general giga coaster track differences:
Tri- and quad-rail track is used in the majority of coaster layouts. Quad rail track is stronger, so it is used it higher-stress areas or where it would be desirable to have more distance between supports. On some coasters, bi-rail track is used near the end of the layout, after the train has slowed down enough that it puts less stress on the track.
Lift hills often use tri- or quad- rail track. A notable exception is Eurofighters, where the vertical lift uses bi-rail track since it can connect to the tower more often.
Brake runs and LIM/LSM launches use bi-rail track. The lack of change in direction on launches means the train puts less stress on the track, even at high speeds. Hydraulic launches, on the other hand, use quad-rail track, since this allows the majority of launch and anti-rollback mechanisms to be containted within the track structure.

So yes, there are cases where bi-rail track is used on 'normal' sections of giga coasters. By the way, @Gymnasiast , the picture you found is of Xcellerator at Knott's Berry Farm, an Intamin launched mini-strata. The track on the left is actually the brakerun; the coaster's launch is hydraulic and therefore uses quad-rail track.
I think that a water-ride-style construction method would work well, but are we only limited to 2 track types? It would be nice to have options for quad-, tri-, and bi-rail track.

**Comment by xp4xbox** [comment]
@YoloSweggLord the quad looks terrible, when combined with the triple. Which is a reason why I did not use it when making the hydraulic sprites, although they do look good when combined with the twister roller coaster.

**Comment by xp4xbox** [comment]
I would use the water coaster style, so that you dont need to add a modification in the window size.

![hack park 2017-05-13 09-20-48](https://cloud.githubusercontent.com/assets/24964930/26025824/ddc5b460-37bd-11e7-9268-0740d1662240.png)

**Comment by Gymnasiast** [comment]
Building boosters on the Mini will be handled by https://github.com/OpenRCT2/OpenRCT2/issues/7648.

**Comment by Gymnasiast** [comment]
Implemented by #10707 (turn on the "Show all drawable track pieces" cheat).
