### ISSUE TITLE
Issues with ride names

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5471]
OS: Windows 7
Version: 0.0.8
Commit/Build: 6472c0e

- Some ride names are different: Dodgems is now Bumper Cars, Merry-Go-Round is now carousel, Circus is now Circus show etc.
- There are no distinct names for food/drinks/souvenir stalls. They are only named food stall, drink stall or shop.
- There is also an issue with the numbering rides. Sometimes, the first ride you build will be no.2 and if you build the same ride again it will go back to no.1. Occasionally, it can also work properly and go form no.2 to no.3.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Steps to reproduce:
1. Build mutiple rides or stalls

**Comment by Gymnasiast** [comment]
1) You have your game set to US English. Bumper Cars is correct for US English. The reason Merry-Go-Round is called Carousel in the build window is actually related to point 2, as odd as that may sound.
2) It appears to fall back on the track name. Carousel, Food Stall and Drink Stall are all names that you don't normally see outside of the Scenario Editor.
3) Most likely a result of 6472c0e (point 2 might also actually be caused by this).

Can you provide steps to reproduce point 3 reliably.

Tagging @rwjuk .

**Comment by SidaRadis** [comment]
How to reproduce point 3:
1. Open the Crazy Castle scenario
2. Build a Ferris Wheel and it will be named Ferris Wheel 2
3. Open the build menu for another non-tracked ride
4. Close the build menu without building anything
5. Open another build menu for a new Ferris Wheel and it will be named Ferris Wheel 1

Note: If you buy another Ferris Wheel immediately after the first one it will be named Ferris Wheel 3

As for point 1, the strange thing is that I do not think that I have changed my language settings recently and the names are now different from what they used to be.

**Comment by rwjuk** [comment]
Thanks - looking into point 3.
