### ISSUE TITLE
Feature: Undo Button to Scenery Window

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5508]
A feature that many of us would like is an undo button. I think it would work especially well in the scenery box such as this:

![untitled](https://cloud.githubusercontent.com/assets/24964930/26466801/1245d8d8-415e-11e7-87f8-19693efba197.jpg)

**Comment by rwjuk** [comment]
Unfortunately, implementing an undo system, with the associated action stack is incredibly complex in a real-time game - even without taking multiplayer into account.

This has been raised and rejected before (#2256), and I can't see that anything has changed since then.

Don't get me wrong, I'd very much like that too (I find myself pressing CTRL-Z on autopilot sometimes!), but it's just not technically feasible.

**Comment by IntelOrca** [comment]
We can look into this after all game actions use the new game action infrastructure.
