### ISSUE TITLE
Current map marker (>>) persists on main menu

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#5584]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 5c5389a

The new "current map" indicator (>>) shows on the main menu after starting a server with a loaded game.

- [No] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. Start ORCT2 from fresh
2. Click the multiplayer button on the main menu
3. Click the Start Server button in the server list
4. Click the Load Game button on the start server dialog
5. Choose any previously saved game
6. Open the file menu (floppy disk)
7. Click Quit to menu
8. Click Load Game
. >>  Will be shown against the last map loaded

**Screenshots / Video:**
![mainmenu](https://user-images.githubusercontent.com/12530301/27004409-981a3298-4e00-11e7-8ac3-87446fefc281.PNG)

**Comment by RogoDarius** [comment]
Also realised this works with offline play as well.
Was this intentional? - Is the marker supposed to show "current map" and "last map" played?

**Comment by Gymnasiast** [comment]
It's supposed to only mark the currently loaded map.

Tagging @wolfreak99 who added this feature.

**Comment by wolfreak99** [comment]
I'm assuming gScenarioSavePath does not get cleared out when a game is quit. I will see if there is any additional usage of gScenarioSavePath and, if it won't effect anything else, i'll have it clear out. I originally chose using this variable over adding a new and dedicated variable to make the PR as little intrusive as possible.

I also may end up creating a seperate variable anyway, as I noticed that sc6 files are not marked as currently loaded when using gScenarioSavePath. That's because gScenarioSavePath is used for the "save" button to know where to overwrite, so raw scenario files can't be stored where they'd easily get overwrote.

I am also going to rework this with the idea of possibly eventually adding a "load last saved game" button.

**Comment by wolfreak99** [comment]
@Gymnasiast
Now that #5598 has been merged, this can be closed.
