### ISSUE TITLE
Feature: Change Train Type in Console

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5608]
This would be a useful feature to be able to change the train type while the ride is running. Especially for hacked rides, were you cannot close the ride to change the train type.

**Comment by Gymnasiast** [comment]
Ooh, that sounds like a can of worms.

**Comment by xp4xbox** [comment]
Just an extended thought, this option would also open a door for a new custom rides never capable before as not all trains are shoestringable (a special hack).

**Comment by Gymnasiast** [comment]
You mean that you could change a train to all front cars, or all non-front cars, or even a weird mix?

**Comment by IntelOrca** [comment]
This will be possible with the new scripting engine.

**Comment by xp4xbox** [comment]
@Gymnasiast I mean that you can change like a coaster train to a log flume train, or something like that while its running.

**Comment by Gymnasiast** [comment]
You were talking about shoestringing. As far as I know, it has nothing to do with changing the vehicle type.

**Comment by xp4xbox** [comment]
It would be usefull for shoestringing because for instance you want to make a shoestringed ride using log flume boats. You would use regular coaster trains that are shoestringable, then once the ride is setup, then you would turn the coaster trains into log flume boats.

**Comment by Gymnasiast** [comment]
There is the '255 cars per train' cheat for that.

**Comment by xp4xbox** [comment]
how does that make log flume cars shoestringable?

**Comment by X123M3-256** [comment]
> Just an extended thought, this option would also open a door for a new custom rides never capable before as not all trains are shoestringable (a special hack).

All trains can be used with a shoestring, not sure what you're talking about here. Why do you think log flume boats are not shoestringable? Obviously, a shoestring requires more than one car per train, but as @Gymnasiast said, there is a cheat to disable that restriction.


This wouldn't make possible anything that's not already possible, as far as I can tell, but it might make certain hacks easier to perform. In the more general form that @Gymnasiast  described it would be very useful (because that particular hack is currently a real pain to set up), but I don't know how easy that would be to implement.

**Comment by xp4xbox** [comment]
@X123M3-256 log flume has certain physics, so that if it goes uphill, it doesn't go down.

**Comment by X123M3-256** [comment]
1) I don't see how that makes it impossible to shoestring (and I just built a shoestring log flume just to verify that it's definitely possible). For a shoestring, all you need is to be able to split the train up somehow, and the usual way to do that is with a track merge, which works fine on the log flume.

2) Being able to change the vehicle type wouldn't solve that, since the powered ride physics are tied to the vehicle type - if you built a different vehicle, and then changed to the log flume, the resulting ride would have the log flume physics.

**Comment by xp4xbox** [comment]
1. How do you merge it, if you cannot get it into reverse direction its going?

2. One the ride would be shoestringed and complete, and all it did was go around a circle. It would be possible to keep the trains because there are no hills.

**Comment by X123M3-256** [comment]
> How do you merge it, if you cannot get it into reverse direction its going?

Track merges can be built in either direction, forward or backward. You can even build a merge that works in both directions, though you don't need that for a shoestring. Attached is a save file with a simple log flume set up as a shoestring.

This requires only "Unlock Vehicle Limits" and "Disable Clearance Checks" to set up. You might have to rename the file from .txt to .sv6 so OpenRCT2 will recognize it (GitHub apparently doesn't like SV6 files).

[LogFlumeShoestring.txt](https://github.com/OpenRCT2/OpenRCT2/files/1185776/LogFlumeShoestring.txt)

**Comment by xp4xbox** [comment]
Not revelent anymore. I figured out how to do this.
