### ISSUE TITLE
Packaging question: generating g2.dat

### ISSUE THREAD

**Issue by ibara** [OpenRCT2/OpenRCT2#5710]
This is not so much an issue as a question.
At the beginning of the CMake install phase, CMake launches openrct2, which generates g2.dat. However, to do this, openrct2 downloads files from the Internet. This is not ok from the viewpoint of OpenBSD package building.

Is it possible to use a g2.dat file generated on one machine on another? Even across CPU architectures? So for instance, let's say I generate g2.dat on an x86-64 machine, will it work on an arm machine? If yes, then the solution is easy: OpenBSD will just distribute a pre-built g2.dat in its package.

**Comment by janisozaur** [comment]
g2.dat is fully portable between supported architectures and there is no internet access required to build it, all the files are in the repo already. We do, however, download gtest redistributable and title sequence archive from the internet when you do `make package` (which is the same with other targets that build on top of package, like `install`).

The former is source only and the latter is again fully portable zip archive. We face the same issues in our android jobs, ideally there would be a way to prepopulate the checkout and have cmake use the cached files, but it's a combination of us lacking the skills to set it up properly, cmake being unnecessarily hard about that and us not bothering enough due to more important stuff.

The title sequence file can be skipped, there will be just an empty opening park, but it'll work. Gtest can also be skipped if built without tests. G2, however, is required.

**Comment by ibara** [comment]
OK great. Thank you. That makes it easy for me to package it up.

**Comment by rwjuk** [comment]
I'll close this for now as it's just informational.
