### ISSUE TITLE
[Feature] Automatically copy RCT1 theme if not found and RCT1 folder set

### ISSUE THREAD

**Issue by keiyakins** [OpenRCT2/OpenRCT2#5743]
**Version:** v0.0.8-develop
**Commit/Build:** f3b3345

If the RCT1 folder is set, the game should be able to copy RCT1 css17.dat to css50.dat on its own, or alternately just load it directly from the RCT1 folder.

**Comment by Gymnasiast** [comment]
It already works like that.

**Comment by keiyakins** [comment]
What the heck? It doesn't work with my copy...


... hunh, bizarre, the steam version doesn't have css17.dat... where is it finding the music then?

**Comment by Gymnasiast** [comment]
The disk version has files on the hard drive and files on the CD. Steam appears to reflect that, while GOG does not. OpenRCT2 can handle all three, but you need to point it to the correct folder if there are two of them.

**Comment by keiyakins** [comment]
So which folder is correct: the one without scenarios, or the one without the music?

**Comment by Gymnasiast** [comment]
It hard because both the disk and the GOG version have all necessary files in one place, while Steam apparently does not, if it indeed saves Scenarios in one folder and music in the other. In such an instance the only thing the user really can do is copy all of them to one folder, as far as I can see.
