### ISSUE TITLE
Mini coaster doesn't appear despite being selected

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5761]
**OS:** 8.1
**Version:** 008
**Commit/Build:** cb28381

Its as if the mini coaster doesn't exist in the object selection at all... can't build it from the build menu, can't select the automobile cars with "select vehicles from other ride types"

- [ ] Multiplayer?
- [ ] Reproducible in RCT2 (vanilla)?

.sv6 provided below:

[Where in the World is the Mini Coaster.txt](https://github.com/OpenRCT2/OpenRCT2/files/1118187/Where.in.the.World.is.the.Mini.Coaster.txt)

I would appreciate it if you are able to get the automobile cars on Spiral Coaster 1.

**Comment by rwjuk** [comment]
I found that if I use the object editor to add a WW/TT Mini Coaster vehicle (a regular RCT2 vehicle doesn't work), the Mini Coaster and Automobile cars show up.

Here's a version with the automobile cars on the Spiral Coaster.
[Where.in.the.World.is.the.Mini.Coaster.zip](https://github.com/OpenRCT2/OpenRCT2/files/1118190/Where.in.the.World.is.the.Mini.Coaster.zip)

**Comment by spacek531** [comment]
Unfortunately I do not have WW nor TT installed.

**Comment by rwjuk** [comment]
Ah, here's a version with the WW/TT object deselected - the automobile cars still show up on the coaster now I've added them.

[Where.in.the.World.is.the.Mini.Coaster.zip](https://github.com/OpenRCT2/OpenRCT2/files/1118200/Where.in.the.World.is.the.Mini.Coaster.zip)

**Comment by spacek531** [comment]
Strange bug. Thanks!

**Comment by rwjuk** [comment]
Strange indeed.

**Comment by Gymnasiast** [comment]
This is due to corrupted research. The mini coaster does not appear anywhere in research, and is not set as invented either. Turning on 'Ignore research status' will make it show up.

This is hard to solve, since removing stuff from research is something vanilla does in order to have non-separated vehicles invented all at once. Nevertheless, a cheat or console instruction to make everything invented could help here.
