### ISSUE TITLE
Support Steam RCT1 file layout

### ISSUE THREAD

**Issue by keiyakins** [OpenRCT2/OpenRCT2#5809]
Steam has its RCT1 files in a sorta weird structure: it effectively does a not-full install, and then keeps the files that would be on the disk in a subdirectory. [A full directory listing of a fresh install is attached.](https://github.com/OpenRCT2/OpenRCT2/files/1127508/dir.txt) As a result, OpenRCT2 doesn't recognize the directory as a valid RCT1 folder. It seems to load the scenarios, but not the music and possibly not some other things, I'm not entirely sure

Though it does of course work fine if you copy files from the 'disc' data folder to the main data folder, it'd be a nice enhancement to not have to do so.

**Comment by janisozaur** [comment]
For reference, steamdb listing of RCT1 (default/English) depot: https://steamdb.info/depot/285311/

You can see listings for other depots here: https://steamdb.info/sub/39496/depots/

**Comment by Keatzee** [comment]
> As a result, OpenRCT2 doesn't recognize the directory as a valid RCT1 folder.

On my end, OpenRCT2 recognizes the Steam RCT1 directory as valid, although this is a mistake as it's missing some needed files. From what I can tell, this is because the OpenRCT2 only checks for csg1.1 or csg1.dat when validating the directory, from the code at [options.c#L867](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/windows/options.c#L867).

So IMO, there are two issues here: the game should be checking for a _complete_ RCT1 directory, and the game should use the game files in `RollerCoaster Tycoon Deluxe\RCTdeluxe_install\Data` instead.
