### ISSUE TITLE
Missing Object Window should point out Vanilla Expansion Objects

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#5855]
https://files.gitter.im/Chaosmeister/ClRr/image.png

The window tells you what objects are missing, does not recognize that the missing objects are from expansion packs. imho it should point that out.

**Comment by rwjuk** [comment]
Would be a nice idea. Could also point out core RCT2 objects in the case of corrupt installs. If the object selection window can display this then we might be able to (unless whether it's a custom object or not can only be determined if it can be loaded - if so we'd need a list of the various types).

**Comment by xp4xbox** [comment]
I can upload a list if you need it.

**Comment by IntelOrca** [comment]
@rwjuk The flags component on the object entry says what the source game is, RCT2, WW, TT or custom.

**Comment by Gymnasiast** [comment]
It should also report vanilla RCT2 objects in case the user is missing one of them. That could happen if he/she accidentally deleted one of them or is using the Mini Game, for example.

RCT2 actually only checks whether the save says an object is original/WW/TT/custom, rather than checking the .DAT files already in the ObjData folder. I have bugged saves that have the balloon stall listed as a custom object, causing RCT2 to create a copy of it. OpenRCT2 also did that, until I put a stop to that. (It now considers an object official if either the save or the user's .DAT files say it is.) 
Still, just for listing objects, relying on just the save shouldn't cause too many problems.

**Comment by rwjuk** [comment]
Implemented in https://github.com/OpenRCT2/OpenRCT2/pull/5869
