### ISSUE TITLE
Ride Entrance/Exit cannot be placed for a few rides

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6052]
**OS:** Windows 7
**Version:** 0.1.1
**Commit/Build:** c595d24

This issue seems to affect the Observation Tower, the Double-Decked Observation Tower, the Launched Freefall and the Roto-Drop. Building only the entrance or the exit works fine but as soon as you try to build both at the same time they simply both disappear. I tried building the entrance then exiting and reopening the build menu but when I do the entrance disappears. 

**Steps to reproduce:**
1. Open the build menu
2. Try to place both the entrance and the exit

**Comment by ZehM4tt** [comment]
It appears to be that this specific line is the culprit https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/map.c#L3376

Most rides would close the construction window once entrance and exit is placed, RCT originally would snap back to the highest element with the mentioned rides which seems to broken too. I'm not sure yet why it would remove the entrance and exit since they are not provisional elements.
