### ISSUE TITLE
RCT1 Free ride price not set by default 

### ISSUE THREAD

**Issue by mrleblanc101** [OpenRCT2/OpenRCT2#6283]
**OS:** macOS 10.13 GM
**Version:** 0.1.2
**Commit/Build:** 6ab0f2f

When playing RCT1 scenario, the scenario have the option for "Paid park entrance/Free ride" by default (RCT2 behavior) but when placing a ride, the default price will be the one set in RCT1 instead of "Free". Also you'll be able to charge for entrance AND ride but no peep will go in ride saying "I won't pay that much for X ride". The price field for rides or park entrance should be disabled following the scenario option to prevent confusion.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Install OpenRCT2
2. Install RCT2
3. Link RCT2
4. Install RCT1
5. Go to preference pane
6. Link RCT1
7. Open any RCT1 Scenario (i.e. Forest Frontier)
8. The scenario option is: "Paid park entrance/Free ride" by default (RCT2 behavior)
9. Place a ride
10. By default it will have the original entrance price of RCT 1 instead of "Free"
11. Because of the scenario option, nobody will go in the ride
12. Every peep says "I won't pay that much for X ride"

**Screenshots / Video:**
<img width="1792" alt="capture d ecran 2017-09-16 a 11 38 35" src="https://user-images.githubusercontent.com/17392251/30513574-9eeb6982-9ad3-11e7-8a4b-2d5025232f88.png">

**Save game:**
[Forest Frontiers.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1308426/Forest.Frontiers.sv6.zip)

**Comment by Gymnasiast** [comment]
The scenario in question has paid rides and paid entry. This is what OpenRCT2 allows.
The fact that doesn't work consistently is because of a limitation in SV6 (which we'll solve when we move to our own save format).

Also, if guests have paid for entry, they don't want to pay as much for rides as they would pay when entry is free.

**Comment by mrleblanc101** [comment]
1) The scenario has 'Paid entrance/Free ride" selected in the option menu... And there is no "Paid entrance/Paid ride" in that menu. 
2) This behavior is clearly different from the one of RCT1 as peeps wool's ride 2$ rollercoaster or 1$ gentle ride. There is clearly something wrong or different from RCT1

**Comment by IntelOrca** [comment]
@mrleblanc101 It will not show that it is paid park entry and paid ride in the menu because of the file limitation. However it will in fact be pay for both entry and ride when loading an RCT1 park or using the cheat. We could indicate this more clearly in the UI.

If you are raising an issue about how guests decide whether to pay for rides or not, you will need to reword your issue to describe that in more detail.

**Comment by Gymnasiast** [comment]
SV6 only supports 'Paid entrance/Free rides' or 'Free entrance/Paid rides'.
SV4 supported 'Paid entrance/Paid rides' or 'Free entrance/Paid rides'.

Since we still save in SV6, we have to pick one. We then activate a cheat to allow asking money for both.

(This, by the way, has been asked _very_ often.)
