### ISSUE TITLE
Use an arrow on park entrance placement

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#6307]
With invisible or symmetrical park entrances it might be a bit difficult to see what the front and back are. This can be solved by having an arrow, pointing towards the inside of the park, when placing it.

Requested by NE.

**Comment by Tay-Sike** [comment]
Since this issue seems to be solved, would you mind closing it? Also on line 1270 of Map.cpp, would it be better to make a new line as gMapSelectFlags |= MAP_SELECT_FLAG_ENABLE_ARROW;
I believe it would just stay consistent with the other flag initializations.

I solved it pretty much the same way but without line 1248 of Map.cpp. Maybe @Gymnasiast can explain why we need to set the inverse of MAP_SELECT_FLAG_ENABLE_ARROW?

**Comment by Gymnasiast** [comment]
> Also on line 1270 of Map.cpp, would it be better to make a new line as gMapSelectFlags |= MAP_SELECT_FLAG_ENABLE_ARROW;
I believe it would just stay consistent with the other flag initializations.

It needs to set two flags. And this is how we did this pretty much throughout the code base.

> I solved it pretty much the same way but without line 1248 of Map.cpp. Maybe @Gymnasiast can explain why we need to set the inverse of MAP_SELECT_FLAG_ENABLE_ARROW?

"The inverse" here means unsetting the arrow flag. This avoids it showing up in places where it doesn't belong. It's a bit cleaner this way.
