### ISSUE TITLE
Using RCTC's g1.dat results in a broken banner font

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#6328]
![forest frontiers 2017-09-29 11-01-41](https://user-images.githubusercontent.com/1478678/31008958-2cd401aa-a506-11e7-9953-8b7cc6ef2311.png)

**Comment by LRFLEW** [comment]
Huh, I guess I wasn't paying attention to this when testing my code. This is likely due to the changes made in the font sprites (as @marijnvdwerf noted on Gitter). I'll see what I can do.

**Comment by LRFLEW** [comment]
This is really bothering me, as I can't figure out the source of the problem.

The tiny font's sprites are different in RCTC than in RCT2, but in a surprisingly simple way. The dark outline that all the fonts in RCT2 have is (mostly) absent from the tiny font in RCTC. This causes the sprites to be smaller by two pixels in each dimension, and the coordinate offsets are 1 (compared to 0 in RCT2). The character spacing can be fixed by adding `g1.x_offset` to the width in `font_sprite_initialise_characters`.

Based on some photoshop experimenting, the text appears to be 16 pixels too far to the right (on all rotations). Looking at everything I could think of in the g1.dat file and in the source code, I can't seem to find where this offset is getting added compared to RCT2. If anybody has an idea how this is happening, please help.

**Comment by LRFLEW** [comment]
I figured it out. The program I used to compare the g1.dat files (which I used to find the ranges to skip) incorrectly accounted for the `x_offset` and `y_offset` variables. Since the scrolling text partially overrides an element from the g1.dat, it was using an incorrect `x_offset` value, which caused the strings to be rendered 16 pixels to the right.

Re-running my script also revealed other sprites with different offsets, which I need to investigate. The one I've identified is for when you grab a guest (RCTC had the grabber cursor have its origin at the top, and not the bottom, so the guest sprite is moved to account for it). Once I have all of the different offsets accounted for, I'll make the PR.
