### ISSUE TITLE
Version information should only be defined for version file

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6370]
**Build System:** cmake
**Commit/Build:** a75d727

Right now cmake will define git version for every translation unit:

https://github.com/OpenRCT2/OpenRCT2/blob/a75d7276852d173d87ad7cba5fc1c650dff57eb4/CMakeLists.txt#L56

This is not desired and should only be defined for files that use it, i.e. https://github.com/OpenRCT2/OpenRCT2/blob/a75d7276852d173d87ad7cba5fc1c650dff57eb4/src/openrct2/Version.cpp

**Comment by vector-of-bool** [comment]
This is a pretty simple fix, and should stop full rebuilds after a commit.

**Comment by nafest** [comment]
I changed that, as suggested, but the current mechanism to add the sha1 information to the build is not reliable. The compile definitions are only updated if a reconfiguration is triggered. For a reliable solution a mechanism as proposed in https://stackoverflow.com/a/4318642/3270292 should be used. I am not sure if the referenced CMake Modules (https://github.com/rpavlik/cmake-modules/blob/master/GetGitRevisionDescription.cmake) can be included in OpenRCT2 since they are Boost licensed.

**Comment by janisozaur** [comment]
Fixed in #6538
