### ISSUE TITLE
Crash when naming rides/attractions

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#6390]
**OS:** [Windows 10]
**Version:** [0.1.2-7]
**Commit/Build:** [25b7226]

problem when naming rides/attraction. when i or some one does game crashes. may not happen all the either. it's random debug crash.

- [ ] Reproducible in RCT2 (vanilla)?
- [ yes] Multiplayer?

**Steps to reproduce:**
1. build any ride and name it anything in multiplayer. it's random it may not occur all the time.
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by 60trainhunter** [comment]
![dsc00471](https://user-images.githubusercontent.com/30908785/31298919-47860124-aaba-11e7-9abb-cafa77f32df3.JPG)

**Comment by ZehMatt** [comment]
Been trying to reproduce this without any luck. I tried all sorts of rides and kept renaming them as client and server but I never managed to make it crash.

**Comment by janisozaur** [comment]
@60trainhunter can you post a dump? And not spam useless things like that photo of a computer?

**Comment by FischNE** [comment]
I have the same issue and someone else had the problem on my server as well.

It only happens in Multiplayer. It's certainly existant.

**Comment by PsychoMark** [comment]
I ran into the same issue with build 0.1.2-develop 10def2a on Windows 10. Reproducing the crash is easy for me: start a server with a new game on Crazy Castle, place a Circus and rename it and the game is gone immediately.

It does not happen for the win32 build, but trying the current x64 commit (ab383571) I can reproduce it in both the official build and Visual Studio. At the deep end, it's an access violation in memcpy.asm (on "rep movsb" under StringCopy) that eventually seems to cause a stack overflow, I've traced it from RideSetNameAction.Serialise down and found something suspicious, but since I'm not familiar with the code nor an expert at C++. Can someone verify my conclusion?

In DataSerialiserTraits.h I ended up in DataSerializerTraits<std::string>.encode where the string length is converted to BigEndian for the stream:
`    static void encode(IStream *stream, const std::string& str)
    {
        uint16 len = (uint16)str.size();
        len = ByteSwapBE(len);
        stream->Write(&len);
        stream->WriteArray(str.c_str(), len);
    }`

This changes it from 13 to 3328, which is fine for the stream. However, this new value is also used as the count for the WriteArray call, which seems like a bug. I changed it to:

`    static void encode(IStream *stream, const std::string& str)
    {
        uint16 len = (uint16)str.size();
        uint16 beLen = ByteSwapBE(len);
        stream->Write(&beLen);
        stream->WriteArray(str.c_str(), len);
    }`

...and it doesn't crash any more. I've tested it with a client connected, and the name is updated properly.

**Comment by janisozaur** [comment]
@PsychoMark will you submit a PR? Include a change to network version in `network.h`.

**Comment by PsychoMark** [comment]
@janisozaur sure, will do!

**Comment by ZehMatt** [comment]
Holy crap how did I miss that
