### ISSUE TITLE
Tofu with CJK and some Arabic glyphs on macOS

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#6542]
**OS:** macOS Sierra
**Version:** 0.1.2
**Commit/Build:** 47f5423

![blackpool pleasure beach 2017-10-23 09-41-33](https://user-images.githubusercontent.com/1478678/31877339-67b80612-b7d6-11e7-972a-c280a27237cc.png)

**Comment by AaronVanGeffen** [comment]
You're missing the 'MS PGothic' font. It ships with Microsoft Office on macOS, I think.
(I hasten to add: I just noticed you're @Gymnasiast, so you're probably aware of this already…)

Ideally, we would provide a font family instead of one particular font, so we can use a font that's available out-of-the-box on each of the supported platforms.

**Comment by Gymnasiast** [comment]
I have Microsoft Office 365 running on that machine.

**Comment by AaronVanGeffen** [comment]
On closer inspection, it looks like Office is no longer installing its fonts to the system library font directory, so that's not helping here. I should have [known](https://aaronweb.net/2016/01/office-2016-mac-decrease-disk-use/). Guessing I had the fonts in there leftover from a previous Office 2011 install, then.

**Comment by Gymnasiast** [comment]
Finding the fonts in the Word package and installing them indeed helps.

I think it would be a good idea to use system-provided fonts. On macOS, it seems that Hiragino Kaku Gothic is meant as such.

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved now that #6571 has been merged.
