### ISSUE TITLE
Adding scenery and paths to Track Designer

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#6844]
Taken from the forum: https://openrct2.org/forums/topic/2754-adding-scenery-and-paths-to-track-designer/

JoshuaSin
> While I love how not just roller coasters were added to the Track Designer but I still feel like it's missing what it needs to make a good looking ride.

YoloSweggLord
>The point of the Coaster Designer is to provide you with a clean environment to make .td6 track saves which you can then import into your parks. I can definitely see scenery being added to the Coaster Designer, but paths would be pointless as they can’t be saved in the .td6 track file.

**Comment by AaronVanGeffen** [comment]
> but paths would be pointless as they can’t be saved in the .td6 track file.

They totally can, though.

**Comment by Patrik356b** [comment]
@Nubbie Your probably confusing td4 with td6 as plenty of vanilla track designs come with paths more often than scenery or scewnery+path.

td4 does not support that though.

**Comment by Nubbie** [comment]
@Patrik356b It's a quote from the forum

**Comment by saxman1089** [comment]
I discovered today that RCTC has this capability. I think it would be good to add to OpenRCT2.

**Comment by awebeer256** [comment]
I've always found the lack of scenery and paths in the Coaster Designer to be downright baffling. The ability to save them with the track automatically makes their presence a core feature of the mode. Given their absence, in order to create or modify a saved track design with these elements, you have to abandon the Coaster Designer and instead use an old save with lots of money and free flat space (e.g. Arid Heights or Razor Rocks, both from Loopy Landscapes), or a user-made sandbox scenario or something.

**Comment by Gymnasiast** [comment]
Implemented by https://github.com/OpenRCT2/OpenRCT2/pull/13587.
