### ISSUE TITLE
Car types that affect ride ratings have graphical clipping in the ride window

### ISSUE THREAD

**Issue by RollingStar** [OpenRCT2/OpenRCT2#697]
![image](https://cloud.githubusercontent.com/assets/4810902/5789742/86a9eed0-9e45-11e4-855a-e8a6899f71f5.png)

edit: This may only happen with Trams, which are affected by #696. Maybe fixing that causes this bug to never show up otherwise.

**Comment by RollingStar** [comment]
@IntelOrca, have you been able to reproduce it in regular RCT2? I haven't seen this bug anywhere since the patch for the Trams. Maybe it's already fixed?

**Comment by IntelOrca** [comment]
I doubt it, I think you only see it in the situation where you have all three modifiers and the description of the vehicle is more than one line. Since the window for this page is always a fixed height, I think this bug exists in the original game and still in OpenRCT2.

Our options are to increase our fixed height, although how many lines of text do we want to allow for? Or have a dynamic height based on the number of lines in the vehicle description. I bet this isn't the only place where this kind problem exists.
