### ISSUE TITLE
Submarine Ride is in the wrong research group

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7006]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 47a2360

The Submarine Ride is researched as a gentle ride instead of a water ride.
Edit: Water Coaster is researched as a water ride but is part of the roller coaster group.

**Comment by Liampie** [comment]
Isn't the submarine classified as both?

**Comment by spacek531** [comment]
Not any more, with the current changes to OpenRCT2. Rides are now grouped into their track type, which now only exists in one tab in the rides menu (instead of two like some e.g. river rafts, row boats, submarine).

It means that the mat slides I made for CTR Christmas are a water ride and there's not a whole lot I can do about it.

**Comment by Gymnasiast** [comment]
This has now been addressed, but for new games only. Old saves will continue to have them in the "wrong" group.
