### ISSUE TITLE
OpenRCT2 cannot see folders with periods in their name

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7032]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** c581656

![image](https://user-images.githubusercontent.com/3454156/34921888-e4a2b3be-f93c-11e7-9920-5db1cf50741c.png)

It would be helpful to be able to load files from folders with periods in their name.

**Comment by AaronVanGeffen** [comment]
This looks to me like a problem with the Windows platform code: [windows.c#L358](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/platform/windows.c#L358)

**Comment by rwjuk** [comment]
@AaronVanGeffen Agreed. There's no reason to exclude directory names with periods in them, I'd say that condition can go.

**Comment by AaronVanGeffen** [comment]
@rwjuk It probably enumerates `.` and `..` as well… But agreed, those should be treated as special cases, rather than this generalised condition.

(As an aside: the whole reason leading periods historically made a directories invisible on UNIX was because of an optimisation intended for the aforementioned two special cases!)

**Comment by rwjuk** [comment]
Yeah, I remember reading about that! An unintended feature - probably the very first widely known one.

**Comment by Broxzier** [comment]
cb720025facfc8d18ea9afef3e6432c2981886ec seems to have fixed this.
