### ISSUE TITLE
Can't place this here / unable to clear

### ISSUE THREAD

**Issue by Nuklon** [OpenRCT2/OpenRCT2#7055]
**OS:** Windows 10
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/51df68a7d99469a494213ef7b42cbf9ff516a57f

At some point, one of my parks stopped being able to clear scenery and place scenery (clearing only works one at a time with right-click, but not with the area tool).

- [ ] Reproducible in RCT2 (vanilla)? No, it works just fine through RCT2.exe (same save).

**Steps to reproduce:**
1. Load the park.
2. Try to place anything.

**Save game:**
[Wacky Waikiki.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1647613/Wacky.Waikiki.sv6.txt)

**Comment by rwjuk** [comment]
There was a bug a little while ago that led to the internal map size ending up as `-1`, causing this exact behaviour. I imagine this park got caught up in that. The bug is fixed now and I've attached a fixed SV6 file for you. If the problem reoccurs on this save again or a new save, please file a new issue.

[Wacky.Waikiki.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1649255/Wacky.Waikiki.sv6.zip)

**Comment by Nuklon** [comment]
Thank you @rwjuk  but I suspect the issue still exists as this started happening after half an hour (while playing on this commit), it did work before.

**Comment by duncanspumpkin** [comment]
For anyone left wondering why this happened again. Turned out there was more than one buffer overflow bug and for some reason the park size seems to be susceptible to being overwritten
