### ISSUE TITLE
Virtual floor keeps enabling itself

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7120]
Using version 0.1.2 d91fd13. 

Regularly when I start the game, I find that the virtual floor has been enabled. It's annoying having to disable it every time, only for it to come back the next day. I never use it, not sure how useful people think it is in general. But regardless of how useful is it I think this is a function that should be disabled by default.

**Comment by AaronVanGeffen** [comment]
By 'has been enabled', are you referring to the setting? Or is the virtual floor itself drawn somewhere on screen? I don't see how the latter would happen.

**Comment by Liampie** [comment]
The setting indeed! The box checks itself. Maybe it happens as the launches updates my game, but I don't think it happens regular enough to be that. Besides, other options don't reset to the default value when the game updates. The virtual floor setting seems to behave differently.

**Comment by Gymnasiast** [comment]
> I think this is a function that should be disabled by default.

It needs to respect your setting, at any rate.

**Comment by AaronVanGeffen** [comment]
I cannot reproduce this... @Liampie, does this still happen for you?

@LRFLEW Could the launcher be responsible for resetting the setting? I was under the impression it only touches a small subset of settings.

**Comment by LRFLEW** [comment]
@AaronVanGeffen It shouldn't, but I won't rule it out.

The launcher should keep any values previously in the config file. It used to be more aggressive with the config file compatibility, but since I removed the majority of settings from the Options menu, the launcher shouldn't change any values it doesn't understand the key for. Either way, it only ever messes with the config file when you open/close the Options window (so just using the updater part shouldn't touch the config).

The only thing I can think of would be some sort of incompatibility between Qt's and OpenRCT2's INI support. It wouldn't be the first time (#2928 and #5279 both were made with this in mind). However, this would more likely result in the config file being entirely blanked (or treated as blank), meaning a lot more than just the virtual floors would be affected. My testing didn't show this happening on my config file, though. If this *is* a problem with the Launcher, send me the config file and I can take a look.

**Comment by Gymnasiast** [comment]
The only way to find out: stop using the Launcher for, say, a week or two.

**Comment by Liampie** [comment]
Two ways for me to get the virtual floor to enable itself:

1. Open OpenRCT using the launcher, developer version, to verify that the virtual floor is disabled
2. Open OpenRCT double clicking a savegame, which somehow opens the savegame using an earlier OpenRCT version.
3. Open OpenRCT using the launcher, still developer version. Virtual floor is enabled.


1. Open OpenRCT using the launcher, developer version, to verify that the virtual floor is disabled
2. Open OpenRCT using the launcher, latest stable version.
3. Open OpenRCT using the launcher, still developer version. Virtual floor is enabled.

**Comment by janisozaur** [comment]
This is all regarding launcher, which is completely separate tool and not our concern, please file that against the launcher.

**Comment by AaronVanGeffen** [comment]
Opening the game with an older version of OpenRCT2 that doesn't have the virtual floor yet will rewrite your config.ini file to only include the settings that version uses. Hence, the next time you use a more recent version of the game, it will fall back to the default value — which is enabled.

**Comment by Liampie** [comment]
How am I supposed to know it's a launcher problem? Sorry dude. Can't say it won't happen again because I'm not tech-savvy enough to understand that this was apparantly launcher-related

**Comment by janisozaur** [comment]
It was not, the problem is you're using two different versions of OpenRCT2 that take turns writing your `config.ini`, as mentioned in https://github.com/OpenRCT2/OpenRCT2/issues/7120#issuecomment-374337877, hence not a bug.
