### ISSUE TITLE
Upgrade some strings to string_view

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7145]
**Commit/Build:** 282553f 

Some uses of `std::string` should be upgraded to `string_view`, see especially https://github.com/OpenRCT2/OpenRCT2/pull/7144#issuecomment-363916954

**Comment by IntelOrca** [comment]
So when do we start this?

**Comment by janisozaur** [comment]
I requested there was one more release prior to doing this and as this is done, I can start updating the toolchains already, if agreed on by others.

**Comment by AaronVanGeffen** [comment]
The most recent version of Xcode supports them, so there should be no objection from the macOS side, I think.

**Comment by Gymnasiast** [comment]
Fine by me.

**Comment by jansegre** [comment]
Small feedback. I get compilations errors on Clang 6.0.0 and GCC 6.4.0 (these are the 2 I use). I can only get around with `#include <experimental/string_view>` instead of `#include <string_view>`.

Although this may be a great improvement there are some packaging drawbacks to be taken into account.

**Comment by janisozaur** [comment]
@jansegre we no longer support GCC 6. We have made a release (0.1.2) that is still compatible. As for clang, we still build with LLVM 5, but with libstdc++ 7.

**Comment by IntelOrca** [comment]
I don't think we need an issue for this. I have been changing things to use `string_view` as I go along.
