### ISSUE TITLE
Game freezes, possibly because of exploding guests cheat

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7229]
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [57be3b4] (but also on earlier builds)

My server froze up a few days ago. This also happened earlier a few weeks ago. It happened approximately one hour after heavily using the exploding guests cheat. I presume thats also what caused it earlier. In my server, i fixed it by using the remove all guests cheat once.

It gets stuck in the following function:

```
rct_peep * ride_get_queue_head_guest(Ride * ride, sint32 stationIndex)
{
    rct_peep * peep;
    rct_peep * result = nullptr;
    uint16 spriteIndex = ride->last_peep_in_queue[stationIndex];
    while ((peep = try_get_guest(spriteIndex)) != nullptr) {
        spriteIndex = peep->next_in_queue;
        result = peep;
    }
    return result;
}
```
I have attached some autosaves which will all freeze up after a few in game days/weeks. 

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Save game:**

[autosave-mp-deurklink.zip](https://github.com/OpenRCT2/OpenRCT2/files/1776853/autosave-mp-deurklink.zip)

**Comment by Broxzier** [comment]
The crash happens when a guest who entered a ride goes back to the queue. I think he wants to insert himself in front of the guest behind him, but that guest left the queue for some reason.

[Video of it happening](https://cdn.discordapp.com/attachments/402526487321772032/419647320406360074/2018-03-04_01-08-12.mp4).

Something else I noticed in the park that may be related, but not to the crash, is that there are two guests two guests stuck while waiting for other passangers to get to a vehicle on Temple Tubs. They've been there forever, since both are complaining they want to get off the ride.

**Comment by duncanspumpkin** [comment]
Have the ride entrances been hacked at all. The code for rejoining the queue has a few areas where peeps can get in a loop if things are not where they should be.

**Comment by deurklink** [comment]
The ride entrances have not been hacked. After removing all peeps once the server ran fine again without any trouble.

**Comment by deurklink** [comment]
Here's another park where the exploding guests cheat was used. Several rides are now stuck, and the game will freeze after some time, unless all guests are removed.
[The OpenRCT2 Group Park 7.97.zip](https://github.com/OpenRCT2/OpenRCT2/files/1800669/The.OpenRCT2.Group.Park.7.97.zip)
