### ISSUE TITLE
Console Commands do not Sync Across Multiplayer

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7417]
This probably isn't a bug, but wanted to bring it up here anyway. It appears that when using console commands these commands do not sync across multiplayer. For more aesthetically-oriented players like myself who use frozen staff as scenery or need to correct certain ratings for a coaster, and who play on MP, it makes it difficult to make some of these changes, as you need to pull the save off of MP and do it in single player, then place the save back onto MP. Is there any reason for not having these commands sync across MP?

**Comment by janisozaur** [comment]
It's much easier to have those commands modify the game state directly rather than doing it through the game command/game action (which is how most part of the engine works and enables multiplayer).

I think for some things, e.g. entertainer costumes, we also skip some checks that would otherwise take place, not sure about other ones. This is still solvable with some amount of work, PRs welcome.

**Comment by Margen67** [comment]
#2987
