### ISSUE TITLE
Path to RCT1 on Windows version of Steam through Wine is invalid on Linux

### ISSUE THREAD

**Issue by JackACase** [OpenRCT2/OpenRCT2#7457]
**OS:** Linux Mint XFCE 18.1
**Version:** 0.1.3
**Commit/Build:** 2ef549b

Selecting RCT1 installed through the Windows version of Steam on linux gives the error "please select a valid RCT1 directory." RCT2 was installed through GOG.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Install the windows version of Steam through Wine
2. Open the options menu to select the RCT1 path
3. Navigate to the RCT1 installation directory and select it

**Comment by janisozaur** [comment]
Please provide a listing of files from said directory

**Comment by qwertychouskie** [comment]
I'm pretty sure it has to do with the case of the files, renaming `Css17.dat` to `css17.dat` allows the RCT1 title music to work (oddly enough, OpenRCT2 doesn't seem to care about the case of the `Data`/`data` folder, only the files within).

**Comment by mijlandst** [comment]
Not sure if I should comment this here or create a new issue. Since I'm generally following up on questions in this issue, I'll leave this as a response.

I run OpenRCT2 on Linux Mint from the development PPA:
```
OpenRCT2, v0.1.3- build  (DEBUG)
Linux (x86-64)
```
I have installed RollerCoaster Tycoon 1 on Windows from CD to use with OpenRCT2. I created a .zip with my windows installation folder (C:\Program Files (x86)\Hasbro Interactive\RollerCoaster Tycoon) of RollerCoaster Tycoon 1 which I unpacked on Linux. Then I attempted to select the unpacked directory as the RCT1 directory for OpenRCT2. Like with @JackACase It also warned me to "please select a valid RCT1 directory." 

Following @qwertychouskie 's advice, I renamed all `.dat` files (using `rename 'y/A-Z/a-z/' *.dat` and `rename 'y/A-Z/a-z/' *.DAT' respectively as per the answer by tristanbailey and Antzi on the stack overflow issue: [How to rename all folders and files to lowercase on Linux?](https://stackoverflow.com/questions/152514/how-to-rename-all-folders-and-files-to-lowercase-on-linux#8167105). **This made RCT1 files show up in OpenRCT2.**

This has left the following message in my console:
```
ERROR[/build/openrct2-QMG5Lp/openrct2-0.1.3-develop-0~6524-201804060902/src/openrct2/drawing/Sprite.cpp:392 (gfx_load_csg)]: Unable to load csg graphics
```
I have not played the RCT1 scenarios or used special rides enough to know if this has any in-game consequences. If it does, I'll create a new issue.
Changing the name of `CSG1.DAT` to either `csg1.dat` or `CSG1.dat` does not remove the log message.

To follow up on @janisozaur 's request, these are **my** files in the RollerCoaster Tycoon/Data folder (before renaming, as produced with `ls -l`, without personal details):
```
total 286244
-rw-r--r-- 1 41402869 Sep 24  2000 CSG1.DAT
-rw-r--r-- 1        9 Jan 15  2000 CSS0.DAT
-rw-r--r-- 1        6 Jan 14  2000 Css10.dat
-rw-r--r-- 1  7023288 Jan 14  2000 Css11.dat
-rw-r--r-- 1        6 Jan 14  2000 Css12.dat
-rw-r--r-- 1  3373390 Jan 14  2000 Css13.dat
-rw-r--r-- 1 20783042 Jan 14  2000 Css14.dat
-rw-r--r-- 1 10009312 Jan 14  2000 Css15.dat
-rw-r--r-- 1        6 Jan 14  2000 Css16.dat
-rw-r--r-- 1  4214806 Sep 24  2000 CSS18.DAT
-rw-r--r-- 1  5071914 Sep 24  2000 CSS19.DAT
-rw-r--r-- 1  4651236 Jan 14  2000 Css1.dat
-rw-r--r-- 1  6135850 Sep 24  2000 CSS20.DAT
-rw-r--r-- 1  4840490 Sep 24  2000 CSS21.DAT
-rw-r--r-- 1  5031050 Sep 24  2000 CSS22.DAT
-rw-r--r-- 1  5533738 Sep 24  2000 CSS23.DAT
-rw-r--r-- 1  6213750 Sep 24  2000 CSS24.DAT
-rw-r--r-- 1  7590778 Sep 24  2000 CSS25.DAT
-rw-r--r-- 1  5347430 Sep 24  2000 CSS26.DAT
-rw-r--r-- 1  5210622 Sep 24  2000 CSS27.DAT
-rw-r--r-- 1  6559210 Sep 24  2000 CSS28.DAT
-rw-r--r-- 1  7655468 Sep 24  2000 CSS29.DAT
-rw-r--r-- 1  3024264 Sep 24  2000 CSS2.DAT
-rw-r--r-- 1  5110330 Sep 24  2000 CSS30.DAT
-rw-r--r-- 1  5755180 Sep 24  2000 CSS31.DAT
-rw-r--r-- 1  5885994 Sep 24  2000 CSS32.DAT
-rw-r--r-- 1  5379884 Sep 24  2000 CSS33.DAT
-rw-r--r-- 1  7015380 Sep 24  2000 CSS34.DAT
-rw-r--r-- 1  5823602 Sep 24  2000 CSS35.DAT
-rw-r--r-- 1  4476904 Sep 24  2000 CSS36.DAT
-rw-r--r-- 1  6651948 Sep 24  2000 CSS37.DAT
-rw-r--r-- 1  5046966 Sep 24  2000 CSS38.DAT
-rw-r--r-- 1  3765804 Sep 24  2000 CSS39.DAT
-rw-r--r-- 1  1244898 Jan 14  2000 Css3.dat
-rw-r--r-- 1  5291306 Sep 24  2000 CSS40.DAT
-rw-r--r-- 1  8139054 Jan 14  2000 Css4.dat
-rw-r--r-- 1  7796656 Jan 14  2000 Css5.dat
-rw-r--r-- 1 15787850 Jan 14  2000 Css6.dat
-rw-r--r-- 1 15331658 Jan 14  2000 Css7.dat
-rw-r--r-- 1 17503414 Jan 14  2000 Css8.dat
-rw-r--r-- 1  7005802 Jan 14  2000 Css9.dat
-rw-r--r-- 1      751 Sep 24  2000 CUSTOM.TXT
-rw-r--r-- 1       25 Jan 14  2000 Game.cfg
-rw-r--r-- 1   307712 Jan 14  2000 Kanji.dat
```

**Comment by janisozaur** [comment]
I think there were changes to handling of RCT 1 path since 0.1.3, which is over half a year old now and you should use 0.2.1 instead. Ping @Gymnasiast

**Comment by Gymnasiast** [comment]
This should not happen any more. @JackACase , can you confirm?

**Comment by Gymnasiast** [comment]
Considering this solved. Let us know if it isn't.
