### ISSUE TITLE
Pick up button for peeps not responding most of the time online (v0.1.3)

### ISSUE THREAD

**Issue by shibatan** [OpenRCT2/OpenRCT2#7554]
**OS:** Mac OSX 10.13.4 and Windows 10
**Version:** v0.1.3
**Commit/Build:** b763a32 *and* ee56021 (only ones I've tested)

When clicking the "Move this person to a new location" button (with a guest selected), nothing happens. Staff are able to be moved, but guests experience this issue. 

This does not happen 100% of the time, however, and if a guest is able to be moved, then that particular guest will continue to be moveable. If a guest is **unable** to moved, then they will continue to be unmovable.

Note that this does not always happen for the server host, so this could possibly be due to a network issue? This has occurred across multiple sessions with the host experiencing the issue only during some games, while the server members experience it every game.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. **Join** an existing server.
2. **Select** a guest.
3. **Click** _"Move this person to a new location"_.
- If you are able to pick up the guest, put them down and try again with someone else.
4. (Notice that clicking the button does nothing.)

**Comment by Broxzier** [comment]
That's because you're desynced and the sprite IDs don't match anymore. For guests that still match their IDs on both the client and server it does work (but only if they're both in a pick-upable state), though even then it's not really synced. For you the guest may be walking, while for the server he may stand in a queue line.

I'm closing this, because picking up peeps is working as expected.
