### ISSUE TITLE
"Back" button often disappears in scenario editor

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7559]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** c89ebb0

Sometimes the back button in scenario editor disappears, which means you will have to reload the map to edit the landscape again. 

It usually happens when you open the object selection through the debug tools menu, click some stuff there, and then go to the invention list. It does not always happen, but it is annoying when it does.

This is a quite recent problem (last time i made a scenario was 2 weeks ago and then this did not happen). In the screenshot it even happened without going to the invention list. 

![backbuttondisappear](https://user-images.githubusercontent.com/6469413/40515652-ecd33e78-5fad-11e8-81e0-f65d7fead99d.png)

**Comment by deurklink** [comment]
I triggered it now by just closing the landscaping tool. Definitely something fishy going on here.

**Comment by Umdlye** [comment]
Was just going through the scenario editor as well, the same thing happened. Notice the peep in the spawn area, pretty sure they're not supposed to appear in the editor...
![1](https://user-images.githubusercontent.com/11657101/40517672-cce58c7a-5fb6-11e8-837b-2469028330bb.PNG)

**Comment by AaronVanGeffen** [comment]
> Related to today's money-related commits?

I don't think so. `string_to_money` is currently only called from the cheats window.

**Comment by Gymnasiast** [comment]
> To reproduce, place a peep spawn in the scenario editor and wait for a peep to spawn

That... shouldn't happen... 
d44d727 looks like a likely suspect indeed.

**Comment by AaronVanGeffen** [comment]
Bisected to 721dc007784734c550c8e0364c2d3b2e4dfa572c. `Park::Update` replaces `park_update`, but no longer contains the check for `gScreenFlags & (SCREEN_FLAGS_SCENARIO_EDITOR | SCREEN_FLAGS_TRACK_DESIGNER | SCREEN_FLAGS_TRACK_MANAGER)`. This is because https://github.com/OpenRCT2/OpenRCT2/pull/5979 moved the check to `GameState::UpdateLogic`, which I didn't account for when I split off the Park class from the GameState PR.

I'll re-instate the check in a PR in a bit. I'm sure this sorts the peeps spawning, but I don't think it keeps the 'back' button from disappearing.

**Comment by AaronVanGeffen** [comment]
With #7560 merged, could you help investigate what's (still) triggering the back button to disappear?

**Comment by Umdlye** [comment]
For me the back button disappeared when the peep spawned, everything seems fine now. Not sure if @deurklink still experiences it.

**Comment by deurklink** [comment]
I just made a new scenario and the back button no longer disappeared for me, whatever I did. It appears to be fixed.
