### ISSUE TITLE
Fix No Money scenarios with funding set to 0

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#7643]
As seen in https://github.com/OpenRCT2/OpenRCT2/issues/7641 , 'No Money' scenarios can exist with the funding set to 0, which means that the user will not have any way to resolve it themselves, as it's impossible to change funding.

To fix this, funding should be set to Normal if:
- it's set to 0.
- it's a no money scenario
- there are uninvented items left.

**Comment by IntelOrca** [comment]
Instead of setting the property, the fix should be to change research update to instead use normal instead of the value of the property if money is disabled.

**Comment by ocalhoun6** [comment]
While having it set to 0 is obviously useless, I could see where it might be useful to scenario-builders to have the option to set it to min/normal/max, in order to make the no-money scenario more or less difficult, forcing players to make choices about what they want to research before the time limit expires.

Maybe on no-money scenarios, if it's set to 0 funding, have it default to minimum funding instead?

**Comment by Gymnasiast** [comment]
> Maybe on no-money scenarios, if it's set to 0 funding, have it default to minimum funding instead?

That is exactly what I proposed.
