### ISSUE TITLE
Extend 'Enable all track pieces' to also include Twister RC pieces for the Vertical RC

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#7648]
Based on an observation in #7645,

Currently, it will only show track pieces not enabled for the current ride group, meaning that it will work for the Car Ride (Monster Trucks pieces) and Junior RC (Classic Mini RC pieces), but not for the Vertical RC (which is a distinct track type from the Twister RC).

- [ ] Vertical brake on the Twister
- [ ] Twister pieces on the vertical
- [x] Boosters on the Mini
- [ ] Boosters on the Air Powered
- [ ] 'covered' downward slopes on the Water Coaster.

**Comment by blackhand1001** [comment]
Another thing we should look into is enabling the ability to building the small flat to vertical piece and the large flat to vertical piece on the same track type. We would need a separate button and icon for this since they both use the same button normally. Right now I accomplish this by switching my vertical drop coaster to twister RC and then back to Vertical RC after placing the piece.
