### ISSUE TITLE
Feature request: lock camera to vehicle in main window

### ISSUE THREAD

**Issue by meatbee** [OpenRCT2/OpenRCT2#7682]
I think it would be a fun feature to lock the main camera (outside of the coaster's own window) to a ride vehicle. Might be fun for title sequences in future to enable a moving tour of the park instead of just static views (particularly if the ride is underground and the camera is in normal mode).

Maybe this could be through a double click of the already existing "locate this on main view" button.

**Comment by meatbee** [comment]
Oops, my bad then. Still it would be nice to have the feature during gameplay.

**Comment by SevenChords** [comment]
any update for if/when a more convenient way than the title sequence editor will be implemented?

**Comment by duncanspumpkin** [comment]
@SevenChords rather than spam every issue related to this it would be more constructive if you implemented it yourself. We are all volunteers doing this in our spare time working on whatever takes our fancy.

**Comment by SevenChords** [comment]
@duncanspumpkin you could've just said on the first issue where i asked this that it isn't planned to implement because other issues are at a higher priority, no need to get rude about it.
and about implementing it myself, i would do that, but unfortunately i am not good enough with c++ yet to do such a thing, which is why i asked wether this was already planned to implement on existing issues, and after the ones i asked it on got closed more or less directly afterwards instead of an answer, i asked again.

**Comment by AaronVanGeffen** [comment]
We already implemented this in OpenLoco, which has a similar codebase. Perhaps some inspiration could be taken from there. cf. https://github.com/OpenLoco/OpenLoco/pull/760

**Comment by SevenChords** [comment]
thanks aaron, will try to figure it out using that

**Comment by seifer7** [comment]
I am working on this now. Will submit a pull request soon.
