### ISSUE TITLE
Money Input Prompt break on certain values

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7729]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 9e052c7

Two issues:
1. Setting a ride's price to something ignores the decimal part for values over 3 when the decimal part is `.10` (3.10, 4.10, 5.10, etc..). Other decimal values seem to work fine.
2. Entering high values in the 'Add/set money' cheat gives back a seemingly random amount. For example, entering `100,000.00` gives you `34,464.00` cash.

**Comment by jmyre1999** [comment]
Is this bug currently being worked on by anybody?

**Comment by Gymnasiast** [comment]
@jmyre1999 No, as far as I know, nobody is working on it. If you would like to work on it, please do!

**Comment by jmyre1999** [comment]
@Gymnasiast I tried to replicate part 1 and it seemed to work as intended

**Comment by joshtucker132** [comment]
I am working with @jmyre1999 on this and I'm having issues with floating point division when trying to fix part 1.

https://github.com/OpenRCT2/OpenRCT2/blob/89330703e0f84b0e94dd4236c4b502a16d7fade8/src/openrct2/localisation/Localisation.cpp#L1513-L1516

For some entered money values (ex. 6.10), `number` evaluates to 6.099999. This causes `fraction` to evaluate to 0 instead of .1. I have tried multiple ways to round `number` to two decimal places (ceiling/floor functions, casting to int and dividing by 100.0, etc.) but no method works as expected. Any particular reason for this error? Even simple division like 610 / 100.0 evaluates to 6.099999 which seems odd.

**Comment by ZehMatt** [comment]
Have a look at this example http://cpp.sh/9ao5v you want to use long double and suffix L.

**Comment by joshtucker132** [comment]
`auto rounded = (static_cast<long>(number * 100 + .5) - (whole * 100)) / 100.0;
    auto fraction = static_cast<uint8_t>(rounded * 100);`

@ZehMatt I tried to implement your solution, but it still did not give me the rounded value that I wanted. I found a work-around by performing the subtraction before the division. It is a little messy but fixes the issue.
