### ISSUE TITLE
Monorail Cycle is not available in Track Designer

### ISSUE THREAD

**Issue by RCTC** [OpenRCT2/OpenRCT2#7739]
**OS:** Windows 7
**Version:** 0.2.0-128
**Commit/Build:** fe76c80

No monorail cycle in Track Designer. It's available in object selection and track design manager but not in track designer.

- Reproducible in RCT2 (vanilla)? No
- Specific to multiplayer? No

**Steps to reproduce:**
1. Open the track designer
2. Search for monorail cycles in the list

**Comment by Broxzier** [comment]
This probably is because it has no "test" option, which makes sense since a guest has to cycle manually. Nevertheless, the vehicles move on their own without guests fine if you open the ride with a different mode.

For the track designer, it would make sense to allow the ride to be tested without passengers.

**Comment by Gymnasiast** [comment]
Only rides that can be tested without passengers appear in the Track Designer. That's already a whole lot more than what vanilla RCT2 did.
