### ISSUE TITLE
Unable to change research spending after unlocking all items

### ISSUE THREAD

**Issue by thyeggman** [OpenRCT2/OpenRCT2#7773]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 3f8c3c3

Once research has been completed, player is still charged for research and unable to change research spending.

**Steps to reproduce:**
- Unlock all rides/attractions in a level
- Observe inability to change research finding
- Observe continued research spending in financials

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/13246299/42529062-44a9eedc-8432-11e8-8f40-4dd04cdc26bc.png)

![image](https://user-images.githubusercontent.com/13246299/42529074-4be85c10-8432-11e8-9d3f-3ed800f0aa09.png)

**Save File**:
[Leafy_Lake.zip](https://github.com/OpenRCT2/OpenRCT2/files/2181679/Leafy_Lake.zip)

(Reported via discord)

**Comment by James103** [comment]
In OpenRCT2 0.2.6 release (6c3c857), if a scenario starts the research at `RESEARCH_STAGE_FINISHED_ALL` (meaning that no researchable rides are present in the scenario from the start, all rides are either researched or unloaded), you are still charged a (sometimes unavoidable) $100 research bill. This is because the game only kills the funding to the research after up to 2 weeks, instead at the start, if there are no rides that are researchable at the start of the scenario.

**Comment by Gymnasiast** [comment]
@James103 Please create a new issue for that.
