### ISSUE TITLE
Add RCT3's low friction toggle to some rides

### ISSUE THREAD

**Issue by moonheart08** [OpenRCT2/OpenRCT2#7783]
the Low Friction toggle does exactly what you'd expect, it lowers the friction applied to some ride's vehicles (by "using better lubricants" according to the game) in exchange for higher maintenance costs.
The amount it should be lowered by is unknown to me, but in RCT3 this option is insanely useful for some ride designs to help maintain high speed

**Comment by Gymnasiast** [comment]
This deviates too much from classic RCT, but could still be put into a plug-in.

**Comment by e-foley** [comment]
This option was added to RCT3 after the first demo came out because people noticed that some RCT2 tracks imported into the game couldn't make a complete circuit because RCT3's default friction is higher than that of the classic games.

Because RCT2 is already running in "low-friction mode," I'd personally oppose a checkbox that lowers it even further unless it's relegated to a plugin.

**Comment by IntelOrca** [comment]
> This option was added to RCT3 after the first demo came out because people noticed that some RCT2 tracks imported into the game couldn't make a complete circuit.

Correct, I don't see why it would be necessary in RCT2 as a configuration option. You would end up changing the behaviour of all current tracks and any saved TD6s would be incompatible depending on whether you had it enabled or not.

**Comment by moonheart08** [comment]
@e-foley Really? Guess a High-Friction mode would make more sense then, for backporting RCT3 designs if that ever becomes possible. :P

**Comment by moonheart08** [comment]
I'm surprised this is still open. Closing.
