### ISSUE TITLE
Waterfall glitch

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7814]
**OS:** Windows 10
**Version:** 0.2.0-224
**Commit/Build:** 426e106

**Issue explanation :**
I was building a Scenario in the Scenario Editor and i wanted to build a waterfall, i used the tile inspector to lower the waterfalls to the height i needed (since they aren't cheats in the Scenario editor), one did just fine but the other was glitched through the slopped floor and the animation is no longer playing

- [X] Reproducible in RCT2 (vanilla)? and exactly to the Scenario editor 👍 
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.Terraform the terrain so you have a slopped terrain (look at screenshot for better explanation of the angles)
2.Put your waterfalls **above the water**
3. Use the tile inspector to lower the waterfalls to the height of the water and voilà your waterfall is glitched

**Screenshots / Video:**
![2018-07-24 09-38-49](https://user-images.githubusercontent.com/41308252/43123902-e06cda2a-8f25-11e8-85ad-79bb8aa6d563.png)

**Save game:**
[Uploading Glitchy waterfalls.txt…]()

**Comment by L3mmy** [comment]
I'm uploading my landscape file, i am doing it as quick as possible 👍

**Comment by L3mmy** [comment]
Tourns out that if you do the glitch, the waterfall will stop it animation, the waterfall appearing above the ground is just a visual glitch

**Comment by Broxzier** [comment]
This is most likely because for animated objects a 'map animation' is created. The Tile Inspector doesn't do anything with map animations yet, so when moving things around, they don't match the map animation's location anymore. The tile inspector doesn't exist in vanilla RCT2, though I bet that if you load this map in vanilla, the issue will be visible too.
