### ISSUE TITLE
Mechanic Attempts to enter ride via the wrong entrance (Literally) 

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#785]
Mechanics will occasionally attempt to enter a ride to fix it via the wrong entrance. They will walk up the queue and then, because they can't enter via the entrance, will turn around and walk down to the end of the queue, then walk back. Eventually he will correct himself, but generally it will be ages before he does. Picking him up and dropping him at the exit will correct this.

No save attached, will attach when I manage to get one of them to do it again.

**Comment by PFCKrutonium** [comment]
https://www.dropbox.com/s/0vci8felqt8zimu/Crazy%20Castle%20-%20Mechanic.SV6?dl=1

**Comment by PFCKrutonium** [comment]
If you leave it running long enough, in my experience, the game will eventually try using another mechanic, and Mechanic 1 will try, and be stuck in the same loop.

**Comment by Gymnasiast** [comment]
Perhaps it's a pathfinding error?
Have you tested it in vanilla OpenRCT2 as well?

**Comment by duncanspumpkin** [comment]
Mechanic code has not been reversed yet so I'm surprised by this one. It probably happens in the original game as well.

**Comment by PFCKrutonium** [comment]
Updated download link because too many people downloaded from my dropbox (Unrelated)

https://openrct.net/cloud/uploads/7719a9632b1fbd5aab617b333a8354cc.SV6

**Comment by mrtnptrs** [comment]
@PFCKrutonium Could you please provide a save which contains this bug and/or confirm whether this bug still happens or not? Your links to the save file don't work anymore.

**Comment by jensj12** [comment]
Using #3423 you should be able to create one yourself. Pathfinding needs to be redone anyways and staff uses queue lines like normal paths. I still see mechanics entering queue lines, whether it's the same ride or not.

**Comment by IntelOrca** [comment]
@zaxcav @duncanspumpkin possible something that can be fixed now if this still happens.

**Comment by zaxcav** [comment]
I have a savegame with this same behaviour and the current pathfinding improvements I've done (and hope soon to submit in a PR) fix this - in brief, the pathfinding get's closest to the goal following the path to the exit station and doesn't get closer to the entrance station via other paths due to search limits (usually junction limits is the killer).  The changes I've done ignore "no through" paths so will no longer consider walking up the path to the exit station as a way of getting to the entrance station.
