### ISSUE TITLE
Six Flags Carolina Park Crash

### ISSUE THREAD

**Issue by RollerCoaster1234** [OpenRCT2/OpenRCT2#8048]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. 426e106]

Downloaded a park made by 'CedarPoint6' on NEDesigns.com, the community contributes their creations for others to see and explore. The user's upload consist of two parks, one where it shoes everything and one that has no roofing sceneries on the buildings they made. The dump and save files I provided in the zip is from the file with the roofing and showing everything. The other park file is okay, I'm only getting problems from this save file.

Thank you for reading, surprisingly never wrote something fast and hopefully understandable until now.

- [ ] Reproducible in RCT2 (vanilla)? I'm not sure about that, I'm using the triple pack.

**Steps to reproduce:** What is this?
1. 
2. 

**Screenshots / Video:**

A link to where I came across it okay? https://www.nedesigns.com/park/1571/six-flags-carolina/

**Files:**

The Zip consist of the save and dump file. and for clarification --- if that's how you put it --- they're all the same I believe, but look at the bottom that shows the latest date; save and dump.
[Six Flags Carolina Crash report and Save.zip](https://github.com/OpenRCT2/OpenRCT2/files/2444729/Six.Flags.Carolina.Crash.report.and.Save.zip)

**Comment by tombomp** [comment]
Confirmed that the "full" save (not the no roofs one) from the site crashes on the dev version but works fine on 0.2.1. Crashes in `map_update_tiles()` on x=208 y=155 - crashes with a "this is nullptr" exception because `map_get_surface_element_at(208, 155)` returns a nullptr on line 3667 which AsSurface() gets called on. In this save file for some reason there's no surface at that co-ordinate (if you check using the tile inspector) so the function just returns nullptr.

**Comment by RollerCoaster1234** [comment]
I see, very new to this. Thank you for commenting, I have the dev version, guess it's best to stick to the full releases to avoid something like that.

**Comment by Gymnasiast** [comment]
@RollerCoaster1234 No, please stick to the develop versions. They are frequently less buggy than release.

Assuming @tombomp 's diagnosis is correctly, there is something at play, since import code should ensure that every tile has a surface element. However, considering you downloaded the file from NE designs, there is a big chance that there is no room for extra tile elements, so it cannot fix it.

**Comment by RollerCoaster1234** [comment]
I see. At the moment I downloaded the full release and when opening the park, it opened fine and can see where some doesn't have a surface that it creates some kind of repeative frozen textures where I moved from, if you get what I mean. Before I have it a shot, I did try the latest dev version again that was an hour ago when I got to it last night, of course as what Tom said, same occurrence. 

Particularly this park I sorta like to explore, and reading the provided document, the greater mentioned about a block limit and had to delete or never further developed of the area around it. They wanted a full strip mall, a full hotel, a McDonald's, full home depot, a local Italian restaurant, 2 warehouses by the railroad, and apartments. But doesn't look so big compared to some parks or maybe it's just the stuff around it and the park is small.

So this is just happened, could be for another topic but same problem. The Thrope Park recreation crashed, with dump file included.

Thanks for reading.
