### ISSUE TITLE
Game crashes when placing an entrance with Zero Clearance cheat enabled.

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8057]
**OS:**Windows 10
**Version:** 0.2.1
**Commit/Build:** 7fd0571

Often when placing an entrance for a ride, the game crashes. It happened several times to me in the last day.

**Steps to reproduce:**
1. Build ride
2. Place entrance

**Dump file**

[c4e2afc8-022d-4db6-8dab-6a3311fa0d71(7fd0571_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/2452832/c4e2afc8-022d-4db6-8dab-6a3311fa0d71.7fd0571_x86-64.zip)

**Comment by deurklink** [comment]
It looks like it happens when 'Disable clearance checks' is enabled.

**Comment by tombomp** [comment]
This is another "this is nullptr" bug where `footpath_fix_corners_around` is passed an entrance from `footpath_remove_edges_at` at line 2618 in Footpath.cpp when it only deals with footpaths. Looks like the if surrounding the call at line 2616 should include an `&& tileElement->GetType() == TILE_ELEMENT_TYPE_PATH` (or possibly the check should happen slightly earlier)

**Comment by LordMarcel** [comment]
This also happens when either the sandbox or no support limits cheat is enabled.

**Comment by LordMarcel** [comment]
That was what I experienced, but the conclusion was wrong. I did some more tests and it turns out that was not because of the cheats, but because I was trying to build an entrance of a station that was higher than the support limits. It doesn't matter if I have any cheats on, whenever I try to build an entrance on a station that's above the normal support limit of the coaster, I get a crash.
