### ISSUE TITLE
Attempting to build entrance/exit on station 2 does not work

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#8141]
**OS:** Ubuntu 18.04
**Version:** 0.2.1+
**Commit/Build:** e5eb61d38d0d19f2a8869d7eed22180124d92904

If I try to place an entrance or exit on station 2 of Frightmare in the enclosed save, it doesn't work.

So far, I have been able to determine that the bug is already in release 0.1.1, but not in release 0.1.0.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open "Mel's World"
2. Remove five sections of station 1 of Frightmare, build an extra station.
3. Try placing an entrance or exit on Station 2.

**Save game:**
[Mel's World-stationbug.zip](https://github.com/OpenRCT2/OpenRCT2/files/2507791/Mel.s.World-stationbug.zip)

**Comment by tombomp** [comment]
I had a look through but I don't really understand what the code is doing but in case it helps here's what stepping through found. The problem is in `ride_get_entrance_or_exit_position_from_screen_position` in ride\Ride.cpp - on line 7260 it calls `loc_6CD18E` to find a direction but that function returns -1, so the calling function decides the entrance position is invalid. In the particular step through I did mapY == entranceMaxY so it went through the conditional at line 7058 but mapX < entranceMinX meaning the function just falls through to the -1.

**Comment by Gymnasiast** [comment]
Bisecting has shown this was caused by https://github.com/OpenRCT2/OpenRCT2/commit/3313590784842688068f8787edbd2a1511d34fe0.
