### ISSUE TITLE
Add option to choose between RCT1 and 2 ride art

### ISSUE THREAD

**Issue by Assassin877** [OpenRCT2/OpenRCT2#8239]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 0cd7f1e

The ride art between RCT1 and RCT2 differs. It would be nice to have to option to choose between the two.

**Screenshots / Video:**
RCT1:
![rct1](https://user-images.githubusercontent.com/43112034/48158554-21eda780-e2d3-11e8-88cb-4285c10c1ca3.png)

RCT2:
![rct2](https://user-images.githubusercontent.com/43112034/48158560-2619c500-e2d3-11e8-94d1-1d7a3bce6375.png)

**Comment by Broxzier** [comment]
Not sure if this is really necessary. Options like these will likely not be used by the average user, maybe not even 1% of the players, and will just cluster the options window.

If you want to see those previews, most of them already exist as custom objects.

**Comment by Gymnasiast** [comment]
I'm afraid I'll have to agree with Broxzier here, even though I usually preview the RCT1 previews - I think they're usually more pleasing to look at - they seem to feature more vegetation, for example.

Since the objects have been moved to JSON objects, we could change the previews, but that would then be visible to everyone.

**Comment by Horsti12** [comment]
Please make it happen

**Comment by Patrik356b** [comment]
Perhaps a plugin could do this.

**Comment by Gymnasiast** [comment]
@Patrik356b This is not stuff that can be easily put into a plug-in.
As IntelOrca mentions, people can edit their own JSON files, though that isn't _that_ easy - especially since they get overwritten with each OpenRCT2 update, and putting the old files back means you miss any updates to them.

It would be possible to add another parameter to the JSON files with this image, along with GUI options for this feature. But as much as I like the RCT1 artwork, I don't think I can justify the amount of infrastructure for a feature with limited appeal.

What we could do is look at ride pictures individually: if people have a strong preference for the RCT1 variant of a particular ride, we could change it. Though if the RCT1 variant gets picked, I would be in favour of recreating that picture, as RCT1 pictures have a built-in border effect and RCT2 ones don't, which makes them look off in the Object Selection and Inventions List.

**Comment by Patrik356b** [comment]
@Gymnasiast Thanks for the explanation and I do agree on the last sentence.

**Comment by Horsti12** [comment]
I would also like to see this as a option.

@Gymnasiast To remove the border problem I would suggest that the border effect should be also added to the invention list and object selection.
![object selection rct1 art](https://user-images.githubusercontent.com/12634026/50054113-fdd97d80-013e-11e9-8f40-d432266992e2.png)

I already updated my own json files.
RCT1
![rct2 ride window rct1 art](https://user-images.githubusercontent.com/12634026/50054238-2615ac00-0140-11e9-87ac-63f195e77310.png)

RCT2
![object selection rct2 art](https://user-images.githubusercontent.com/12634026/50054296-acca8900-0140-11e9-9e5d-7abf7eababbd.png)

If somebody would implement it, I would help with the json files.

**Comment by archifont** [comment]
I’d love to have the RCT1 icons, that’s how I remember the game from the earlier days!

What has to be exactly changed in the JSON files? Idid find for example in the Bobsleigh coaster JSON file the line that has to do with the image:

` "images": ["$RCT2:OBJDATA/BOB1.DAT[0..2706]"],`

What do I need to modify in order to get the RCT1 icon? (I have both the installations oft RCT1 and 2).

**Comment by Gymnasiast** [comment]
The first three images are the icons (there are three of them because RCT2 allows a vehicle to work on up to three ride types, but no official vehicle uses this). You can leave the second and third image blank.

`"images": ["$CSG[offset]", "", "", "$RCT2:OBJDATA/BOB1.DAT[3..2706]"]`

You will need to look up at which offset CSG1.DAT saves the image you want and modify the first entry accordingly. Do note that you will need to have RCT1 linked to OpenRCT2, and that updating OpenRCT2 typically also overwrites the JSON objects.

**Comment by archifont** [comment]
> The first three images are the icons (there are three of them because RCT2 allows a vehicle to work on up to three ride types, but no official vehicle uses this). You can leave the second and third image blank.
> 
> `"images": ["$CSG[offset]", "", "", "$RCT2:OBJDATA/BOB1.DAT[3..2706]"]`
> 
> You will need to look up at which offset CSG1.DAT saves the image you want and modify the first entry accordingly. Do note that you will need to have RCT1 linked to OpenRCT2, and that updating OpenRCT2 typically also overwrites the JSON objects.

Great, thanks for the swift reply!

**Comment by Gymnasiast** [comment]
More specifically: the offsets start at 64195. You then need to add the RCT1 ride type id, as listed here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/rct1/RCT1.h#L775-L859

**Comment by Gymnasiast** [comment]
Since this is not going to be implemented in the game itself, I'm closing this.
