### ISSUE TITLE
BACKTRACE 7d8b76 infinite loop inside vehicle_update_track_motion

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8393]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/7d8b76ccd67e045c20a1e912915319f23b8a66033dbb398f692fb47d75d9a4a9?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Dec 09 2018 01:24:51)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\maste\\OneDrive\\Documents\\OpenRCT2\\6a993813-cb24-4943-a272-51e5bb3fed63.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\maste\\OneDrive\\Documents\\OpenRCT2\\6a993813-cb24-4943-a272-51e5bb3fed63.sv6.gz: <em>1</em><br><strong>commit:</strong> dc7d141: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>vehicle_get_head -> vehicle_update_crossings -> vehicle_update_track_motion_forwards -> vehicle_update_track_motion -> vehicle_update_moving_to_end_of_station -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by bdupree5** [comment]
My team and I would like to work on this issue, we will update you as we continue to work on it.

**Comment by janisozaur** [comment]
Cool. The park attached should reproduce the issue.

**Comment by bdupree5** [comment]
So when i try to load the save my game freezes. Is this what is suppose to happen?

**Comment by janisozaur** [comment]
Either that or crash. The issue was originally reported with https://github.com/OpenRCT2/OpenRCT2/commit/dc7d14163ff7ca1f9d0e52df4855479b2d1c0d11 so you can check what happened on that commit just to be sure. In any case, it shouldn't hang just continue working normally. I can't check right now, but judging by the call stack I imagine there is list traversal at the bottom, which loops. You can brake the cycle using tortoise and hare algorithm.

**Comment by IntelOrca** [comment]
There is an example of tortoise and hare in `find_sprite_list_cycle` which you can refer to.

**Comment by bdupree5** [comment]
Just wanted to let you know that we couldn't figure out a way to fix this issue.

**Comment by w-flo** [comment]
The root cause might be that there's a guest using sprite ID 1183 and apparently there is also a car on that launched coaster close to the park entrance using sprite ID 1183 (according to debug output I added in the S6Importer, it's on the train that has head vehicle 1537). For what it's worth, the sprite_identifier for sprite 1183 is set to 0 (SPRITE_IDENTIFIER_VEHICLE), so it seems like the peep sprite was created first and then overwritten with vehicle data. It also has a linked_list_type_offset of 10 (UNKNOWN).

I'm not sure yet why the next_vehicle_on_train value for vehicle 4183, which is the next car after 1183 in that train, is incorrectly set to 0 even though it should be 0xFFFF (since it's the last car in the train). That value is apparently the reason for this specific infinite loop. Maybe the guest corrupted 1183 and that somehow lead to corruption in 4183, too. Or maybe there is more corruption in other places.

Now I'm not sure if I got all the corruption details right. I wonder if the fact that sprite 1183 is used for two different things is just another level of corruption that was caused by something else, or if that is actually the first thing that went wrong and causes all kinds of issues. It seems like that park intentionally produces lots of crashes (according to recent ticker messages), so maybe that somehow caused a sprite to end up in both lists, the one for unused sprites and the one for peeps?
