### ISSUE TITLE
Unable to save track with colon symbol in name of ride

### ISSUE THREAD

**Issue by MisterSchmidt** [OpenRCT2/OpenRCT2#873]
Its not possible to save a track when there is a colon symbol in the name like the screen below.

Nothing happens if you press "save track design" maybe an error would be the solution if its too hard /impossible to fix.

![nodoubledotsave](https://cloud.githubusercontent.com/assets/11180804/6377774/f668195e-bd26-11e4-9cbe-3954ec8ec55f.jpg)

**Comment by Gymnasiast** [comment]
That's possibly Windows choking on the colon, since those are reserved for drive letters. (In the same way Windows garbled the file names of Linux network shares if they contained colons).

Probably solveable by filtering the proposed file name for special characters like the colon, the asterisk, the question mark, etc. (Perhaps SDL has a function for this?)

**Comment by IntelOrca** [comment]
DId this happen in the original game?

**Comment by duncanspumpkin** [comment]
Yup it happened in the original since the file name is the ride name and vice-versa.

**Comment by Nubbie** [comment]
@duncanspumpkin 
If there would be a error message popping up, would it be something like `STR_3346    :Can't save track design...` or more of a custom message that tells the user why? Like that it can't use colons in names

**Comment by duncanspumpkin** [comment]
There would be no harm in making it a custom one with the limitations stated.

**Comment by Gymnasiast** [comment]
Or just get rid of the incorrect characters. I find an error message a lot less helpful. 
This would preferable be done on platform level, as Linux can handle colons in filenames without any problems.

**Comment by IntelOrca** [comment]
> Or just get rid of the incorrect characters. I find an error message a lot less helpful. 
This would preferable be done on platform level, as Linux can handle colons in filenames without any problems.

It isn't ideal though if you want to share those track designs. Allowing those characters should wait until we have our own format where we can store a non-constrained full UTF-8 name.

**Comment by AaronVanGeffen** [comment]
So, rather than failing silently, it's best to just strip the offending characters for now, then, right?

**Comment by Christipher** [comment]
This I think probably should be held off until during the implementation into the Standalone build (late fifth stable) as if we are already seeing the standalone build impending, plus, windows typically chokes on those things.  With windows you can't actually save a file with such a name, though you can (and this is why I'm calling hold off on this since this will cause issues with backwards compatibility) have it so that the data written to the file is different than the file name, so that you can also save multiple tracks with the same name (so in the case of Goliath, the first would be Goliath, the second would have the file name Goliath1, the third Goliath2, and so forth but all would return the name "Goliath" when you go into the prebuilt ride menu for that particular type).

**Comment by Patrik356b** [comment]
There is actually a very simple way to temporarily overcome the issue: use a character that is supported with a character code. 

Like web pages might do %20 for "white space". 
It is not ideal though because it would only work in OpenRCT2. (see http://www.w3schools.com/tags/ref_urlencode.asp for an example)
