### ISSUE TITLE
Last Action details not set for clients when using GameActions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8798]
The Last Action details are not set client side. This means admins cannot see what users have been doing. This only affects game actions but as we move more over to the new framework it is becoming more obvious. (Server side this does work)

Game commands log it within the ProcessCommands loop. https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/network/Network.cpp#L1890-L1977
```
player->LastAction = NetworkActions::FindCommand(command);
player->LastActionTime = platform_get_ticks();
player->AddMoneySpent(cost);
```
a similar solution will be required for game actions.

**Comment by ZehMatt** [comment]
I'm looking at the GameAction::Execute right now and it does call 'network_set_player_last_action' which sets the LastAction and LastActionTime also it calls 'network_add_player_money_spent' which calls 'player->AddMoneySpent'

The only difference right now is that this is only done server side, which is actually the right way to do it, if you were to set it both on client and server then late joined clients would otherwise not see what was done before joining. I think the reason it doesn't work properly right now is because the player list is not synchronizing those values.
