### ISSUE TITLE
Raising water shows money effect at the bottom rather than new height.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8804]
![2019-03-01_08-12-14950eca2339200d9f5](https://user-images.githubusercontent.com/5415177/53622449-20d1e480-3bfa-11e9-9bf4-11efce595b99.gif)

The original doesn't do this, instead it would show the money at the new height.

**Comment by duncanspumpkin** [comment]
This would get fixed when porting to game actions.

**Comment by tomlankhorst** [comment]
> This would get fixed when porting to game actions.

Why?

**Comment by AaronVanGeffen** [comment]
Presumably because #8799 implements it.

**Comment by duncanspumpkin** [comment]
#8799 doesn't fix it but as part of the conversion I'd be using the same code for lower and raise.

**Comment by tomlankhorst** [comment]
That's even better.

**Comment by duncanspumpkin** [comment]
Okay lol found the issue. `!=` `!=` `==`

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Map.cpp#L1512
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Map.cpp#L1425

They should both be `==`. Since this is such an easy fix I'll change it to a good first issue and someone can do it whenever as not sure when game action conversion will be.
