### ISSUE TITLE
Virus False Positive

### ISSUE THREAD

**Issue by GigaG11** [OpenRCT2/OpenRCT2#8923]
Windows 10
OpenRCT2 0.2.2-077 (68aa512)

OpenRCT2.exe is detected as a virus false positive by Norton, along with several other antiviruses according to VirusTotal.  I am running the x86 version. (x64 is currently unavailable.)

**Comment by Krutonium** [comment]
There's nothing we can do about this, aside from blame the Antivirus Companies. I've contacted a lot of them, and some of them have fixed it, at least temporarily. Because we release builds so often, they frequently flag them because they are similar to other executables that they know, but not quite, which is a thing that viruses used to frequently do, where they change an executable just a little bit. Regardless, the solution is simple: Contact Norton and complain.
