### ISSUE TITLE
Fails to build on Mac OS X without SDL2 port installed

### ISSUE THREAD

**Issue by ian-h-chamberlain** [OpenRCT2/OpenRCT2#895]
Hi – I just cloned this repository and attempted to build using the `install.sh` and `build.sh` files included, using Mac OS 10.10 and `homebrew`. It seems that the `install.sh` file did not include everything necessary for building; I had to manually run `brew install sdl2` in order for the project to build using `build.sh`. My understanding is that it would be easy enough to simply add sdl2 to the `install.sh` file to fix this, but perhaps I am mistaken.

**Comment by IntelOrca** [comment]
I think it was something to do with being able to install SDL2 without super user permission, but not sure. @mzmiric5 Any ideas?

**Comment by mzmiric5** [comment]
Um, well basically the `install.sh` actually downloads the SDL2 library and sets it up to be usable enough to run. I'm not sure why it would have failed for you @ian-h-chamberlain . Do you remember if there was any output warnings or errors when you ran `install.sh`? This will all change once we set up a full interactive build system.

The main reason why we are not using just `brew install sdl` or whatever the linux equivalent would be, is probably because we need to do some patching on sdl in order to support the mingw compiler we are using at the moment. This is what `install.sh` does after it downloads sdl.

Anywho @ian-h-chamberlain if you can provide us with some more details we might be able to do some more investigating on what causes this issue.

**Comment by ian-h-chamberlain** [comment]
Okay, I just ran `brew uninstall sdl2` followed by `install.sh` to see if I could get the error messages from before back – interestingly, I got no errors and `build.sh` seems to run just fine.

Unfortunately, like a fool, I didn't save the error output on build previously. I do remember that the error had to do with `CMakeLists.txt` (or maybe `CMakeLists_mingw.txt`), and in particular had to do with the `PKG_SEARCH_MODULE(SDL2 REQUIRED sdl2)` line. The final build error was related to finding a particular `.obj` file, I think.

Sorry I can't be more helpful, I really should have saved the error output. It's also possible that something was funky with my setup, but now it seems to be working as expected.

**Comment by kevinburke** [comment]
Wondering if we could save the install logs in timestamped log files... then they wouldn't get overwritten all the time

**Comment by Gymnasiast** [comment]
Now there are native OS X builds and Wine is no longer supported on OS X, I think this can be closed.

**Comment by Gymnasiast** [comment]
Closing this as OS X has gained native builds in the meantime and Wine is not supported on OS X anymore.
