### ISSUE TITLE
Can't place stalls "Can't construct this here...(Undefined String)"

### ISSUE THREAD

**Issue by Bamaman11** [OpenRCT2/OpenRCT2#8957]
**OS:** [Windows 10]
**Version:** [0.2.2]
**Commit/Build:** [9cbc308]

Playing Lightning Peaks and get an error trying to place stalls in valid tiles and positions:
"Can't construct this here...(Undefined String)"

Was able to toggle disable clearance checks a few times and build stall successfully

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Play Lightning Peaks, no cheats enabled
2. Try to place stall
3. Error pops up

**Screenshots / Video:**

![OpenRCT2_Bug](https://user-images.githubusercontent.com/15695743/54885086-7f2f6300-4e46-11e9-96f1-e1161e1625cf.PNG)

**Save game:**

[Lightning Peaks_Bug.txt](https://github.com/OpenRCT2/OpenRCT2/files/3000792/Lightning.Peaks_Bug.txt)

**Comment by duncanspumpkin** [comment]
Please fill out the template correctly. What version is this on?

**Comment by Bamaman11** [comment]
Sorry about that, first bug that I have reported. Had updated the OS and build/commit, but hadn't deleted the e.g.  If there is anything else I missed, please let me know.

**Comment by duncanspumpkin** [comment]
Thats fine. I just see the e.g. and assume it hasn't been filled out.

**Comment by benhhopkins** [comment]
Upon opening the save it looks like there isn't enough funds to build a stall (with enough funds it constructs fine for me). Still a bug though since it should display the funds error message.

It looks like the error is coming from the z attempts to place the object at half-heights. These errors are overriding the correct missing funds errors generated at other z values.
https://github.com/OpenRCT2/OpenRCT2/blob/d41822e0f50596ddc2071e35a93a29418b8c8540/src/openrct2/actions/TrackPlaceAction.hpp#L202-L205

I'll defer to the people who've been recently working on this game action, just thought I'd take a quick while trying to learn your codebase.

**Comment by ZehMatt** [comment]
This should be fixed, can you confirm that it works now?

**Comment by djb140419** [comment]
OS: Win 7
Version: 0.2.2
Build: 298c9f8

Getting this error in scenario Electric Fields (same issue - not enough cash to build, with enough cash there's no problem)

Screenshot:
![BUG_stall-undefined-string_Win7-32_0-2-2_298c9f5](https://user-images.githubusercontent.com/49607454/56090245-fc775200-5e9f-11e9-9b87-22a57125452c.png)

Save:
[BUG_stall-undefined-string_Win7-32_0-2-2_298c9f5_Electric-Fields.txt](https://github.com/OpenRCT2/OpenRCT2/files/3077169/BUG_stall-undefined-string_Win7-32_0-2-2_298c9f5_Electric-Fields.txt)

**Comment by aw20368** [comment]
@ZehMatt I just checked that this is fixed on latest develop (the report above was on 0.2.2 release, before the relevant PR).

![NoMoneyUndefined](https://user-images.githubusercontent.com/29646196/59164485-4b75e800-8adb-11e9-92bb-7b74b6ae13c5.png)

**Comment by James103** [comment]
Not completely fixed in the above image, only the bottom text "Not enough cash - requires $250.00" shows and not the top text "Can't construct this here". Is that also fixed?
