### ISSUE TITLE
Station style drop-down list is untranslated

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#8994]
**OS:** GNU/Linux
**Version:** 0.2.2
**Commit/Build:** (stable)

- [ ] Reproducible in RCT2 (vanilla)? No idea, but I don't believe this is the case
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Play in German
2. Click on a roller coaster
3. Click the paint brush tab
4. Use the drop-down list for station styles

Expected result: All station style names are in German.
Actual result: All station style names are in English.

This is a regression. It worked in 0.2.1 but now it is broken in 0.2.2.

**Comment by AaronVanGeffen** [comment]
These are translated using the object files nowadays, and no longer through the `de-DE.txt` language file. It's entirely possible the object files do not have the appropriate strings in German yet.

**Comment by Wuzzy2** [comment]
How is this not a bug? At the end of the day, these strings are *not translated* but were before.

Also, I want to guess that other languages are affected as well.

**Comment by AaronVanGeffen** [comment]
It is not a bug, but a localisation issue. The strings were changed in English as well, so I think the author of the new station objects opted for re-translation instead of copying the old ones.

Feel free to PR new translations strings against [the objects repository](https://github.com/OpenRCT2/objects).

**Comment by Gymnasiast** [comment]
They are untranslated because the strings have moved to the objects repository, as documented https://github.com/OpenRCT2/Localisation/issues/1625 . You can downvote Aaron all you like, but he is right, and downvoting will not change anything.

Rather than being so arrogant, why don't you add those translations yourself? Currently, you're wasting everyone's time, including your own.
