### ISSUE TITLE
Feature: Tool to remove corrupt elements

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#9051]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 6afd0dc

Corrupt elements are very useful for making stuff invisible, but are annoying to remove if you decide to remove a ride. Sometimes on my server a person drops out during the round, and it often leaves behind corrupt elements which will make stuff invisible later during the round if they don't get removed. It would be very useful (in my opinion) to have a tool like the scenery removal tool that removes any corrupt elements on those tiles. Not sure where it could fit nicely it in the UI though.

**Comment by duncanspumpkin** [comment]
Would require a new game action. (which doesn't mean it can't be done I'm just listing the things that would be needed). Its quite easy to modify the scenery clear tool for additional items. We aren't too far off new save format and hopefully when that comes out we can get rid of the idea of corrupted elements and just have a simple tick box that decides if an element should render.

**Comment by IntelOrca** [comment]
Perhaps we could auto remove corrupted tiles if all items between the surface element and the corrupted element are removed and the corrupted element is at the top.

**Comment by ocalhoun6** [comment]
>Not sure where it could fit nicely it in the UI though.

Right there with the scenery removal tool, of course. Would it be too resource-intensive to have the scenery removal tool check the map for corrupt elements and only show the button for removing them if there are corrupt elements on the map? That way, you could avoid confusing new players who don't know what corrupt elements are, without having to have an option to enable/disable it.

>when that comes out we can get rid of the idea of corrupted elements and just have a simple tick box that decides if an element should render.

When that happens, the corrupt element remover could simply be changed from 'remove corrupt elements' to 'remove invisible objects'. It would still be pretty useful.

Oh, and I guess in that case, you'd also want a new view mode of 'show invisible objects' that would override the tick box setting so that you could see everything that you've hidden.

Actually, for that matter... #9056

**Comment by deurklink** [comment]
I'll close this because plugins have been made for it
