### ISSUE TITLE
Introduce a cooldown for kicked players.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9234]
I've talked to a few people who run OpenRCT2 servers and one thing that always comes up is that they can't do much about trolls other than kicking them right now, but that doesn't prevent them from coming back right away, so the idea is the moment when a player is kicked he will get a cooldown on IP basis for lets say 10 minutes so he won't be able to just immediately reconnect. I think this should at least minimize the amount of annoyance those people can bring onto the servers and is very simple to implement.

**Comment by deurklink** [comment]
I would love to see this happen, because kicked players usually keep coming back using different names until you change the standard role to mute, or until you use the 'block unknown players' option, both options I don't like to use for an extended time.

**Comment by CorySanin** [comment]
I created [a plugin](https://github.com/CorySanin/openrct2-ffa-plugin-suite/blob/master/lib/ip-ban.js) that does this. The default is 60 minutes, but the timeout period can be adjusted via plugin.store.json:
```json
{
    "ip-ban": {
        "timeout": 10
    }
}
```
At the time of writing, the only way to kick a player and have this ban take effect is to assign the player the "IP-BAN" group. This method of selecting a player is not as error prone as issuing a command in chat and can be done very quickly. It also leaves the built-in kick functionality intact, which I find useful.

In any case, I think this can be closed because virtually any variation of this feature can be implemented as a plugin now.
