### ISSUE TITLE
Replace repeated 3d to 2d functions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9288]
Related to #8723. There is also repeated implementations of the 3d to 2d function `coordinate_3d_to_2d` https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Map.cpp#L140-L164

For example https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Sprite.cpp#L643-L664 should be replaced by using the already implemented function. To complete this issue the codebase should be searched for any other instances of this function. Perhaps a search such as `(*y + *x) / 2 + *z` where * is a wild card would show up instances of this function. Unsure what would be the best way to find them.

In addition make sure  all local variables are in lower camelCase and all function names are in upper CamelCase. https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by aw20368** [comment]
I'll start working on this. Also do we still need someone to do #8723?

**Comment by duncanspumpkin** [comment]
Nothing needs to be done with 8723 just that it's a similar exercise.

**Comment by aw20368** [comment]
I meant, since the person saying that they would do 8723 hasn't gotten around to it, can someone (i.e. myself) take that one on as well?

I believe that I've found all of them, I did a search for `.*/.*[^3]2.*-`, which turned up under 200 results, a lot of false positives but small enough to go through them all. I also searched for `switch.*direction` and `switch.*rotation` to make sure I didn't miss anything.

There are two instances where the inputs are int32_t but `coordinate_3d_to_2d` uses int16_t (for example, https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Map.cpp#L2048-L2072). I don't think the coord numbers go that high, so is it safe to just cast them into int16_t? Or should I overload `coordinate_3d_to_2d`?

**Comment by duncanspumpkin** [comment]
We are trying to move the codebase to use coordsXY+ for everything where sensible/possible which is 32bit but yes all values are currently in the 16bit range. I want the 3d to 2d function to eventually be a member function of coordsXYZ+. Really the function should return an appropriate struct instead of take the two pointers but at this moment i don't know what struct would be best.

Yes feel free to take on the other issue as well.

**Comment by aw20368** [comment]
In that case, instead of replacing the repeated code with the 16bit `coordinate_3d_to_2d`, should I replace it with the 32bit CoordsXYZ version `translate_3d_to_2d_with_z`? (https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Map.cpp#L2048-L2072)

**Comment by duncanspumpkin** [comment]
Lol see that is exactly why i want to consolidate it into one. Yes replace it with that one. I don't like it returning a CoordsXY though as it's really a screen coordinate and not a tile coordinate but I'm not sure we have a separate name for that right now. In openloco we have gfx::point.
