### ISSUE TITLE
Trying to delete ride piece while paused does move the selection

### ISSUE THREAD

**Issue by SijmenSchoon** [OpenRCT2/OpenRCT2#9314]
**OS:** Linux
**Version:** 0.2.2
**Commit/Build:** abf72eda7f0b60399e79018ec5f2ce12c4c0008a

When trying to delete a ride piece while the game is paused, the previous ride piece does get selected. This should not happen, as the ride piece is not removed.

This does _not_ happen in vanilla.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start building a roller coaster, and place some track pieces
2. Pause the game
3. Press the delete button

**Screenshots / Video:**
[Video](https://i.imgur.com/jhVHvvZ.mp4)

**Comment by SijmenSchoon** [comment]
This seems to have been introduced with the refactor to a TrackRemoveAction

**Comment by aw20368** [comment]
I'll investigate this. At first glance it seems that TrackRemoveAction is missing a `game_is_paused()` check and I've tested that adding 
```
if (!(GetActionFlags() & GA_FLAGS::ALLOW_WHILE_PAUSED))
{
    if (game_is_paused() && !gCheatsBuildInPauseMode)
   {
       return MakeResult(
           GA_ERROR::DISALLOWED, STR_CONSTRUCTION_NOT_POSSIBLE_WHILE_GAME_IS_PAUSED);
    }
}
```
to TrackRemoveAction::Query() will stop the player from removing the track while paused.

However the problem might be somewhat deeper based on the following observations:
1. Adding that above "fix" gives the wrong error message: "Can't construct this..." instead of "Can't remove this..."
2. TrackPlaceAction has that above code, but debugging shows that it does not run when I try to build a track while game is paused. I assume that the paused error is caught earlier, and the action is aborted before hitting that code.
3. Other actions also give the "Can't construct this..." message when paused. For example, trying to remove a footpath doesn't display "Can't remove footpath from here...". It looks like this is a related bug.

**Comment by duncanspumpkin** [comment]
Yeah the common error messages (pause, insufficient funds) are broken right now (the error message isn't always correct). It will get fixed eventually.

The pause check is meant to happen elsewhere within the game action calling code. See GameActions::Query. I suspect the mistake is in the function calling the query.
