### ISSUE TITLE
Attempting to build fence across tracks returns a "land not owned" error

### ISSUE THREAD

**Issue by aw20368** [OpenRCT2/OpenRCT2#9354]
**OS:** Windows 7
**Version:** 0.2.2+
**Commit/Build:** 3ee6be0db

Self-explanatory screenshot below. While this may be related to #4480, it's probably not the same issue since I am not able to repro this in 0.2.2 or before; it gives a normal "can't build this here...". I've checked that this is neither caused by nor will be fixed by my PR #9341.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a piece of track.
2. Try and build a fence where the track occupies.

**Screenshots / Video:**
![FenceNotOwned](https://user-images.githubusercontent.com/29646196/58775556-0b22e100-8594-11e9-9f4e-70b8b67853fb.png)

**Comment by AaronVanGeffen** [comment]
Maybe have been caused by one of the recent game action refactor PRs (place wall?)

**Comment by duncanspumpkin** [comment]
Yeah it will be using the wrong error message after doing the interaction check.

**Comment by cheweytoo** [comment]
This also happens when a wall or fence build attempt collides _with the side_ of a ride track:

![wall_collision_wrong_error_message](https://user-images.githubusercontent.com/29800630/63217351-48cfe880-c145-11e9-9fb4-8af0892b5162.png)

I tried to find out why this happens in WallPlaceAction.hpp, but got a bit lost.
( STR_CANT_BUILD_PARK_ENTRANCE_HERE has the wrong name, hasn't it? )

The correct error message is shown for shrubs etc. that go in a quadrant of tile and not on its edge.

**Comment by Ruedii** [comment]
Right result: error out
Wrong error: Should say "{RideName} is in the way"

**Comment by Gymnasiast** [comment]
This consists of two issues: https://github.com/OpenRCT2/OpenRCT2/issues/10196 (behaviour) and https://github.com/OpenRCT2/OpenRCT2/issues/10701 (error message).
