### ISSUE TITLE
Deleting an underground path with a banner causes crash 

### ISSUE THREAD

**Issue by fafeitsch** [OpenRCT2/OpenRCT2#9396]
**OS:** Ubuntu 18.04.2 LTS
**Version:** `0.2.2-develop-0~7499-201906091155-g993709c~ubuntu18.04.1`

When you delete (i.e. rightclick on a path) going from the upper left to the lower right corner of the screen, the game crashes.
This issue might be related to issue #8526 though this one is single player. Could not test it on multiplayer.

**Steps to reproduce:**
1. Open an arbitrary scenario map (I tested it with RCT1 and RCT2 scenarios)
2. find or build a path
3. rotate your view so that the path goes from the upper left corner of the  screen to the lower right corner of the screen (see screenshot).
4. Open the Scenery(Szenerie in german, do not know english translation) dialog and select a banner.
5. While having the banner in your hand, right click (i.e. delete) a piece of the path (marked with red in the screenshots)
6. the game hangs and must be killed with SIGKILL.
7. If you right click on a path not going from upper left to lower right then everything works as expected, that is: the path vanishes and I get 10 Euros worth of money.

This error message appears on the command line infinitely:

`ERROR[/build/openrct2-Xk7X9u/openrct2-0.2.2-develop-0~7499-201906091155/src/openrct2-ui/../openrct2/actions/BannerRemoveAction.hpp:60 (Query)]: Invalid banner location, x = 2656, y = 2752, z = 64, direction = 3`

**Screenshots / Video:**
![banner_crash2](https://user-images.githubusercontent.com/842642/59218735-34112a80-8bc1-11e9-8c11-4cd126a2f118.png)
![banner_crash](https://user-images.githubusercontent.com/842642/59217771-fd3a1500-8bbe-11e9-8354-3180e4eab907.png)

**Comment by aw20368** [comment]
I'll take a look at this.

I can repro this on Windows, latest develop. I checked that it does not freeze in 0.2.2. 

Note: It's not just underground, and instead of the direction having to be specifically top-left -> bottom-right...it crashes when the banner matches the direction of the path (i.e when it's possible to place the banner at that tile). Based on the command line error, something goes wrong when it tries to remove the ghost banner.

![BannerPathCrash](https://user-images.githubusercontent.com/29646196/59220464-057c5b00-8b93-11e9-895b-f2bb93f66507.png)

**Comment by aw20368** [comment]
@duncanspumpkin I'd like a bit of help on this, as the resolution isn't obvious. An infinite loop occurs at
https://github.com/OpenRCT2/OpenRCT2/blob/288921132d628a79cb406502a3b0ec40fe37487e/src/openrct2/actions/FootpathRemoveAction.hpp#L149-L164
`ExecuteNested(...)` calls `BannerRemoveAction::Query()`, shown below, where `GetBannerElementAt()` returns a `nullptr` since the banner is a ghost. So the tileElement isn't ever removed, leading to the infinite loop above.
https://github.com/OpenRCT2/OpenRCT2/blob/288921132d628a79cb406502a3b0ec40fe37487e/src/openrct2/actions/BannerRemoveAction.hpp#L56-L62

Before the GameActions refactor, the old `BannerRemove()` function look like it removes regardless of whether the banner is a ghost: https://github.com/OpenRCT2/OpenRCT2/blob/aa65e25c6b0c7c0e5148ce1de2f1b59900e7105c/src/openrct2/world/Banner.cpp#L62-L118
So I tested by making `GetBannerElementAt()` return a `BannerElement*` even if the banner is a ghost (i.e. deleting lines 145-146 from BannerRemoveAction.cpp below) which seems to work. However, I'm not sure whether this is the right change and whether this would introduce other issues.

https://github.com/OpenRCT2/OpenRCT2/blob/288921132d628a79cb406502a3b0ec40fe37487e/src/openrct2/actions/BannerRemoveAction.hpp#L132-L154

**Comment by duncanspumpkin** [comment]
Yeah its not passing the correct flags to the nested function call. Shouldn't be hard to fix.
