### ISSUE TITLE
Certain 4-station rides can't be saved properly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#9472]
**OS:** Ubuntu 19.04
**Version:** 0.2.2+
**Commit/Build:** a0b77c4bf

Copied from https://forums.openrct2.org/topic/3833-certain-4-station-rides-cant-be-saved-properly/

Original text:
` After saving, some 4 station rides will be blank in the ride previewer. When trying to build them, nothing happens except an empty ride construction window opening and, if money is involved, an immediate build and delete transaction. From my testing, it seems that a faulty saved ride can be made by creating a 4 station ride in a way such that station 1 of the saved ride would be longer than 2 segments, though I don't know if it's the only way. Original RCT2 seems to have the same problem but simply raises an access violation upon selecting the faulty saved ride.

I've attached a save file with the same coaster in 4 rotations, with one station being 3 segments long and the others 2 segments long. The one named "4station fail" produces a faulty track file. I've also attached the faulty and non-faulty track files.﻿`

**Save files**
Can be downloaded from https://forums.openrct2.org/topic/3833-certain-4-station-rides-cant-be-saved-properly/

**Comment by jensj12** [comment]
Probably related: #6123

**Comment by duncanspumpkin** [comment]
Its to do with there being 4 stations and it tries to allocate a 5th. Still trying to work out why its doing that. Looks like some sort of issue in the code that checks the station pieces or perhaps the backwards check that works out the start of a coaster.

**Comment by duncanspumpkin** [comment]
Okay I've worked it out. When you have four stations you pretty much are guaranteed to cause it break if your first station is >2 pieces long. This happens because the start of the ride is marked by the first station piece it then iterates forward around the track. For every station it encounters it checks to see if its connected to another station and if not allocates it a new station number. The problem happens when it gets back to the first station. By this point it has already allocated every station number and it doesn't realise that it is connected to the first station.

**Comment by Ryder17z** [comment]
don't close it, if it's still an issue.
This one can't be built: [Steel Twister 1.zip](https://github.com/OpenRCT2/OpenRCT2/files/4146416/Steel.Twister.1.zip)
created with: 3f837f5 today
