### ISSUE TITLE
OpenRCT2 freezes computer

### ISSUE THREAD

**Issue by TheDude53** [OpenRCT2/OpenRCT2#9554]
**OS:** Windows 10
**Computer:** Lenovo ideapad 100s series laptop
**Version:** 0.2.3

When I open the OpenRCT2 program from the launcher, the game freezes the whole computer (which I have to manually hold the power button to restart) before anything comes up on the screen. I am not sure if it is possible to reproduce or if it is related to my computer's performance. I could also not find any dump files.

**Comment by jensj12** [comment]
How long did you wait before switching off your computer? Can you run the original RCT2 properly? Since you mentioned the launcher, is the problem specific to the launcher? Are you aware of any other issues on your laptop (other freezes or low storage or ram)?
I don’t know what could have caused your entire computer to freeze and not just OpenRCT2. Did you try to close it using the task manager (ctrl+shift+esc+hold until it pops up)? Note that closing a frozen program may still take a few minutes.

**Comment by ZehMatt** [comment]
I would suggest you give your Laptop a better look on what might be wrong, OpenRCT2 is unlikely to be the actual issue and rather triggers an already existing one, try to run a few tools like Prime95 to see how your Laptop reacts under stress.

**Comment by TheDude53** [comment]
I waited about 5 minutes before manually powering down the computer. I only have the data files; not the RCT2.exe . My laptop has about 6GB of space free and 2GB of RAM and works fine with everything else. The launcher works fine (I tried the develop and release branches). The entire computer was frozen, Ctrl+Alt+Delete did not work, the mouse did not move, even the clock stopped.

**Comment by Broxzier** [comment]
Try opening OpenRCT2 while you have task manager open on the process tab and have the CPU, Memory, Disk usage and GPU columns visible. It may give us some insight on what the bottleneck is exactly.
