### ISSUE TITLE
FHS: Game binary location

### ISSUE THREAD

**Issue by Berbe** [OpenRCT2/OpenRCT2#9748]
**OS:** GNU Linux
**Version:** 0.2.3
**Commit/Build:** ac7a1ebf71566afb093befcb8293406c1a4025b4

According to the [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html), games shall be placed into `/usr/local/games`, not `/usr/local/bin`.
If you want for users to benefit from `$PATH` environement variable discovery, I don't know if creating a symlink in `/usr/local/bin` is appropriate or if it shall be left to the user to add `/usr/local/games`.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by janisozaur** [comment]
Would you submit a PR?

**Comment by janisozaur** [comment]
To be honest though, I'm not sure if I've ever seen a game that would use this. Not even fortune https://www.archlinux.org/packages/community/x86_64/fortune-mod/, supertuxkart https://www.archlinux.org/packages/community/x86_64/supertuxkart/, 0ad https://www.archlinux.org/packages/community/x86_64/0ad/ or wesnoth https://www.archlinux.org/packages/community/x86_64/wesnoth/ use that location, so I'm not really sold yet on that.

**Comment by IntelOrca** [comment]
Or OpenTTD:
https://www.archlinux.org/packages/community/x86_64/openttd/

**Comment by janisozaur** [comment]
@IntelOrca sure, that too, but I specifically provided a list of fully libre projects, which would be more likely to follow FHS.

**Comment by ryao** [comment]
Anything under `/usr/local` in Linux distributions is managed by the system administrator rather than the package manager. Some distributions might have it in PATH while others might not. Some distributions with `/usr/local/games` also have create a `/usr/games` directory, which isn't in the Linux FHS. In Gentoo, we have our own FHS that is very similar to the Linux FHS, but it lacks a `/usr/local/games` directory because it simply does not make sense:

https://devmanual.gentoo.org/general-concepts/filesystem/index.html

The system administrator could always add it if he wants, but no distribution following the Linux FHS should be using `/usr/local/games` for a user or putting games into the non-standard analog `/usr/games`. I can't imagine any system administrators using `/usr/local` with OpenRCT2 would want this behavior changed, even on Linux systems that follow the Linux FHS to the letter.

Furthermore, OpenRCT2 works on systems where the Linux FHS doesn't apply. Rather than adapt this project to follow the Linux FHS' suggestion, I think that it should be ignored for portability purposes and that it should be deleted from the next revision of the Linux FHS. What system administrators do there is up to them.

That is my opinion on the subject.

**Comment by ryao** [comment]
> To be honest though, I'm not sure if I've ever seen a game that would use this. Not even fortune https://www.archlinux.org/packages/community/x86_64/fortune-mod/, supertuxkart https://www.archlinux.org/packages/community/x86_64/supertuxkart/, 0ad https://www.archlinux.org/packages/community/x86_64/0ad/ or wesnoth https://www.archlinux.org/packages/community/x86_64/wesnoth/ use that location, so I'm not really sold yet on that.

They don't because `/usr/local` is only used when a system administrator installs outside of the system package manager. The `/usr/games` directory is optional in the FHS, so practically nobody following the Linux FHS uses it. It isn't portable across Linux systems, much less non-Linux systems. For example, FreeBSD doesn't have this:

https://www.freebsd.org/doc/handbook/dirstructure.html

**Comment by Berbe** [comment]
You are right... `/usr/local` should actually be used for manually installed resources.

This seems to be an oddity (for historical reasons?) from the FHS, being incoherent between its proposed `/usr` & `/usr/local` directory trees.

Let's stick to `/usr/bin`?

**Comment by ryao** [comment]
@Berbe The current behavior is basically what every other piece of software does. The prefix for the install is /usr/local by default and the packaging scripts will override that to set it to /usr. The binary files go into prefix + /bin.

**Comment by Gymnasiast** [comment]
Sticking to current behaviour then ;)
