### ISSUE TITLE
Multiplayer commands missing from readme

### ISSUE THREAD

**Issue by Enzemo** [OpenRCT2/OpenRCT2#997]
Hey,

So I discussed briefly with @PFCKrutonium the multiplayer functionality for OpenRCT2 and he mentioned that it exists in a very basic and unstable state, but he doesn't know the commands.

I realized that as the commands aren't in the readme, nobody is able to work on improving it as they can't test it (Or may not even be aware that it exists). I appreciate that it's a long, long way off, but if you could update the readme with the commands it would be helpful.

Thanks

**Comment by Saren-Arterius** [comment]
Is there a multiplayer functionality for OpenRCT2? How come not letting anybody know it?

**Comment by duncanspumpkin** [comment]
Its in a sub branch that hasn't been updated for a month or so. Its not currently building correct and there are many issues with it. Hang tight it might get looked at eventually when 0.0.2 is finally done.

**Comment by Enzemo** [comment]
Thanks very much Duncan. I've got little to no experience in programming aside from some xml and basic lua, but if I can help with anything please let me know

**Comment by IntelOrca** [comment]
I have updated the network branch so that it has the latest updates and bug fixes. A couple of more things in multiplayer now work but it is still far from playable.

**Host example:**
```
.\build\Release\openrct2.exe 'C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Electric Fields.SC6' --port 5920
```

**Client example:**
```
.\build\Release\openrct2.exe 'C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Electric Fields.SC6' --server 127.0.0.1 --port 5920
```

**Things that work:**
* Changing park name.
* Terraforming.
* Building footpaths.
* Chat via T key shortcut.
* Only IP address hostnames can be used for --server.
* Only one client is supported.

**Comment by IntelOrca** [comment]
There is now a wiki page with details and an intuitive interface.
